### ISSUE TITLE
Multiple Themes: Editor font styles not loading in Gutenberg v9.9.3

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#3280] opened 2021-02-15 21:24 UTC
## Steps to replicate

Many of our older themes target a classname that doesn't appear to exist anymore in the editor, which results in their font styles not being applied. Here's an example from AltoFocus: 

https://github.com/Automattic/themes/blob/3fa9d68c06fb4d174aebe58f58952061839efbb2/altofocus/assets/stylesheets/editor-blocks.css#L22-L28

This targets `editor-block-list__block`, which no longer exists in Gutenberg v9.9.3 as far as I can tell. Changing it to `block-editor-block-list__block` works. (Or more preferably, these styles should be enqueued via `add_editor_style()` and the font styles should be applied to `editor-styles-wrapper`). 

This is also a problem in: 

- Independent Publisher 2
- Penscratch 2
- Libre 2
- ... and likely [many other older themes](https://github.com/Automattic/themes/search?q=editor-block-list__block). 

## Result

The editor loads the browser default for font + font size, or it uses Noto Serif. 

Safari:
![Screen Shot 2021-02-15 at 4 08 18 PM](https://user-images.githubusercontent.com/1202812/107994044-d6460000-6fa9-11eb-8f4e-b0826537fddf.png)

Chrome:
![Screen Shot 2021-02-15 at 4 11 21 PM](https://user-images.githubusercontent.com/1202812/107994045-d6460000-6fa9-11eb-9487-6ce79d0910a7.png)

## Expected

The theme should be using the Libre Baskerville font stack as specified in the stylesheet.

**Comment by xpurichan** [comment] 2021-02-17 19:53
Experienced this in the Veni theme on a customer's website in 27820699-hc. I wanted to note that this issue is present in the customizer (not only in the block editor).

We can even see some oddities when we go to edit the Veni theme demo site in the customizer (not the different fonts used for the "featured pages" description texts:
![Screen Shot 2021-02-17 at 2 50 59 PM](https://user-images.githubusercontent.com/33190975/108260004-66f61a80-7127-11eb-9519-0e1e48917f0c.jpg)

Versus what we see when we visit the Veni theme demo site at https://venidemo.wordpress.com/:
![Screen Shot 2021-02-17 at 2 51 12 PM](https://user-images.githubusercontent.com/33190975/108259990-62316680-7127-11eb-93d8-91c18b511ae7.jpg)

**Comment by donalirl** [comment] 2021-02-18 00:15
This may be affecting WordPress.com/support as well. In the editor, we noticed the font now shows in a serif font, when it used to be sans-serif.

**Comment by retnonindya** [comment] 2021-02-18 05:56
A user reached out on chat about this too on theme **Button 2**. They are curious why the font size on editor suddenly got smaller.

**Comment by fresatomica** [comment] 2021-02-18 08:19
There are a few reports on the WordPress.com forums: [here](https://wordpress.com/forums/topic/font-in-editor-suddenly-got-smaller/), and [here](https://wordpress.com/forums/topic/how-to-change-font-displayed-in-copy-editor/).

**Comment by jamiepalatnik** [comment] 2021-02-20 00:03
Reported in 17960158-hc too.

**Comment by noteeth** [comment] 2021-02-20 22:50
Additional report regarding Independent Publisher 2 in  3752006-zen

**Comment by aleone89** [comment] 2021-02-24 15:17
Another report here: https://wordpress.com/forums/topic/font-size-in-blocks-editor/#post-3639659

**Comment by vinnykaur** [comment] 2021-03-12 08:33
Another one here: hc-25451080

**Comment by aleone89** [comment] 2021-03-18 13:13
This has been reported on Twitter here: https://twitter.com/SifaPoulton/status/1372516404700790785 the theme in use is Independent Publisher 2

**Comment by aleone89** [comment] 2021-03-18 15:09
This has been reported in the forums here: https://wordpress.com/forums/topic/editor-font-randomly-changes/ the theme in use is Sela

**Comment by erricgunawan** [comment] 2021-03-19 01:09
Reported on 28246108-hc and followed up on 3835024-zen

It happens on multiple sites with multiple retired themes (i.e. Chateau, Panel)

**Comment by aleone89** [comment] 2021-03-19 08:56
This has been reported in the forums here: https://wordpress.com/forums/topic/why-cant-i-choose-classical-editor-in-my-wordpress-dashboard-anymore/ the theme in use is Lodestar

**Comment by simison** [comment] 2021-03-19 18:47
another in p1616175586038800-slack-gutenberg-on-dotcom

Gutenberg: v10.2.1
https://wordpress.com/theme/nucleare

**Comment by jordesign** [comment] 2021-03-20 21:23
Another report in #3839734-zen
Gutenberg: v10.2.1
Theme: Baskerville 2

**Comment by lakellie** [comment] 2021-03-21 16:03
Another report in #3840473-zen
Theme: Baskerville 2

**Comment by WunderBart** [comment] 2021-03-22 12:09
👋 This is now (hot)fixed via D59109-code on Simple sites (v10.2.1). Atomic sites should receive the fix with the v10.3.0 upgrade. cc @simison

**Comment by aleone89** [comment] 2021-03-23 15:36
This has been reported here: https://wordpress.com/forums/topic/post-editor-formatting-suddenly-stopped-matching-blog-format/

**Comment by rinazrina** [comment] 2021-03-24 07:38
Another report #3848009-zen
Theme: Lovecraft

**Comment by swoodipto** [comment] 2021-04-01 13:50
Another report: 28681526-hc / 3872799-zen
Theme: Sela (retired)

**Comment by aleone89** [comment] 2021-04-13 12:49
Another report here: https://wordpress.com/forums/topic/%d7%91%d7%93%d7%a1%d7%a7%d7%98%d7%95%d7%a4-%d7%94%d7%aa%d7%a6%d7%95%d7%92%d7%94-%d7%a9%d7%9c-%d7%a2%d7%a8%d7%99%d7%9b%d7%aa-%d7%94%d7%a4%d7%95%d7%a1%d7%98%d7%99%d7%9d-%d7%94%d7%a9%d7%aa%d7%a0%d7%aa/?view=all#post-3663810
Theme: Cerauno

**Comment by ericamQA** [comment] 2021-04-24 00:51
Another instance in 29132404-hc 

Theme: TwoTone

Editor is using a monospaced font for paragraphs which is neither displayed on their site or the [theme demo](https://twotonedemo.wordpress.com/)

**Comment by ianstewart** [comment] 2021-05-03 21:58
@WunderBart just following up on this issue. It sounds like there was a fix put in place but with the ongoing reports it looks like it's not working? Is that correct?

**Comment by simison** [comment] 2021-05-04 11:29
Hm, anything relevant in themes that might be overlaying the original issue? @jeffikus @scruffian 

Upstream fix was in https://github.com/WordPress/gutenberg/pull/30080 and from what I can tell it wasn't reverted.

**Comment by scruffian** [comment] 2021-05-04 14:21
There's another fix that's needed in Gutenberg: https://github.com/WordPress/gutenberg/pull/30205

**Comment by WunderBart** [comment] 2021-05-04 16:12
> There's another fix that's needed in Gutenberg: [WordPress/gutenberg#30205](https://github.com/WordPress/gutenberg/pull/30205)

@fullofcaffeine, @simison - something we might consider hotfixing on Simple sites?

**Comment by fullofcaffeine** [comment] 2021-05-04 16:41
@WunderBart Thanks for the ping. I looked at the PR, and I'm wary of hotfixing it on WPCOM before it gets accepted, see: https://github.com/WordPress/gutenberg/pull/30205#issuecomment-822415983.

**Comment by davipontesblog** [comment] 2021-10-15 18:32
@chad1008 this has come up with another user today in chat, this is what they see in the editor:

<img width="740" alt="Screen Shot 2021-10-15 at 2 29 42 PM" src="https://user-images.githubusercontent.com/31009008/137535748-2a0a3761-ac19-4691-bc5d-50c053fb2f1d.png">

and this is what they see on front end:

<img width="640" alt="Screen Shot 2021-10-15 at 2 29 24 PM" src="https://user-images.githubusercontent.com/31009008/137535768-5dff271b-1ee0-4d2d-9aeb-e08c44e053df.png">

The theme in my case is Rowling, but it seems like this is affecting several themes still. Simple site. Here is the info on my est site where I can replicate the issue:

Gutenberg: v11.7.0
CoBlocks: 2.10.1
Editing Toolkit: 3.17007
WP AMP: 2.0.5

Is there any way this can be fixed in Gutenberg as opposed to the Themes?

**Comment by nicolynramos** [comment] 2021-10-17 20:32
Another report of this on simple site: 4382863-zd
Theme: Independent Publisher 2

**Comment by formosattic** [comment] 2021-10-18 06:50
+1 4383731-zd-woothemes
Theme: Independent Publisher 2

User reported issue back in February, seems like was fixed for some time, but has popped back.

**Comment by formosattic** [comment] 2021-10-19 03:55
Theme: Apostrophe 2

+1 32272678-hc

**Comment by formosattic** [comment] 2021-10-19 05:24
Looks like this issue re-appearing is actually https://github.com/Automattic/wp-calypso/issues/57043

I'll let the Theme team triage or close this.

**Comment by KokkieH** [comment] 2021-10-20 10:49
Another report in https://wordpress.com/forums/topic/very-small-font-size-again-in-the-editor/?view=all

Theme: Button 2

**Comment by chad1008** [comment] 2021-10-20 13:15
Thanks for the ping @davipontesblog. There was a similar report related to the recent Gutenberg release: https://github.com/Automattic/wp-calypso/issues/57043 (which I now see above, as _this_ issue was just mentioned _there_ yesterday ♾️ 

I was able to reproduce that issue in core, and reported it in https://github.com/WordPress/gutenberg/issues/35730

Where this issue has been quiet since May, I'm wondering if these new cases are actually related to the other, newer issue.

@oandregal has been looking into potential fixes in Gutenberg itself - ccing you here in case these additional impacted themes are helpful to know about.

**Comment by cuemarie** [comment] 2021-10-21 22:43
Another report: 4378950-zd-woothemes

Theme: Rowling

**Comment by jordesign** [comment] 2021-10-21 23:41
I'm closing this (again) in favor of https://github.com/Automattic/wp-calypso/issues/57043 so we can track instances all in one location. It looks like the fix is being worked on in https://github.com/WordPress/gutenberg/issues/35730

please feel free to re-open if I've done this in error.

**Closed as completed** 2021-10-21 23:42 UTC
Labels: [Type] Bug, Support, [Theme] Independent Publisher 2, [Theme] Lodestar
