### ISSUE TITLE
Pique Theme - Text color chosen in editor not reflected on the front end

### ISSUE THREAD

**Issue by csonnek** [Automattic/themes#5709] opened 2022-03-18 15:41 UTC
## Steps to replicate

To replicate, set your theme to Pique and type any text in a paragraph block, and set the text color to black (`#000000`). 

## Result

On the published post, see the text isn't black. Inspecting the HTML shows the class `has-black-color has-text-color` applied, but in the CSS panel in dev tools in Firefox, under Computed, it appears no stylesheet is being loaded that includes that class:

<img src="https://d.pr/i/EamADo+.jpg">

## Expected

I expected the text color to be black. 

User report/follow-up thread: https://wordpress.com/forums/topic/text-color-for-a-group-block-is-not-displaying-the-right-color/?view=all

**Comment by PeterNdomano** [comment] 2022-03-20 16:07
Hello there...

I had a look at the mentioned theme's code (pique) and didn't find anything that would cause the above issue. So I decided to replicate the issue on my 3 sandboxes (one on a local server, another on wordpress.com free hosted site and the other on my online server).

**The results show that this issue happens only on free sites hosted at wordpress.com because on the other hosts this theme works as expected.  Refer to the screenshots below**

___


### LOCAL SERVER RESULT
![Screenshot 2022-03-20 at 18-23-45 BLACK COLOR TEST on local server – My WP-Sandbox](https://user-images.githubusercontent.com/28900892/159170315-ff26f0ed-9d3c-409a-bc7b-c32b995e6ae7.png)

As you can see, theme works as expected on a local server


___




### WORDPRESS.COM FREE SITE RESULT (post link: https://pnsandbox.wordpress.com/2022/03/20/black-color-test/)

![Screenshot 2022-03-20 at 18-24-29 BLACK COLOR TEST on wordpress com free site](https://user-images.githubusercontent.com/28900892/159170430-86cc470f-140c-4653-9a33-bb9131f61a47.png)
As you can see the black color is overridden by the default color on this free site hosted by wordpress.com




___


### **MY ONLINE SERVER RESULT** (Post link: https://werenium.com/wpsandbox/?p=5)
![Screenshot 2022-03-20 at 18-24-55 BLACK COLOR TEST on another online server – WP Sandbox](https://user-images.githubusercontent.com/28900892/159170526-ae3dd7ea-54e0-4d6d-9fb8-595d54c113db.png)

As you can see it also works as expected when theme is used on a site hosted on another online server other than wordpress.com hosting.






___


### MY SUGGESTIONS

1. Maybe it's an issue with wordpress version. I failed to figure out what wp version is used  on free hosted sites at wordpress.com but on all my other two sandboxes  wp version is 5.9 and the theme works as expected  there. So I think for those who get this error on other versions of wp may try to upgrade their wp version if host supports doing so.
2. It may also be an issue with some recent changes (if any) at wordpress.com on handling these freely hosted sites because the blogger who initially filed this issue on  wp forum said that it has just begun recently


Thanks. 

@KokkieH 
@csonnek

**Comment by KokkieH** [comment] 2022-03-22 12:48
Thanks for testing and the thorough notes, @PeterNdomano. Hopefully it will help our developers get to the bottom of this when they get to this thread :)

**Comment by bobmatyas** [comment] 2022-08-22 18:24
This doesn't appear to be an issue any longer. I tested using the steps provided above on WordPress.com and got the following result:

<img width="882" alt="Screenshot on 2022-08-22 at 14-22-49" src="https://user-images.githubusercontent.com/45246438/185992020-a77c7d09-5163-4740-8771-6ee5ceafd1d6.png">

I also confirmed that it doesn't happen on a self-hosted version of the theme.

I'm going to close this but we can reopen if it comes up again.

**Closed as completed by bobmatyas** 2022-08-22 18:24 UTC
Labels: [Type] Bug, [Theme] Pique, Triaged
