### ISSUE TITLE
Baskerville 2: Infinite scroll adds extra space before posts in category pages

### ISSUE THREAD

**Issue by damiannep** [Automattic/themes#262] opened 2018-09-19 14:28 UTC
## Steps to replicate

1. Open a category page with many posts and Infinite Scroll turned on.
2. Scroll up and down a few times:

![post-behaviour](https://user-images.githubusercontent.com/30090682/45759115-7bb4e800-bc27-11e8-85f4-3435c5c3a794.gif)

## Result

Extra space is added at the top of the page. I replicated this in Chrome and Firefox.

## Expected

Page should look fine with posts arranged in the grid.

* User report: #5411040-hc
* Follow-up ticket: #1427808-zen
* User's site: https://integration-resources.com

**Comment by laurelfulford** [comment] 2018-09-19 16:31
Hey @damiannep - thanks for the report! This looks like a duplicate of #208, so I've moved the user information over there!

**Closed by laurelfulford** 2018-09-19 16:31 UTC
Labels: bug
