### ISSUE TITLE
Twenty Sixteen: Media attachment page displays the image as a site logo if no logo is set

### ISSUE THREAD

**Issue by aisajib** [Automattic/themes#4786] opened 2021-09-30 06:19 UTC
### Quick summary

If you visit an image attachment page on Twenty Sixteen, the image itself shows up as the Site Logo at the top left, even when there are no Site Logos set on the site. 

### Steps to reproduce

1. Activate Twenty Sixteen on a Simple site. 
2. Navigate to the Media (`/wp-admin/upload.php`)
3. Click on an image and then click the View attachment page
4. Wait for the attachment page to open.

### What you expected to happen

The attachment page opens with the header/site logo area unaffected.

### What actually happened

The image attachment page opens, but the image shows up as a site logo at the top. 

You can see that on Twenty Sixteen's live demo on WordPress.com.

1. a1C318-4w-p2
2.a1C318-4f-p2

### Context

Reported originally on this [forum thread](https://wordpress.com/forums/topic/removing-automated-blocks-on-images/?view=all).

### Operating System

Windows, macOS

### Browser

Google Chrome/Chromium

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Yes.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Workaround details

Provided this temporary CSS workaround on the forum for now: 

```
/* Hide Site Logo (bug) on image attachment pages) */
.attachment .site-logo-link {
	display:none;
}
```

**Comment by jordesign** [comment] 2021-12-09 05:42
Scrubbed and confirmed. Twenty Sixteen is active on 6,146,263 sites

**Comment by danieldudzic** [comment] 2021-12-15 11:06
This one is an odd bug.

The culprit is located in Jetpack: `modules/theme-tools/site-logo/inc/functions.php`

In the absence of a logo, inside the `jetpack_the_site_logo` a `bool(false)` value gets passed as `$logo_id` into the `wp_get_attachment_image()` - (which isn't a valid value by the way, as the function expects an `int - Image attachment ID`) - this in turn results in the function outputting the current page attachment image.

As an experiment, passing `bool(true)` results in no output at all (expected behavior).

**Comment by scruffian** [comment] 2022-02-14 17:48
Since this appears to be a Jetpack bug I think we should close this issue.

**Closed as completed by scruffian** 2022-02-14 17:48 UTC
Labels: [Type] Bug, [Pri] High, Triaged
