### ISSUE TITLE
Quadrat Paragraph Block: Link color not working when custom text color is set

### ISSUE THREAD

**Issue by swoodipto** [Automattic/themes#4148] opened 2021-07-01 12:40 UTC
## Steps to replicate

* Activate Quadrat theme
* Create a new post or page and add some text with links
* Set link color, check preview [this should work]
* Now set text color, check preview [the link color option stops working]

## Result

| Live Site | Editor |
| ------------- | ------------- |
| **In the live site**, the links show default theme link color if a custom text color is set.  | **In the editor** the link color is overwritten by the custom text color |
| ![Markup on 2021-06-29 at 17:07:39](https://user-images.githubusercontent.com/29238672/124125291-114b5a80-da97-11eb-9b51-d2c29c8c88d9.png) | ![Markup on 2021-06-29 at 17:06:55](https://user-images.githubusercontent.com/29238672/124125607-70a96a80-da97-11eb-9832-083c067d487e.png) |

## Expected

The link color option should work even if there is a custom text color set.

**Comment by pbking** [comment] 2021-07-02 14:02
I was not able to reproduce this.  Links and other text were all the colors I expected.  Tried custom colors as well as using presets (and combinations of the two). 
![image](https://user-images.githubusercontent.com/146530/124286141-a47aa380-db1c-11eb-9c12-e03914d74565.png)

**Comment by swoodipto** [comment] 2021-07-03 11:11
@pbking I am still able to replicate this issue. Here's the screen recording: https://d.pr/v/mUzYtD/5JmaPaWg9y

Not sure how specific to the browser this is, FWIW I tested this on:

* Vivaldi 4.0 (based on Chromium 91.0)
* Firefox 89.0.2

And the issue persists on both browsers.

**Comment by MaggieCabrera** [comment] 2021-07-05 15:26
This is a dotcom only issue, you can check it [here](https://theamdemo.wordpress.com/2019/06/24/gutenberg-paragraph/)

**Comment by MaggieCabrera** [comment] 2021-07-05 15:51
Same issue as https://github.com/Automattic/wp-calypso/issues/45456

**Comment by pbking** [comment] 2021-07-07 13:54
Closing as a duplicate.

**Closed as completed by pbking** 2021-07-07 13:54 UTC
Labels: [Theme] Quadrat
