### ISSUE TITLE
Eighties theme: Comments layout is broken

### ISSUE THREAD

**Issue by rinazrina** [Automattic/themes#8293] opened 2024-10-21 06:35 UTC
### Quick summary

Comments layout is broken on a simple site with the Eighties theme active. Gravatars are appearing too large and covering the comment text.

### Steps to reproduce

1. Activate Eighties theme on a simple site
2. Create a new post or open an existing one
3. Add a comment to the post
4. Check the comment section layout

### A clear and concise description of what you expected to happen.

The comments section should be readable and the gravatar image should be displayed in the correct size. 

![Image](https://github.com/user-attachments/assets/a7553f83-6ff4-4f67-9513-c49d6495ea9a)

### What actually happened

The comments section appears broken, and the gravatar image seems off. 

![Image](https://github.com/user-attachments/assets/d75e945b-9184-4854-b9ac-3c78cbd885ec)

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### If the above answer is "Yes...", outline the workaround.

Users can disable the Avatar from the Discussions settings (wp-admin/options-discussion.php) so the comments text can be visible. 

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

Reproducible on Chrome. 

Occurs on the Eighties theme. 

User report: 8912981-zd-a8c

**Comment by Robertght** [comment] 2024-10-22 14:27
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated 
- Tested on Atomic – Could Not Replicate 

📌 ACTIONS
- Triaged
- Leaving this as a high priority because of the overlapping elements.

📌 Message to Author
Thank you for testing and flagging this @rinazrina!

**Comment by xavier-lc** [comment] 2024-10-23 14:21
PR ready for review: 156454-ghe-Automattic/wpcom-themes

**Comment by xavier-lc** [comment] 2024-10-24 10:37
The fix has been deployed.

**Closed as completed by xavier-lc** 2024-10-24 10:37 UTC
Labels: [Type] Bug, [Pri] High, Triaged, [Platform] Simple, [Status] Priority Review Triggered, Customer Report, [Feature Group] Appearance & Themes

**Comment by rinazrina** [comment] 2024-10-25 06:00
Thank you for testing @Robertght and for fixing this @xavier-lc 

I no longer see the issue on my test site. I've informed the user too.
