### ISSUE TITLE
Intergalactic 2: Image Captions in editor are invisible/white

### ISSUE THREAD

**Issue by formosattic** [Automattic/themes#4002] opened 2021-06-04 05:42 UTC
In the editor (live page is ok), image captions are white, as if invisible, looks like the .is-dark-theme is applied when it shouldn't:

```
.is-dark-theme .wp-block-image figcaption {
    color: hsla(0,0%,100%,.65);
}
```

![image](https://user-images.githubusercontent.com/15944096/120751464-9bf17600-c53a-11eb-8efb-796143126054.png)

* Follow-up ticket: 4042339-zd-woothemes

**Comment by ericamQA** [comment] 2021-06-04 17:08
Duplicate of #53422

**Closed as completed by ericamQA** 2021-06-04 17:08 UTC
Labels: [Type] Bug, [Theme] Intergalactic 2

**Comment by ericamQA** [comment] 2021-06-04 17:10
Closed in favor of https://github.com/Automattic/wp-calypso/issues/53422
