### ISSUE TITLE
Twenty Ten (up to Twenty Sixteen): Multi-level list blocks don't cascade in editor

### ISSUE THREAD

**Issue by druesome** [Automattic/themes#6691] opened 2022-10-25 06:51 UTC
### Quick summary

Multi-level list blocks created on the following themes appear on the same level in the editor.  Moreover, there is no differentiation of bullets between each level, making it more difficult to work with this type of list.

- Twenty Ten
- Twenty Eleven
-  Twenty Twelve
- Twenty Thirteen
- Twenty Fourteen
- Twenty Fifteen
- Twenty Sixteen

<img width="678" alt="image" src="https://user-images.githubusercontent.com/98869/197701301-689bbefa-f2fc-4db3-86ae-ab201c17f0e2.png">

Related: [#6612](https://github.com/Automattic/themes/issues/6612)

### Steps to reproduce

1. Activate any of the above themes
2. Create a new page or post
3. Add a list block with nested list items
4. Check the published page. You will notice that this issue only happens in the editor.

<img width="386" alt="image" src="https://user-images.githubusercontent.com/98869/197701560-98d65ada-4c8c-4035-8012-4f1dbb7421d3.png">

### What you expected to happen

I expected the editor to show that cascading/nesting style that is present on the published page.

### What actually happened

The editor shows a multi-level list as they were a single-level list.

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Context

5536111-zen

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by kavyagokul** [comment] 2022-11-01 09:09
📌 SCRUBBING : RESULT
- Tested on Simple: Replicated
- Tested on AT: Replicated
- Tested on Self-hosted: Replicated
- Replicable on Core? Yes


📌 ACTIONS
- Closed as duplicate of https://github.com/Automattic/themes/issues/6604

📌 Message to Author
@druesome Thanks for the additional details and testing on other themes. I'm closing this and adding details from here on the existing report

**Closed as completed by kavyagokul** 2022-11-01 09:09 UTC
Labels: [Type] Bug, [Pri] High, Triaged, [Platform] Simple, [Platform] Atomic
