### ISSUE TITLE
Seedlet Blocks: Removing title from home page removes from all posts/pages

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#2679] opened 2020-10-23 20:07 UTC
I'm not sure if this is exactly a theme issue or a site editor issue. :) 

Because seedlet-blocks uses `singular` for both posts and pages that means that if one is to make a home page _without_ creating a special template for just the front-page of their site _and_ wants to remove the title from their home page in the site editor … it's quite possible to accidentally delete the title from all posts/pages.

Perhaps this is a site editor issue. But I wondered if it could be potentially mitigated by having a template just for the front-page of the site?

For full context, this will likely be most apparent on WP.com where we commonly create a site with a static home page. We may perhaps just want to conditionally create front-page templates for themes that don't have them.

**Comment by kjellr** [comment] 2020-10-26 17:07
cc @jameskoster — we can "fix" this by adding another template in Seedlet Blocks, but since we can't control in general what templates a theme provides or doesn't, it sounds more like a site editor issue to me.

**Comment by ianstewart** [comment] 2020-10-26 17:27
Plus one to the above.

**Comment by jameskoster** [comment] 2020-10-27 10:37
I think this will in part be solved once [this](https://github.com/WordPress/gutenberg/issues/20474#issuecomment-664969448) and [this](https://github.com/WordPress/gutenberg/issues/19259#issuecomment-707753912) are implemented, so that you can duplicate a template while editing or on save.

But neither of those affordances indicate that one must duplicate a template to achieve the desired result in the OP. I personally think this is largely caused by the complexity of the Singular (and Single) templates. They are very handy affordances for theme developers who live in code editors, but when it comes to representing them in a visual theme builder (the Site Editor)... the ambiguity is troublesome to say the least 🙈. Even with a description, "Singular" is simply not descriptive enough to communicate all the scenarios in which this template might resolve to the average user. Compared to something like "Page" or "Post"... it is night and day.

I would say that most of the heavy-lifting is to be done on the Site Editor end, but I think there is also a balance to be struck by the theme. Yes, including separate `single-post` and `page` templates might duplicate some code, but if it improves the UX then perhaps it is worth it? The Singular template is increasingly feeling like "advanced" territory to me.

**Comment by MaggieCabrera** [comment] 2021-09-08 14:08
This is fixed via Blockbase, we have a "blank" template that we can use if we don't want the header and footer to show on a per post/page basis

**Closed by MaggieCabrera** 2021-09-08 14:08 UTC
Labels: [Theme] Seedlet Blocks
