### ISSUE TITLE
Blank Canvas: Display Site Title & Tagline option is checked

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#3154] opened 2021-02-02 01:57 UTC
Even though the Blank Canvas theme does not display Site Title and Tagline, the option is still there in the Customizer, and it's checked by default. 

## Steps to replicate
1. Activate Blank Canvas theme.
2. Go the the Customizer > Site Identity
3. Note that "Display Site Title & Tagline" option is checked. 
4. Toggling the option does nothing (as expected I guess).

## Result
I found it confusing that the option to display Site Title is there at all (but also that it was checked). 

Not sure if this was intentional because adding an optional Site Title & Tagline is on the cards for this theme in the future? But anyway, for the time being, it could trip customers up, so I thought I'd bring it up.

No customer report, found through my own testing.

**Comment by scruffian** [comment] 2021-02-04 11:13
Yeah this is a bit annoying. The problem is that if we don't show this option until the user enables the header in Content Options then they will need to reload the customizer to see this option too. We added a note about it to the Customizer:

<img width="389" alt="Screenshot 2021-02-04 at 11 11 46" src="https://user-images.githubusercontent.com/275961/106884877-c8ef6280-66d9-11eb-8cfe-5e8b0acff1c5.png">

This is far from an ideal solution - the solution lies in FSE, so I think this is wontfix I'm afraid :(

**Closed as completed by scruffian** 2021-02-04 11:13 UTC
Labels: [Theme] Blank Canvas
