### ISSUE TITLE
Tag links appear where category links are supposed to appear

### ISSUE THREAD

**Issue by hacchism** [Automattic/themes#7257] opened 2023-07-22 06:03 UTC
### Quick summary

With some themes such as **Independent Publisher 2** and **Twenty Sixteen**(I have tested with these two themes only so far), when you have a tag and category with the same text string, a tag link appears where a category link is supposed to appear.

### Steps to reproduce

1. Activate **Independent Publisher 2** or **Twenty Sixteen**.
2. Create a new post.
3. Assign a category and tag with the same text string (i.e. Orange).
4. Publish the post and see its single post page.

### What you expected to happen

The category should link to its category archive URL:

![Screen Shot on 2023-07-22 at 14:50:35](https://github.com/Automattic/themes/assets/32432463/e83e31d1-c858-46d9-83a7-5e257daad6e0)

### What actually happened

The category links to a tag archive URL instead:

![Screen Shot on 2023-07-22 at 14:59:29](https://github.com/Automattic/themes/assets/32432463/c8cb3405-abc2-4b58-ad78-1929ea7da969)

See this only happens when there are both category and tag with the same string(Orange):

![Screen Shot on 2023-07-22 at 14:56:42](https://github.com/Automattic/themes/assets/32432463/e548be4e-634e-408c-862a-f5bab4702a7c)

![Screen Shot on 2023-07-22 at 14:58:59](https://github.com/Automattic/themes/assets/32432463/d401e00f-9fec-4461-90cf-ad34a1ca5dad)

### Context

Originally reported at 6542558-zen

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

None

**Comment by cuemarie** [comment] 2023-07-24 18:22
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple –  **Could Not Replicate**
- Tested on Atomic – **Could Not Replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- On both Simple and AT sites, I gave a new post a tag & category with the same string. In both Independent Publisher 2 and Twenty Sixteen, the category and tag links appeared in the correct place across the single post page.

#### Screenshots/Recordings

**AT Site, Independent Publisher 2**

_Category Link_
![Markup on 2023-07-24 at 11:18:36](https://github.com/Automattic/themes/assets/27249804/4e584785-eabf-439e-855b-a7961f79b742)

_Tag Link_
![Markup on 2023-07-24 at 11:19:07](https://github.com/Automattic/themes/assets/27249804/9be1e853-9101-4ca3-842c-79738d6181e1)

**New Simple Site, Twenty Sixteen**

_Category & Tag Links_

![Markup on 2023-07-24 at 11:20:56](https://github.com/Automattic/themes/assets/27249804/e3c058d8-214c-48c6-a473-9e930c324842)

📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)

📌 Message to Author
- @hacchism I'm not sure if this resolved since you reported, or if something specific is going on with that user's site, but this is not reproducible in test environments for me. LMK if I missed anything in the above tests, otherwise, this might need another look at the user's site specifically. Thanks!

**Closed as not planned** 2023-07-24 18:23 UTC
Labels: [Type] Bug, [Pri] Normal, Triaged, Themes

**Comment by hacchism** [comment] 2023-07-25 06:36
@cuemarie Thanks for looking.

Interestingly, the issue is gone now even on my test site (simple + Independent Publisher 2). I can still see the issue on the user's site though😔

I'll check their site again and reopen this if I find anything new.
