### ISSUE TITLE
Apostrophe 2: Cookie Banner Showing in Front of Content

### ISSUE THREAD

**Issue by carinapilar** [Automattic/themes#5349] opened 2022-01-14 18:19 UTC
### Quick summary

The cookie banner on a site with Apostrophe 2 is showing in front of the content.

### Steps to reproduce

1. Activate the Apostrophe 2 theme on a free site.
2. Check the live site.

### What you expected to happen

That the cookie banner would show on the bottom.

### What actually happened

The cookie banner is showing in front of the content.

### Context

It's the default banner, not added through widgets. Reported on: https://wordpress.com/pt-br/forums/topic/faixa-cinza-na-tela-impede-navegacao-correta-no-site

Replicated on my test site:

![CookieBannerIssue](https://user-images.githubusercontent.com/16104522/149565309-0ebf1ae9-2eb6-4c6b-9011-04292272ad38.jpg)

**Comment by jerrysarcastic** [comment] 2022-01-17 22:34
Also reported in 
https://wordpress.com/forums/topic/display-error-black-line-over-text/
https://wordpress.com/forums/topic/a-line-appears-in-the-middle-of-the-screen/

**Comment by jerrysarcastic** [comment] 2022-01-17 22:35
Also noted here:  https://github.com/Automattic/themes/issues/5340

**Comment by jerrysarcastic** [comment] 2022-01-18 01:20
This appears to have been fixed in D73234-code so I'm closing this but feel free to re-open if there are more reports

I've confirmed all user sites seem to be working correctly and have let them know.  @carinapilar I have not let your user know since they will probably prefer to hear it in Portuguese but their site appears to be fine as well, thanks!

**Closed as completed by jerrysarcastic** 2022-01-18 01:20 UTC
Labels: [Type] Bug, [Pri] High, Triaged
