### ISSUE TITLE
Blank Canvas: Spacing between blocks inside Query doesn't match between the editor and preview.

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#4163] opened 2021-07-05 05:45 UTC
I'm not 100% sure if this is an editor or a theme issue, but I noticed the spacing between blocks inside a Query block differs significantly between the editor and the preview. 

## Step-by-step reproduction instructions
1. Create a new page (on a site with a couple of existing posts ).
2. Add a Query block to the page.
3. Take note of the spacing between elements.
4. Save and then preview the page. Not the spacing is very tight and does not match the editor view.

## Expected behaviour
I expected the spacing between blocks would be the same in the editor and in the site preview. 

## Screenshots or screen recording (optional)
Spacing in the editor:
![image](https://user-images.githubusercontent.com/4550351/124423041-bb80f600-dda7-11eb-9b51-e949731f4131.png)

Spacing in preview:
![image](https://user-images.githubusercontent.com/4550351/124423068-c9cf1200-dda7-11eb-9af9-418c42e4913b.png)

I tested this with a couple of different themes (TT1, Seedlet, Blank Canvas), and the spacing was off in all of them.
It was not off however in TwentyTwenty, which leads me to believe it's a theme issue.

**Comment by scruffian** [comment] 2021-07-23 15:12
This is a duplicate of #4207

**Closed as completed by scruffian** 2021-07-23 15:12 UTC
Labels: [Type] Bug, [Theme] Seedlet, [Theme] Blank Canvas
