### ISSUE TITLE
Twenty Nineteen: Blog Posts Block Styling with Background Colour difficult to read

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#1849] opened 2020-03-11 16:25 UTC
![image](https://user-images.githubusercontent.com/545779/76439797-ecefda00-638a-11ea-8f31-8202269a7488.png)

cc @iamtakashi @alaczek

**Comment by danieldudzic** [comment] 2021-06-02 22:26
I have now committed a fix: r59030 & r59031

Review request: @jeffikus

**Comment by pbking** [comment] 2021-06-03 16:07
Confirmed that the fix addresses the issue.  Wasn't able to find anything negative caused by the change.  As the change has already been committed and deployed closing this issue.

**Closed by pbking** 2021-06-03 16:07 UTC
Labels: [Block] Blog Posts
