### ISSUE TITLE
Dyad 2: Theme ignoring the recent posts to display number

### ISSUE THREAD

**Issue by koffieneko** [Automattic/themes#266] opened 2018-09-20 20:21 UTC
## Steps to replicate

* Create a site with Dyad 2 and add some posts. The theme will display the recent posts on the homepage. 
* Reduce the number of posts displayed on the hompage by adjusting the settings in wp-admin or Calypso. i.e. Settings > Reading in wp-admin.
Settings asking for 1 post: 
<img width="481" alt="screen shot 2018-09-20 at 21 06 20" src="https://user-images.githubusercontent.com/699309/45844443-5fde3e80-bd1a-11e8-82d7-4a7ae5dd6def.png">

Using macOS High Sierra, Chrome 68

## Result

The theme seems to be ignoring the settings. I tried adjusting them in Calypso and in wp-admin.
Homepage showing 3 posts: 
<img width="2032" alt="screen shot 2018-09-20 at 21 08 31" src="https://user-images.githubusercontent.com/699309/45844461-6cfb2d80-bd1a-11e8-962c-7c40afffbe24.png">

## Expected

The theme should only display the number of recent posts set in the reading settings.

* User report: #4503455-hc
* Follow-up ticket: #1431261-zd
* User's site: https://wwlifetimeachievement.com/ (homepage) and recreated the issue on a test site https://justanotherwp.site/

**Comment by alaczek** [comment] 2018-09-23 23:04
I tried replicating this both on a simple and AT site, and was not able to. One thing to note, is that sticky posts are not included in that "Blog pages show at most" setting, so for example on my test site I set to display one post, but had two sticky posts as well, and so my blog page displayed three posts. But the user does not have any sticky posts so I'm stomped as to what might be wrong here :| Since you were able to replicate on your test site, do you have any plugins installed there?

**Comment by scosgro** [comment] 2018-09-27 20:14
In this particular instance, it's due to Infinite Scroll settings, which is expected behavior.

Disabling Infinite Scroll (Load more posts using the default theme behavior) makes the theme match the number of posts on the homepage to the number displayed in their settings. Can likely be closed, @alaczek?

**Comment by allancole** [comment] 2018-10-01 19:08
Yeah, @scosgro I’m going to go ahead and close this. I tried testing with the Infinite Scroll setting disabled and got the same results as you.

**Closed by allancole** 2018-10-01 19:08 UTC
Labels: bug, support
