### ISSUE TITLE
Videomaker: Post titles too close to content in editor

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4989] opened 2021-11-04 14:21 UTC
In the editor, the post titles are too close to the content:
<img width="855" alt="Screenshot 2021-11-04 at 14 20 02" src="https://user-images.githubusercontent.com/275961/140330710-6a5a448e-1a38-4e7b-9192-ab29bedd5647.png">

**Comment by jeffikus** [comment] 2021-11-11 14:04
@matiasbenedetto can you take a look at this issue please?

**Comment by matiasbenedetto** [comment] 2021-11-11 18:46
Hi :wave: , I did some debugging around the problem featured in this issue and I found that:

- The issue is only reproducible on "Tablet" and "Mobile" editor preview modes.
- This is not a Videomaker theme specific problem
- The issue is also reproducible in Blockbase theme

The same issue using Blockbase: 
![image](https://user-images.githubusercontent.com/1310626/141352086-514e42a9-8e38-4e55-9565-d348dd1873f9.png)



- Some details more:
    - The CSS responsible for the margin of the element in desktop editor view is [this line](https://github.com/WordPress/gutenberg/blob/7da0f6d2620b315c64c6d11b7c0c13b8c409a6c9/packages/edit-post/src/components/visual-editor/style.scss#L49) from Gutenberg repo.
    - The issue is caused by the fact that the Tablet and Mobile editor previews are loaded inside an `<iframe>`, and it's not possible to apply styles from the outer page (linked before :point_up: ) to iframe contents.

**Comment by MaggieCabrera** [comment] 2021-11-12 09:43
I can't reproduce this in Videomaker with the latest from GB trunk:

<img width="1637" alt="Screenshot 2021-11-12 at 10 42 47" src="https://user-images.githubusercontent.com/3593343/141446040-38b43ff8-b4c2-4879-8a28-acd88aab91ba.png">

<img width="1636" alt="Screenshot 2021-11-12 at 10 42 59" src="https://user-images.githubusercontent.com/3593343/141446033-b82d93e6-aeee-4b6a-bf58-3cef9900b1b3.png">

**Comment by matiasbenedetto** [comment] 2021-11-12 14:37
@MaggieCabrera this can't be reproduced with the paragraph like the first element of the page because the paragraph has `margin-top:
![image](https://user-images.githubusercontent.com/1310626/141476082-88a9db94-0dfe-48c6-aef0-a10d04f5d39b.png)

**Comment by matiasbenedetto** [comment] 2021-11-12 14:37
After confirming with @MaggieCabrera and @pbking (thanks both!) that this is a Gutenberg issue I'm creating a [new issue](https://github.com/WordPress/gutenberg/issues/36450) in the Gutenberg repository and closing this one.

**Closed as completed by matiasbenedetto** 2021-11-12 14:37 UTC
Labels: [Type] Bug, [Theme] Videomaker
