### ISSUE TITLE
Cubic: Gutenberg Gallery block displays incorrectly on Cubic posts

### ISSUE THREAD

**Issue by gpmw** [Automattic/themes#270] opened 2018-09-26 02:03 UTC
## Steps to replicate
- Create a post with Gutenberg active on Cubic theme.
- Add a gallery block with 3 or 4 images and 3 or 4 rows
- Publish

[Please include screenshots, browser information, and anything else that can help us recreate the problem.]

Link to screenshot:
http://cld.wthms.co/wcwowr
or
https://wpglenntechthemes.blog/wp-content/uploads/2018/09/gutenberg-gallery-on-cubic.jpg

Browser:
Chrome - Version 69.0.3497.100 (Official Build) (64-bit)

## Result

Gallery was displayed incorrectly

## Expected

Gallery was supposed to display 3 or 4 thumbnail images in a row, Gallery style

* User's site: [https://wpglenntechthemes.blog/2018/09/26/test-gallery-post/]

**Comment by alaczek** [comment] 2018-09-27 00:30
The issue is fixed in r50189-wpcom-themes

@gpmw if this was regarding customer on a Business plan, the changes will be visible once the code is deployed (should happen on Friday). Oh, in the future, please include ticket link if possible.

**Closed by alaczek** 2018-09-27 00:30 UTC
Labels: bug, support

**Comment by gpmw** [comment] 2018-09-27 13:12
Hey! Thanks for looking into this and getting a fix for it.
I found this while testing Gutenburg on one of my sites and then I replicated it on one of my test sites.

There was no ticket. :)
