### ISSUE TITLE
Spearhead: Gallery block not showing images on click

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#2670] opened 2020-10-22 10:34 UTC
## Steps to replicate

Gallery block – when clicking to view an image, nothing appears. 

## Result

[Video](https://d.pr/v/J3PPCw/k94GxKPPMv)

**Comment by jffng** [comment] 2020-10-26 15:49
I'm unable to reproduce this locally or on theamdemo.wordpress.com. 

Can you verify that this is still occurring for you @MaggieCabrera?

**Comment by MaggieCabrera** [comment] 2020-10-26 16:03
This was reported by team Athena [here](pNEWy-dfi-p2#comment-52094), I only made issues for each item but the issue does happen on the Jetpack tiled gallery here: pcrugM-6M-p2

**Comment by jffng** [comment] 2020-10-26 16:35
Closing this as the issue is gone through no intervention of ours.

**Closed by jffng** 2020-10-26 16:35 UTC
Labels: [Theme] Spearhead, [Type] Bug
