### ISSUE TITLE
Twenty Twenty-One - Blog Posts block media behind setting produces grey sections

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/themes#3341] opened 2021-02-23 16:57 UTC
## Steps to replicate

Create some posts and assign them with featured images that have a horizontal orientation.
Add the Blog Posts block to display posts.
Assign the "Use media behind option".
None of the other settings for the block matter.

## Result

The images display with grey sections in the images: https://d.pr/i/yUjHzD
It doesn't matter what other settings are applied to the block, the grey sections either move or expand but are still present.

On the customer's site, featured mages with an original ratio closer to being square displayed fine. On my test site, the image size and orientation don't matter, everything I try results in grey sections appearing in the images.

## Expected

I expected the image to fill the image area: https://d.pr/i/FsmNgS (this screenshot is with the Spearhead theme)

* User report: 24809301-hc
* Follow-up ticket: 3765224-zen

**Comment by danieldudzic** [comment] 2021-06-02 15:16
@MaggieCabrera was able to locate the cause of this issue.

It's the inline image styles, that Twenty Twenty One injects in images via:
```
function twenty_twenty_one_get_attachment_image_attributes( $attr, $attachment, $size ) {

	if ( is_admin() ) {
		return $attr;
	}

	if ( isset( $attr['class'] ) && false !== strpos( $attr['class'], 'custom-logo' ) ) {
		return $attr;
	}

	$width  = false;
	$height = false;

	if ( is_array( $size ) ) {
		$width  = (int) $size[0];
		$height = (int) $size[1];
	} elseif ( $attachment && is_object( $attachment ) && $attachment->ID ) {
		$meta = wp_get_attachment_metadata( $attachment->ID );
		if ( $meta['width'] && $meta['height'] ) {
			$width  = (int) $meta['width'];
			$height = (int) $meta['height'];
		}
	}

	if ( $width && $height ) {

		// Add style.
		$attr['style'] = isset( $attr['style'] ) ? $attr['style'] : '';
		$attr['style'] = 'width:100%;height:' . round( 100 * $height / $width, 2 ) . '%;max-width:' . $width . 'px;' . $attr['style'];
	}

	return $attr;
}
add_filter( 'wp_get_attachment_image_attributes', 'twenty_twenty_one_get_attachment_image_attributes', 10, 3 );
```

I'm not 100% sure why it's being done in the first place, but a hacky fix would be to include a filter in the wpcom.php file and strip those inline image styles. An alternative solution would be to try and reset them using CSS like:
```
width: revert !important;
height: revert !important;
max-width: revert !important;
```

That said, I'm reluctant to introduce `!important` as a fix.

**Comment by scruffian** [comment] 2021-06-08 10:33
I believe this should be fixed in the block: https://github.com/Automattic/newspack-blocks/pull/768

**Closed as completed** 2021-06-14 13:04 UTC
Labels: [Type] Bug, [Theme] Twenty Twenty-One
