### ISSUE TITLE
Rockfield: Button text invisible on hover

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#2505] opened 2020-09-25 05:23 UTC
When Buttons block is placed inside a cover or media & text block, the text becomes invisible when you hover over the button.

## Steps to replicate
1. Add a Cover or Media & Text block to a post or a page.
2. Add a Buttons block inside, don't change any settings.
3. Save and preview the post. Hover over the button. Note the button text is invisible (technically it's the same as the background).
4. This does not happen when Buttons block is inserted straight into the document, without nesting.

## Result

![image](https://user-images.githubusercontent.com/4550351/94229148-14cb1780-ff42-11ea-90bb-efa9cf93dcc4.png)
_Cover block + buttons block (hovering over the button on the right)._ 

![image](https://user-images.githubusercontent.com/4550351/94229376-b2bee200-ff42-11ea-9830-a67b8be6b899.png)
_Media & Text block + Buttons block. Hover state on the right._

Note that when custom background color is used on the Media & Text block (as in example above), the default buttons state looks broken too. If I remove the background color, both the default state and hover are fine.

Found in my own testing.

**Comment by MaggieCabrera** [comment] 2020-09-29 09:37
@alaczek I could not reproduce this locally or on a wordpress.com site myself with either combination :(

**Comment by alaczek** [comment] 2020-09-30 01:09
Hmm... I just tested it again and can still reproduce. Here's the exact background color I used: `#f4f4f4`. I did notice now that this does not happen with every background color, although I didn't figure out why.

Background color `#f4f4f4f`

![image](https://user-images.githubusercontent.com/4550351/94631892-65f55580-030c-11eb-9dfe-3fb5edbb59b7.png)

Background color `#505050` (the button on the right has hover on it)
![image](https://user-images.githubusercontent.com/4550351/94631943-950bc700-030c-11eb-8077-b9ac13e1c888.png)

Background color `#116821` (from the theme color palette)
![image](https://user-images.githubusercontent.com/4550351/94632077-064b7a00-030d-11eb-8736-60ed9ef894d5.png)

Seeing it all on a live site might be more useful. I also added the examples with cover image in there: https://gutenboardinghp3.wordpress.com/media-text-test/

Let me know if you have any more questions!

**Comment by MaggieCabrera** [comment] 2020-09-30 07:22
Ok, on the steps to reproduce this we would need to add:
* For the cover image we need to select a white/subtle gray/lighter gray overlay. The rest of the colors or no overlay doesn't have the bug for me
* For the Media & Text block we need to change one of those 3 same colors as the background color. It doesn't happen with no color selected or with one of the other, darker colors.

I think this is caused by `currentcolor` being applied to the button and that color changes depending on the background color in order to provide good contrast. I think a solution would be to exclude buttons from having `currentcolor` applied to them in this case.

**Comment by TeniCola** [comment] 2020-12-14 17:00
> I think this is caused by `currentcolor` being applied to the button and that color changes depending on the background color in order to provide good contrast. I think a solution would be to exclude buttons from having currentcolor applied to them in this case.

The `currentColor` class was also an issue for another user I had where, their button blocks were displaying their gray background, instead of the white text they selected in the block settings and that was visible in the editor. As a workaround, I helped this user set their button to a "custom color" in the block settings, and then set _that_ color to # FFFFFF to force it to display white (3567400-zen).

To quote my colleague in our discussion, linked in the support ticket:

> "The problem is that the button has color set to `currentColor` and also to `inherit` [...] it is supposed to get the current text color, which is white, but ultimately it is inheriting the original body color of # 444"

Ideally, I agree that it may help to nix the `currentColor` class to fix this related issue as well (not sure if it should be created separately yet, but adding this anecdote since the two seem related to the same cause in this theme).

**Comment by scruffian** [comment] 2021-02-10 12:31
This seems to be fixed on the test site you linked. Feel free to reopen this if you can still see issues.

**Closed by scruffian** 2021-02-10 12:31 UTC
Labels: [Theme] Varia
