### ISSUE TITLE
Radcliffe 2: Background image issue

### ISSUE THREAD

**Issue by simranjeetkaur10** [Automattic/themes#100] opened 2018-04-12 15:35 UTC
## Steps to replicate

Steps to reproduce:

1. Go to https://wordpress.com/ > My Sites > Customize > Colors & Backgrounds 
2. Add Background image
3. View the site on Android phone and iPhone

## Result

Background image displays differently on Android phone and iPhone.

Screenshot of the Andriod phone (Chrome): 
![android screenshot](https://user-images.githubusercontent.com/34896144/38687407-42dc6df2-3e94-11e8-9d41-b15b355a3920.jpeg)

Screenshot of the iPhone (Safari): 
![iphone screenshot](https://user-images.githubusercontent.com/34896144/38687412-467bde84-3e94-11e8-81ef-7c091beab6e8.jpg)

## Expected

No inconsistency in the background image on different OS/browsers.

* User report: [#2713261-hc](https://mc.a8c.com/support-stats/happychat/transcript.php?id=2713261)
* Follow-up ticket: [#1084640-zd](https://woothemes.zendesk.com/agent/tickets/1084640)
* User's site: https://griffinforselectman.com/

**Comment by alaczek** [comment] 2018-04-24 04:15
From these screenshots it's hard to say what the problem is, as they don't show the exact same area of the page. Could you elaborate on what the problem seems to be? That the background is repeating? 
Also some more details would help:
* what device are you testing with? 
* what were the background settings - position, repeat?
* were you able to replicate on a test site? If so please provide a link.

**Comment by simranjeetkaur10** [comment] 2018-04-24 07:35
The background image displays differently on Android phone and iPhone.

Below are the screenshots:

1. **Moto X1 - Android 5.1 - Chrome**

![whatsapp image 2018-04-24 at 12 37 56 pm](https://user-images.githubusercontent.com/34896144/39171828-962c8eba-47bd-11e8-9136-dc6189788c2f.jpeg)

2. **iPhone 6s - iOS 11.3 - Chrome**

![whatsapp image 2018-04-24 at 12 38 32 pm 1](https://user-images.githubusercontent.com/34896144/39171908-c6be2d68-47bd-11e8-9e68-c0b0f6bad72a.jpeg)

**iPhone 6s - iOS 11.3 - Safari**

![whatsapp image 2018-04-24 at 12 57 52 pm](https://user-images.githubusercontent.com/34896144/39172384-3981d0ce-47bf-11e8-8b6f-36575077a192.jpeg)


- **what were the background settings - position, repeat?**

The below settings are applied:

![capture](https://user-images.githubusercontent.com/34896144/39172129-7a9dc186-47be-11e8-8f0b-74d8cda138e1.PNG)

- **were you able to replicate on a test site? If so please provide a link.**
Yes, here is the link to my test site: wp20171130.com

When I first encountered this issue, I asked for help in themes channel in Slack. Here is the link to that conversation: https://a8c.slack.com/archives/C029FM1EH/p1523538939000613

**Comment by alaczek** [comment] 2018-04-26 00:46
Thanks for the update - this helps a lot! I narrowed it down to the fixed position of the background - [mobile browsers don't really support it](https://stackoverflow.com/questions/19045364/fixed-body-background-scrolls-with-the-page-on-ios7), and unfortunately they go about it differently (hence the difference in appearance). This affects tablets too.

The solution here would be to disable the fixed background attachment on mobile devices, I'm just not sure how to construct media query to target actual devices only (phones and tablets), given the ever growing screen sizes which blur the lines between desktop and mobile devices.

I explored using `@media handheld`, but apparently [it's useless](https://stackoverflow.com/questions/3893342/do-iphone-android-browsers-support-css-media-handheld). I'm really hoping there's a way to do this without JavaScript. Ideas welcome!

Also a side note - this probably affects most if not all of our themes.

**Comment by laurelfulford** [comment] 2018-05-03 21:14
Yeah, this seems like it would be a Core issue, or at least an issue with how WordPress.com handles the background image styles (I'm not 100% sure they're identical), rather than a theme issue. 

Radcliffe 2 isn't doing anything unusual with the background images, it just has the default implementation.

**Comment by crunnells** [comment] 2019-02-07 20:09
The "Colors & Backgrounds" tab in the Customizer comes from a WP.com plugin, so the issue is there rather than in Core. I _don't_ think this is theme-specific, because the `background-position: fixed` comes from that plugin and should apply to **all themes**. It seems like we should probably fix it there, rather than try to override on a theme level.

One thought; we can add a media query to the CSS that overrides the `background-position` from `fixed` to `scroll` for small screens.

**Comment by davidakennedy** [comment] 2019-07-16 19:27
I'm closing this since it's not a theme specific issue.

**Closed by davidakennedy** 2019-07-16 19:27 UTC
Labels: [Pri] Normal, bug, needs testing, support
