### ISSUE TITLE
Apostrophe 2: <script> not rendering in Custom HTML widget

### ISSUE THREAD

**Issue by jesscga** [Automattic/themes#25] opened 2018-03-01 21:58 UTC
## Steps to replicate

Add the following code to a Custom HTML widget:

`<div id="amzn-assoc-ad-97baaf2c-dea5-4d47-a1cc-e300259d271f"></div><script async src="//z-na.amazon-adsystem.com/widgets/onejs?MarketPlace=US&adInstanceId=97baaf2c-dea5-4d47-a1cc-e300259d271f"></script>`

## Result

Nothing displays. 

The console shows warnings `The SSL certificate used to load resources from <URL> will be distrusted in M<XX>. Once distrusted, users will be prevented from loading these resources. See <URL> for more information.` with this and other themes.

Page source shows the code as it was added.

## Expected

A list of Amazon products appears.

With other themes, the Page Source shows the links converted into product data.

* User report: #1942102-hc
* Follow-up ticket: #989594-zd
* User's site: https://yesterdaygirl.blog

**Comment by kathrynwp** [comment] 2018-03-02 13:00
Noting that this is an Atomic site.

@jesscga Were you able to replicate on another Atomic and/or WordPress.com site running this theme?

**Comment by jesscga** [comment] 2018-03-02 13:22
Yes, I replicated on an Atomic test site. The code rendered as expected with Radcliffe2, Dara and Intergalactic and then stopped working when I switched to Apostrophe2. I didn't test on a WordPress.com site since <script> isn't allowed on non-Atomic sites.

**Comment by kathrynwp** [comment] 2018-03-02 13:25
Great, thanks for clarifying, @jesscga ! (re: script on non-Atomic - I wasn't sure if Amazon was one of our whitelisted domains.)

**Comment by jesscga** [comment] 2018-03-02 13:50
I tested on a simple site, just to be 100% sure, and got the `Tag <script> is not allowed` error.

**Comment by sixhours** [comment] 2018-03-02 18:17
The SSL warning appears regardless of the theme, so I don't think that's the cause in this case. I'm also unable to get the script to work in Dara. 

Doing a bit more digging.

**Comment by sixhours** [comment] 2018-03-02 18:35
I've narrowed it down to something in the theme's CSS; when you disable certain widget styles, it works. Working to narrow it down further.

**Comment by sixhours** [comment] 2018-03-02 18:47
Aha, this is a weird one. It appears the Amazon.com content will not appear unless the given area is wide enough; in the case of Apostrophe 2, the 8.333% padding around the widget in the sidebar makes it too narrow.  Adding the Amazon script to the footer of the site works.

This is a wontfix; we can't rework the widget areas in themes with narrower sidebars. It's also really difficult to use Custom CSS to completely resize the widget area in this theme since it's a grid-based layout.

We could remove the padding on that specific widget with Custom CSS, though, since we know the ID (let us know if you need help with that), or they can put the widget in the footer instead.

**Closed by sixhours** 2018-03-02 18:47 UTC
Labels: bug, support
