### ISSUE TITLE
Intergalactic 2: Embedded video incorrectly cropped

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#478] opened 2019-01-07 07:04 UTC
## Steps to replicate

1. Create a new post in the classic editor
2. Post a Youtube video link on its own line so it auto-embeds, or use the Youtube shortcode
3. Publish and view post.

## Result

The embedded video is cropped to a 4:3 aspect ratio even if the video itself has a different aspect ratio

![youtube_test_ _shift_to_the_left](https://user-images.githubusercontent.com/11873759/50753456-9eaceb80-125a-11e9-85fc-d8e4dd46b758.png)

## Expected

For the embedded video to display at its actual aspect ratio. This works as expected in the old Intergalactic theme, and also in Intergalactic 2 if the block editor is used instead.

![youtube_test___shift_to_the_left](https://user-images.githubusercontent.com/11873759/50753494-b5ebd900-125a-11e9-9261-3504c58ec2af.png)

Also tested with a Vimeo video and it works as expected, so the issue appears to be specifically with Youtube videos.

![youtube_test_ _shift_to_the_left](https://user-images.githubusercontent.com/11873759/50753417-82a94a00-125a-11e9-8207-7201dfee6e33.png)

* User report: https://en.forums.wordpress.com/topic/youtube-videos-in-wrong-aspect/
* User's site: https://ertvmusictests.wordpress.com/2019/01/03/video-test/

**Comment by laurelfulford** [comment] 2019-01-07 19:36
So it looks like this change might be the culprit:

https://github.com/Automattic/jetpack/issues/10678

Jetpack now checks whether themes include `add_theme_support( 'responsive-embeds')` before it will apply its own responsive video fix, even if a theme supports it too with `add_theme_support( 'jetpack-responsive-videos')`. 

This fixes an issue where the two different responsive embeds behaviours clashed with each other. This works well with new sites only using the block-based editor, but as seen here, causes issues with existing sites whose themes now support Gutenberg, even if they're not using the new editor.

I'm going to do a bit more digging in this, to see if there's a way around it in the theme, or if it's something we'd need to have looked at on the Jetpack level.

**Comment by laurelfulford** [comment] 2019-01-07 20:14
> actually on second thought, this is mostly probably an issue in themes that expect the .jetpack-video-wrapper class to be there; I need to do some testing with themes that aren't styling that.

Nope, looks like the issue is less obvious with themes that don't try to style that class (like Lodestar), but it's noticeable when you view posts from the classic editor or block with a YouTube video on mobile devices.

**Comment by laurelfulford** [comment] 2019-01-07 21:36
> actually on second thought, this is mostly probably an issue in themes that expect the .jetpack-video-wrapper class to be there; I need to do some testing with themes that aren't styling that.

After some testing, it looks like the issue is less obvious with themes that don't try to style that class (like Lodestar), but it's noticeable when you view posts from the classic editor or block with a YouTube video on mobile devices.

**Comment by laurelfulford** [comment] 2019-01-07 23:10
Created an issue for Jetpack here: https://github.com/Automattic/jetpack/issues/11097

I'm also going to investigate if there's something we can do on the theme level to avoid this issue, since I'm not sure it's possible to actually have Gutenberg's and Jetpack's responsive video functionality work nicely together.

**Comment by KokkieH** [comment] 2019-01-08 05:47
[Another report](https://en.forums.wordpress.com/topic/karuna-theme-displaying-videos-wrong/) of this happening in Karuna.

Site: https://phlevel.wordpress.com/

**Comment by supernovia** [comment] 2019-01-08 20:17
Just noting the person who had trouble with Karuna reports that the aspect ratio is fine when they use blocks, but not when using the classic editor. :/

**Comment by supernovia** [comment] 2019-01-08 20:20
Here you can see the same on Intergalactic:
https://justvelda.wordpress.com/2019/01/08/video-ratio-classic/
https://justvelda.wordpress.com/2019/01/04/video-ratio/

**Comment by supernovia** [comment] 2019-01-08 20:31
Here we go: https://github.com/Automattic/jetpack/issues/11097

**Comment by KokkieH** [comment] 2019-01-09 06:15
> Just noting the person who had trouble with Karuna reports that the aspect ratio is fine when they use blocks, but not when using the classic editor

As also mentioned in this issue above:

> This works as expected in the old Intergalactic theme, and also in Intergalactic 2 if the block editor is used instead.

**Comment by laurelfulford** [comment] 2019-02-04 19:40
Verifying that this is now fixed in Jetpack. 

I'll follow up in the two forum threads linked above.

**Closed by laurelfulford** 2019-02-04 19:40 UTC
Labels: bug, support

**Comment by KokkieH** [comment] 2019-02-05 04:47
Thank you!
