### ISSUE TITLE
Varia: Remove featured image support on pages

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#1461] opened 2019-10-01 16:07 UTC
See discussion in #1443.

The gist is that we should remove the featured image support from pages since the theme doesn't display on the front of the site, and having the UI in the editor is confusing.

**Comment by allancole** [comment] 2019-10-01 17:39
Fixed in #1462 👍

**Closed by allancole** 2019-10-01 17:39 UTC
Labels: enhancement, varia

**Comment by iamtakashi** [comment] 2019-10-11 13:19
Thanks @liviopv, that's a good point that we forgot about. 

We should have a separate feature for that in WP.com that works regardless of the activated theme so that the customers can have a clear and consistent experience.

Having said that, in the meantime, we probably need to reenable it for pages and display it on the front-end :/

@allancole, any opinion?

**Comment by eduardozulian** [comment] 2019-10-11 15:03
> I think we need to reopen this issue and consider reverting it because it ends up creating a collateral problem of not allowing users to have control over the image that gets passed to social media.

We have a similar case on #1502 where the customer has an old logo showing up on social media and there's no way for us to force a new one.

It feels harder to set a thumbnail for FB and Twitter especially with logos extremely compressed on those themes.

Apparently, the only way would be to ask them to change to another theme, which we already did.

**Comment by cecoates** [comment] 2019-10-11 16:04
> We should have a separate feature for that in WP.com that works regardless of the activated theme so that the customers can have a clear and consistent experience.

That would be excellent, but things like podcasts, Facebook, etc. also pull featured images per post/page as well.

So having just 1 site image wouldn't cover our customer's needs.

Is it possible to have the cover block pass the necessary tags to work with Twitter, FB, etc.?

**Comment by iamtakashi** [comment] 2019-10-11 16:17
> It would still need to be individually customizable on each page/post.

Yes, absolutely. If we were making this feature, it'd be another panel in the sidebar of the editor, and it's always there regardless of the activated theme. But I'm not sure if that's going to happen anytime soon.

**Comment by gracie** [comment] 2019-10-18 13:19
How long should we expect to have this feature restored?

Another case in #6867587-HC

**Comment by tijosh** [comment] 2019-10-23 17:36
Another report of this in #2442698-zen

In this case, the OG image is being selected from other posts on the site—not the home page—which is producing a very undesired effect for the user.

In the short term, I'd say reverting this ASAP would be ideal, and in the long term, building out a universal Social Media Preview module for all themes if possible.

**Comment by JoshuaGoode** [comment] 2019-10-23 17:41
> > We should have a separate feature for that in WP.com that works regardless of the activated theme so that the customers can have a clear and consistent experience.
> 
> That would be excellent, but things like podcasts, Facebook, etc. also pull featured images per post/page as well.
> 
> So having just 1 site image wouldn't cover our customer's needs. It would still need to be individually customizable on each page/post.
> 
> Is it possible to have the cover block pass the necessary tags to work with Twitter, FB, etc.?


Preferably, the feature would be similar to Yoast's.  Yoast allows you to set a frontpage OG image that social sites use and also a default image in the event a page/post doesn't have any images.

With Yoast, you can also set the OG image used on individual posts and pages too but the aforementioned would be sufficient. 

Re: https://kb.yoast.com/kb/custom-open-graph-tags/

**Comment by jgcaruso** [comment] 2019-10-23 17:53
Another report of this here #2438866-zen

User wants to set a specific image for the static homepage but its not available for their theme (Maywood)

Just curious if the plan is to restore the 'Featured Image' functionality so I can give some options to the user: changing themes vs waiting for the feature to be returned

**Comment by allancole** [comment] 2019-10-23 21:52
After some reconsideration around this, I think its best to bring this feature back. I’ll spin up a PR for it today, and customers can expect a fix to land in the next few days. Here’s how it’ll work:

1. Revert this feature bringing back the Featured Image section for Pages in the editor.
2. Add the template tag to Page templates to display the image.
3. Connect the Featured Image to Jetpack Content Options and set it to `off` by default. This way customers can select a Featured Image for the `og:image` and have an option to display or hide the image on home page (or any other page) in the customizer.

**Comment by iamtakashi** [comment] 2019-10-24 19:07
> Connect the Featured Image to Jetpack Content Options and set it to off by default. This way customers can select a Featured Image for the og:image and have an option to display or hide the image on home page (or any other page) in the customizer.

@allancole We discussed about this a bit, but I'm concerned about adding such a big feature in Customizer that's going away soon. I think we should avoid adding Customizer dependent features to template-first themes that are soon to be compatible with FSE.

@apeatling What is the plan for Customizer when we roll out FSE to all the template-first themes?

**Comment by apeatling** [comment] 2019-10-24 19:21
> @apeatling What is the plan for Customizer when we roll out FSE to all the template-first themes?

As each theme is updated, they would lose customizer access.

**Comment by apeatling** [comment] 2019-10-24 19:22
Also, agreed we should not be adding anything to the customizer for these themes. If something needs to be added we should open an issue and consider how this would work in a Gutenberg only world.

**Comment by allancole** [comment] 2019-10-25 17:47
@apeatling @iamtakashi, I recognize the customizer is going to go away soon—I can’t wait for that day to arrive ;-) However, we’re not all the way there yet and it makes things tougher for HE’s to help customers with TF-themes when they’re missing customizer controls with no alternative solve from FSE available yet. Some of the (anecdotal) feedback has shown that HEs end up recommending other non-TF-themes just so they can provide a solution in the moment. 

> If something needs to be added we should open an issue and consider how this would work in a Gutenberg only world.

Definitely agree here, and I’d imagine content options for featured images, meta-data, etc. would be something that could exist in some capacity in Gutenberg. But then the next question, becomes how long would that take and what do we do in the meantime to help HEs and customers feel confident with our theme products? 

My feeling on adding or not adding customizer support in Varia is based on how transitional these TF-themes need to be right now. The `site-logo` customizer option is a good example. We all know `site-logo` will go away when FSE arrives, but in my opinion that doesn’t mean we should take it away now and wait until FSE is ready. If we did, many customers (and HEs) would view these themes as _not as good_ as other, older themes that _do_ offer these common options that they’re used to. 

I don’t think we should go crazy with customizer support, though and I do think we have to draw a line between whats worth supporting and not. That line for me is drawn at how difficult adding customizer support might be. If it would have taken a week of refactoring to get content-options to work, I would have definitely opted to not do it. But because it relies on Jetpack filters I maybe spent about 30-40min working out the PR which means its an easy (albeit temporary) win for all the TF-themes (should we decide to merge it). And then when FSE is ready, those customers who didn’t experience friction in the TF-themes would gain the benefits of FSE immediately where as the others who bailed and went to an older theme would be stuck, and I’d guess they’d be more reluctant to adapt to the new themes anyway. I guess my overall feeling is that Varia should offer the best of whats possible at all times, so if it’s a standard (Jetpack) easy to implement customizer option like content-options, lets support it now. Then when the better FSE solution is available, we can shift to that immediately and have HE’s communicate that to customers too. 

I know my perspective doesn’t take into account literally everything thats happening in FSE and beyond. Let me know what other factors might influence our approach on this. What harm might be caused by `content-options` support when FSE arrives? Does it create more engineering problems for FSE with the `content-options` in place? Is it more about trying to push customers toward the editor and away from the customizer in general (which I also understand and agree with in most cases).

**Comment by iamtakashi** [comment] 2019-10-25 19:11
@allancole Let's think about this scenario — My site is using Maywood and I customize my site with the content options in Customizer. And when FSE is rolled out and I'd no longer have an easy way to go to Customizer, and I won't be able to change the setting anymore unless typing the URL manually.

How I see this is that if we add more options in customizer as short term solutions, we're essentially creating more feature gaps for customers when FSE gets rolled out with those themes.

**Comment by iamtakashi** [comment] 2019-10-26 08:30
@allancole I understand the need for featured image and the option to hide asap. But I think the option shouldn't be in Customizer. Maybe a checkbox inside the featured image panel in the editor?

**Comment by iamtakashi** [comment] 2019-10-26 11:33
How about...

1. Add the featured image support back for pages in the themes. Customers will be able to specify an image for social media again which is the most pressing issue to fix. 
2. But we don't add the template tag in pages. This avoids the images that suddenly start appearing on pages in their sites. This will take us back to #1443.
3. Add a checkbox to the featured image panel in the editor that controls show/hide on the front-end of the site. Alternatively, we could add a notice in the panel to the sites with the themes explaining that the image is for social media.

**Comment by donalirl** [comment] 2019-10-27 04:03
Here's a case of needing control over the social preview image: #2450090-zen

**Comment by allancole** [comment] 2019-10-28 18:08
@iamtakashi, Yeah I’m mostly in agreement with you here especially around this point:

> if we add more options in customizer as short term solutions, we're essentially creating more feature gaps and frustrating UX for those customers when FSE gets rolled out until we have equivalent options in Gutenberg.

There’s quite a few things that we want to stay away from to reduce feature gaps and bad UX. Customizer options is certainly one of those things but so is theme-specific options, in my opinion. My main worry is that if we build the solution into Varia then it becomes an _exclusive_ feature that only Varia supports which isn’t exactly terrible, but to me it feels like this kind of option should come from core or FSE itself rather than from Varia. 

> Add a checkbox to the featured image panel in the editor that controls show/hide on the front-end of the site. Alternatively, we could add a notice in the panel to the sites with the themes explaining that the image is for social media. 

Do you know if its possible for that show/hide option to come from FSE? Or maybe the better question is do we know if/how FSE will support Social Media thumbnail images or have featured images controls in the future? To me, these options seems like something that should ultimately come from core. But without knowing if thats the plan, it’s tough to determine what should happen in Varia right now. Maybe, it can temporarily go in Maywood since thats the only theme supporting FSE right now? 

To sum it all up, I think we should go forward with steps (1) and (2) as you described for next steps, which would allow us to close this ticket, I think. And then we can think through the 3rd step a bit more just so we can align with whats expected for the future of FSE. Let me know what you think ;-)

**Comment by iamtakashi** [comment] 2019-10-29 14:34
> My main worry is that if we build the solution into Varia then it becomes an exclusive feature that only Varia supports which isn’t exactly terrible, but to me it feels like this kind of option should come from core or FSE itself rather than from Varia.

I too don't think it should be a theme-specific feature. However, I also doubt that's going to be a feature in FSE or core because I _think_ featured image being as the first choice for OG:image is dotcom specific. From the core point of view, themes should just drop the featured image support if the theme doesn't want to show the image on the front of the site.

So I think the show/hide feature could be a little dotcom specific feature for the template-first themes until we have a dedicated panel for social media image for all the themes. I think we need to hear more opinions on this from a wider people though.

Anyway, we are in agreement on 1) and 2) as next steps, so let's go back to where we were with #1443 asap. Could you update your PR #1572?

**Comment by allancole** [comment] 2019-10-30 14:27
Gotcha. Yeah, I fully agree with you now. I’ll get steps (1) and (2) sorted out first thing today and then we can do (3) in the `wpcom.php` compatibility file in the theme.

**Comment by jenlynnemc** [comment] 2019-12-02 09:11
We have been contacted by a user that was looking for an update.
The issue is now resolved is that correct @allancole & @iamtakashi? Thanks for your  help.
