### ISSUE TITLE
Quadrant and Blockbase -  Fonts section does not work

### ISSUE THREAD

**Issue by tinjure20** [Automattic/themes#4334] opened 2021-07-27 12:39 UTC
I have been playing around Quadrat and Blockbase themes for possible use in my personal site. With 5.8 updates, the `blockbase_fonts_url` function seems to have broken. Fonts section in Blockbase as well as its child themes does not work, now. The `clamp()` function was working before but with 5.8 update it doesn’t work either. Thank you

**Comment by pbking** [comment] 2021-07-27 13:43
I might need some more information about this.  I'm unable to reproduce (fonts are working for me with both Blockbase and Quadrat).  I'm running WordPress 5.8 and Gutenberg 11.1.0.  

What version of Gutenberg are you running?
Do color customizations continue to work? 
Do the font change preview (but not persist?)

**Comment by tinjure20** [comment] 2021-07-27 17:24
@pbking Thank you. My test environment:

- WordPress version: 5.8
- Guttenberg: 11.1.0
- Blockbase: 1.1.0
- Quadrat: 1.1.0
- Local WordPress setup: Flywheel Local

I have been primarily testing with VSC editor using Firefox browser. I have tested this issue in Chrome as well. To avoid cache issue, I frequently clear browser cache as well.

Yes, color, font-size customization work just fine fine, as expected. But I don't see font-changes in preview screen.

<img width="1244" alt="screenshot-1" src="https://user-images.githubusercontent.com/59660253/127199430-03282c1c-3c22-479e-9f12-fc5ef63d4364.png">

<img width="1044" alt="screenshot-2" src="https://user-images.githubusercontent.com/59660253/127199477-3dfdd6ac-24c5-461b-944d-625356541bf2.png">

Thank you for your prompt response.

**Comment by pbking** [comment] 2021-07-28 13:15
Since yesterday I have found this issue happening in another environment but have been unable to reproduce locally.  I'm experiencing exactly what you describe there though, and knowing that colors are persisting is very helpful and ensures I'm working on the same problem.  [This](https://github.com/Automattic/themes/pull/4336) seemed related but fixing it seems to have more easily uncovered this issue (whatever it turns out to be).

I'm continuing to dig into this today.  Thank you @tinjure20 for reporting and providing additional information.

**Comment by pbking** [comment] 2021-07-28 13:23
Note, you MAY also be experiencing [this issue](https://github.com/WordPress/gutenberg/issues/33681) which has a [temporary work-around](https://github.com/WordPress/gutenberg/issues/33681#issuecomment-887441698).

**Comment by pbking** [comment] 2021-07-28 13:57
Further research points to this being a problem with the User Theme JSON being sanitized of any data not fitting the theme JSON schema.  This seems to strip both the `settings.typography.fontFamilies` but also the entirety of `settings.custom` values.  The Font Customization is dependent on the user controlling these values.

I'm unsure which combination of versions and environment conditions cause this strict sanitization to happen, but I have been unable to reproduce this locally with the same version of WordPress and Gutenberg though it is happening on wpcom.

**Comment by tinjure20** [comment] 2021-07-28 17:17
Hmmm, I wonder why it can't be replicated. I am using MacOS machine, Local version 6.0.0. Gutenberg plugin is active and enable site editor OFF.

Font display in [this Maggie's demo Quadrat site](https://wp-themes.com/quadrat/) looks similar in my browser (browser default ) not `theme.json` defined `dm-sans`.

Because this is my learning project only, I would wait for a permanent fix from you guys. Thank you

**Comment by MaggieCabrera** [comment] 2021-07-28 17:22
The frontend issue seems to be related to the [GB issue](https://github.com/WordPress/gutenberg/issues/33681) that Jason pointed, since other themes are affected as well that don't provide any customizer options at all (I had it happen on emptytheme too). The workaround works on my current environment for that if you want to keep testing. Hopefully the GB issue will get a fix soon.

**Comment by tinjure20** [comment] 2021-07-28 18:42
Thank you @MaggieCabrera and @pbking. The simple [temp-workaround](https://github.com/WordPress/gutenberg/issues/33681#issuecomment-887441698) works like a charm!

**Comment by tinjure20** [comment] 2021-07-29 01:16
One other issue I had noted together with FontFamily was use of [clamp()](https://developer.mozilla.org/en-US/docs/Web/CSS/clamp()) function defining custom layout `contentWidth` and fontSize in `theme.json`.  

While playing with Quadrat v1.1.0 and Blockbase v1.1.0, I was using `clamp()` defining custom layout `contentWidth` (inspired by this [post](https://piccalil.li/quick-tip/use-css-clamp-to-create-a-more-flexible-wrapper-utility/)) and `fontSize`. 

For example, for layout as:

```
"layout": {
	"contentSize": "clamp(16rem, 90vw, 58rem)",
	"wideSize": "clamp(16rem, 90vw, 80rem)"
},
```

and for h1 fontSize as:

```
"h1": {
       "fontSize": "clamp(48px, 7vw, 80px)"
}
```

Both worked fine before the 5.8 updates. After the updates, the layout `contentWidth` with `clamp()` does not work but `fontSize` with `clamp()` works just fine.

This probably is a minor issue, also related to [GB](https://github.com/WordPress/gutenberg), but thought to share with your team. Thank you

**Comment by pbking** [comment] 2021-07-29 03:23
Cool, since the temp-workaround fixed what ailed you I'm going to close this as a dupe of [33681](https://github.com/WordPress/gutenberg/issues/33681). Hopefully that doesn't take long to fix.  

Thanks for the heads up about the troubles with `clamp()`.  We haven't used it in Blockbase themes yet but it's something to be considered.  And I hadn't considered using it for values of layout!  That's a really neat idea.

**Closed as completed by pbking** 2021-07-29 03:23 UTC
