### ISSUE TITLE
Skatepark: Social Links navigation is not properly aligned on desktop

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4590] opened 2021-09-14 18:25 UTC
It's a little too high, and a little off to the right. 

---

Current:

<img width="884" alt="Screen Shot 2021-09-14 at 2 24 47 PM" src="https://user-images.githubusercontent.com/1202812/133312884-a59c7224-1a9a-48e0-8386-34bd3927a5cf.png">

Intended: 

<img width="880" alt="Screen Shot 2021-09-14 at 2 24 29 PM" src="https://user-images.githubusercontent.com/1202812/133312899-700d0c2b-8353-43a2-8081-937fc3fc9fab.png">

**Comment by kjellr** [comment] 2021-09-22 14:18
Following [my comments in the PR](https://github.com/Automattic/themes/pull/4635#issuecomment-924932762), I'm going to reopen this until we can confirm that it's fixed.

**Comment by scruffian** [comment] 2021-10-12 13:44
This should be fixed by https://github.com/Automattic/themes/pull/4482

**Comment by pbking** [comment] 2021-10-12 17:08
Confirmed that #4482 does address this.  

![image](https://user-images.githubusercontent.com/146530/136999686-d8f3e788-7e58-4a27-bd3d-eeb1982357a7.png)

Closing.

**Comment by melchoyce** [comment] 2021-10-12 17:46
Seeing the opposite problem now, where the menu has extra space on the right:

![image](https://user-images.githubusercontent.com/2846578/137004431-a363b4be-25a5-4c3e-9858-e03cf87b5541.png)

**Comment by mikachan** [comment] 2021-10-27 10:25
I think this is fixed again, but I'd appreciate if someone else could check as well in case I'm doing something wrong.. This is what I can see currently on trunk:

![image](https://user-images.githubusercontent.com/1645628/139048327-02f23dc1-2d9d-4ec9-91e9-331adad68b77.png)

**Comment by beafialho** [comment] 2021-10-27 11:59
I see the same as @mikachan, it looks as intended.

**Closed as completed** 2021-10-27 12:22 UTC
Labels: [Type] Bug, [Theme] Skatepark
