### ISSUE TITLE
The + icon on the Navigation Menu doesn't add menu items in the Blockbase themes

### ISSUE THREAD

**Issue by happychait** [Automattic/themes#6162] opened 2022-07-06 04:45 UTC
### Quick summary

In the Site Editor, selecting the Navigation Menu block and clicking the + icon only brings up this toolbar, but we can't create new menus, or add menu items.

![Captured at 06-07-2022 at 16 34 24@2x](https://user-images.githubusercontent.com/1519466/177470774-8e0ebfec-4f1d-404e-bf40-2281bbcfd40b.png)

### Steps to reproduce

1. Open the Site Editor
2. Select the Navigation menu block in the header
3. Click the + icon on the Navigation block to add menu items.

### What you expected to happen

`Add link` option should be added to the Navigation block as in this screenshot:  
![Captured at 06-07-2022 at 16 38 51@2x](https://user-images.githubusercontent.com/1519466/177470798-f5757bd5-09d8-45b3-bedc-bf5236d62caa.png)

### What actually happened

1. The + icon simply pulls up the block's toolbar which can only be hidden by selecting the Navigation Menu block in the List View and hitting the Escape key.
2. No way to add menu items.

Video of what happens:

https://user-images.githubusercontent.com/1519466/177470195-d05f4fc6-bf24-4b58-9837-51c77fe6ae5a.mp4

A few screenshots showing the issue:
![Captured at 06-07-2022 at 16 00 43@2x](https://user-images.githubusercontent.com/1519466/177470987-960d2c19-99a8-49b9-8438-1fcc1546098e.png)

![Captured at 06-07-2022 at 16 01 20@2x](https://user-images.githubusercontent.com/1519466/177471051-98a914ce-37fc-40ce-8bed-d5980fa05178.png)

### Context

Discovered this bug while trying to help the user add the Navigation Menu from the Site Editor in 35992415-hc

Also confirmed the bug in exploratory testing.

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Yes, seems to be specific to the Blockbase and all its child themes.

### Reproducibility

Consistent

### Available workarounds?

Yes, easy to implement

### Workaround details

We can workaround by:

1. Choosing the `Top toolbar` option for the Site Editor preferences.
2. Editing the Navigation Menu from the template or template parts editor instead of the Site Editor.

**Comment by jordesign** [comment] 2022-07-06 05:15
📌 SCRUBBING
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

On Atomic and Self Hosted - the error was only present with the Gutenberg plugin activated

📌 FINDINGS/SCREENSHOTS/VIDEO

I was able to recreate this consistently when Blockbase and the Gutenberg plugin were both active

📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Closed as could not replicate (please reopen the issue reoccurs)
- Transferred to Themes Repo

**Comment by getdave** [comment] 2022-07-06 09:58
I tested this on Gutenberg Core `trunk` using `Empty Theme` theme and I wasn't able to reproduce.

That said there are a number of bugs with the popover that seem to have been introduced as a result of the upgrade to the core component's underlying library. One of these is that [the block toolbar is appearing over the top of the Nav block](https://github.com/WordPress/gutenberg/issues/41575). You can also see the Link UI disappearing off screen.

Not sure if those issues are related to what you're seeing here.

https://user-images.githubusercontent.com/444434/177524792-5ef42488-271c-4a10-a8bb-8de1372d5337.mp4

**Comment by happychait** [comment] 2022-07-06 23:20
@getdave In your video, the `Top toolbar` option is selected in your block editor, and hence the issue can't be reproduced. So that's another workaround as @tanjoymor  helped find it originally.

Edited the issue description and included this second workaround.

**Comment by pbking** [comment] 2022-07-07 14:56
I didn't realize this was Blockbase specific.  I thought that this was the behavior of the Navigation Block.  I'll look into this today; thank you for all the details.

**Comment by pbking** [comment] 2022-07-07 15:28
I don't believe this is an issue with Blockbase per-se.  It happens with Blockbase but I believe because of the layout of the header.  The navigation is so close to the top that the panel hides the button.  If I introduce space above then everything works as expected.  When Gutenberg is de-activated the panel in question is rendered below the navigation which I expect is the correct behavior for a block in that position.

<img width="1275" alt="image" src="https://user-images.githubusercontent.com/146530/177811806-7da39111-6a13-4e84-8d09-56ae019d4854.png">

I observed the same behavior on Pendant which is not a Blockbase child theme but has a header with navigation a similar distance from the top of the page.

<img width="560" alt="image" src="https://user-images.githubusercontent.com/146530/177812099-79d17bda-8a8c-4947-96ac-8d4b23ef876e.png">

This seems to be properly[ represented in the issue ](https://github.com/WordPress/gutenberg/issues/41575)that @getdave mentioned above.

**Comment by tanjoymor** [comment] 2022-07-07 19:03
@pbking You are totally right! I just retested on Twenty Twenty-Two and if I move the Navigation block to the very top the same issues occur. As a point of interest, Simple sites (that don't have access to plugins) can't deactivate Gutenberg.

**Comment by pbking** [comment] 2022-07-08 13:42
Going to close this considering the above.  Hopefully this gets resolved via[ Gutenberg #41575 soon](https://github.com/WordPress/gutenberg/issues/41575)!  It makes using that nav block extra hard!

**Closed as completed by pbking** 2022-07-08 13:42 UTC
Labels: [Type] Bug, [Pri] High, [Theme] Blockbase, Triaged
