### ISSUE TITLE
Apostrophe 2: Blog list not generating complete list

### ISSUE THREAD

**Issue by ricklabsdotn8** [Automattic/themes#8335] opened 2024-11-04 03:38 UTC
### Quick summary

The endless post loading on the front page only loads a limited number of posts

### Steps to reproduce

1. Activate Apostrophe 2
2. Set the front page to display posts under Settings → Reading
3. View home page

### A clear and concise description of what you expected to happen.

The post list uses endless loading and should load posts as you scroll

### What actually happened

The list only generates a few posts

### Impact

Most (> 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

8987379-zen

**Comment by renatho** [comment] 2024-11-04 15:02
Hi @ricklabsdotn8!

I see the issue on the user's site, but I could not reproduce the issue. See a video with my test (simulating a slow connection):

https://github.com/user-attachments/assets/e658ae5d-c245-498b-b015-bac1a7958592

I see that you could reproduce the issue on your test site. Could you try to deactivate the plugins you have in this test site to see if it could be related to a specific plugin?

> Set the front page to display posts under Settings → Reading

About this step, I didn't do anything since by default it was displaying the posts to me. Could I be missing something here?

![Image](https://github.com/user-attachments/assets/dc2347df-db8b-4228-bf31-5a5d37461ef1)

**Comment by ricklabsdotn8** [comment] 2024-11-05 10:51
Hi @renatho, did a plugin conflict test, and it appears the issue is coming from WooCommerce. Thanks for taking a look.

**Comment by renatho** [comment] 2024-11-05 12:31
Thanks, @ricklabsdotn8! So I'm closing the issue here. Could you open a new issue in the WooCommerce repository with the details you found?

**Closed as completed by renatho** 2024-11-05 12:31 UTC
Labels: [Type] Bug, [Pri] High, Needs triage, [Platform] Atomic, [Status] Priority Review Triggered, Customer Report, Groundskeeping

**Comment by ricklabsdotn8** [comment] 2024-11-11 00:47
Here is the bug report on WC - https://github.com/woocommerce/woocommerce/issues/52690
