### ISSUE TITLE
No styling/hover effects on buttons on live view, works in preview. Hever theme

### ISSUE THREAD

**Issue by radtechgh** [Automattic/themes#7338] opened 2023-08-30 12:48 UTC
### Quick summary

Button styles in edit view works, they have hover and color styles. When viewing on live view, buttons are not styled the same, and they are colored black. No hover color.
Edit view:
<img width="671" alt="Screenshot on 2023-08-30 at 08-42-20" src="https://github.com/Automattic/themes/assets/8058729/73767cf9-a1c9-47fb-bb28-586b5c710827">
Live view:
<img width="780" alt="Screenshot on 2023-08-30 at 08-43-05" src="https://github.com/Automattic/themes/assets/8058729/376efcc5-71b2-4d0d-aa46-d393cb50906e">

### Steps to reproduce

1. change theme to Hever.
2. add page or post with buttons
3. view live or preview, buttons are not styled correctly.

### What you expected to happen

buttons should look the same in live view, and should have a hover color change

### What actually happened

buttons are rounded, and black in color. No hover color change.

### Context

Customer report. AT site testing

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by radtechgh** [comment] 2023-08-30 12:49
6644591-zen

**Comment by cuemarie** [comment] 2023-08-30 19:14
Closing as duplicate of 

- https://github.com/Automattic/themes/issues/7309

@radtechgh deactivating Page Optimize is a workaround to this issue.

**Closed as not planned by cuemarie** 2023-08-30 19:14 UTC
Labels: [Type] Bug, [Pri] Normal, [Theme] Hever, Triaged, [Status] Duplicate, Customer Report, [Feature Group] Appearance & Themes
