### ISSUE TITLE
Not possible to change page/post templates when `Peirao` theme is active

### ISSUE THREAD

**Issue by ClassicRKR27** [Automattic/themes#7766] opened 2024-04-23 20:12 UTC
### Quick summary

User should be able to switch the templates that their pages/posts are using, but in the course of this conversation I found that this is a bug with this theme: 8087247-zd-a8c

### Steps to reproduce

1. Activate the `Peirao` theme on any WordPress.com site
2. Try to edit either a page or post by changing the template - you'll see that there is no option to switch the template: ![ygaqq1.png](https://github.com/Automattic/themes/assets/51870544/db2cf45c-790e-4573-b925-bc2bd7fc85e7)

### What you expected to happen

Users should be able to switch their page/post templates

### What actually happened

It is not possible to switch the templates

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

None

**Comment by liviopv** [comment] 2024-04-30 15:15
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
Simple site
https://github.com/Automattic/themes/assets/14153300/04d8f588-ffae-4b78-87cd-c96b996466d0

Same as the above on Atomic

📌 ACTIONS
- Closed as by design 

📌 Message to Author
@ClassicRKR27 that's the expected behavior, unless I'm missing some context from the interaction.

As you can see, once I add a custom template, the "Swap Template" option shows up for both Post and Pages.

Looking at the user's site, they don't have any custom template that can be applied to any post/page, so it's correct for them to only see "Edit Template" and "Create New Template".  

They only have a [custom template for a specific page, "Instruction"](https://ipbsf6.wpcomstaging.com/wp-admin/site-editor.php?path=%2Fwp_template&activeView=ipbfarley&isCustom=false)

**Comment by ClassicRKR27** [comment] 2024-04-30 15:22
@liviopv are we sure this is by design? Because the `Swap Template` option appears in other themes with no custom templates: ![SPahWM.png](https://github.com/Automattic/themes/assets/51870544/6b406f85-2b5f-4fe0-92c5-6c02262eab01)

The above is with the `Cakely` theme, and for the `Peirao` theme it's still not possible to swap templates even once a custom template has been created.

**Comment by liviopv** [comment] 2024-04-30 15:24
@ClassicRKR27 Cakely has two custom Page Templates bundled in the theme, unlike Peirao:

![CleanShot 2024-04-30 at 16 23 20@2x](https://github.com/Automattic/themes/assets/14153300/a44200b0-77e9-4df7-9a20-654516272e91)

**Comment by ClassicRKR27** [comment] 2024-05-01 13:09
@liviopv in that case, why is the option to swap templates not appearing for this user when they _do_ have a custom template? ![BfDZZM.png](https://github.com/Automattic/themes/assets/51870544/4b2ba215-71d7-4bfb-af7b-484ce8aa9eb4)

If this is expected behavior, then it's very confusing - it's not clear why some themes come with custom templates and some don't, there doesn't seem to be any indication of _why_ they're not able to switch templates when there isn't a custom template created.

**Comment by liviopv** [comment] 2024-05-01 14:19
@ClassicRKR27 That template is for a specific page, Instruction, as mentioned at the end of my first message. 

> If this is expected behavior, then it's very confusing - it's not clear why some themes come with custom templates and some don't, there doesn't seem to be any indication of why they're not able to switch templates when there isn't a custom template created.

You're welcome to share that feedback on https://github.com/WordPress/gutenberg/issues just make sure to avoid sharing any a8c-related information.

That said, the behavior makes sense to me, as "Swap Template" only shows up when there's a template to swap to:

- Custom or theme template that can be applied to pages or posts exists > "Swap Template" and "Create New Template" show up
- No available template > only "Create New Template" shows up.

In cases like Peirao where there's no template to "Swap" to, where would the "Swap Template" link to?

**Closed as completed** 2024-05-01 14:20 UTC
Labels: [Type] Bug, Triaged, [Pri] TBD, Customer Report, [Feature Group] Appearance & Themes
