### ISSUE TITLE
Natural: Fig Captions are aligned left when image block is set to Centered

### ISSUE THREAD

**Issue by villanovachile** [Automattic/themes#3850] opened 2021-05-12 22:29 UTC
## Steps to replicate
1. Create Image block
2. Enter fig caption
3. Align as Centered

The current workaround seems to be to deselect center/left/right alignment, and fig caption defaults to center alignment.

![](https://d.pr/i/SpLLKF+)
Image Link: https://d.pr/i/SpLLKF

## Result

The result was a left aligned fig caption

![](https://d.pr/i/bNiQaT+)
Image Link: https://d.pr/i/bNiQaT

## Expected

I expected the fig caption to be centered:

![](https://d.pr/i/i8YGbu+)
Image Link: https://d.pr/i/i8YGbu

* User report: 10984343-hc
* Follow-up ticket: 3985466-zen

**Comment by Sandkorner** [comment] 2021-08-04 08:40
Same issue.

User Report: 4190078-zen
Theme: Hemingway Rewritten

Would have offer custom CSS solution to (text-align: center; ), but Personal plan.

**Comment by rw-ye** [comment] 2021-12-13 08:59
Another report here: 32773571-hc

Theme: Hemingway Rewritten

Provided a CSS workaround:

```
/* Center captions under images | 32773571-hc RW */
.wp-block-image .aligncenter>figcaption {
text-align: center;
}
```

**Comment by kylemcph** [comment] 2021-12-30 14:59
Looks like this is a duplicate of issue #2938, which has been closed and moved to Trac.

**Comment by kylemcph** [comment] 2021-12-30 15:01
User report: 29883060-hc
Theme: Natural

What I found was the image captions only displayed incorrectly when the image was set as to "Align center". When we changed alignment to "None", the captions displayed correctly.

We also found that the images were displayed correctly via Firefox, but incorrectly via Chrome and Safari.

Provided workaround to set image alignment to "None".

**Comment by kylemcph** [comment] 2021-12-30 15:01
Looks like this is a duplicate of issue Automattic/themes#2938, which has been closed and moved to Trac.

**Comment by marianearchimbaud** [comment] 2022-10-25 14:51
I see the same issue on Baskerville 2 theme.
The issue was reported here: 36947902-zd

I shared this code with them to solve this in the meantime:

```
/* Center captions under images | 5658274-hc MA */
.wp-block-image.aligncenter>figcaption {
    display: block;
}
```

**Comment by cuemarie** [comment] 2023-03-11 19:49
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple: **Could not replicate**

📌 FINDINGS/SCREENSHOTS/VIDEO
- Natural is a retired premium theme, and I was not able to replicate this issue anymore.

**Simple Example**
![Markup on 2023-03-11 at 12:37:55](https://user-images.githubusercontent.com/27249804/224508461-c35a2d87-e518-4733-bffe-26fcb76b6bb0.png)

📌 ACTIONS
- Closed as could not replicate (please reopen the issue reoccurs **on theme this theme**)

📌 Message to Author
- HEs please do not reopen this issue for other themes - create a new report for that specific theme, or for multiple themes if you can replicate it across other themes.
- I've opened a specific issue report for **Hemingway Rewritten**, as that is the only theme where I could replicate this issue: https://github.com/Automattic/wp-calypso/issues/75934

**Closed as completed** 2023-03-11 19:49 UTC
Labels: [Type] Bug, Premium, Images
