### ISSUE TITLE
[Bug] Varia Child Themes: Default Colors Unset

### ISSUE THREAD

**Issue by rosepajaroja** [Automattic/themes#7661] opened 2024-02-24 10:10 UTC
### Quick summary

The background color of the navigation bar and social icons were changed to white preventing the navigation links to be visible. The demo site is affected - https://shawburndemo.wordpress.com/.

![Screen Shot on 2024-02-24 at 18:10:48](https://github.com/Automattic/themes/assets/9984867/b01bd09e-2592-4487-8284-49b43bb0f203)

### Steps to reproduce

1. Go to Appearance → Themes → Shawburn → Activate theme
2. Preview website

### What you expected to happen

The colors will be the same as on the preview image. https://d.pr/i/HBmnw1/oY2QiHnKK1

### What actually happened

1. Social icons are white on white background. 
2. Navigation links are in white fonts on white navigation bar background. 

### Browser

Mozilla Firefox

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Other notes

Issue happening both in simple and atomic sites, as well as demo site. 

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

### Workaround details

1. Go to Appearance → Customize → Colors & Background
2. Click "Default" button for Colors.

**Comment by cselamor** [comment] 2024-02-24 14:47
zen-7787369

**Comment by mahfuzurwp** [comment] 2024-02-24 17:14
Here is another report but the user is using a different theme. 7787369-zen

**Comment by Aurorum** [comment] 2024-02-24 18:32
7789076-zen

**Comment by Aurorum** [comment] 2024-02-24 19:18
This is a Varia problem, not just Shawburn. Reported with Hever here - 7788731-zen

**Comment by Aurorum** [comment] 2024-02-24 19:21
7789408-zen - Morden. Definitely a Varia problem.

**Comment by Aurorum** [comment] 2024-02-24 19:26
7789361-zen 

This deffo needs to be top priority for theme backlog

**Comment by Aurorum** [comment] 2024-02-24 19:42
7788132-zen 
7789127-zen
7788699-zen
7788564-zen

**Comment by Mfarroq1** [comment] 2024-02-25 08:38
7788981-zen same issue with hover theme

**Comment by Aurorum** [comment] 2024-02-25 09:43
7790898-zen

**Comment by Aurorum** [comment] 2024-02-25 09:49
7791045-zen

**Comment by Aurorum** [comment] 2024-02-25 10:04
Some users in those tickets are reporting more than just colour losses:

> Not only have the colors changed, I have lost everything I had laid out, colors, fonts, menus... there is nothing left and I want them to restore it just as it was 3 days ago.

**Comment by anthcodes** [comment] 2024-02-25 11:22
7791200-zen 

Was able to restore their colors using the default, looks to be working as expected again here.

**Comment by mariammcWP** [comment] 2024-02-25 14:40
7791496 - zen

**Comment by anthcodes** [comment] 2024-02-25 16:54
7792036-zen

restored default on this one also

**Comment by Aurorum** [comment] 2024-02-25 20:08
7787186-zen

**Comment by rajwpdev117** [comment] 2024-02-26 08:39
7793202 - zen

Hever theme child theme of the Varia themes.

**Comment by jromales** [comment] 2024-02-26 13:14
7794270-zd-a8c - using Stow theme

**Comment by AlexanderSky** [comment] 2024-02-26 17:35
7793052-zen Hever theme

**Comment by AlexanderSky** [comment] 2024-02-26 18:05
7797188-zen Barnsbury theme - child of Varia

**Comment by OgeAmadi** [comment] 2024-02-26 18:19
7797078 - _Barnsbury (Free) Theme_

**Comment by OgeAmadi** [comment] 2024-02-26 18:20
7796313 - _Shawburn (Free) Theme_

**Comment by adelineyaw** [comment] 2024-02-26 20:06
7797835-zen - Shawburn Theme

**Comment by isocialtish** [comment] 2024-02-26 23:33
7798612-zd (Shawnburn theme) It's a pretty bad bug "This is really concerning and Im literally getting yelled at about this...about how this can happen"

**Comment by rinazrina** [comment] 2024-02-27 01:48
Encountered in: 

- 7799199-zd-a8c
- 7798971-zd-a8c

Both are using Shawburn theme.

**Comment by rinazrina** [comment] 2024-02-27 02:31
Another one with Shawburn: 7799301-zd-a8c

**Comment by jromales** [comment] 2024-02-27 06:12
7799967-zd-a8c - two sites affected, using Shawburn

**Comment by AlexanderSky** [comment] 2024-02-27 07:08
7793269-zen Stow theme

**Comment by OgeAmadi** [comment] 2024-02-27 07:47
7798860 - _Exford (Free)_

**Comment by Aurorum** [comment] 2024-02-28 16:45
7793629-zen

**Comment by cat-og** [comment] 2024-03-01 06:58
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
 This has occurred across various Varia Child themes including, but not limited to:
  - Barnsbury
  - Exford
  - Hever
  - Morden
  - Shawburn
  - Stow
  - Stratford

The provided workaround works consistently, as does setting any new color in the customizer.  

📌 ACTIONS
- Triaged
- Renamed for clarity

**Comment by cat-og** [comment] 2024-03-01 07:04
7798620-zd-a8c

**Comment by Aurorum** [comment] 2024-03-02 09:36
7821270-zen - user cancelled their subscription because of this bug

**Comment by Aurorum** [comment] 2024-03-02 13:12
Several reports in the forums too - here's a couple, all with Varia child themes:

- https://wordpress.com/forums/topic/shawburn-theme-menus-suddenly-invisible-unless-clicked/
- https://wordpress.com/forums/topic/why-are-my-menu-items-hidden/
- https://wordpress.com/forums/topic/barnsbury-theme-default-green-header-not-showing/
- https://wordpress.com/forums/topic/text-formatting-across-website-lost/

**Comment by Aurorum** [comment] 2024-03-02 13:14
Just adding missed interactions: 7796313-zen 7797078-zen 7793202-zen 7798860-zen

**Comment by fgelsano** [comment] 2024-03-07 01:56
7791006-zen, reported here. HC helped them to set it to default but now it changes the fonts and the banner photo becomes blurry. I'm trying to replicate it but no luck.

**Comment by donnapep** [comment] 2024-11-15 15:06
Closing as this is no longer reproducible. The [Shawburn demo site](https://shawburndemo.wordpress.com/) is no longer showing the issue and I can't reproduce on Atomic either.

**Closed as completed by donnapep** 2024-11-15 15:06 UTC
Labels: [Type] Bug, [Theme] Varia, [Theme] Morden, [Theme] Exford, [Theme] Hever, [Theme] Shawburn, [Theme] Stratford, [Theme] Barnsbury, Needs triage, [Interaction #] > 20, Customer Report, [Feature Group] Appearance & Themes
