### ISSUE TITLE
Karuna: post author not shown if only one

### ISSUE THREAD

**Issue by tvolpert** [Automattic/themes#6084] opened 2022-06-11 20:00 UTC
### Quick summary

In the `Karuna` theme, when there's only one author for your published posts, the author name will not be displayed on blog index pages, even when the box is checked in the customizer. Changing any published post to have a different author will cause them to be displayed, even if that particular post doesn't appear in the list (IE it's too old)

### Steps to reproduce

1. activate `Karuna` on any site (simple or atomic), preferably without too many posts by different authors, for ease of testing
2. have at least two users, but only write posts under one username to start
3. make sure you have either the homepage showing latest posts, or a separate blog page with a post list
4. navigate to the Appearance > Customize > Content Options, and verify that `Display author` is checked under `Post Details`
5. The author name will not be visible in the feed:
![Annotation on 2022-06-11 at 14-46-39](https://user-images.githubusercontent.com/34486913/173202896-47e73ffc-e705-4110-8dd5-437b63d489c5.png)
6. Change any one post to be by a different author: 
![Annotation on 2022-06-11 at 14-47-20](https://user-images.githubusercontent.com/34486913/173202913-c393aa0f-fec2-4a15-b5ba-a9dc5eb6e34c.png)
7. view the site again, and the author names should be shown: 
![Annotation on 2022-06-11 at 14-56-20](https://user-images.githubusercontent.com/34486913/173202986-e8dd0982-d821-409d-90e8-c694f8efbab2.png)

### What you expected to happen

The author name should be displayed when the box is checked, regardless of how many authors have contributed to the site

### What actually happened

The author name is not displayed if only one author has contributed

### Context

Reported in #35746201-hc and confirmed by my own testing.

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Karuna

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

This can be remedied by changing the authorship of any public post, but some users may want this information shown even if they don't have any other authors on the site. Also, they may not want to either share credit for something they've written, or create a dummy post in their feed.

**Comment by Gustavo-Hilario** [comment] 2022-07-18 14:09
I was able to reproduce this. However, isn't this the correct and expected behavior? On the Customizer, it says we can enable post author on the single posts page:

<img width="379" alt="Markup 2022-07-18 at 10 57 11" src="https://user-images.githubusercontent.com/50875131/179529873-88fad59e-88cf-4d91-bf67-cc2d1626dac7.png">

I can see Karuna shows the author on the single posts page ([example](p7BJtq-4c-p2)) but not on the blog index page ([here](https://karunademo.wordpress.com/blog/)). If a user wants to show the author on the blog page, they can consider creating a new blog page using the `Query Loop` or `Blog Posts` block.

If the site can use CSS, it might help too:

```
.byline {
  display: inline;
}
```

**Comment by kathrynwp** [comment] 2022-07-18 15:44
> The author name is not displayed if only one author has contributed

This is not a bug, but the **intended behaviour** – in fact, it was a common convention in many themes, a number of years ago. The logic was that there's no need to keep repeating the same author's name over and over on a blog that only has one author. You can see that intended behaviour in the CSS in this theme, and others from the same era:

```
.byline,
.updated:not(.published) {
	display: none;
}

.single .byline,
.group-blog .byline {
	display: inline;
}
```

This behaviour isn't going to be revisited on an old theme at this late stage, as it would affect existing sites. In addition, enhancements on old themes is not a priority for the theme team, given limited resources.

Closing as a wontfix.

**Closed as not planned by kathrynwp** 2022-07-18 15:44 UTC
Labels: [Type] Enhancement, [Status] wontfix, [Pri] Low, [Theme] Karuna, Triaged
