### ISSUE TITLE
Blockbase (+ Quadrat) color changes made via Customizer do not reflect on wpcom

### ISSUE THREAD

**Issue by jffng** [Automattic/themes#4197] opened 2021-07-09 16:02 UTC
## Steps to replicate

1. Go to the site editor on wpcom
2. Change some colors in the palette
3. Verify they show up in the front-end
4. Go to the customizer (/wp-admin/customize.php) and change some colors or select a palette other than the default. 
5. Save and refresh, or view the front-end

## Result

The colors return to the default palette

## Expected

The color changes from the Customizer to be reflected everywhere.

**Comment by scruffian** [comment] 2021-07-15 12:13
This is now working for me, but I do see a delay in them being changed - I guess if we add that caching PR that might solve the delay, but I'd like someone else to try as I couldn't replicate the problem before :)

**Comment by pbking** [comment] 2021-07-15 14:50
This was still broken for me. The behavior was unchanged.  Then I used the site editor to "reset to default".  Once done my user JSON was reset.  Once I attempted to persist the color change again things then worked as expected. 

Well, with the exception of the cacheing.  This time I DID experience the color cache issue.  It took a couple of minutes and a few refreshes before I saw the color change in the view.  It did update in the FSE immediately after changing in the customizer.

**Comment by scruffian** [comment] 2021-07-15 14:52
@pbking can you test with https://github.com/Automattic/themes/pull/4181 to see if that resolves the caching issue for you?

**Comment by pbking** [comment] 2021-07-15 15:03
I can, and I did, and it does!

**Comment by scruffian** [comment] 2021-07-15 15:07
great, shall we merge it?

**Comment by scruffian** [comment] 2021-07-16 10:19
I think we can close this now, but I'd appreciate another pair of eyes.

**Comment by pbking** [comment] 2021-07-19 18:41
This is currently working as expected for me on .com.  I'm closing this now; we'll reopen if it happens again.

**Comment by jffng** [comment] 2021-07-26 16:12
Re-opening, and revising the title as this is will ultimately be resolved in blockbase.

**Comment by jffng** [comment] 2021-07-26 16:38
I did some light debugging, and it looks like the `settings.color.palettes.user` of the theme.json is getting wiped out.

When I select a palette, it looks like that data is saved (note the selected border state), however the colors themselves are not:

<img width="289" alt="Screen Shot 2021-07-26 at 12 37 05 PM" src="https://user-images.githubusercontent.com/5375500/127026057-80b738dd-6435-41ae-84c9-5b465b481e6c.png">

**Comment by pbking** [comment] 2021-07-27 05:10
I've been unable to reproduce this on wpcom.  Attempted with all Blockbase themes.

The behavior you describe is what was happening to me when it was happening to me (the radio button selection was stored in theme_mod but the JSON was nulled out).  I was unable to store color OR font information.

But it's been behaving for me now and I cannot reproduce.

**Comment by pbking** [comment] 2021-07-28 13:58
I BELIEVE that this was part of the problem, but also related is [this issue ](https://github.com/Automattic/themes/issues/4334)which will fix the font-related aspect.

**Comment by pbking** [comment] 2021-07-29 14:00
Part of the problem was happening because (for reasons unknown) the User Theme JSON was getting wiped out and losing some metadata.  [This PR](https://github.com/Automattic/themes/pull/4336) has addressed that.
That has now revealed another related issue where the values to customize the fonts are not being persisted in the User Theme JSON.  [This issue](https://github.com/WordPress/gutenberg/issues/33759) describes that situation a bit more fully.

**Comment by pbking** [comment] 2021-08-12 16:49
I believe all aspects of this have been addressed and this can now be closed.

When the user theme JSON is unfortunate to enter a "null" state #4336 allows customizations to continue.
Somewhat related font customization problems were addressed in #4389

**Closed as completed by pbking** 2021-08-12 16:49 UTC
Labels: [Type] Bug, [Theme] Quadrat
