### ISSUE TITLE
Themes: More block not displaying

### ISSUE THREAD

**Issue by kspilarski** [Automattic/themes#4789] opened 2021-10-03 09:22 UTC
### Quick summary

More block can be added in the post editor, but it's not displaying in the  Blog / Posts page.

### Steps to reproduce

1. use any of these themes 
- Twenty Twenty
- Twenty Twenty One
- Twenty Nineteen
- Barnsbury 
- Alves 
- Mayland 
- Seedlet 
- Maywood 
- Balasana 
- Baker
- Pollard
- Spearhead 
- Dalston
- Rivington
- Storefront
- Astra

2. Create or edit post  
3. add More block 
4. Update or publish
5. View Blog  / Posts page. 

### What you expected to happen

Read more is displayed in posts in the Blog / Posts page.

### What actually happened

Read more is not displayed in posts in the Blog / Posts page.

### Context

Customer report and self-testing.

Editor: 
<img width="1351" alt="Screen Shot 2021-10-03 at 11 38 06 AM" src="https://user-images.githubusercontent.com/36863633/135748126-18cbcc91-d97f-4f56-a70a-3fa0b4b0ded5.png">

Blog / Posts page:
<img width="550" alt="Screen Shot 2021-10-03 at 11 38 45 AM" src="https://user-images.githubusercontent.com/36863633/135748145-4b0ba076-3a71-47c9-825c-e0a66ffeb68e.png">

### Operating System

macOS

### Browser

Mozilla Firefox

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

- Twenty Twenty
- Twenty Twenty One
- Twenty Nineteen
- Barnsbury 
- Alves 
- Mayland 
- Seedlet 
- Maywood 
- Balasana 
- Baker
- Pollard
- Spearhead 
- Dalston
- Rivington
- Storefront 
- Astra

### Severity

All

### Available workarounds?

Read more plugin, or use another theme.

**Comment by synora** [comment] 2021-10-05 14:08
Triaged. Can also replicate with the Sigler theme.

**Comment by kspilarski** [comment] 2021-10-17 13:39
4362387-zd, Twenty Nineteen theme.

**Comment by helenaartmann** [comment] 2021-11-03 01:04
32391243-hc, Hemingway Rewritten theme.

**Comment by jordesign** [comment] 2021-12-03 03:42
Confirming this behaviour - but unsure if this is an opinionated preference that is up to each theme? Flagging it for discussion - and if it is something that is prioritised - we may need issues for each of the themes we can change it for.

**Comment by nagpai** [comment] 2021-12-16 06:04
One more case - Barnsbury - 33220379-hc

**Comment by zdenys** [comment] 2022-02-11 13:59
Another case in 4767663-zd-woothemes. Theme Ryu. I also tested this on my site and Twenty Twenty Two is affected as well.

**Comment by scruffian** [comment] 2022-02-14 09:41
Given that this is an issue for so many themes, its probably a gutenberg issue rather than a theme issue.

**Comment by madhusudhand** [comment] 2022-03-04 11:43
This seems to be working fine except for the following
* Twenty Twenty One
* Twenty Twenty Two

<img width="473" alt="image" src="https://user-images.githubusercontent.com/1935113/156755536-85e16822-d4d9-40d7-a8e1-f193d579ecef.png">

@kspilarski Can you confirm?

**Comment by jromales** [comment] 2022-03-20 08:35
Another report in 4876576-zd-woothemes where I suggested using a "Read more" plugin as workaround.  They are using the `Geologist` theme.

**Comment by madhusudhand** [comment] 2022-03-22 11:29
I believe the way read more block works with Gutenberg is slightly different.
For more context please refer the below comment.

https://github.com/WordPress/gutenberg/issues/27214#issuecomment-822410291

**Comment by jamiepalatnik** [comment] 2022-04-07 00:53
> Another case in 4767663-zd-woothemes. Theme Ryu. I also tested this on my site and Twenty Twenty Two is affected as well.

This user returned in 35073195-hc to report that the More tag is still causing formatting issues. Recommended removing More tag to resolve and suggested using excerpts instead. User requested an email when this is fixed, since they have a lot of posts on their site and this bug is causing issues.

**Comment by MaggieCabrera** [comment] 2022-04-13 07:36
This is not a bug, simply the way the block works, as @madhusudhand mentioned. I'm closing this one as there's nothing we can do from a theme perspective

**Closed as completed by MaggieCabrera** 2022-04-13 07:36 UTC
Labels: [Type] Enhancement, [Pri] High, [Theme] Seedlet, [Theme] Spearhead, [Theme] Rivington, [Theme] Twenty Twenty-One, Triaged, [Theme] Twenty Twenty-Two
