### ISSUE TITLE
Baskerville 2: Center align is not followed

### ISSUE THREAD

**Issue by dericleeyy** [Automattic/themes#719] opened 2019-04-09 06:53 UTC
## Steps to replicate

1. Create new post
2. Insert image block with image and caption
3. Align center the image block
4. Publish

## Result

Image is aligned left. Caption is also aligned left.

https://cloudup.com/csXjmxnSSBe

## Expected

Image and caption should be centered.

* User report: #8192063-hc
* Follow-up ticket:

**Comment by torres126** [comment] 2019-04-09 07:46
#403

**Comment by torres126** [comment] 2019-04-09 07:47
Duplicate of #403

**Closed** 2019-04-09 09:49 UTC
Labels: bug, support
