### ISSUE TITLE
Quadrat: List of blog posts pattern missing

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#4259] opened 2021-07-21 08:12 UTC
## Steps to replicate

On WordPress.com the "List of blog posts" pattern doesn't show. This seems to relate to the "blockType" setting, as when that is removed it works. Since this is only on WordPress.com I think this must be an issue relating to that environment. I'm just logging this issue to keep track of it. Hopefully when Gutenberg/Wordpress is next updated it's fixed :)

**Comment by MaggieCabrera** [comment] 2021-09-03 14:48
Closing this as I can't reproduce on dotcom anymore

**Closed as completed by MaggieCabrera** 2021-09-03 14:48 UTC
Labels: [Theme] Quadrat
