### ISSUE TITLE
Quadrat: Polygon looking weird in Footer

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#4068] opened 2021-06-16 11:58 UTC
Here's how the polygon shape is looking in the Footer.

<img width="1530" alt="Captura de ecrã 2021-06-16, às 12 52 56" src="https://user-images.githubusercontent.com/65220155/122214510-12c73100-cea2-11eb-8c3c-826d55d4606c.png">

Is it possible to have it going until the end of the screen, without that bar at the bottom?

<img width="1346" alt="Captura de ecrã 2021-06-16, às 12 55 35" src="https://user-images.githubusercontent.com/65220155/122214593-2c687880-cea2-11eb-9744-9830c5de605c.png">

**Comment by jffng** [comment] 2021-06-28 15:28
Also when the page is short, the header and footer polygons sometimes overlap.

**Comment by pbking** [comment] 2021-06-29 13:33
The space at the bottom seems to be [caused by the stats smily](https://github.com/Automattic/themes/issues/3833#issuecomment-860731594).

**Comment by danieldudzic** [comment] 2021-06-30 17:20
This will be fixed by #4137

**Closed as completed by danieldudzic** 2021-06-30 17:20 UTC
Labels: [Theme] Quadrat
