### ISSUE TITLE
Lodestar: iPhone/Tablet Background does not repeat

### ISSUE THREAD

**Issue by ktyfuller604** [Automattic/themes#454] opened 2018-12-28 17:14 UTC
## Steps to replicate

1. Select Lodstar Theme
2. Select a background image in Colors & Backgrounds
3. View site on an iPhone or Apple tablet

## Result

Background image does not repeat. Leaving white space below the image. 
Screenshots attached below. 

## Expected

The background image should repeat like it does on Android and in the preview tablet/phone mode. 

* User report: #8999539-hc
* Follow-up ticket: #1673498-zen
* User's site: https://lunaseacatisland.net/ (
is changing themes, so the attached screenshots may be a better source)

## Screenshots
![img_9441](https://user-images.githubusercontent.com/38542929/50522607-d1f0bd00-0a99-11e9-8563-0c6f4a40499d.jpeg)
![img_3787](https://user-images.githubusercontent.com/38542929/50522616-dc12bb80-0a99-11e9-9bf4-a51be2d87709.jpeg)
![img_3788](https://user-images.githubusercontent.com/38542929/50522619-df0dac00-0a99-11e9-8e42-1d983c48c420.jpeg)

**Comment by laurelfulford** [comment] 2018-12-29 01:12
Looking at the site's settings, it looks like the background is not set to repeat under Customize > Colour & Background > Options:

![image](https://user-images.githubusercontent.com/177561/50531695-8c48ea00-0ac3-11e9-8197-caa102f5403a.png)

When I tested this and set the 'Repeat' to repeat, it did repeat the background for me on my iPhone.

I'm going to close this ticket and I'll add a comment to the ZD ticket above relaying this!

**Comment by pauljacobson** [comment] 2018-12-31 06:41
I tested this on an iPhone emulator through Browserstack, using both a Safari and Chrome emulator, and I was able to reproduce the issue there. Here's on Safari:

![lunaseahome_wordpress_com_background_ios11_safari](https://user-images.githubusercontent.com/2912202/50555602-73188700-0cd7-11e9-8c2b-d55952724e17.png)

Here's in Chrome (also on iOS):

![lunaseahome_wordpress_com_background_ios11_chrome](https://user-images.githubusercontent.com/2912202/50555611-86c3ed80-0cd7-11e9-8f22-e1a2f5da6e4e.png)

According to Browserstack, they were using iOS 11 for this.

I tested the site on my Android device, using Firefox, and the background repeated as expected. I saw the same result in Browserstack testing with a Samsung Galaxy 9+ using Chrome.

So this seems to be a iOS issue, albeit seemingly inconsistent given that @laurelfulford wasn't able to reproduce the issue on an iPhone.

**Comment by laurelfulford** [comment] 2018-12-31 19:10
Thanks for double-checking this, @pauljacobson!

I wasn't super clear in my original comment: I _was_ able to recreate the issue on the site above, but thought it was working as expected because the background isn't actually set to repeat. But I didn't think about it much further than that (I blame Friday!).

I took another look; on the user's site, the background is set to fixed; this uses the style `background-attachment: fixed`, which [isn't supported by some mobile browser like Safari](https://caniuse.com/#search=background-attachment). So as a fallback, the background moves with the page, and doesn't look the same at all (especially on tall pages!). 

This isn't unique to Lodestar, and unfortunately, I'm not sure it's exactly fixable -- the closest would probably be adding a better fallback to the Core behavior, but that could cause even more confusion over what the heck the background is doing when `background-attachment: fixed` isn't supported. 

In this specific case, I think the best bet would be switching the background to be not-fixed, and to repeat; it won't look the same as what they have  on desktop, but it would get closer to what they want on mobile. 

I am going to re-close, since it isn't an issue with the theme, but just let me know if anything above doesn't make sense!

**Closed by laurelfulford** 2018-12-31 19:10 UTC
Labels: bug, needs testing, support
