### ISSUE TITLE
[Bug]: Shawburn Theme - Featured images are not responsive on the posts

### ISSUE THREAD

**Issue by carolframen** [Automattic/themes#7067] opened 2023-05-09 16:00 UTC
### Quick summary

When using the Shawburn theme the featured images on the posts are not responsive.

### Steps to reproduce

1. Activate the Shawburn theme on a simple site
2. Create a post with a featured image
3. Open the post either on a mobile device or on the customizer using the tablet/mobile view

### What you expected to happen

The featured image should be responsive and adjust to the screen size

### What actually happened

The featured image is huge and does not fit the theme background

### Browser

Google Chrome/Chromium, Android Chrome

### Context

An user reported this on #6272093-Zen

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

Tested on two simple sites and one atomic. Atomic site did not have the issue. Both simple sites did.

![image](https://github.com/Automattic/themes/assets/119800062/e3561e82-fdaf-43b1-8105-38fe717409bb)
![image](https://github.com/Automattic/themes/assets/119800062/c4a61871-fe9f-4be8-8152-2dfc86b7f14b)

It is also possible to check this on the website's customizer

![image](https://github.com/Automattic/themes/assets/119800062/67ab9a43-7188-448b-988a-8c1daab63ab0)
![image](https://github.com/Automattic/themes/assets/119800062/21393796-05a1-4438-9fe6-555516e087f5)

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

None

**Comment by AnjanaV93** [comment] 2023-05-24 07:30
Another report in 6319441-zen. The issue here is specific to the site logo being not responsive.

**Comment by tellisbethel** [comment] 2023-05-25 20:22
Another case here, but on the Stow theme in this case: 6328733-zd-woothemes
In this case both the logo and post featured images are unresponsive on mobile (**except in Chrome**!)
The user has some CSS applied which doesn't appear to be doing anything. Suggesting they try another theme for now.

Stow and Shawburn are child themes of Varia, so it might be a broader issue. (I just tested on Exford as well and the issue persists.)

**Comment by carolframen** [comment] 2023-05-28 17:21
Another case with Exford  6330905-zen

**Comment by carolframen** [comment] 2023-05-29 19:32
Another case with Shawburn #6339751-zen

**Comment by carolframen** [comment] 2023-05-29 19:32
Another case with Shawburn #6339751-zen

**Comment by carolframen** [comment] 2023-05-30 16:20
Another case with Shawburn #6338135-zen

**Comment by cuemarie** [comment] 2023-05-30 19:01
Duplicate of https://github.com/Automattic/wp-calypso/issues/77561

Please collect all future interactions on that report

📌 ACTIONS
- Closed as duplicate

**Closed as not planned by cuemarie** 2023-05-30 19:01 UTC
Labels: [Type] Bug, [Pri] Normal, Triaged, [Status] Duplicate, [Pri] TBD

**Comment by cuemarie** [comment] 2023-05-31 20:40
A [fix has been deployed](https://github.com/Automattic/wp-calypso/issues/77561#issuecomment-1570917159)

**Comment by cuemarie** [comment] 2023-05-31 21:57
A batch user reply will be sent out to all interactions noted above this comment. Please refer to main issue https://github.com/Automattic/wp-calypso/issues/77561 for updates on that process.
