### ISSUE TITLE
Dara: MailChimp block layout is different from the editor

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/themes#2892] opened 2020-12-06 19:21 UTC
## Steps to replicate

1. Connect MC to a WordPress.com site
2. Add the MC block to a site: https://wordpress.com/support/wordpress-editor/blocks/mailchimp-block/
3. Check the published post/page

## Result

* The email field is really narrow
* The button font size is huge

<img width="801" alt="Captura de Tela 2020-12-06 às 16 16 17" src="https://user-images.githubusercontent.com/1136160/101290000-8cd57980-37de-11eb-96c6-024437e8bc17.png">

## Expected

To see something similar to how the form is displayed in the editor.

<img width="823" alt="Captura de Tela 2020-12-06 às 16 20 57" src="https://user-images.githubusercontent.com/1136160/101290110-0a00ee80-37df-11eb-97a5-419648944f18.png">

* User report: 3539238-zen

**Comment by kuropixel** [comment] 2021-09-19 05:42
Had a user come in with this issue for MailChimp, but for Promenade theme. CSS was given to fix the issue. 31750623-hc

**Comment by Gustavo-Hilario** [comment] 2022-10-14 21:26
I couldn't reproduce this issue. The input and button layout seems okay to me:

![Markup on 2022-10-14 at 16:25:15](https://user-images.githubusercontent.com/50875131/195946574-bf2dc3b0-09f8-42f8-ad02-7db1e69afe3c.png)

I'm closing this issue for now.

**Closed as completed by Gustavo-Hilario** 2022-10-14 21:26 UTC
Labels: [Type] Bug, [Status] Cannot reproduce, Support, [Theme] Dara
