### ISSUE TITLE
[Bug]: Overlaid Theme - Adding any patterns causes "unexpected error" on Simple sites

### ISSUE THREAD

**Issue by pak-cia** [Automattic/themes#7683] opened 2024-03-16 05:33 UTC
### Quick summary

Attempts to add _any_ patterns results in "unexpected error" modal and console errors: https://prnt.sc/NHgCyLcEM1qt

### Steps to reproduce

1 - Open any editor on a _Simple_ site
2 - Select any pattern to insert
3 - "The editor has encountered an unexpected error." notification modal appears

### What you expected to happen

Pattern to be successfully inserted and editor can continue to be used

### What actually happened

Error notification appears and editor cannot be used.

### Browser

Google Chrome/Chromium

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

console error that prints after error occurs:

`TypeError: Cannot read properties of undefined (reading 'some')
 at https://s0.wp.com/wp-content/plugins/gutenberg-core/v17.9.0/build/blockeditor/index.min.js?m=1710352031i&ver=52678fd4b2dc7ee02926:124:10709
 at Array.filter (<anonymous>)
 at https://s0.wp.com/wp-content/plugins/gutenberg-core/v17.9.0/build/blockeditor/index.min.js?m=1710352031i&ver=52678fd4b2dc7ee02926:124:10664
 at Object.useMemo (https://s0.wp.com/wp-content/plugins/gutenbergcore/v17.9.0/build/vendors/react-dom.min.js?m=1710352031i&ver=18:1:115217)
 at e.useMemo (https://s0.wp.com/wp-content/plugins/gutenbergcore/v17.9.0/build/vendors/react.min.js?m=1710352031i&ver=18:1:9875)
 at LC (https://s0.wp.com/wp-content/plugins/gutenberg-core/v17.9.0/build/blockeditor/index.min.js?m=1710352031i&ver=52678fd4b2dc7ee02926:124:10623)
 at St (https://s0.wp.com/wp-content/plugins/gutenberg-core/v17.9.0/build/vendors/reactdom.min.js?m=1710352031i&ver=18:1:47627)
 at $s (https://s0.wp.com/wp-content/plugins/gutenberg-core/v17.9.0/build/vendors/reactdom.min.js?m=1710352031i&ver=18:1:120574)
 at Sl (https://s0.wp.com/wp-content/plugins/gutenberg-core/v17.9.0/build/vendors/reactdom.min.js?m=1710352031i&ver=18:1:88649)
 at kl (https://s0.wp.com/wp-content/plugins/gutenberg-core/v17.9.0/build/vendors/reactdom.min.js?m=1710352031i&ver=18:1:88577)``

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Change theme, though that's unlikely to go well with some users

**Comment by pak-cia** [comment] 2024-03-16 05:33
7892306-zen

**Comment by ha-un** [comment] 2024-03-27 21:14
Seeing same error with Lativ theme: 7953466-zd-a8c
Raised awareness here: p1711577715672529-slack-C0160HSMDQV

**Comment by liviopv** [comment] 2024-03-28 09:56
@ha-un @pak-cia I was able to reproduce this in Overlaid and Lativ, but it's inconsistent.

I was not able to reproduce in:
- Atomic site
- Simple site with a .wordpress.com domain
- Simple Site with Creator (only Explorer)
- Simple Site with an edge sticker, so running GB 18 instead of 17.9
- Themes: TT4, Feeling Good, StartAce, Sunderland

Please try to reproduce it on your own sites with the Gutenbrg Edge sticker applied. If you can't (like I couldn't), it means we don't need to worry too much about it, as it will be fixed very soon when WordPress.com is upgraded to GB 18.

**Comment by nuriapenya** [comment] 2024-12-03 08:59
@ha-un @pak-cia @liviopv, I'm just circling back on this issue as part of triaging. I could not reproduce it, either. I tested:

* Atomic site
* Simple site with a .wordpress.com domain
* Themes: Overlaid and Lativ themes.

I assume this has been fixed with the latest updates, so closing for now as fixed.

**Closed as completed by nuriapenya** 2024-12-03 08:59 UTC
Labels: [Type] Bug, [Pri] Low, Triaged, FSE, [Theme] Overlaid, Customer Report
