### ISSUE TITLE
Blockbase children: Site editor crashes on launch in Safari

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4523] opened 2021-09-02 16:09 UTC
## Steps to replicate

1. Activate the Gutenberg plugin, v11.4.0
2. Activate a blockbase child theme (Quadrat, Skatepark, etc.)
3. Using Safari, try to open the site editor. 
4. Note the error. 

## Result

<img width="1285" alt="Screen Shot 2021-09-02 at 12 06 25 PM" src="https://user-images.githubusercontent.com/1202812/131878562-04543750-fea8-4df1-ac4a-c7968f26957b.png">

## Expected

I expected the site editor to load. 🙂

The site editor works fine with TT1 Blocks, Emptytheme, and Blockbase. So this may be a child theme issue. The site editor also loads just fine in Chrome.

**Comment by jffng** [comment] 2021-09-02 17:46
Hey there — I was unable to replicate this. Tested the following scenarios / combinations:

- Gutenberg latest plugin release (11.4.0) and trunk
- Skatepark, Quadrat, and Seedlet Blocks
- Chrome, Safari, Firefox

The site editor loaded in all combinations of those.

**Comment by pbking** [comment] 2021-09-02 18:42
I HAVE reproduced this locally.

Doesn’t repo on Firefox or Safari for me.
Only in Chrome.
(which I think is the opposite for others experiencing it)

Happens with the plugin or a build.
Doesn’t happen on .com (with 11.4.0)

I’m at a loss as to even what to point at that might be broke.

Removing the top-level `fontWeight` from `styles.typography` in theme.json makes the error go away.

Error seems to be kicked off by this:
```
Uncaught TypeError: Cannot read property 'name' of undefined
```

**Comment by pbking** [comment] 2021-09-02 19:49
Reported here on Gutenberg: https://github.com/WordPress/gutenberg/issues/34483
Closing this as it's not a theme issue and can be tracked there.

**Closed as completed by pbking** 2021-09-02 19:49 UTC
Labels: [Type] Bug, [Theme] Quadrat, [Theme] Skatepark
