### ISSUE TITLE
Mayland: Masonry Gallery Block Lightbox Does Not Work in Template or Activating Theme.

### ISSUE THREAD

**Issue by scosgro** [Automattic/themes#1830] opened 2020-03-01 01:01 UTC
## Steps to replicate

1. Activate Mayland on a WordPress.com site. 
2. Edit the homepage to make sure the Masonry Gallery Block used has Lightbox activated. 
3. Test it. Images will open in a new window, and lightbox will fail.

1. Activate any theme on a WordPress.com site. 
2. Create a new page, and use the Mayland Template. 
3. Make sure lightbox is turned on for the images in the Masonry Gallery Block. 
4. Test it. Images will open in a new window, and lightbox will fail.

.gif using the template (gif is too large for Github, so using Cloudup):
https://cloudup.com/clHoZ2J--Jk

## Result

Lightbox fails to load when using the Masonry Gallery block that comes with the theme/template. 

## Expected

Lightbox to work.

The current workaround is to delete the Masonry Gallery Block, and replace it with a new Masonry Gallery Block. I'm not sure why, but it'll work when replaced with a new one. 

* User report: [shortlink to chat/forum thread/ticket, ie #16389303-hc]

**Comment by WunderBart** [comment] 2020-08-26 13:38
Closing this one as I cannot reproduce after the recent update (https://github.com/Automattic/wp-calypso/issues/45033).

**Closed by WunderBart** 2020-08-26 13:38 UTC
Labels: [Type] Bug
