### ISSUE TITLE
Varia Themes: Group Block background color #000000 not visible on live site

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/themes#5723] opened 2022-03-22 17:23 UTC
### Quick summary

Using the theme "Stratford", the user had Group blocks with a background color set in the block editor in Black. This does not show on the site. See screenshots below:

- Editor: 

![X3yKgZ](https://user-images.githubusercontent.com/31009008/159536599-22e2287e-4966-4a8a-83bf-59ea3404f861.jpeg)
 
-  Live: 

![P8vVC6](https://user-images.githubusercontent.com/31009008/159536649-f8920eb0-1598-448f-8fde-25eca7a4e302.jpeg)

It looks like the theme is missing styles for the block, but the user reported this wasn't always the case. Might be related to a recent Gutenberg update? 

There is a workaround to ask the user to set the color to `#000001` instead of black - it works.

Here are some issues that are likely related:
https://github.com/Automattic/wp-calypso/issues/56781
https://github.com/Automattic/themes/issues/3291
https://github.com/Automattic/themes/issues/5567

they probably have an underlying cause beyond the individual blocks.

### Steps to reproduce

1. With a Varia theme add a Group block on a page
2. Set a background color to the Group block of `#000000`
3. see if the color shows on the live page/ Preview

### What you expected to happen

To show the color

### What actually happened

it doesn't

### Workaround details

Set the color to `#000001`

**Comment by davipontesblog** [comment] 2022-03-22 17:26
user report 4883684-zd-woothemes

**Comment by MaggieCabrera** [comment] 2022-04-05 09:14
Looks like the same issue as https://github.com/Automattic/themes/issues/3291 and this is not theme specific, but an editor issue instead. I could reproduce with Twenty Thirteen. Any theme that doesn't define one of core's palette colors will fail to render the color in the frontend.

**Comment by MaggieCabrera** [comment] 2022-04-05 09:21
https://github.com/WordPress/gutenberg/issues/40043 I opened a GB issue for this

**Comment by MaggieCabrera** [comment] 2022-04-13 07:39
I'm closing this one since it's a bug in the editor, please refer to the GB issue for a solution to this

**Closed as completed by MaggieCabrera** 2022-04-13 07:39 UTC
Labels: [Type] Bug, [Theme] Varia, Editor

**Comment by MaggieCabrera** [comment] 2022-05-09 14:09
I can't reproduce this one anymore on 2013 and Stratford so I think this might have been fixed.
