### ISSUE TITLE
Barnsbury: Color settings not working correctly on menus

### ISSUE THREAD

**Issue by philnick206** [Automattic/themes#3001] opened 2021-01-10 17:17 UTC
## Steps to replicate

1. Load color settings under Customization options
2. Try to change colors to custom colors

## Result

Color settings are not reflected in the menus on AT sites

<img width="1373" alt="Markup 2021-01-10 at 17 07 16" src="https://user-images.githubusercontent.com/51966986/104130197-5e136b80-5367-11eb-97fa-90bb86eec64a.png">

Labels for the colors settings are not shown either, nor are complementary colors on AT site

<img width="710" alt="Markup 2021-01-10 at 17 09 00" src="https://user-images.githubusercontent.com/51966986/104130218-71263b80-5367-11eb-8a8c-bccfc443c6e0.png">

On simple sites this appears to be working fine

<img width="1439" alt="Markup 2021-01-10 at 17 09 25" src="https://user-images.githubusercontent.com/51966986/104130244-869b6580-5367-11eb-9e31-5b7bd3a22c21.png">

## Expected

Color settings are reflected accurately and labels appear appropriately

* User report: #24287875-hc
* Follow-up ticket: #3637661-zen

**Comment by tbradsha** [comment] 2021-01-11 16:32
This seems to be an issue with any theme using the color picker in Customizer: I tried Seedlet, Dalston, and Independent Publisher 2.

With Seedlet activated, JS console shows this when loading the Customizer:

![image](https://user-images.githubusercontent.com/32492176/104210264-e5a4bd00-53ef-11eb-93a1-28b1a124f6f9.png)

Selecting a color shows this:
![image](https://user-images.githubusercontent.com/32492176/104210315-f5240600-53ef-11eb-94c3-c3ce899f30bc.png)

**Comment by tbradsha** [comment] 2021-01-11 16:54
Looks like there may be two separate issues here:
1. menu colors in Barnsbury not changing
2. color labels and complimentary colors not loading on any AT site

Split the second (higher-impact) issue off to Automattic/wp-calypso#48773.

**Comment by pbking** [comment] 2021-02-08 17:51
I wasn't able to reproduce this with the latest; I suspect it has been addressed due to other fixes.

The color picker was working as expected (complete with complimentary colors) and the menu was tracking changes to changing colors.

**Comment by MaggieCabrera** [comment] 2021-02-09 10:30
I can't reproduce this either on simple or atomic sites. I'm going to close this, please feel free to reopen if you encounter this again.

**Comment by scruffian** [comment] 2021-02-09 12:16
I can reproduce. Created a PR here: 22-gh-Automattic/custom-colors

**Comment by jordesign** [comment] 2021-12-10 03:04
I could no longer recreate this - so closing.

**Closed as completed by jordesign** 2021-12-10 03:04 UTC
Labels: [Type] Bug, [Theme] Varia, Triaged
