### ISSUE TITLE
Exford: Centered Quote Block appears to the left in the Editor view, with centered text.

### ISSUE THREAD

**Issue by marcuswisecaesar** [Automattic/themes#2626] opened 2020-10-17 14:48 UTC
## Steps to replicate

In the Exford theme, on a Premium Plan

Add a quote block that is centered on a page. 

## Result

While the text is centered, the block itself appears to the left in the editor only (but is centered in preview and live). 
![screenshot](https://d.pr/i/yTSeVe+)
[Direct Link](https://d.pr/i/yTSeVe)

## Expected

The text and block to be centered as it appears in Preview and Live, in the editor as well. 

* User report: (https://mc.a8c.com:443/support-stats/happychat/transcript.php?id=24833571)[#2483357-hc]
* Follow-up ticket: (https://woothemes.zendesk.com/agent/tickets/3401669)[#3401669-zd]

**Comment by Gustavo-Hilario** [comment] 2022-10-14 17:43
I couldn't reproduce this issue on local sites and WordPress.com using Exford and Varia themes. I'm closing this issue for now.

**Closed by Gustavo-Hilario** 2022-10-14 17:43 UTC
Labels: [Theme] Varia, User Report, [Theme] Exford
