### ISSUE TITLE
Radcliffe 2: Links Indistinguishable From Unlinked Text in Editor

### ISSUE THREAD

**Issue by mdrockwell** [Automattic/themes#1990] opened 2020-05-07 21:48 UTC
## Steps to replicate

1. Activate Radcliffe 2
2. Open a new post or page in the editor
3. Insert some text.
4. Add a link to some of that text.

## Result

There is no style applied to the linked text to distinguish it from unlinked text.

## Expected

The linked text to have a different color or be underlined so that it can be easily distinguished from the rest of the text.

Here is a video to illustrate the issue: https://d.pr/v/MkCZ24

* User report: #13415396-hc
* Follow-up ticket: #2954015-zd

**Comment by nielslange** [comment] 2020-05-08 13:02
Hello @mdrockwell 👋 Thanks for reporting this issue. This is the second deep dive I did today. It seems that the issue which you reported is caused by one of the most recent Gutenberg versions. Gutenberg adds the following editor styles, which overwrite the link styling of the corresponding theme:

```
.editor-styles-wrapper a {
    color: inherit;
    transition: none;
}
```

When testing this issue locally and deactivating the Gutenberg plugin, so that WordPress is using the core block editor, then the links look as expected. You can verify this by creating the test case above on an atomic site and then deactivate the Gutenberg plugin. 

That said, I reported this issue on https://github.com/WordPress/gutenberg/issues/22221, so that it can be addressed accordingly. As this issue need to be fixed in Gutenberg, I'm going to close this issue for now.

**Comment by kjellr** [comment] 2020-05-11 12:23
Thanks for the report! This is fixed in Gutenberg, and will be sorted out when WordPress.com migrates to the next release. 👍 https://github.com/WordPress/gutenberg/issues/22221#issuecomment-626667480

**Closed by kjellr** 2020-05-11 12:23 UTC
Labels: [Type] Bug
