### ISSUE TITLE
Adonay: Hard coded navigation ref, footer spacing missing

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#8167] opened 2024-09-17 00:23 UTC
Adonay has a hard coded navigation ref in the header template part, that needs to be removed.

https://github.com/Automattic/themes/blob/f46466de7605be90d255b6dcda95595e042670df/adonay/parts/header.html#L5

Additionally, there's no spacing in the footer on the internal pages only:
<img width="1313" alt="image" src="https://github.com/user-attachments/assets/252e46e4-a840-4aba-92c4-5f528cf23969">

cc @iamtakashi @MaggieCabrera

**Comment by iamtakashi** [comment] 2024-11-04 12:22
I remember fixing these at some point. I'm closing as I can't reproduce this anymore.

**Closed as completed by iamtakashi** 2024-11-04 12:22 UTC
