### ISSUE TITLE
Sophisticated Business: Theme Will Not Center Photos

### ISSUE THREAD

**Issue by robertsonredsox** [Automattic/themes#646] opened 2019-02-28 06:51 UTC
I have a photo as the first block in my post today. I click on it, and click on align center. I clicked publish, but then in the post it is not centered. It is left aligned. So I went back into the editing, and selected right align to see what that would do, and I click update, refresh the page, and then the picture is right aligned, so good the align function is working. I change the photo back to center aligned, click update, click view post... the photo is left aligned somehow. In the editor, it says it is center aligned. I even converted the block to HTML and it has class="aligncenter" in the figure tag. I do not get it. I have tried it in safari and chrome, and cleared the cache and cookies as well in both and the dang photo is always left aligned! Even trying a "large" photo, and full width, it still will be left aligned. It looks odd being left aligned! Here is the link to the post I am talking about: https://mookiescookie.com/2019/02/28/february-27th/

## Steps to replicate

1. Use "Sophisticated Business" Theme
2. Create Post with a photo. 
3. Align center the photo
3. Publish and view said post
4. See the left aligned photo (should be centered)

## Result

Photo is left aligned

## Expected

Center aligned photo

---------------------------------------------

I contacted Wordpress customer support, and the person helping said there is an issue in the CSS. They said the following:
![screen shot 2019-02-27 at 11 32 09 pm](https://user-images.githubusercontent.com/48081864/53546786-7f0fa200-3aea-11e9-843f-f2c1aae7568b.png)

Hopefully this helps.

**Comment by alaczek** [comment] 2019-03-11 05:28
I can re-create this on my test site as well. 
It looks like the margins on `.entry .entry-content .wp-block-image .aligncenter` are not set correctly.

Thanks for reporting! We'll update the ticket when this is fixed.

**Comment by davoraltman** [comment] 2019-04-08 07:14
1 more report - 1945255-zen

I can also reproduce this issue on my test site.

**Comment by torres126** [comment] 2019-05-02 18:21
PR in #648 btw :)

**Comment by danieldudzic** [comment] 2019-09-24 22:16
Sophisticated Business has been retired so I'm closing this as a wontfix.

We have launched a replacement called Rivington: https://wordpress.com/theme/rivington

**Closed by danieldudzic** 2019-09-24 22:16 UTC
Labels: [Pri] High, bug
