### ISSUE TITLE
[Bug]: Creatio 2 - Submenu options "Open on Click" and "Show Arrow" do not apply to mobile menu

### ISSUE THREAD

**Issue by Brianmitchtay** [Automattic/themes#7525] opened 2023-12-03 21:20 UTC
### Quick summary

When working with a navigation block, there are submenu options that control the behavior of the submenus, requiring them to be clicked to open, or show a down arrow.

It's not clear if these options are meant to extend to the mobile menu. Currently they do not, it seems like they should.

![image](https://github.com/Automattic/themes/assets/45057772/872a7c91-3b28-4162-a2d3-42974263c7b7)

### Steps to reproduce

1. Setup Creatio 2 theme on a site
2. Create a menu in the site editor
3. Open a template that has this menu (The navigation block settings cannot be accessed from inside the menu editor)
4. Toggle the "Submenus" settings (Open on Click, or Show Arrow)
5. Reduce screen size to show mobile menu
6. See the submenu settings have no effect	

### What you expected to happen

Both I and the customer in 7368601-zd-a8c expect the submenu settings to work on the mobile version of the menu as well.

### What actually happened

The submenu options have no effect on mobile menus. I see that classes are added like `open-on-click` but those aren't functioning as expected for the mobile version of the menu.

### Browser

Google Chrome/Chromium

### Platform (Simple, Atomic, or both?)

Atomic

### Other notes

Some assorted errors in the CLI but it's not clear if any of these are related

```
[03-Dec-2023 18:59:44 UTC] PHP Deprecated:  strpos(): Passing null to parameter #1 ($haystack) of type string is deprecated in /wordpress/core/6.4.1/wp-includes/class-wp-theme-json.php on line 3727
[03-Dec-2023 18:59:44 UTC] PHP Deprecated:  preg_match_all(): Passing null to parameter #2 ($subject) of type string is deprecated in /wordpress/core/6.4.1/wp-includes/class-wp-theme-json.php on line 3730
```

### Reproducibility

Consistent

### Severity

Most (> 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

This could be worked around with some custom CSS I believe, but it'd be rather cumbersome to implement and probably hard to get truly desirable behavior using pseudo classes like `:hover` or `:active`

**Comment by liviopv** [comment] 2023-12-28 14:52
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
This is not exactly broken but it's a UI that can certainly be improved.
It's not theme-specific, and it is not WordPress.com-specific - it's how the Navigation Block works in any WordPress  setup.

From my local site with TT4:
 
![CleanShot 2023-12-28 at 14 51 27@2x](https://github.com/Automattic/themes/assets/14153300/c685e391-8c70-451f-968d-a6cc3641c8b3)

📌 ACTIONS
- Triaged
- Closed as by design
- Reported upstream as a feature request: https://github.com/WordPress/gutenberg/issues/57425

📌 Message to Author
@Brianmitchtay in the future, please test with different themes to check if what you're reporting is theme-specific or not, so you can report accordingly.

**Closed as completed by liviopv** 2023-12-28 14:52 UTC
Labels: [Type] Bug, Triaged, [Status] Core fix needed, [Pri] TBD, Customer Report
