### ISSUE TITLE
Mayland: Footer credit cannot be changed.

### ISSUE THREAD

**Issue by chrisfromthelc** [Automattic/themes#1424] opened 2019-09-25 19:41 UTC
## Steps to replicate

1. Navigate to Customizer
2. Click Site Identity
3. Change Footer Credit selection and click Publish

## Result

In Customizer on a simple site, changing the footer credit does not alter the credit line on the site.

* User report: #15493717-hc

**Comment by iamtakashi** [comment] 2019-10-04 15:55
@chrisfromthelc Were you able to replicate this issue? The option works for me without a problem.

**Comment by chrisfromthelc** [comment] 2019-10-04 19:22
After much digging and chasing rabbit trails, I was able to reproduce the issue.

Importing their entire site into a test site, applying the same plan, and going setting-by-setting to make everything match, _including the site language_.

When set to EN-GB for the site language, the theme fails to allow footer credit changes.

**Comment by zdenys** [comment] 2019-10-05 15:48
I can confirm that `en-GB` causes the issue. Changing that to just `en` fixes it. Switching Themes didn't help indeed.

In my case 2381372-zen it was Maywood.

**Comment by iamtakashi** [comment] 2019-10-07 07:56
Interesting, I didn't think the language setting was something to do with the issue. Thanks @chrisfromthelc for the investigation!

> Switching Themes didn't help indeed.

This doesn't seem to be the theme-specific issue. With `en-GB`, the footer option didn't work for me in Radcliffe2 or Twenty Nineteen. This seems worth to be reported in /wp-calypso.

**Comment by chrisfromthelc** [comment] 2019-10-09 23:05
After more research, it seems this is an issue with the way we do footers and is a known issue we have not taken action to fix: https://themedevp2.wordpress.com/2019/03/03/ongoing-footer-credit-issue/

**Comment by brezocordero** [comment] 2019-10-22 22:22
Also reported here with Stratford theme (en-GB): 2440357-zen

**Comment by damiannep** [comment] 2019-11-07 12:56
Another report for Maywood in 16500130-hc

**Comment by aleone89** [comment] 2019-11-18 12:26
Another report for Maywood 16732122-hc

**Comment by zdenys** [comment] 2019-12-20 18:58
Fixed in D36982-code as per https://github.com/Automattic/wp-calypso/issues/35968#issuecomment-568037889

**Comment by philnick206** [comment] 2020-03-13 15:43
This issue is still present. Reported here: 2787100-zen
CC: @kwight

**Comment by kwight** [comment] 2020-03-13 18:01
Ah, I fixed the dotcom side, but not the Atomic side. PR ready for review in https://github.com/Automattic/at-pressable-footer-credit/pull/4

**Comment by kwight** [comment] 2020-03-13 18:07
(I should note again too, this is not a theme-specific issue, it applies to all themes.)

**Closed** 2020-03-16 16:33 UTC
