### ISSUE TITLE
Global Styles in Attar theme - Unable to select "Default" font in "Global Styles > Typography > Text" panel

### ISSUE THREAD

**Issue by zyousafi** [Automattic/themes#7677] opened 2024-03-14 06:54 UTC
### Quick summary

I'm unable to select the "Default" font from the "Font" field in the "Global Styles > Typography > Text" panel.  I can select any other font, but can't select "Default" for some reason.  I can select "Default" in all of the other sections in the "Global Styles > Typography" panel, but the same doesn't work in the "Global Styles > Typography > Text" panel

### Steps to reproduce

1. Start by activating the Attar theme
2. Navigate to the "Single Posts" template via the "Appearance > Editor > Templates" panel
3. Navigate to the "Global Styles > Typography > Text" panel
4. Try selecting the "Default" option from the "Font" dropdown

### What you expected to happen

The "Default" font should have been selected

### What actually happened

The previously selected font remains selected (i.e., the value doesn't change to "Default")

### Browser

Google Chrome/Chromium

### Context

Customer report (7886563-zen)

Tested this on my own Atomic and SImple site, the issue exists there as well

### Platform (Simple, Atomic, or both?)

Both

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

**Comment by retnonindya** [comment] 2024-03-20 12:36
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
I can replicate the issue. 
1. With theme Attar active, open Editor then Styles
2. Check the font option
3. Choose "Default"
4. The "Default" option is not highlighted, instead it keeps reverting to font Inter. Might be because the default font for theme Attar is Inter?

![Mar-20-2024 20-34-02](https://github.com/Automattic/themes/assets/44726232/3e7eb6ef-3852-4fa3-b5c1-5acbb92569d6)

📌 ACTIONS
- Triaged

**Comment by fditrapani** [comment] 2024-11-12 16:14
@zyousafi I just tested this and it appears that this is the intended behaviour.

> The "Default" option is not highlighted, instead it keeps reverting to font Inter. Might be because the default font for theme Attar is Inter? Might be because the default font for theme Attar is Inter?

@retnonindya that is correct. The default font is Inter. If you pick something else, when you pick Default, it goes to the theme default `Inter`. I tried this on some other themes and replicated the behaviour.

@zyousafi I'm going to close this issue. If it comes up again as a problem, please feel free to open it.

**Closed as completed by fditrapani** 2024-11-12 16:14 UTC
Labels: [Type] Bug, [Pri] Low, Needs triage, [Themes] Attar, Customer Report
