### ISSUE TITLE
Atomic: Site editor deletes template content when saving

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/themes#7999] opened 2024-08-07 00:40 UTC
## Steps to replicate

1. Activate Startfitter theme
2. Open the Front Page template in the Site Editor
3. Edit the existing content a couple times to trigger revisions
4. Specifically remove and re-add the period in the existing paragraph blocks in the Header and in the Content
5. Click Save and Save again

It is really hard to be precise with these instructions, but here's a recording of the exact steps I took:

https://github.com/user-attachments/assets/0539a70d-b20b-4b98-b906-816e3a7639ab

It feels a bit random at first, and then it is consistently reproducible. I've confirmed this on three different sites.

## Result

The Choose a pattern modal displays. It "looks" like the content is still there, but if you refresh and go to the list of Templates, the template shows as Empty.

## Expected

For the content to properly save.

* User report: [shortlink to chat/forum thread/ticket, ie 12345-hc]
* Follow-up ticket: [shortlink to ticket, ie 12345-zen]

**Comment by dsas** [comment] 2024-08-07 06:41
I can't repro on a simple site, only on atomic.

The POST requests being triggered look like this:
 * `/wp-json/wp/v2/templates/startfitter//front-page?_locale=user` - includes ID and content fields in both request and response
 * `/wp-json/wp/v2/template-parts/startfitter//header-home?_locale=user` - includes ID and content fields in both request and response
 * `/wp-json/wp/v2/templates/startfitter//front-page?_locale=user` - includes ID but no content in request, the content in the response is blank (technically `"content":{"raw":"","block_version":0}`)

The symptoms are reminiscent of https://github.com/Automattic/wp-calypso/issues/92191 (escalated as p1719520111073669/1719520111.073669-slack-C02FMH4G8) which seemed to be down to a Woo bug but https://github.com/Automattic/wp-calypso/issues/91763 might be a closer match (I couldn't repro this last time I tried).

**Comment by jartes** [comment] 2024-08-07 12:05
👋🏻 @tanjoymor Thanks for reporting this! Please use Bugomattic to report bugs so it's added to our triage workflow. Thanks!

**Comment by tanjoymor** [comment] 2024-08-07 16:52
Reporting to the repo for Premium Themes through Bugomattic is broken and I wasn't able to: https://github.com/Automattic/bugomattic/issues/196

Edit: This has been fixed now.

**Comment by tanjoymor** [comment] 2024-08-07 17:22
I was able to reproduce this issue in Cakely as well. I tested 4 Premium Themes:
Startfitter and Cakely both use the Front Page template - you get the pre-flight check list on saving - the issue occurs
Bark and Hevor use the Blog Home template - you don't get the pre-flight check list on saving - the issue does not occur

https://github.com/user-attachments/assets/54765d41-1975-4253-ab34-28858e9975e2

Should I do any additional testing?

**Comment by dsas** [comment] 2024-08-07 18:00
@tanjoymor can you just confirm that you've only repro'd this on atomic sites?

**Comment by tanjoymor** [comment] 2024-08-08 03:53
@dsas Yes, just tested a Simple site and can confirm it’s only happening on Atomic. 

Unrelated, but I am also confused why some themes are giving the Save pre-flight list and some are not.

**Comment by jartes** [comment] 2024-08-08 05:42
@tanjoymor, I see; thanks for reporting that issue on Bugomattic!

**Comment by dsas** [comment] 2024-08-08 19:16
I enabled StartFitter on a simple site and can't repro there still.

Testing with Startfitter, if I just edit the template, then I can't repro. I can only repro when doing a multi-entity save  where the entities are a template and a template part (not gs) and 

it seems only if I make a change, undo that change and then save - i.e. the content being saved is identical to the initial theme template.

I can only reproduce it with the Gutenberg plugin (18.9.0) enabled (no other plugins except jetpack and askismet), I can't reproduce with it disabled.

Next step: Check to see if I can reproduce using dotorg with the gb plugin.

**Comment by dsas** [comment] 2024-08-08 19:37
> Next step: Check to see if I can reproduce using dotorg with the gb plugin.

~~Unfortunately not 🤔 it must be something atomic specific.~~

I can repro on dotorg with the gb plugin, but only with jp activated and on gb 18.9.0 not gb trunk (c495c7) and not reliably.

**Comment by dsas** [comment] 2024-08-13 14:06
Testing on atomic, I've built and uploaded GB from trunk and I can't reproduce the problem.

Like [before](https://github.com/Automattic/themes/issues/7999#issuecomment-2272733943) I'm seeing these requests:
 * /wp-json/wp/v2/templates/startfitter//front-page?_locale=user
 * /wp-json/wp/v2/template-parts/startfitter//header-home?_locale=user
 * /wp-json/wp/v2/templates/startfitter//front-page?_locale=user

but this time the last request still includes content.

Looking over the commits since 18.9.0 was release, nothing obviously stands out as being a relevant fix.

**Comment by dsas** [comment] 2024-08-13 16:55
Testing with vanilla WP and vanilla WP + JP + GB and I can't reproduce the problem. With vanilla WP the same three requests are made and the third one doesn't include any content - however it still received content back in response.

----

I've bisected and it appears to have been fixed by https://github.com/WordPress/gutenberg/commit/3c7d4d6aff43d1da924bdc6c501dc4389b6e9d9b which will be in GB 19.0.0 (currently on atomic edge sites only). 

That change is related to better error handling when saving content, so it sounds convincing. I'm not sure if this is a fix for the problem, or if it is a fix that papers over it.

@jsnajdr given you reviewed the above commit, do you have any insights to share here?

**Comment by jsnajdr** [comment] 2024-08-13 18:51
@dsas The only change in #58022 that could be relevant to this is that the `editor.savePost` action now has a `try/catch` block around the `coreData.saveEntityRecord` action call. Previously, an error thrown from `saveEntityRecord` would immediately abort `savePost` and `savePost` would also throw. Now the error is catched, stored in local variable and handled as error.

The `POST` requests that save a template or a template part are most likely triggered by `saveEntityRecord`. One thing to check is if in one of these saves the `saveEntityRecord` call really throws and why.

Maybe some `saveEntityRecord` is called with the `throwOnError` option.

**Comment by Robertght** [comment] 2024-08-14 06:12
👋 

I'm seeing these cases on a daily basis with customers reporting their content is gone, so I'm assume this is part of the problem. 

This doesn't seem to be theme related as I've seen it on multiple other themes.

**Comment by dsas** [comment] 2024-08-14 08:08
@Robertght I'll continue looking at this today as my main priority.

I think there possibly two things going on:
 * Atomic sites don't appear to have [this change](https://github.com/WordPress/wordpress-develop/commit/ddd78e3851ebcac3bfdbeac0fbf22b051403e610) which prevents blanking a template if it's saved without specifying template content.
 * ~~When older versions of GB are in use, saving a template sometimes results in two update requests being made, the first includes the template content and the second does not. In GB trunk this does not happen, both requests include the template content. I don't know why two requests are being made.~~ Edit: I don't think this is a factor

**Comment by dsas** [comment] 2024-08-14 18:21
With Jetpack enabled I can repro on GB trunk and 18.9.0.

The cause of the deletion is described in [the fix linked above](https://core.trac.wordpress.org/ticket/61550), but essentially it happens when saving a template if both the following is true:
 1. Something (anything, doesn't matter what) is hooking `hooked_block_types`
 2. Something tries to update a template without providing it's `post_content`

**The fix is due to be released in WP 6.6.2** which is [scheduled](https://make.wordpress.org/core/2024/08/13/agenda-dev-chat-wednesday-aug-14-2024/#next-maintenance-release-6-6-2) for the 26th of August.

[Jetpack hooks `hooked_block_types`](https://github.com/search?q=repo%3AAutomattic%2Fjetpack%20hooked_block_types&type=code) in a number of places, mostly for the "Automatically add subscription forms to your site" functionality, and so the workaround is clear: toggle those settings off.

There's one exception: [adding the sharing button](https://github.com/Automattic/jetpack/blob/f82adf1cbfd924dfb8a971f0312cfb7ff799fe7f/projects/plugins/jetpack/extensions/blocks/sharing-button/sharing-button.php#L38), and this is probably the cause for most of the complaints, it's on by default and I can't see a way to disable it. I've checked, and commenting out the `init` hook-up here does prevent the book.

I don't understand yet why something in GB tries to update a template without providing any `post_content` when POSTing to /wp-json/wp/v2/templates/startfitter//front-page?_locale=user, after the content change has already been made.

CC @anomiex / @jeherve for any JP insights.

**Comment by anomiex** [comment] 2024-08-14 19:49
I have no insight other than that the core issue suggests that you could reproduce it with a mu-plugin like this (instead of Jetpack).
```php
<?php
function somehook() {}; add_filter( 'hooked_block_types', 'somehook' , 10, 4 );
```

**Comment by tanjoymor** [comment] 2024-08-17 22:42
This situation is happening with template parts now too. It's become rather common for templates and template parts to end up empty. I've run into two situations in the last hour of empty Headers with revisions available, both Atomic on different themes from any others so far.

**Comment by dsas** [comment] 2024-08-19 07:52
Oddly, I can't repro on GB 19.0.0 on atomic. I've asked for an eta on shipping that (p1724053673796819-slack-CBTN58FTJ).

**Comment by dsas** [comment] 2024-08-20 16:34
GB 19.0.0 has been rolled out thanks to @rafaelgallani and I can no longer reproduce this issue  🤞. I'm going to close it but please feel free to reopen it if it happens again.

**Closed as completed by dsas** 2024-08-20 16:34 UTC
Labels: [Type] Bug, [Pri] High, Triaged, Customer Report, [Theme] StartFitter
