### ISSUE TITLE
Multiple Themes: Buttons in sidebar no longer apply correct colours since Block Widget Editor introduced.

### ISSUE THREAD

**Issue by poojashetty18** [Automattic/themes#4580] opened 2021-09-14 11:57 UTC
## Steps to replicate

- Activate the Canard theme.
- Add the Follow blog widget.
- Update the theme colors from Colors and Background. 

![Screen Capture on 2021-09-14 at 15-08-29](https://user-images.githubusercontent.com/44837596/133253348-5a212283-1c99-4a29-b07c-ad7cfbf9dc5f.gif)

## Result
The follow blog widget color does not update. 

## Expected

The theme color should be reflected correctly on the follow blog widget and the user noticed this issue a month ago when they noticed the Gutenberg block widgets enabled.

* User report: 11041308-hc
* Follow-up ticket: 4297015-zen (the user wants to let them know once it's fixed)

**Comment by mikeicode** [comment] 2021-09-15 13:18
The issue appears to be that this button now has the class `wp-block-button__link`. This apparently unintentionally changes the style of the buttons on this block.

<img width="1328" alt="Screen Shot 2021-09-14 at 07 21 10" src="https://user-images.githubusercontent.com/10353785/133440377-0f95643c-416c-47c2-b61c-6384699e8377.png">


I've also run into this issue on another theme Maxwell (retired theme).

**Comment by DavidSaladu** [comment] 2021-09-17 13:28
I've put the ticket on hold for now, in this case, should this be corrected at the theme level? (the customer is under personal plan so we can't patch it with CSS)

**Comment by Robertght** [comment] 2021-09-18 04:07
I remember from @sixhours there's a core issue regarding widget updating, but I'm not sure if it's related to this.

**Comment by jeffikus** [comment] 2021-09-21 12:55
@danieldudzic @mikachan can either of you confirm this is theme related please?

**Comment by mikachan** [comment] 2021-09-21 14:59
I've just taken a look at this and I can see what you're seeing, @mikeicode, where the `wp-block-button__link` class is being applied and overriding the correct/current button color. I've tried a few different themes and I can see the same issue in each one, where the theme colors aren't applied to the Follow button.

I would guess this means it's not theme related, although I'm struggling to find a related issue in Gutenberg (there's a lot of issues related to buttons!). I'll report back if I find one.

**Comment by jordesign** [comment] 2021-11-17 00:00
Triaging this and it seems apparent this is effecting multiple themes and should be considered more holistically. At this stage reports are for:

* Canard
* Maxwell
* TwentySixteen

The bug effects any buttons which are included in a widget area (including those automatically included as part of widgets like the 'Follow' widget). This may have come into place when the Block Widget Editor was released.

It seems to be caused by the addition of the `wp-block-button__link` and custom color classes to buttons within widget areas - but the theme is not including styles targetting those regions.

```
<a class="wp-block-button__link has-white-color has-bright-red-background-color has-text-color has-background">Button 1</a>
```

Closing related issues so the wider issue can be tracked here.

**Comment by jordesign** [comment] 2021-11-17 00:06
To elaborate - it _looks_ like the styles which would be expected to work when classes like `has-white-color` and `has-bright-red-background-color` are not targetting the element when it is in a widget area?

Raising this as higher priority for another look as it appears to be effecting multiple themes.

**Comment by mikachan** [comment] 2022-01-05 12:58
Possible fix for Twenty Sixteen here: D72519-code

**Comment by mikachan** [comment] 2022-02-15 11:16
Closing this as D72519-code has been deployed.

**Closed as completed by mikachan** 2022-02-15 11:16 UTC
Labels: [Type] Bug, [Pri] High, Triaged
