### ISSUE TITLE
Blockbase + children: header and post meta items need to use the new flex layout

### ISSUE THREAD

**Issue by MaggieCabrera** [Automattic/themes#4463] opened 2021-08-24 14:36 UTC
After https://github.com/WordPress/gutenberg/pull/33812 was merged, there's a new css rule being applied to the default layout support: `$selector > * + * { margin-top: var( --wp--style--block-gap ); margin-bottom: 0; }` This is adding a margin top to every children of the container except the first, causing the post meta groups to break:

Quadrat:
<img width="669" alt="Screenshot 2021-08-24 at 16 31 29" src="https://user-images.githubusercontent.com/3593343/130635953-319e22bb-9e37-45c0-9681-30e9b26afe7b.png">

Seedlet + Mayland:
<img width="398" alt="Screenshot 2021-08-24 at 16 34 38" src="https://user-images.githubusercontent.com/3593343/130636190-8b7bba48-4281-4ab6-8e86-086d325f8a01.png">

Skatepark:
<img width="308" alt="Screenshot 2021-08-24 at 16 35 22" src="https://user-images.githubusercontent.com/3593343/130636265-b667d0b7-132a-47d5-80ab-d46f037fe9b9.png">

<img width="1405" alt="Screenshot 2021-08-24 at 16 36 14" src="https://user-images.githubusercontent.com/3593343/130636431-e3b6c5eb-a29e-4df8-9cc8-a4f85ac0572d.png">

We need to refactor any group block we have added display flex manually on CSS to use the new flex layout instead.

**Comment by jffng** [comment] 2021-08-24 15:48
I took at the issue in [that last screenshot](https://user-images.githubusercontent.com/3593343/130636431-e3b6c5eb-a29e-4df8-9cc8-a4f85ac0572d.png) of Skatepark's header, and that group is already defining flex support via the block: https://github.com/Automattic/themes/blob/trunk/skatepark/block-template-parts/header.html#L1

The cause of the issue is actually our alignment rules 😅 , so let's double check our fix there against the skatepark header.

**Comment by MaggieCabrera** [comment] 2021-08-24 15:49
> The cause of the issue is actually our alignment rules 😅 , so let's double check our fix there against the skatepark header.

Doh!

**Comment by scruffian** [comment] 2021-09-03 09:31
This was fixed by #4468

**Closed as completed by scruffian** 2021-09-03 09:31 UTC
Labels: [Type] Bug, [Theme] Blockbase, [Theme] Skatepark
