### ISSUE TITLE
Baskerville 2: Wordads not showing fully on homepage on mobile 

### ISSUE THREAD

**Issue by poeticabdul** [Automattic/themes#5445] opened 2022-02-02 16:23 UTC
## Steps to replicate

1. Activate the Baskerville 2 theme on a site with Wordads active
2. Set the homepage to display latest posts
2. Check the site on mobile
3. Notice some of the ads on the homepage are not showing fully 

![ads-mobile](https://user-images.githubusercontent.com/4719037/152193834-5a1582c3-7a5e-4a47-b5ee-8aab8dc3862e.png)

![Screenshot_20220202-145006_Chrome](https://user-images.githubusercontent.com/4719037/152193854-e68315a6-2355-4110-bc10-6ff5f892ec3d.jpg)

## Result

Ads showing on the homepage on mobile devices are not showing the full graphic

## Expected

Ads should show the full graphic on mobile devices

* User report: 33920594-hc
* Follow-up ticket: 4742563-zen

**Comment by cphilleo** [comment] 2022-02-04 19:54
This issue is caused by the ads loading _after_ the Masonry library has run the layout on the posts container.

A call to `jQuery( '.posts' ).masonry( 'layout' );` will fix the layout and expand the ads. Maybe this can be added to the page load event to fire after ads have finished loading.

**Comment by zdenys** [comment] 2022-02-05 13:23
>A call to jQuery( '.posts' ).masonry( 'layout' ); will fix the layout and expand the ads. Maybe this can be added to the page load event to fire after ads have finished loading.

@cphilleo you mean this can be done by someone from our theme team, right? The user is on a Simple Site, so no plugins or scripts can be added to their site.

**Comment by cphilleo** [comment] 2022-02-07 19:41
> @cphilleo you mean this can be done by someone from our theme team, right? The user is on a Simple Site, so no plugins or scripts can be added to their site.

Correct. It would need to be added by the theme team. Just pointing out a potential fix to save whoever ends up working on this a little debugging time.

**Comment by MaggieCabrera** [comment] 2022-04-12 10:18
I can't reproduce this anymore and I don't see the ads on the user site

**Comment by MaggieCabrera** [comment] 2022-04-13 07:37
I'm closing this one for now, if this surfaces again on a site we can reproduce this bug on please feel free to reopen

**Closed as completed by MaggieCabrera** 2022-04-13 07:37 UTC
Labels: [Type] Bug, [Status] Cannot reproduce, [Pri] Normal
