### ISSUE TITLE
Resonar: Featured images not shown after upgrading to WP5.6

### ISSUE THREAD

**Issue by priethor** [Automattic/themes#2901] opened 2020-12-10 16:24 UTC
## Steps to replicate

Resonar Version: 1.0.8

On any browser, after upgrading a site to WP5.6, the featured images are not shown on any page.

Inspecting the element `.entry-header-background`, the inline `height` property doesn't exist, thus the element has no height and doesn't show the featured image in the `background-image` property.

## Result

The featured images don't get a `height` inline style and are not displayed at all.

## Expected

The element `.entry-header-background` should have an inline `height`.

* User report: #26245284-hc

**Comment by Gilmoursa** [comment] 2020-12-11 19:05
The issue is occurring on Atomic sites. It can be resolved by installing the Enable jQuery Migrate Helper: https://wordpress.org/plugins/enable-jquery-migrate-helper/
Then go to the plugin’s settings: website.com/wp-admin/tools.php?page=jqmh (example link. Please change “website.com” to the user’s website address)
Then set the jQuery version to “Legacy 1.12.4-wp”
User report: #26270644-hc

**Comment by erricgunawan** [comment] 2020-12-11 23:52
Also got a report here: 5303074-hc

Followed up with the user on 3567669-zen by sharing the workaround from @Gilmoursa above (thanks!)

**Comment by happychait** [comment] 2020-12-13 03:01
Another report in 17094336-hc

@Gilmoursa 's workaround [above](https://github.com/Automattic/themes/issues/2901#issuecomment-743370398) helped. Thank you so much, Austin!

**Comment by danieldudzic** [comment] 2021-02-20 01:44
Hi!

This has been fixed on WordPress.com with the Resonar 1.0.9 update.

Unfortunately, at the moment there's no easy & quick way to push this fix to the WordPress.org theme repo.

For now, please use @Gilmoursa 's suggested fix or you can also download the WP.com version of Resonar, here: https://wordpress.com/theme/resonar

**Closed as completed by danieldudzic** 2021-02-20 01:44 UTC
Labels: [Type] Bug

**Comment by rastrau** [comment] 2021-10-06 11:33
Will this update be available any time soon for self-hosted WP instances through the WordPress theme repo? It seems only version 1.0.8 is available there.
