### ISSUE TITLE
Exford: 2-col Image Gallery block collapsing to 1-col

### ISSUE THREAD

**Issue by inaikem** [Automattic/themes#2446] opened 2020-09-10 08:57 UTC
The expected 2-col layout is visible when editing the homepage - see "Reporting: analytics..." section. However, when previewing the published page/accessing it directly, it shows the 2-col Image Gallery block collapsed into a single column.

Adjusting the column widths has no effect on the gallery and simply makes the content area smaller.

Further follow-up by @MaggieCabrera shows this can be replicated on a test site. The CSS was found to be different from the editor to the frontend, for some reason it’s not calculating the width correctly.

* User report: [#24009050-hc]
* Follow-up ticket: [#3304087-zd]

**Comment by kathrynwp** [comment] 2020-09-10 15:25
Duplicate of #2437

**Closed by kathrynwp** 2020-09-10 15:25 UTC
