### ISSUE TITLE
[Bug]: [Russell Theme] Bullet points not visible in the WordPress editor, but visible on the frontend

### ISSUE THREAD

**Issue by ricklabsdotn8** [Automattic/themes#7613] opened 2024-01-17 04:00 UTC
### Quick summary

Bullet points are not showing when adding an unordered list in the WordPress editor, but show on the frontend 

### Steps to reproduce

1. Activate the Russell theme
2. Create/edit a page/post
3. Add an unordered list
4. Publish the page/post, then preview

### What you expected to happen

The bullet points should be showing on the WordPress editor.

### What actually happened

The bullet points show on the frontend only.

### Browser

Google Chrome/Chromium, Mozilla Firefox, Microsoft Edge

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

7589304-zen

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by maciejpilarski** [comment] 2024-01-17 20:37
📌 REPRODUCTION RESULTS
– Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
I was not able to reproduce the issue:
![Markup on 2024-01-17 at 21:34:43](https://github.com/Automattic/themes/assets/9025643/1c77f636-374c-4f8c-8998-a75a30da5d9c)

📌 ACTIONS
– Requested author feedback

📌 Message to Author
Hi @ricklabsdotn8 👋 

I have followed your steps and was not able to reproduce the issue on my test site. Does the problem still occur on your side? Are you able to share with us some screenshots of the issue?

Thanks in advance!

**Comment by OmarFPG** [comment] 2024-01-18 02:32
Hi there @maciejpilarski I just played into this ticket, and I tested, too

Works fine on Atomic:
![image](https://github.com/Automattic/themes/assets/122303439/8abc51c0-2dfd-47d1-82c4-a60c43bf0d26)

I was able to replicate it on Simple sites (the user is on the Explorer plan):
![image](https://github.com/Automattic/themes/assets/122303439/3b2cb329-1687-4341-b50c-184715ce9d99)

**Comment by ricklabsdotn8** [comment] 2024-01-18 13:40
@maciejpilarski Seems to be isolated on Simple Sites.

I tested again, and the issue still occurs on Simple Sites - https://share.zight.com/Z4u2wvxQ

Appears to be working on self-hosted - https://share.zight.com/P8uwYdYw

Also working on Atomic - https://share.zight.com/DOuJvWQp

Updated report to Simple only.

**Comment by mgozdis** [comment] 2024-01-19 18:59
Another report here on a Simple site with `Arbutus` theme. Font sizes and some other CSS styling is also displayed differently in the Site Editor only: 7610250-zd-a8c

**Comment by ccwalburn** [comment] 2024-01-25 21:55
I received a report on a Simple site with the Appleton theme.
Font size is smaller in the editor than it is on the front end and images in a full-width 3-column block are overlapping in the editor but not on the front end.
7640201-zd-a8c

**Comment by ccwalburn** [comment] 2024-01-25 22:15
Another report on an AT site with a custom theme that was created by Built By WordPress.com.
Font family is different in the editor than it is on the front end 
7638691-zd-a8c

**Comment by maciejpilarski** [comment] 2024-05-05 09:21
Another report here on a Simple site 8129691-zd-a8c

**Comment by alaczek** [comment] 2024-08-21 01:07
I can't replicate this issue on simple anymore. Maybe there was a fix in Gutenberg since this issue was reported, and it's now fixed on both Atomic and Simple?

> Font size is smaller in the editor than it is on the front end and images in a full-width 3-column block are overlapping in the editor but not on the front end.

@ccwalburn this sounds like a different issue to me? If this is still happening might be worth opening separate issue for the Appleton theme.

**Comment by donnapep** [comment] 2024-10-09 19:53
I'm not able to reproduce this one either on Russell. For bonus points, I tried on the Free plan, then upgraded to the Premium (Explorer) plan as per https://github.com/Automattic/themes/issues/7613#issuecomment-1897671145 and both worked.

Given this, I'm going to close the issue.

**Closed as completed by donnapep** 2024-10-09 19:53 UTC
Labels: [Type] Bug, [Pri] Normal, Triaged, Customer Report
