### ISSUE TITLE
Business: Social Links Menu - There is no margin or padding around social icons on mobile

### ISSUE THREAD

**Issue by lakellie** [Automattic/themes#331] opened 2018-11-10 00:03 UTC
## Steps to replicate

- Install Business theme on a simple site
- Go to Customizer > Menus and create a Social Links Menu
- Add at least 2 social media links to the menu
- Check the "social menu" menu location box
- Visit the site, shrink the browser to less than 815px wide, and scroll to bottom of the homepage to view the social links menu

## Result

When the browser is smaller than 815px wide, there is no padding or margin between the social media icons.

Screenshot: http://cld.wthms.co/8F5Tr8

* User report: #4505655-hc
* Follow-up ticket: #1556059-zen
* User's site: https://mancelos.com/ (Issue is present at the bottom of homepage)

**Comment by arunsathiya** [comment] 2018-11-10 14:12
I tested this and can reproduce this issue as well on WordPress.com.

<img width="398" alt="screenshot 2018-11-10 at 19 41 47" src="https://user-images.githubusercontent.com/18581859/48302274-c7498b00-e520-11e8-860a-f0b398c1af0c.png">

On downloading the theme from [this page](https://wordpress.com/theme/business) for my self-hosted WordPress (WordPress.org)/local WordPress site, I am not able to reproduce the issue though.

<img width="398" alt="screenshot 2018-11-10 at 19 42 09" src="https://user-images.githubusercontent.com/18581859/48302275-c7e22180-e520-11e8-844f-61ddc6ae4121.png">

**Comment by laurelfulford** [comment] 2018-12-28 22:05
I can recreate this issue, too.

Assigning to @mendezcode in case this was tackled in the upcoming bunch of Business updates -- Ernesto, if not, feel free to unassign! :)

**Comment by mendezcode** [comment] 2019-01-10 11:22
All good @laurelfulford – I'll take care of this! :-)

**Comment by mendezcode** [comment] 2019-01-17 20:25
Fixed in [Automattic/default-small-business-theme@8b8d902](https://github.com/Automattic/default-small-business-theme/commit/8b8d9020ce949bbd7624445677d5e82f457d87da)

**Closed by mendezcode** 2019-01-17 20:25 UTC
Labels: bug, needs patch, support
