### ISSUE TITLE
Independent Publisher 2: Media & Text Block Background Color

### ISSUE THREAD

**Issue by joweber123** [Automattic/themes#2105] opened 2020-06-05 07:14 UTC
## Steps to replicate

1. Add a Media & Text Block
2. Add a background color to the text area of the block

## Result
The background color is not being displayed in the editor but is being displayed on the live site.

![media_text](https://user-images.githubusercontent.com/24914028/83847349-0a90cd80-a747-11ea-964a-0d4561136725.png)

## Expected

I expected the background color selected would display in the editor as it does on the live site.  This is especially problematic if the user would like to have a color background with white text.  

* User report:  #21667459-hc
* Follow-up ticket: #3035687-zd

**Comment by Gustavo-Hilario** [comment] 2022-08-02 13:47
I tested this bug on a local site and on WP.com simple and AT sites. I couldn't reproduce this issue. I think this is already solved, and we can close it now.

**Closed** 2022-08-02 18:29 UTC
Labels: [Type] Bug, [Theme] Independent Publisher 2
