### ISSUE TITLE
Baskerville 2: Image landscape format blog posts

### ISSUE THREAD

**Issue by Robertght** [Automattic/themes#7170] opened 2023-06-29 05:38 UTC
### Quick summary

A user recently share with us that their posts are not in order.

After digging around we noticed that turning off the featured image on the archives fixes the blog posts order, but so is increasing the height of it.

### Steps to reproduce

1. Create several posts(6-9)
2. Make sure the posts are set to the Image format
3. Add landscape image as a featured image [Example](https://3stepcasserolecom.files.wordpress.com/2023/05/13.-pom-poms-1.jpg) (3696x1384px)
4. Published them

### What you expected to happen

The posts to display in the reverse chronological order

![nxoSDm.png](https://github.com/Automattic/themes/assets/6737345/d9901d63-2f39-4e9b-9aa6-21b2b9108cdf)

### What actually happened

The posts displayed mostly in reverse chronological order but after the first row, they started to display weirdly:

![0HzdKs.png](https://github.com/Automattic/themes/assets/6737345/b815cc57-a6f9-40d5-82c3-5f9e828d3ec6)

### Browser

Google Chrome/Chromium

### Context

6463916-zen

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Intermittent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

As a workaround, I forced the height of the card  with CSS so it calculates the position correctly with JavaScript:

```
/* Tempx fix for the post order | xxxxxx-zen rg */
.hentry, .post {
    min-height: 226px;
}
```

**Comment by cuemarie** [comment] 2023-06-29 18:43
Hey @Robertght ! I think this is behaving by design. Baskerville 2 orders the posts based on the vertical position of the posts on the page, not just left-to-right by row. That means that the height/length of posts earlier in the page impact the order of posts later on the page; that's why the height of the landscape featured image impacts the order.

<img alt="screenshot" src="https://user-images.githubusercontent.com/27249804/209446045-426100f2-2cf1-4287-8740-df78a744a750.png">

I found this when triaging an earlier similar report here: https://github.com/Automattic/wp-calypso/issues/71096

---

Understanding this feature of the theme, the user may want to build a manual Blog Posts block page instead, where the content appears in order by row regardless of height. Or, they'll want to be very consistent with their featured images and excerpts.

📌 ACTIONS
- Closing as by design

**Closed as not planned by cuemarie** 2023-06-29 18:43 UTC
Labels: [Type] Bug, [Pri] Low, Triaged, [Theme] Baskerville 2, Themes
