### ISSUE TITLE
Independent Publisher 2: video embed problem

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#2454] opened 2020-09-12 13:28 UTC
#1140  Steps to replicate

1. Enable theme, and ensure the sidebar contains at least one widget.
2. Create a new post
3. Add some text with a paragraph block
4. Embed a Youtube video (also replicated with a Vimeo video
5. Add some more text after the video, and publish.
6. View published post
7. Visit Customizer and remove all widgets from the sidebar.
8 View post again.

## Result

The embedded video has apparently become zoomed in, and appears taller, obscuring the paragraph that was added underneath it, and even in some cases post meta, sharing buttons, etc.

## Expected

For the post to appear the same, except with no sidebar.

## Screenshots

**With sidebar widget**

![Youtube_embed_–_Shift_to_the_left](https://user-images.githubusercontent.com/11873759/92996449-ec87f580-f50b-11ea-9da7-20bb1e4a8eed.png)

**Without sidebar widget**

![Youtube_embed_–_Shift_to_the_left](https://user-images.githubusercontent.com/11873759/92996462-0aedf100-f50c-11ea-873d-00e7d9b66c01.png)

This does not appear to affect existing video embeds on a site, but only new embeds.

* User report: https://wordpress.com/forums/topic/youtube-embed-is-not-dispalyed-correctly/

**Comment by fstath** [comment] 2020-09-15 08:14
Another report of the exact same issue:
https://wordpress.com/forums/topic/trouble-embedding-a-youtube-video-wrong-aspect-ratio-hidden-text-not-centered-wrong-width/

**Comment by jerrysarcastic** [comment] 2020-09-16 00:19
The user replied to clarify that the issue seems to be related to the alignment settings for the embed block. I have confirmed this on my test site.  

If you set the block to "Wide Width" the full embed is shown:

![Screenshot on 2020-09-15 at 14-13-55](https://user-images.githubusercontent.com/1967448/93277646-0d478980-f75e-11ea-84b4-bbc0a747ea91.png)

If the block is set to "Full Width" it displays the full embed, but no longer centered:

![Screenshot on 2020-09-15 at 14-14-38](https://user-images.githubusercontent.com/1967448/93277670-1df7ff80-f75e-11ea-928f-ab7928a4c27f.png)

Setting the block to "Align Center" the embed is cropped and does not show the full aspect ratio of the video thumbnail, as reported originally:

![Screen Shot 2020-09-15 at 2 14 32 PM](https://user-images.githubusercontent.com/1967448/93277786-73341100-f75e-11ea-8870-eaab1b1825b6.png)

**Comment by philnick206** [comment] 2020-09-24 07:58
I had a similar report here: https://woothemes.zendesk.com/agent/tickets/3339573

Adding video embeds into a Columns block causes the video to appear incorrectly (it looks like it's trying to show it in the full width of the container but is being cut off):

![Markup 2020-09-24 at 08 49 35](https://user-images.githubusercontent.com/51966986/94117331-fda60000-fe43-11ea-8fb0-346979c071d7.png)

**Comment by KokkieH** [comment] 2020-09-28 05:25
Another one: https://wordpress.com/forums/topic/blocks-arent-working-for-me/

**Comment by KokkieH** [comment] 2020-11-24 06:25
Another report in https://wordpress.com/forums/topic/youtube-embedded-player-is-covering-up-following-block/

**Comment by kathrynwp** [comment] 2020-11-30 22:11
Another one in 25845482-hc - gave wide-alignment workaround

**Comment by poojashetty18** [comment] 2020-12-13 07:06
Another one reported on #3568100-zen

**Comment by synora** [comment] 2021-01-25 14:39
@arcangelini 👋 I noticed your merged commit at https://github.com/Automattic/themes/pull/2662. Is there anything else that needs to be done for this bug to be fixed?

**Comment by tarunvijwani** [comment] 2021-02-05 07:49
Another one reported on 13968364- HC.

Suggested them to use wide-width alignment as a workaround

**Comment by fstath** [comment] 2021-02-18 10:59
I got another report.
https://wordpress.com/forums/topic/why-are-my-embedded-youtube-videos-not-shown-properly/

**Comment by henziger** [comment] 2021-06-06 11:03
I have the same issue. Any idea when the fix in #2662 is expected to find its way into production?

**Comment by jordesign** [comment] 2021-11-08 10:21
Let's prioritise this one as it looks like we have an open PR ready to go!

**Comment by MaggieCabrera** [comment] 2022-04-18 10:19
We should confirm if this one was fixed by https://github.com/Automattic/themes/pull/2662

**Comment by jeffikus** [comment] 2022-04-22 17:51
@MaggieCabrera I'll test this on Monday.

**Comment by MaggieCabrera** [comment] 2022-04-25 10:12
Looks like this one has been fixed, closing.

**Closed by MaggieCabrera** 2022-04-25 10:12 UTC
Labels: [Type] Bug, Support, [Status] Needs Testing, [Pri] High, User Report, [Theme] Independent Publisher 2, Triaged
