### ISSUE TITLE
Twenty-Twenty-Four theme - Menu is supposed to displays a border but it's not visible in our demo.

### ISSUE THREAD

**Issue by mauropereiira** [Automattic/themes#8459] opened 2024-11-26 08:58 UTC
### Quick summary

Our Twenty-Twenty-Four theme (https://wordpress.com/theme/twentytwentyfour?tab_filter=all) displays a border around the menu when highlighted. 

![Image](https://github.com/user-attachments/assets/d414f9f5-86e3-4c73-8654-3809905ca7ed)

It shows correctly in .org demo version here →  https://wordpress.org/themes/twentytwentyfour/preview/
But on our demo version, it doesn't →  https://wordpress.com/theme/twentytwentyfour?tab_filter=all

This was reported by this user, who mentioned being impacted by their theme decision due to this bug →  9041831-zd-a8c

### Steps to reproduce

1. Active the theme on your website.
2. Go to the Editor.
3. Select the mobile view or change the "Overlay Menu" to `Always` to collapse the navigation menu.
4. When previewing the page and clicking on the menu, it is supposed to have a border when highlighted.

### A clear and concise description of what you expected to happen.

The theme works as expected, but our demo version doesn't.

This is the .org demo version and what it's expected to do: 
![Image](https://github.com/user-attachments/assets/e5259f9c-25b4-41d5-baa1-4f3680ced7fb)

### What actually happened

This is what our demo version shows: 
![Image](https://github.com/user-attachments/assets/4b784de9-ac0f-4ca4-a1e2-e27115b98bd3)

### Impact

One

### Available workarounds?

There is no user impact

### If the above answer is "Yes...", outline the workaround.

A workaround could be using CSS on the navigation menu:

`outline: none;`

### Logs or notes

The theme is Twenty-Twenty-Four.

**Comment by iamtakashi** [comment] 2024-11-26 16:50
@beafialho I looked into this issue for a bit. The theme has this additional CSS as default, which does the outline effect mentioned here.

```
:where(.wp-site-blocks *:focus){
        outline-width:2px;outline-style:solid
}
```

![Image](https://github.com/user-attachments/assets/ccf9be92-8701-4118-ac02-9405e5615a08)

However, for some reason, the demo site in dotcom only has this as additional CSS. Do you know anything about it? Can we add the above to the demo site?

```
a {
	text-underline-offset: .2em;
}
```
![Image](https://github.com/user-attachments/assets/654fd689-994d-4746-8d0c-aecf713d67a0)

**Comment by beafialho** [comment] 2024-11-27 09:47
@iamtakashi I don't know anything about this but I searched in the theme trac history and found [this issue](https://core.trac.wordpress.org/ticket/60535). Maybe this has impacted the result?

**Comment by jartes** [comment] 2024-11-27 15:36
Thanks for taking a look at this one @iamtakashi @beafialho. 

I've added this bug report to your board. Let me know if that's not correct. Thank you!

**Comment by iamtakashi** [comment] 2024-11-28 17:39
I'm unsure who or why the custom CSS for the text underline was added, but I have reset the global style to the default on the demo site since that will give an accurate impression of the theme.

**Comment by iamtakashi** [comment] 2024-11-28 18:03
I'm closing this. I can confirm the focus state is now how it should be in the theme. Feel free to reopen if the demo site still behaves something unexpected.

**Closed as completed by iamtakashi** 2024-11-28 18:03 UTC
Labels: [Type] Bug, [Pri] Low, Triaged, Customer Report, [Feature Group] Appearance & Themes, [Status] Auto-allocated, [Theme] Twenty Twenty-Four

**Comment by jartes** [comment] 2024-11-28 20:41
Thanks for fixing this one, @iamtakashi! I can confirm that both demo sites look the same :)
