### ISSUE TITLE
Orvis: Sidebar missing from Portfolio Project Type Archives

### ISSUE THREAD

**Issue by juliasydnor** [Automattic/themes#218] opened 2018-08-01 18:03 UTC
## Steps to replicate

1. Go to Settings > Writing and make sure Portfolio Projects are enabled.
2. Publish at least one portfolio project, and assign at least one project type to it.
3. Go to Customize > Widgets > Sidebar and make sure at least one widget has been added.
4. View the portfolio project type archive: http://yourgroovysite.wordpress.com/project-type/project-type-slug/

## Result

No sidebar is displayed on the portfolio project type archive. It's completely missing from the markup.

## Expected

The sidebar to be displayed on portfolio project type archives, as it is on other themes.

* User report: 5160208-hc
* Follow-up ticket: 1319103-zen
* User's site: https://cosimacobleycarr.com/project-type/optic-nerve/
* Reproduction site: https://julesthenoo.wordpress.com/project-type/project-type/

**Comment by alaczek** [comment] 2018-08-02 06:12
Orvis treats portfolio differently then blog/pages, and lack of sidebar on portfolio archives/single projects is the intended behaviour. It would also be too big of a change to introduce in a live theme, so I'll be closing this one as wontfix.

Some text can be added to the left of the images from Customize > Portfolio (as seen on the demo https://orvisdemo.wordpress.com/project-type/mains/).
If they are open to theme switch, maybe they'd like [Blask](https://blaskdemo.wordpress.com/) (has widgets in the footer)?

**Comment by jjchrisdiehl** [comment] 2018-08-30 19:12
**Issue still persists**

Perhaps the issue should be rephrased. The user currently sees a sidebar area in the customizer, even though this theme supposedly doesn't use a sidebar area on this template:

![Customizer](https://cldup.com/mAJvKsFaD6.png)

Which yields a big blank space on the live site:

![Live](https://cldup.com/BhvzEuxOFb.png)

**Fix**
Would be great to find out why the sidebar area is loading in the customizer altogether for the portfolio page type, as @alaczek mentioned this theme _shouldn't_ do that.

I gave the user the following CSS to adjust the appearance on the live site, but it is only a temporary solution since they'll still see the sidebar load in the Customizer:

`.tax-jetpack-portfolio-type .content-area{
    margin: 0 auto;
    float: none;
}`

Thanks!

**Comment by jaymendoza** [comment] 2018-08-30 20:33
If this gets fixed, user in #1382833-zen would like to be notified.

**Comment by joshuatf** [comment] 2018-10-12 11:38
Is there any update on this?  The user has checked back in and the issue appears unresolved.

**Comment by davidakennedy** [comment] 2018-10-12 12:47
@jjchrisdiehl reopened this and @joshuatf flagged it so I took another look...

I see on the customer site that the widget area showing up in the Customizer is doing so because of the widget visibility feature in Jetpack.

See: https://cloudup.com/cNRNZKD1n1c

If that is removed, I believe this will be solved for the customer. I don't see any related bugs to this in Jetpack right now. Given that the Gutenberg publishing experience is coming soon, this likely wouldn't be high on the list to be looked into.

This isn't caused by the theme, so I'm closing it again.

**Closed by davidakennedy** 2018-10-12 12:47 UTC
Labels: bug, support, wontfix

**Comment by ezebecke** [comment] 2018-10-19 16:39
Thank you @davidakennedy for taking another look.
Unfortunately, is not a self-hosted site. So the ability to disable widget visibility isn’t possible.  
I understand that it might not be worked on since the issue will be resolved when Gutenberg is implemented. I'll be recommending the user another theme.
