### ISSUE TITLE
[Dara]: Duotone only works in Editor - not published page.

### ISSUE THREAD

**Issue by AnjanaV93** [Automattic/themes#7054] opened 2023-05-04 10:01 UTC
### Quick summary

Duotone configurations for images are only visible in Editor, and not in the frontend.

### Steps to reproduce

1. Use Dara theme.
2. Create a post and include an image.
3. Apply duotone filter.
4. Confirm that things look fine on editor:
    
    ![image](https://user-images.githubusercontent.com/129587477/236173175-353ff6db-3221-4150-8e53-c1182603e6e8.png)

5. Notice that the filter is not applied on the published page:
    
    ![image](https://user-images.githubusercontent.com/129587477/236173270-628ea8bc-23fa-4e79-9780-d28545b80a5a.png)

### What you expected to happen

Duotone filter to be applied on the fronend as well.

### What actually happened

Duotone is only visible in Editor.

### Browser

Google Chrome/Chromium

### Context

6259701-zen

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

None

**Comment by tellisbethel** [comment] 2023-05-04 11:40
Same issue on the Sequential theme here: 27843422-hc

I assigned a CSS class to the gallery block that had the duotone applied and provided CSS to turn the images grayscale as a close approximation to their original duotone settings:

/* Set images grayscale to somewhat imitate duotone feature | 27843422-hc (db) */
.homepage-logos {
    filter: grayscale(100%);
    opacity: 80%;
}

**Comment by cuemarie** [comment] 2023-08-31 18:09
Closing as duplicate of https://github.com/Automattic/wp-calypso/issues/78442

**Closed as not planned by cuemarie** 2023-08-31 18:09 UTC
Labels: [Type] Bug, Needs triage, [Status] Duplicate, [Pri] TBD, Customer Report
