### ISSUE TITLE
Photos: All Content Hidden by Dark Background

### ISSUE THREAD

**Issue by torres126** [Automattic/themes#462] opened 2018-12-31 09:44 UTC
## Steps to replicate

1. Create a WordPress.com site with the Photos theme 
2. Publish a post which has a title, or some content 
3. Go into the Customiser
4. Select "Colours and Backgrounds" 
5. Pick a dark background, or choose one of the two darker options 
6. See issue 

## Result

**Dark background - content isn't readable**

![hfgddgfhdfghfgdh](https://user-images.githubusercontent.com/43215253/50566193-a6d2cb80-0d2e-11e9-9aaf-61a5e8ef221a.png)

**Light background - works fine**

![fasdsfadsfadfdsa](https://user-images.githubusercontent.com/43215253/50566199-b0f4ca00-0d2e-11e9-8eb4-99baa125563b.png)

## Expected

If there's a dark background, the content should still be readable and a lighter colour, such as white. It's especially bad as Photos offers two darker options by default, and though the text isn't completely unreadable, it's still very difficult to read and far from ideal. 

* User report: Noticed on my test site

**Comment by laurelfulford** [comment] 2019-02-04 18:32
Thanks for this report, @torres126!

This sounds like a broader issue we have reported for custom colours - basically, free plans can use theme's custom palettes or change the background colour; other plans have access to more colour customization. However, the preview for free themes wrongly shows that the text colour will change to contrast against the background, when in reality, it doesn't.

The issue is: 8119-wpcom. 

I'm going to close this issue in favour of that one, and add this report there. 

In testing this I've noticed that Photos doesn't have it's own built in colour palettes, like other themes - I'm going to create a separate issue for that.

**Closed by laurelfulford** 2019-02-04 18:32 UTC
Labels: bug
