### ISSUE TITLE
Twenty Fifteen: Image Captions Not Centered

### ISSUE THREAD

**Issue by aamills** [Automattic/themes#802] opened 2019-05-14 21:09 UTC
## Steps to replicate

When adding an image to a post in twenty fifteen, the image caption looks centered in the editor, but when viewed live, it's pushed to the left.

- Create a site with the Twenty Fifteen theme
- Publish a post with an image and a caption on that image
- View the post live to see the image caption location (reflected as centered in the editor, but to the bottom left of the image when viewed live)

## Result

While the image caption looks centered in the editor view, once published and viewed live, the caption is shown to the bottom left of the image.

Live view example:
![TwentyFifteenImageCaptions](https://user-images.githubusercontent.com/29556134/57732044-5f076d80-7659-11e9-8797-3d41b7b72c0c.JPG)

## Expected

I expected what I saw created in the editor and the location of the caption to be replicated on the live site.

Editor View: 
![TwentyFifteenEditorView](https://user-images.githubusercontent.com/29556134/57732090-7f372c80-7659-11e9-9085-2b1f19ca6c51.JPG)

Originally reported by user: #1388954-hc
Then replicated/tested on my own site (example screenshots)

In the chat, we gave them the following CSS as a work around:

```
.wp-caption.aligncenter .wp-caption-text {
  text-align: center;
}
```

## Other notes
Tested on another theme (Lovecraft), and captions were centered as seen in the editor.

**Comment by pbking** [comment] 2021-06-02 13:54
I was not able to reproduce this. Captions appear centered in both the editor and the view for this theme. Alignment is correctly being applied by the block.  Likely this has been addressed in Gutenberg since this was reported.

![image](https://user-images.githubusercontent.com/146530/120492837-6ad14400-c388-11eb-940f-6829181abd21.png)

Closing this item.  Though if the problem persists then please reopen.

**Closed by pbking** 2021-06-02 13:54 UTC
Labels: [Type] Bug, support
