### ISSUE TITLE
Seedlet: Jetpack newsletter sign-up block style conflict

### ISSUE THREAD

**Issue by melchoyce** [Automattic/themes#3021] opened 2021-01-13 18:20 UTC
## Steps to replicate

1. On a site with Jetpack enabled, add a Newsletter Sign-up block to a post.
2. See that the disclaimer text is small and a regular font weight.
3. Preview your post.
4. See that the disclaimer text is larger and bold.

## Result

In the editor, the Jetpack newsletter signup block disclaimer looks like this:

![image](https://user-images.githubusercontent.com/2846578/104492553-d36a8080-55a1-11eb-8b8b-8ab6bd7d9e0e.png)

While on the front-end, it looks like this:

![image](https://user-images.githubusercontent.com/2846578/104492588-e2e9c980-55a1-11eb-893a-8a1ea8fb6c56.png)

## Expected

I expect the front-end to mirror the styling in the editor.

**Comment by danieldudzic** [comment] 2021-01-15 23:23
I have done some investigating and found out that, Jetpack:

- Loads the [editor-ui.css](https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/modules/contact-form/css/editor-ui.css) file in the editor
- Loads the [grunion.css](https://github.com/Automattic/jetpack/blob/e13487d0dbbe4c743739b6f1a3e37c143a8c2614/projects/plugins/jetpack/modules/contact-form/css/grunion.css) file on the frontend

The styling (in `grunion.css`) "causing" the issue is:
```
.contact-form label {
    margin-bottom: 0.25em;
    float: none;
    font-weight: bold;
    display: block;
}
```
Since the code in `grunion.css`, styles Contact Form labels in a specific way - I'm assuming this is the correct styling.

The solution isn't for me clear here.

Should `grunion.css` be also loaded in the editor? Or should we copy over (a part of) the code to `editor-ui.css` to fix the issue?

In addition to the above, the selector used in `grunion.css`, `.contact-form` is not present in the editor. Making it work would require changing the selector in css or adding an extra class in the Contact Form block editor markup.

**Comment by danieldudzic** [comment] 2021-01-15 23:25
I'd appreciate your thoughts on this :)

cc: @scruffian @kjellr

**Comment by scruffian** [comment] 2021-01-18 11:49
This looks like a Jetpack issue, not a theme one. I'd move it to the Jetpack repo and close this.

**Comment by kjellr** [comment] 2021-01-18 13:03
Yeah, that sounds good to me. 👍

**Comment by danieldudzic** [comment] 2021-01-19 00:07
https://github.com/Automattic/jetpack/issues/18404

**Closed as completed by danieldudzic** 2021-01-19 00:07 UTC
Labels: [Plugin] Jetpack, [Theme] Seedlet
