### ISSUE TITLE
Geologist is missing header editor in site editor

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/themes#7371] opened 2023-09-15 10:22 UTC
### Quick summary

Prem plan
Theme Geologist
Set a static page in Settings->Reading to assign a page as the home page. The page will have pages as template
Go to the site editor to edit the pages template
The option to edit the header vanishes - 
<img width="620" alt="Markup 2023-09-15 at 20 18 11" src="https://github.com/Automattic/themes/assets/13706336/c83353bd-69dc-4e8f-86f9-1df70ef3d1e5">
Unset the static page and the option comes back
![Markup on 2023-09-15 at 20:20:40](https://github.com/Automattic/themes/assets/13706336/503f876f-69f6-4cbc-a5ab-d3edf071b176)

### Steps to reproduce

See above

### What you expected to happen

The header to be always editable

### What actually happened

It's missing

### Browser

Google Chrome/Chromium

### Context

6827472-zd

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

No but the platform is still usable

### Workaround details

Edit the header template directly

**Comment by cuemarie** [comment] 2023-09-21 19:30
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
I was able to replicate this as described:

https://github.com/Automattic/themes/assets/27249804/6b3a379a-d3bf-49d1-89d8-680f0fd8a227

📌 ACTIONS
- Triaged
- Possibly related: https://github.com/Automattic/wp-calypso/issues/81928

**Comment by alaczek** [comment] 2024-08-27 03:52
I can't reproduce this anymore following the steps from the video - it might have been due to editor issue that has since been fixed. I will be closing this issue - we can reopen/create a new one if it crops up again.

**Closed as completed by alaczek** 2024-08-27 03:52 UTC
Labels: [Type] Bug, [Pri] Normal, [Theme] Geologist, Triaged, Customer Report, [Feature Group] Appearance & Themes
