### ISSUE TITLE
Wilson: Published dates displaying inconsistently when they're inside a "Block Posts block.

### ISSUE THREAD

**Issue by ezebecke** [Automattic/themes#1820] opened 2020-02-26 03:17 UTC
## Steps to replicate

[Please include screenshots, browser information, and anything else that can help us recreate the problem.]

1- Add a block  `Block Posts` to a page.
2- Make sure that the `Show Date` option on the block is enabled.
2- View/preview the page

## Result

Most of the posts won't display the published date.

## Expected

To see all posts with the published dates next to the author.

* User report and follow up: #2744206-zd

**Comment by nielslange** [comment] 2020-02-27 12:09
Duplicate of https://github.com/Automattic/themes/issues/1821

**Closed by nielslange** 2020-02-27 12:09 UTC
Labels: support
