### ISSUE TITLE
Archeo theme - Page Break Block doesn't work

### ISSUE THREAD

**Issue by silvio-meter** [Automattic/themes#7424] opened 2023-10-11 16:51 UTC
### Quick summary

When the Page Break Block is added to a page, the pagination below the content isn't shown. Also, only the content above the Page Break is shown, and there's no way to reveal the other content, nor to open it in a new page.

### Steps to reproduce

1. Check the site [redacted]
2. Open one page in Block Editor
3. Add dummy content and a few Page Break blocks
4. Check the preview

### What you expected to happen

Page break links should be shown below the content.

### What actually happened

Only the content above the Page Break Block is shown, but there are no page break links that should lead to the content below the Page Break Block.no page break links 

### Context

URL: URL: [redacted]

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by cuemarie** [comment] 2023-10-13 00:40
Duplicate of https://github.com/Automattic/themes/issues/7425

**Closed as not planned by cuemarie** 2023-10-13 00:40 UTC
Labels: [Type] Bug, [Status] Duplicate, [Pri] TBD, [Feature Group] Appearance & Themes
