### ISSUE TITLE
_Dsgnsystm: Collapsed Button Width

### ISSUE THREAD

**Issue by danieldudzic** [Automattic/themes#1084] opened 2019-07-17 23:26 UTC
![Aligned_buttons](https://user-images.githubusercontent.com/905781/61418603-4f2b3480-a8fb-11e9-9dd7-cfb69480f270.jpg)

-------
They are displaying correctly in the editor, though:
![Editor_buttons](https://user-images.githubusercontent.com/905781/61418661-7da90f80-a8fb-11e9-8608-735bdda6faf3.jpg)

**Comment by iamtakashi** [comment] 2019-07-18 10:41
It looks like this is the cause.

```
header *, main *, footer * {
    max-width: inherit;
}
```

**Comment by danieldudzic** [comment] 2019-07-18 10:48
This actually seems to be caused by:

`.alignleft {
    max-width: 50%;
}`

and

`.alignright {
    max-width: 50%;
}`

**Comment by iamtakashi** [comment] 2019-07-18 13:02
Oh. right. That's what the button is inherited.

I can understand the intention of those max-widths for the `.alignleft` and `.alignright`, but it might cause unexpected result like this when everything inside is inheriting the max-width. 

I suppose this is something new in _dsgnsystm? I don't see this rule in Twenty Nineteen. @allancole any opinion?

**Comment by allancole** [comment] 2019-07-18 17:27
> I can understand the intention of those max-widths for the .alignleft and .alignright, but it might cause unexpected result like this when everything inside is inheriting the max-width.

Yeah, that approach might be a bit too aggressive if it’s effecting the buttons negatively. I’ll work out a fix that excludes buttons (and maybe a few other elements).

**Comment by allancole** [comment] 2019-07-18 22:10
This is now fixed in #1092 . 
Closing this issue…

**Closed by allancole** 2019-07-18 22:10 UTC
Labels: _dsgnsystm
