### ISSUE TITLE
Baskerville 2: White space above posts and gaps in layout

### ISSUE THREAD

**Issue by goblinartificer** [Automattic/themes#208] opened 2018-07-21 02:53 UTC
## Steps to replicate

**Browser:** I did this on Firefox 61 on High Sierra, original issue was first found in Chrome on Win10. Replicated in Safari but it didn't occur for the user in Edge/Win10. 

1. Set up a Baskerville 2 WordPress.com site with at least 20ish posts. 
2. Turn on infinite scroll. 
3. Set a static homepage and a separate Posts page.
4. View the site. Navigate to the Posts page, reload this a few times or click forward and back to it. You may need to scroll while the reload is happening.

## Result

One of three things:
1. Posts often start after a large gap at the top.
2. Six (or three, a full row or two) posts are situated at the top, followed by a large gap and then the rest.
3. A couple of posts are at the top, but either not in the right place (just one to the centre right, for example) or flickering out after first loading.

## Expected

The posts to display seamlessly, with no gaps.

## Observations

Please note that the HC transcript includes a useful video from the user which has sound. The user's also given blanket permission to tinker with their site.

On my test site, this issue did not occur until I had both set that non-repeating background image *and* the post transcripts rather than full text. I saw outcome 3 then (a single, very old post showing where the first post should then disappeared, showing outcome 1).

On the user's site, I saw outcome 2 for five reloads before seeing outcome 1. The next reload gave me outcome 2 again, but with three posts instead of the six I'd seen prior.

Where the top left post should say `style="position: absolute; left: 0px; top: 0px;"` within the page CSS, and does when inspected upon first functional load, when it's malfunctioning the CSS seems to specify a random pixel distance from the top. I've seen `1701px` (user's site, post right below background image), as well as `3374px` on my test site (over a screen's scrolling below the end of the background image). 

* User report: #5149171-hc
* Follow-up ticket: #1293959-zd
* User's site: https://jaacsmotors.com/cars/

**Comment by laurelfulford** [comment] 2018-07-23 21:38
I was able to replicate this on the user's site by scrolling down aggressively when the page is loading, but it took a few tries.

Just wanted to note I think the background image is not a necessary step -- the post lined up nicely with it when they were mislaid out, but I think that was just a coincidence.

**Comment by laurelfulford** [comment] 2018-07-23 21:54
I was able to recreate this on a test site without the background image, so I removed that step from the description.

We also have a second report of this in #210 (hattip @rezzap ):

User report: #4920299-hc
Follow-up ticket: #1298320-zd
User's site: https://cilantroroots.com Issue is on the homepage.

**Comment by MindyPostoff** [comment] 2018-07-24 08:51
Reported by user here: #1300124-zen

**Comment by laurelfulford** [comment] 2018-07-24 19:09
Another report (hattip: @krutidugade from https://github.com/Automattic/jetpack/issues/9595):

User report: 5218710-hc
User's site: http://sandeepa.in
Screenshots from the user: https://cloudup.com/ckkcGkLEs81

**Comment by cecilerainon** [comment] 2018-08-01 09:58
Also reported in #5404394-hc with Chrome 67 on Windows 7

- User is immersivefr
- Site is https://theatre-immersif.com/
- Screenshots: http://cld.wthms.co/6wSkQR

**Comment by thebud15** [comment] 2018-08-02 02:04
Reported again in 2911134-hc. 
I told user we could keep him posted via email here: 1319828-zen
Site: sitecorecompetencies.com
User's screenshots: https://sitecorecompetencies.files.wordpress.com/2018/08/error2.png and https://sitecorecompetencies.files.wordpress.com/2018/08/error1.png

**Comment by KokkieH** [comment] 2018-08-06 12:08
Another via the [forums](https://en.forums.wordpress.com/topic/white-space-7/)

Site: https://meglizpalmer.wordpress.com/

User provided the detail that it only happens if they publish more than nine posts on the site. (Reading settings are set to display ten posts at a time, but changing that to a lower number does not appear to trigger the bug.)

**Comment by blazevivan** [comment] 2018-08-08 11:42
User asked for an update on this in #1333035-zen

**Comment by gemmagarner** [comment] 2018-08-15 12:09
Another report in this [forum thread](https://en.forums.wordpress.com/topic/baskerville-2-huge-gap-between-menu-and-content-on-start-page/).

Site: https://glaciers2aral.wordpress.com/

**Comment by laurelfulford** [comment] 2018-08-22 23:48
Another report (originally from #5025-wpcom-themes).

Site: ​https://vantagesfromvandalia.com/

User report: #4948082-hc

**Comment by formosattic** [comment] 2018-08-27 01:07
Another report in 5949235-hc
Site: https://illiberalpolitics.com/blog/
Follow-up: 1373459-zen

**Comment by sarahfg** [comment] 2018-08-27 17:40
Another report HC 5998473
site: wasserundeis.com
They are probably switching themes

**Comment by sarahfg** [comment] 2018-08-27 17:41
Another report Zen- 1368163
Site https://thatdashekid.wordpress.com

**Comment by ajaykj** [comment] 2018-08-30 07:17
#zen-1319828 came into play again. Keeping that on `on-hold` for now.
Site: sitecorecompetencies.com

**Comment by gemmagarner** [comment] 2018-09-17 16:27
Another report in [this thread](https://en.forums.wordpress.com/topic/half-of-the-page-is-shown-empty/).
Site: https://refugebyreveur.wordpress.com/

I haven't been able to replicate the behaviour but two people have reported it happens in Windows 8.1/Firefox 62/Chrome 68 and Windows 10/Chrome 68.

**Comment by edwinho89** [comment] 2018-09-19 07:58
User had a secondary followup on #1426789-zen

**Comment by laurelfulford** [comment] 2018-09-19 16:30
Another report (hattip @damiannep):

* User report: #5411040-hc
* Follow-up ticket: #1427808-zen
* User's site: https://integration-resources.com

**Comment by dcoleonline** [comment] 2018-10-10 16:33
User report & Follow-up Ticket: #1467605-zen
User's site: nationaltrustfamily.co.uk

They're noticing this on iOS 12 in Safari that there is a large gap under one of their posts that has a Jetpack gallery in the featured image area.

**Comment by selectedselections** [comment] 2018-10-17 19:11
#zen-1427808 came into play for me today. Keeping the ticket on on-hold for now.
Site: https://integration-resources.com

**Comment by ccwalburn** [comment] 2018-10-24 20:12
#zen-1427808 came back into play for me today. Put ticket on hold again.
Site: https://integration-resources.com

**Comment by ccwalburn** [comment] 2018-10-31 21:55
#zen-1427808 came back into play for me today. Put ticket on hold again.
Site: https://integration-resources.com

**Comment by jordesign** [comment] 2018-11-16 00:40
#zen-1427808 came back into play for me today. Put ticket on hold again.
Site: https://integration-resources.com

**Comment by torres126** [comment] 2018-11-18 08:37
This was also reported in this forum thread: https://en.forums.wordpress.com/topic/gap-before-the-post/

Site: https://frombrushtoheart.org/newsupdates/

**Comment by torres126** [comment] 2018-11-22 20:07
Also reported in this forum thread: https://en.forums.wordpress.com/topic/homepage-layout-glitch

Site: http://www.acoffeestainednotebook.wordpress.com/

Just noting that the user first saw this issue after backdating a few posts.

**Comment by KokkieH** [comment] 2018-11-29 06:01
Another report from [the forums](https://en.forums.wordpress.com/topic/baskerville-2-blog-post-excerpts-do-not-load-properly-sometimes/)

Site: https://thatbubbleteablog.wordpress.com/reviews/

**Comment by jordesign** [comment] 2018-12-14 07:07
#zen-1427808 came back into play for me today. Put ticket on hold again.
Site: https://integration-resources.com

**Comment by jordesign** [comment] 2018-12-21 08:06
#zen-1427808 came back into play for me today. Put ticket on hold again.
Site: https://integration-resources.com

**Comment by gemmagarner** [comment] 2018-12-28 12:10
Reported in [this thread](https://en.forums.wordpress.com/topic/gaps-before-blogs-appear/).

**Comment by torres126** [comment] 2018-12-31 09:16
Another report in the thread [above](https://en.forums.wordpress.com/topic/gaps-before-blogs-appear/#post-3242206).

> For some reason, the CSS is positioning each post-container element on the home page several thousand pixels down from the top.

**Comment by laurelfulford** [comment] 2019-01-01 19:06
I think I have a fix for this; I've deployed it, but would appreciate a second (third, or fourth!) set of eyes to confirm it's behaving better on these sites before following up with folks. It's one of those annoying issues that doesn't happen every time, so I want to make sure it's actually fixed.

/cc @danieldudzic, plus anyone above who may have time to double check!

Fix is in r52696-wpcom-themes.

**Comment by torres126** [comment] 2019-01-01 19:15
Tried about four times on around half a dozen sites and I couldn't recreate this anymore. :tada:

**Comment by danieldudzic** [comment] 2019-01-02 12:52
@laurelfulford I was unable to replicate the issue, so I believe the fix worked 😃

**Comment by laurelfulford** [comment] 2019-01-02 20:23
Thanks @torres126 and @danieldudzic for the tests!

Going back through the tickets, it looks like these are largely older reports, so I can't add a comment to most. I will focus on following up on forum threads.

I've retested all of these sites with an ad blocker off, scrolling up and down frantically, and I can't recreate the issue. However, when following up, I think it'd still be a good idea to say something like, "we've deployed a fix and have done a lot of testing, but given the inconsistent nature of the bug, it's possible we've missed something", and encourage folks to follow up if they do continue to see issues after clearing their browser cache. I'll keep an eye on this ticket should it be reopened. 

If any HEs who have reported this issue are available, the following reports need to be followed up with: 

* 1293959-zen (https://jaacsmotors.com/cars/)
* 1298320-zen (https://cilantroroots.com)
* 1300124-zen (https://sandeepa.in/)
* 5404394-hc (https://theatre-immersif.com/)
* 1319828-zen (sitecorecompetencies.com) 
* 4948082-hc (https://vantagesfromvandalia.com/)
* 1373459-zen (https://illiberalpolitics.com/blog/) - have switched to Tortuga
* 5998473-hc (https://wasserundeis.com)
* 1368163-zen (https://thatdashekid.wordpress.com)
* 1467605-zen (https://nationaltrustfamily.co.uk) - have switched to Huntt

I've added a comment for follow up to:

* 1427808-zen (https://integration-resources.com)

I'll work through the forum threads now, and follow up once all have been replied to.

**Comment by laurelfulford** [comment] 2019-01-02 20:54
I've added comments to, and signed up for email alerts, for:

* https://en.forums.wordpress.com/topic/half-of-the-page-is-shown-empty/ (https://refugebyreveur.wordpress.com)
* https://en.forums.wordpress.com/topic/gap-before-the-post/ (https://frombrushtoheart.org/newsupdates/)
* https://en.forums.wordpress.com/topic/homepage-layout-glitch (http://www.acoffeestainednotebook.wordpress.com/)
* https://en.forums.wordpress.com/topic/baskerville-2-blog-post-excerpts-do-not-load-properly-sometimes/ (https://thatbubbleteablog.wordpress.com/reviews/)
* https://en.forums.wordpress.com/topic/gaps-before-blogs-appear/ (https://joinedupcollective.wordpress.com and https://deborahj.home.blog/)
* https://en.forums.wordpress.com/topic/white-space-7/ (https://meglizpalmer.wordpress.com/)
* https://en.forums.wordpress.com/topic/baskerville-2-huge-gap-between-menu-and-content-on-start-page/ (https://glaciers2aral.wordpress.com/) - followed up on thread, but they have switched to Rowling

I'm going to close this ticket, because the issue should be fixed, but please comment/reopen if anything similar persists!

**Closed by laurelfulford** 2019-01-02 20:54 UTC
Labels: bug, needs testing, support

**Comment by goblinartificer** [comment] 2019-01-03 00:45
followed up:

-  1293959-zen (https://jaacsmotors.com/cars/) _in 1684462-zen_
-  1298320-zen (https://cilantroroots.com) _in 1684495-zen_
-  1300124-zen (https://sandeepa.in/) _in 1684500-zen_
-  5404394-hc (https://theatre-immersif.com/) _in 1684508-zen_
-  1319828-zen (sitecorecompetencies.com) _in 1684511-zen_
-  4948082-hc (https://vantagesfromvandalia.com/) _in 1684520-zen_
-  1373459-zen (https://illiberalpolitics.com/blog/) - have switched to Tortuga _in 1684523-zen_
-  5998473-hc (https://wasserundeis.com) _in 1684546-zen_
-  1368163-zen (https://thatdashekid.wordpress.com) _in 1684534-zen_
-  1467605-zen (https://nationaltrustfamily.co.uk) - have switched to Huntt _in 1684531-zen_
-  1427808-zen (https://integration-resources.com) - _in still-open ticket_

**Comment by KokkieH** [comment] 2019-01-03 07:14
Thank you for the forum follow-ups, @laurelfulford!

**Comment by KokkieH** [comment] 2019-01-03 08:32
Several forum users have confirmed it's working for them now.

**Comment by laurelfulford** [comment] 2019-01-03 21:55
Thanks for following up with folks, @goblinartificer!

> Several forum users have confirmed it's working for them now.

Yay! :D
