### ISSUE TITLE
[Bug]: Tenku Theme: Blog Posts block not showing the latest post in the front page

### ISSUE THREAD

**Issue by kspilarski** [Automattic/themes#7803] opened 2024-05-14 15:06 UTC
### Quick summary

Adding a Blog Posts block in the site editor will display the latest post but not in the live front page.

### Steps to reproduce

1. Activate the Tenku theme.
2. Go to the site editor and add a Blog Posts block and save. In the editor, you should see the posts including the latest post. 
3. Go to the live front page, and all posts will be there except for the latest post. 
4. Publish a new post in Posts. 
5. Visit the live front page again. The second to the last post (that wasn't appearing before) will now appear, but not the recently published post. 

### What you expected to happen

The latest post will appear not only in the site editor but also in the live front page.

### What actually happened

The Blog Posts block in the site editor shows the latest post, including the other posts. But on the live front page, only the other posts are displayed and not the latest one. Publishing a new post will display the second to last post in the live page, but not the latest one.

This works fine though on regular pages, just not the site editor on the Tenku theme. 

### Browser

Google Chrome/Chromium

### Context

Customer report 8188892-zen and self-testing

### Other notes

User case: 8188892-zen
I was able to replicate this on my test site. 

Site Editor, the latest post is `awqqw` : 
<img width="1226" alt="Screenshot 2024-05-14 at 16 42 09" src="https://github.com/Automattic/themes/assets/36863633/f8a0df9c-cd4e-46c1-a6c6-deab40ceb7d5">

Viewing the front page does not show the  latest post `awqqw` :
<img width="1477" alt="Screenshot 2024-05-14 at 16 42 56" src="https://github.com/Automattic/themes/assets/36863633/f7c4f91f-9094-416a-a185-7aae8d80ba02">

---

I published a new post called `Newest post` and it appears in the site editor:
<img width="1274" alt="Screenshot 2024-05-14 at 17 05 00" src="https://github.com/Automattic/themes/assets/36863633/85d4683b-ed57-4695-8629-8e4c83e7c3d8">

But on the front page, it does not show the latest post  `Newest post` but displayed the one before that which is `awqqw` : 
<img width="1494" alt="Screenshot 2024-05-14 at 17 03 29" src="https://github.com/Automattic/themes/assets/36863633/08341685-c119-4a06-9365-deda194ef2b9">

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

Yes, easy to implement

### Workaround details

In the Blog Posts block, select specific posts to display the latest post. Or use the Latest Blog Posts block.

**Comment by rickmgithub** [comment] 2024-05-23 06:18
## 📌 REPRODUCTION RESULTS ##
- Tested on Simple – Replicated  
- Tested on Atomic – Replicated 

## 📌 FINDINGS/SCREENSHOTS/VIDEO ##
Replicated it exactly as the OP describes.

## 📌 ACTIONS ##
Triaged

**Comment by liviopv** [comment] 2024-05-23 09:58
Closing as Duplicate of https://github.com/Automattic/wp-calypso/issues/69306 

cc @kspilarski @rickmgithub

**Closed as completed by liviopv** 2024-05-23 09:58 UTC
Labels: [Type] Bug, [Pri] Normal, Triaged, FSE, Customer Report
