### ISSUE TITLE
Dyad 2: Customizer background color not reflected in the editor

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/themes#7245] opened 2023-07-18 15:07 UTC
### Quick summary

The `Dyad 2` theme defaults to a dark background color in the Customizer, which suggests you should use a light (or white) color for text on the site. However, the default font color is not modifiable in the Customizer, and setting a light font color in the editor for individual blocks is difficult, as the editor always appears with a white background.

Compare to a theme like `Hever`, where setting a dark background color changes the editor's background color.

### Steps to reproduce

1. Activate Dyad 2.
2. Check the Customizer > Colors & Backgrounds area to ensure the "background" color is set to a dark color.
3. Open the editor for a page or post.

### What you expected to happen

With the editor's "show theme styles" preference enabled, I'd expect the dark background color to be present in the editor as well, so font colors can be tested in the editor without needing to preview each change. That would also allow lighter font colors to be used (to contrast against the site's dark background) while still being legible in the editor.

### What actually happened

The editor background is always white. 

### Context

6549835-zd-woothemes

### Platform (Simple, Atomic, or both?)

Atomic

### Other notes

Not yet tested on Simple or self-hosted.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by cuemarie** [comment] 2023-07-18 17:20
📌 SCRUBBING : RESULT - *Replicated / Could Not Replicate / Uncertain*
- Tested on Simple – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
- With Dyad 2 active on a test site and a dark color set as the background, the theme still gives the actual content area a white background, which matches the editor accurately.

#### Screenshots/Recordings

![Markup on 2023-07-18 at 10:14:05](https://github.com/Automattic/themes/assets/27249804/0262f176-e836-4e25-932a-8af086fa5a8f)

![Markup on 2023-07-18 at 10:15:00](https://github.com/Automattic/themes/assets/27249804/252b5245-4392-4d88-a0d2-e00c730dbfc2)

![Markup on 2023-07-18 at 10:14:41](https://github.com/Automattic/themes/assets/27249804/b20bb848-9d15-4b0a-aedd-772b45571822)

![Markup on 2023-07-18 at 10:15:41](https://github.com/Automattic/themes/assets/27249804/73ad1400-07cc-45bf-880c-d3ab66d8536c)

📌 ACTIONS
- Closing as won't fix (theme is working by design)

📌 Message to Author
- Hey @jp-imagines ! I checked out the user's site, and it looks like they customized the background color of the content with CSS - that's not the default behavior of the theme.  

<img width="550" alt="screenshot" src="https://github.com/Automattic/themes/assets/27249804/3fc4fb05-1992-47d9-b25a-a152278ee355">

**Closed as not planned by cuemarie** 2023-07-18 17:20 UTC
Labels: [Type] Bug, [Pri] Low, Themes

**Comment by jp-imagines** [comment] 2023-07-18 21:36
> I checked out the user's site, and it looks like they customized the background color of the content with CSS - that's not the default behavior of the theme.

@cuemarie 🤦 I saw that CSS and didn't think twice about it. Totally missed that the "background" color doesn't actually apply to the content area. My bad! Thanks for taking the time to triage this anyway! 😅
