### ISSUE TITLE
Mayland: colour options in Editor all Black/Red

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#2495] opened 2020-09-22 19:37 UTC
This screenshot from the Editor in a new site using Mayland …

![image](https://user-images.githubusercontent.com/545779/93929041-daaf0b00-fce0-11ea-8fd7-485cbce81211.png)

Doesn't seem to match the variety of intended palette styles …

https://github.com/Automattic/themes/blob/master/mayland/functions.php#L57

I suspect this is a colour annotation bug.

**Comment by ianstewart** [comment] 2020-10-22 14:52
Hmm. When I reported this issue, I was seeing one colour pre-selection in the inspector UI, and another upon selection. I can't reproduce this now, perhaps due to the set up of the original test site.

I'll close this issue as I can't reproduce. If it pops up again for me, I'll report with more details.

**Comment by bsanevans** [comment] 2020-11-02 00:29
I have another user reporting  similar thing happening on the Maywood theme. I could reproduce this on the user site in Support Sessions, but not on my test site. An HC was able to reproduce this on their test site, though, so it seems to happen intermittently.

### User Report

Site: https://visa-to.com/
Theme: Maywood
Context: User says it started after they upgraded from Personal to Premium. This could just be coincidental. (3424784-zd-woothemes)
What I've tried:

- I can reproduce the issue on the user's site in Support Session
- Creating a new page and using new blocks shows the same thing
- Clearing the page cache from the mu-menu, and clearing the site's color cache didn't help
- I can't reproduce the issue on my own test site on the Premium plan, using Maywood theme
- The user tried switching themes to Redhill, and got the same thing happening there
- Switching back to Maywood didn't reset anything and the issue persists.

Screenshot from user site:
![Markup 2020-10-30 at 14 57 24](https://user-images.githubusercontent.com/49054298/97819744-e03f3e00-1ced-11eb-8c0d-6bf25acf13e4.png)


### Bug Report by Happiness Contractor

Report: pbEMJv-id-p2
Test Site: http://ayanamogi.blog
Theme: Maywood
Other notes: The HC changed their site theme to Balasana, and the color options showed correctly.

**Comment by bsanevans** [comment] 2020-11-02 01:10
I was directed to a similar issue here: https://github.com/Automattic/wp-calypso/issues/46527

I tried the solution mentioned there... resetting the color settings in the Customizer and saving changes, and that fixed the issue!

I'll close this again, but decided to leave the solution here for others to find, too.

**Closed by bsanevans** 2020-11-02 01:10 UTC
Labels: [Pri] High

**Comment by ivan-ottinger** [comment] 2021-02-02 16:05
Just noting here that there was same issue, but with Balasana theme.

Reseting the colors in Customizer helped.

3706045-zd-woothemes
