### ISSUE TITLE
Resonar featured images not displayed on WordPress v.5.6

### ISSUE THREAD

**Issue by fstath** [Automattic/themes#2910] opened 2020-12-14 10:54 UTC
On WordPress version 5.6 featured images on posts and pages are not displayed. I tested this on both an Atomic site and on a local installation.

Reverting to version 5.5.3 resolves the issue.

* User report: https://wordpress.org/support/topic/featured-image-not-working-following-upgrade-to-5-6/

**Comment by federico-pepe** [comment] 2020-12-30 10:22
I have Resonar installed on my website. I noticed this problem some days ago but today my wordpress went in recovery mode when I tried to update a post because Resonar was causing an error. I also realized that with Resonar all the images in my posts are not displayed (everything works fine if I switch to Twenty Fourteen, for example).

Is it possible to fix this problem asap?

**Comment by irisv** [comment] 2020-12-30 11:35
> Is it possible to fix this problem asap?

While we wait on a fix, reverting to Wordpress version 5.5.3 resolves the issue. You can use the plugin WP Downgrade to do this, or downgrade manually.

**Comment by federico-pepe** [comment] 2020-12-30 11:54
> While we wait on a fix, reverting to Wordpress version 5.5.3 resolves the issue. You can use the plugin WP Downgrade to do this, or downgrade manually.

I just re-installed Wordpress 5.5.3 but the featured images are not showing on Resonar

**Comment by irisv** [comment] 2020-12-30 12:09
> I just re-installed Wordpress 5.5.3 but the featured images are not showing on Resonar

Right, well, I'm not the developer of this theme, I'm just another user who subscribed to this issue because I'm also waiting for a permanent fix. For me, the downgrade to 5.5.3 worked so I can confirm that featured images work with Resonar on WP 5.5.x. I also read that it worked for other people with similar issues with this and other themes, which all started with the 5.6 upgrade. 

If it doesn't work for you, that probably means there's more going on at your end. Sometimes downgrades are incomplete, so check that (there's a "At a glance" box on the dashboard that lists the version). If you have a backup you can revert to (last backup before you upgraded to 5.6), I'd try that.

**Comment by irisv** [comment] 2021-01-22 13:52
Will this issue be fixed? Or should we consider Resonar at its end of life now and switch to a newer theme?

**Comment by mjchamplin** [comment] 2021-01-22 14:36
I was hoping for a fix, but it's looking less and less likely at this point. 

I'm going to try and find the time to see what's causing the issue and get a feeling for whether it's a big or small fix, but I don't know.

**Comment by maniu** [comment] 2021-02-02 16:09
This issue is related to jQuery changes in 5.6. Installing "Enable jQuery Migrate Helper" and enabling legacy jQuery version makes it work again.
More proper fix involves changing line 20-in js/functions.js to:
`headerImageHeight = $( '.header-image' ).length ? $( '.header-image' ).height() : 0,`

**Comment by JessBoctor** [comment] 2021-02-03 23:24
If you don't want to install the "Enable jQuery Migrate Helper" plugin, you can also use custom CSS to set the height for the featured images. This will make all of the featured images the same height though, unless you customize it per page/post

```
/* Set Featured image height */

.entry-header-background {
height: 500px;
}

```

**Comment by annacmc** [comment] 2021-02-04 03:16
Another report of this issue (HC-26517993) CSS workaround above fixed it in the meantime.

**Comment by fresatomica** [comment] 2021-02-04 08:06
Another report here: https://wordpress.com/forums/topic/resonar-featured-images-not-working/.

**Comment by msilbers** [comment] 2021-02-04 17:47
reported in 3829474-hc
provided the CSS workaround for now

**Comment by mjchamplin** [comment] 2021-02-04 23:55
@maniu your js fix worked for me, thanks. 

Here's hoping they push out an update soon!

**Comment by mjchamplin** [comment] 2021-02-05 00:06
Seems like it would be fairly easy to update `functions.js` to fix this issue and do a PR, but I don't see the theme in this repository. Is it no longer supported, or just no longer open source?

**Comment by danieldudzic** [comment] 2021-02-05 12:18
This has now been fixed in r57711.

**Closed as completed by danieldudzic** 2021-02-05 12:18 UTC
Labels: [Type] Bug, Support
