### ISSUE TITLE
[Bug]: Tenku Theme - Time to read block not rendering / not compatible?

### ISSUE THREAD

**Issue by OmarFPG** [Automattic/themes#7624] opened 2024-01-23 20:08 UTC
### Quick summary

The Time to read block is broken on this theme. Apparently, it is not supported for some reason, but it is included in the template.

### Steps to reproduce

Install the Tenku theme, go to the site editor and check on the Single Posts template, you'll find the Time to Read block on the header is broken.; you'll

### What you expected to happen

The block should work and render properly.

### What actually happened

Simple sites:
![image](https://github.com/Automattic/themes/assets/122303439/91226350-0126-4c8e-af2a-33d647c25e84)

Atomic sites:
![image](https://github.com/Automattic/themes/assets/122303439/23ae9c1a-1b59-470e-80a1-21a4a879858f)

### Context

7628989-zen

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

None

**Comment by rickmgithub** [comment] 2024-01-24 10:48
## 📌 REPRODUCTION RESULTS ##

* Tested on Simple with Tenku 
- Another issue spotted
- The time to read block doesn't appear as an option

https://github.com/Automattic/themes/assets/13706336/c7a59065-a89c-4912-9951-35a865e01cea

 
- Tested on Atomic – Could Not Replicate
Block appears and works as I change the content length

https://github.com/Automattic/themes/assets/13706336/ec453e45-26ea-46f2-a6a3-e9878386b57d


## 📌 ACTIONS ##
Triaged 
- Author feedback

##Message to author##
Thanks so much for the report @OmarFPG  I couldn't replicate the issue on an Atomic site. Was there perhaps a specific way the page was set up? I've kept this open due to the missing block on a simple site but please do add a comment with more details if you can still replicate on Atomic.

**Comment by OmarFPG** [comment] 2024-01-28 14:29
Hi @rickmgithub thank you so much for looking into this. Here's a quick video replicating this on my Pro site: https://share.zight.com/2Nu95ZZB. I hope this helps!

**Comment by renata-franco** [comment] 2024-02-01 10:44
I got a report of this block not rendering correctly on a simple site with "Rowling" theme. 7580105-zen.

**Comment by caitlindawn** [comment] 2024-05-17 07:04
Reported on 8203203-zen with the "Spiel" theme on a simple site.

**Comment by chekle** [comment] 2024-05-21 23:20
Reported on 8221470-zd-a8c with the "Spiel" theme on a simple site.

**Comment by dsas** [comment] 2024-10-30 13:04
**I can't reproduce an issue otherwise right now.**

The time to read block is part of the Gutenberg plugin, but [it is not part of Core](https://github.com/WordPress/gutenberg/issues/53776#issuecomment-2008279426). If the Gutenberg plugin is deactivated the error will occur.

There was also a [bugfix for a block error in May](https://github.com/WordPress/gutenberg/pull/61614).  

I also can't reproduce any issues on Spiel with a simple site, or with Tenku with an atomic site. 

Looking at the linked issues:
 * 8221470-zd-a8c - sounds possibly different, because they mention being able to see the block
 * 8203203-zd-a8c - as above, but with screenshots
 * 7580105-zd-a8c - here they say the issue only happens when the reading time is > 1 minute. I can't reproduce this though.

I'm going to close this issue, feel free to open a new one if similar sounding problems occur.

**Closed as not planned by dsas** 2024-10-30 13:04 UTC
Labels: [Type] Bug, [Pri] Normal, Triaged, Customer Report, [Theme] Spiel
