### ISSUE TITLE
Lettre: Respect “current” class on desktop

### ISSUE THREAD

**Issue by simison** [Automattic/themes#7071] opened 2023-05-10 08:50 UTC
Via p9Jlb4-787-p2

@crisbusquets wrote:

> General nav
>
> On desktop, the `current` class doesn’t seem to work properly. The first item is always underlined, no matter if I’m on a post or on a different page.
>
>  https://github.com/Automattic/themes/assets/87168/ad54915c-758b-41f5-bc4e-557e581488d8

**Comment by edanzer** [comment] 2023-05-23 17:03
@crisbusquets @simison - This issue also traces back to a core block, in this case the navigation block. I can duplicate the issue on a vanilla WordPress site with the navigation block.

The issue is that as soon as you open the menu, the first item in the menu has 'focus', and [there's a css rule](https://github.com/WordPress/gutenberg/blob/97ab6b167cc0d9da6c5f0ecf6be9457570d33731/packages/block-library/src/navigation/style.scss#L65) that applies underline to any element with focus.

Is it worth me trying to open a PR in Gutenberg for the nav block for this? That would take a bit of learning, but I wouldn't mind getting up and running for Gutenberg. I do think the PR process is slower there. 

Other thoughts?

**Comment by simison** [comment] 2023-05-23 17:05
at least opening, and checking if there is one already, a bug report in Gutenberg would be good

I think there's a team focusing on navigation block specifically

**Comment by simison** [comment] 2023-05-23 17:06
also if you wanna fix a core block, go for it! :-)

**Comment by crisbusquets** [comment] 2023-05-23 18:01
> The issue is that as soon as you open the menu, the first item in the menu has 'focus', and [there's a css rule](https://github.com/WordPress/gutenberg/blob/97ab6b167cc0d9da6c5f0ecf6be9457570d33731/packages/block-library/src/navigation/style.scss#L65) that applies underline to any element with focus.

I'm not sure I understood this correctly: the `focus` overrides `current` (or the other way around)?

+1 to @simison, if that's the way to fix it 🙏🏼

Thank you @edanzer !

**Comment by edanzer** [comment] 2023-06-27 15:09
@crisbusquets @simison - Long over due, but I opened an issue to start a conversation about this on the Gutenberg repo here: https://github.com/WordPress/gutenberg/issues/51982

@crisbusquets - to your question above, :focus is overriding current. Indeed, from what I can tell, the block isn't applying a current class to the nav menu item for the current page. But they're definitely setting the focus to the first item on the menu each time user opens the mobile menu. 

I noted in the Gutenberg issue, I suspect this is for clarity for accessible navigation. It works well from an accessibility perspective if you click return to open the mobile menu, and the first item is immediately highlighted, and then you can tab through items. 

So I think this is kind of an issue where what's best/clearest for accessibility may not be best/clearest for all other considerations.

**Comment by edanzer** [comment] 2023-06-28 14:39
I've added a Gutenberg issue here: https://github.com/WordPress/gutenberg/issues/51982

I will monitor that and follow up. If I get time, I may submit a PR there. Because of the accessibility considerations, I suspect there will need to be discussion about this in the Gutenberg community for any PR.

**Comment by crisbusquets** [comment] 2023-06-28 15:14
> I've added a Gutenberg issue here: [WordPress/gutenberg#51982](https://github.com/WordPress/gutenberg/issues/51982)
> 
> I will monitor that and follow up. If I get time, I may submit a PR there. Because of the accessibility considerations, I suspect there will need to be discussion about this in the Gutenberg community for any PR.

Thank you for creating the issue, @edanzer. Should we leave this issue open, then?

**Comment by edanzer** [comment] 2023-06-28 15:33
I'd say leave this open as a reminder to check the Gutenberg issue. It'll help me at least :).

**Comment by edanzer** [comment] 2023-07-03 20:11
This was resolved in https://github.com/Automattic/themes/pull/7167

**Closed as completed by edanzer** 2023-07-03 20:11 UTC
Labels: [Type] Bug, [Theme] Lettre
