### ISSUE TITLE
Pique: Header/featured image noticeably resizes upon page load 

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/themes#15] opened 2018-02-24 04:48 UTC
This issue was originally reported by @SiobhyB in 4372-wpcom-themes:

The header/featured image on individual posts/pages noticeably resize upon page load.

You can see an example of this by visiting this post from the [theme's demo site](https://piquedemo.wordpress.com/):

https://piquedemo.wordpress.com/2015/11/12/where-does-coffee-come-from/

The following gif is taken from loading the above page in the latest version of Chrome on macOS Sierra: 

![](https://cldup.com/8560eL9l2G.gif)

This looks to be caused by the fact that a height is set inline on the header element as well as in the theme's CSS: 

![](https://cldup.com/z3h1dR-uFt-3000x3000.png)

* User report: 142440-hc
* Follow-up ticket: 3051922-t
* User's site: https://exceptionhandler.com

@tavilla61 added a second user report:

* User report: 1391397-hc
* Follow-up ticket: 870541-zd
* User's site: https://dbskatingpro.com

**Comment by sixhours** [comment] 2018-03-05 16:29
Going to wontfix this, since the theme specifies this is the intended behavior. The workaround in this case is to crop the image to the desired height of 240px before uploading it to the site.

Let me know if I can help further!

**Closed by sixhours** 2018-03-05 16:29 UTC
Labels: bug, needs patch, support
