### ISSUE TITLE
text-decoration shorthand with thickness has no support in WebKit browsers

### ISSUE THREAD

**Issue by madhusudhand** [Automattic/themes#6243] opened 2022-07-15 09:42 UTC
## Steps to replicate

Text decoration short hand that has thickness included makes the entire css style invalid in safari.

```
"typography": {
	"textDecoration": "none 0.25rem"
}
```

<img width="789" alt="image" src="https://user-images.githubusercontent.com/1935113/179197230-1f8f5dac-76a9-4b7b-a7b1-a72e1d68da78.png">

## Browser support

<img width="789" alt="image" src="https://user-images.githubusercontent.com/1935113/179196995-54a14a26-d77c-46fa-b6ad-be73638d9fad.png">

## Result

This effects following block themes.

- [x] Vivre https://github.com/Automattic/themes/pull/6490
- [x] Pendant https://github.com/Automattic/themes/pull/6490
- [x] Disco

## Expected

Should separate `text-decoration-tickness` from `theme.json` and define in `style.css`

**Comment by pbking** [comment] 2022-07-15 12:56
"Safari, the new Internet Explorer"

**Comment by pbking** [comment] 2022-08-09 17:30
I rather think we should just close this one.  I don't think we have an option to NOT use shorthand in a few places, at least not without/until a Gutenberg change.  If anything this should be opened there I think (though I'm not sure exactly what the change should be... maybe including text-decoration-thickness as a Global Styles-able attribute?)

**Comment by matiasbenedetto** [comment] 2022-08-12 10:44
I updated the title because I can confirm that isn't working with other WebKit browsers either.

![Screenshot from 2022-08-12 12-43-32](https://user-images.githubusercontent.com/1310626/184338783-0efad0ef-9853-454c-bb79-6a694abcedd1.png)

**Comment by matiasbenedetto** [comment] 2022-08-12 10:58
I took this approach for Disco: https://github.com/Automattic/themes/pull/6384

**Comment by mikachan** [comment] 2022-09-01 14:40
Closing with https://github.com/Automattic/themes/pull/6490.

**Closed as completed by mikachan** 2022-09-01 14:40 UTC
Labels: [Type] Bug, [Theme] Pendant, [Theme] Vivre
