### ISSUE TITLE
Varia: Hide scrollbars when using Verse Block

### ISSUE THREAD

**Issue by nielslange** [Automattic/themes#2842] opened 2020-11-22 02:40 UTC
## Steps to replicate

1. Activate Varia or any of its child-themes
2. Create a page or a post using the [Verse Block](https://wordpress.com/support/wordpress-editor/blocks/verse-block/)

## Result

Vertical and horizontal scrollbars are visible right and below the text:

<img width="813" alt="Screenshot 2020-11-22 at 09 36 09" src="https://user-images.githubusercontent.com/3323310/99892297-290f6480-2ca6-11eb-9434-697a06d595e4.png">

## Expected

No scrollbars are visible:

<img width="924" alt="Screenshot 2020-11-22 at 09 40 11" src="https://user-images.githubusercontent.com/3323310/99892354-b8b51300-2ca6-11eb-8f8f-4fc1eb47a249.png">

* User report: https://wordpress.com/nl/forums/topic/scrollbar-verzen/

**Comment by jacklenox** [comment] 2020-12-07 11:08
This appears to be expected behaviour. The theme's `_normalize.scss` file specifies the `overflow: scroll` property for the `pre` element which is used for the Verse block:

https://github.com/Automattic/themes/blob/ab448ae5e45e87326259f5747cb4c590fc39ffe3/varia/sass/base/_normalize.scss#L64-L68

In Chrome, this leads to greyed out scrollbars being shown. Though I note from my limited testing that Firefox doesn't match this behaviour. The same `_normalize.scss` is used in Seedlet and Seedlet-based themes.

A custom CSS fix for this is to apply `overflow: auto` to the `pre` element, or specifically `pre` elements with the `wp-block-verse` class if we just want to target Verse blocks.

**Comment by scruffian** [comment] 2020-12-07 11:13
What would happen if we just remove `overflow: scroll;`?

**Comment by jacklenox** [comment] 2020-12-07 13:28
From what I can see, that'll fix it. But I think there are a lot of themes where we're following this pattern and using this flavour of normalize.css, so do we change them all?

I fear also there might have been a good reason why this was done at some point. Although I note with interest that this particular declaration isn't in [the current iteration of normalize.css](https://github.com/necolas/normalize.css/blob/fc091cce1534909334c1911709a39c22d406977b/normalize.css#L64-L67).

I'm up for changing them if you are? :smile:

**Comment by scruffian** [comment] 2020-12-07 16:16
We added a lot of code to Varia and Seedlet to account for shortcomings in Gutenberg which have since been addressed. I think it would be interesting to try removing it from Varia and the child themes and then creating an issue to do the same for Seedlet if that goes ok.

**Comment by jacklenox** [comment] 2020-12-10 10:06
Thanks for the added context here. I'll sort a PR now.

**Closed as completed** 2021-01-05 16:36 UTC
