### ISSUE TITLE
Soho: Logo no longer displaying

### ISSUE THREAD

**Issue by JoshuaGoode** [Automattic/themes#4026] opened 2021-06-08 17:09 UTC
Logos are no longer appearing for sites with the Soho theme. Including the WordPress.com demo. 

Does not currently impact WordPress.com on Atomic sites, just Simple. 

## Steps to replicate

1. Activate Soho on a Simple site or visit one with it already active. 
2. Access Site Identity and set a logo.

## Result

No logo.

![image](https://user-images.githubusercontent.com/4887830/121228155-64483e00-c85a-11eb-85b4-a6f56a0dec36.png)

## Expected

A logo to appear as seen in the demo.

![image](https://user-images.githubusercontent.com/4887830/121228194-732ef080-c85a-11eb-8ffa-03b350ea8d40.png)

* User report: 29618704-hc
* Follow-up ticket: 4053426-zen

**Comment by JoshuaGoode** [comment] 2021-06-08 17:57
After discussing internally, p1623172456449300-slack-C029FM1EH , appears to be due to recent v10.7.4 Gutenberg patch release. 

r226861-wpcom
D62435-code

Started another internal discussion:
p1623174912090300-slack-CBTN58FTJ

**Comment by danieldudzic** [comment] 2021-06-08 18:00
Closing this, as the issue was caused by a Gutenberg update on dotcom.

**Closed as completed by danieldudzic** 2021-06-08 18:00 UTC
Labels: [Type] Bug, Premium
