### ISSUE TITLE
[Bug]: Startfitter duplicating tab title within the description field.

### ISSUE THREAD

**Issue by sverleis** [Automattic/themes#7537] opened 2023-12-07 13:35 UTC
### Quick summary

When using the Startfitter theme, a Woo product has the content title of each of the Woo Tabs duplicated to the top of the tab itself. This does not happen on other themes, such as Tsubaki.

### Steps to reproduce

1. Load up the Startfit or Startfitter themes.
2. Navigate to a single product page
3. Notic the WooCommerce Tabs section.

### What you expected to happen

Title is duplicated.
![nBnXlE.png](https://github.com/Automattic/themes/assets/16252298/6ee101ec-fff6-4fb2-8669-3c991f6ca43d)

### What actually happened

Title is duplicated.
![nBnXlE.png](https://github.com/Automattic/themes/assets/16252298/6ee101ec-fff6-4fb2-8669-3c991f6ca43d)

### Browser

Google Chrome/Chromium

### Context

User report - 7407562-zen

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Possible to remove with CSS. 

```
 /* Hide the tab heading | 7406208-zen rg */ 
div#tab-description h2:first-child {
display: none; 
}
```

**Comment by liviopv** [comment] 2023-12-28 13:44
📌 REPRODUCTION RESULTS
- Tested on Atomic – Replicated
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
Not theme-specific, as I'm able to replicate on TT4
![CleanShot 2023-12-28 at 13 40 18@2x](https://github.com/Automattic/themes/assets/14153300/2a0f59bf-9549-4941-9fe8-025f6423be1a)

Same happens on a local site with TT4, which makes me think this is by design:

![CleanShot 2023-12-28 at 13 41 25@2x](https://github.com/Automattic/themes/assets/14153300/4322a6ca-50c4-4bcd-910f-7ac07e4c0a5f)

Interestingly, Storefront has the same thing:

![CleanShot 2023-12-28 at 13 42 08@2x](https://github.com/Automattic/themes/assets/14153300/bdd45b72-31da-4218-aaf3-f8d23858ac00)


📌 ACTIONS
- Triaged
- Requested author feedback

📌 Message to Author
@sverleis can you point out a default Woo theme that *does not* work this way? I feel like this could be by designed, but I can't recall if it's something new or introduced recently.

As you can see above, even Storefront has duplicated headings for the product details section.

**Comment by liviopv** [comment] 2023-12-28 14:24
Slack: p1703773436938229-slack-C3NCP7ZJ6

**Comment by liviopv** [comment] 2024-03-26 11:38
@sverleis closing as by design, but please reopen if you have confirmation that it shouldn't be working this way.

**Closed as completed by liviopv** 2024-03-26 11:38 UTC
Labels: [Type] Bug, [Status] wontfix, [Plugin] WooCommerce, Triaged, [Pri] TBD, Woo Express, Customer Report
