### ISSUE TITLE
has-text-align-center class not applying to live site

### ISSUE THREAD

**Issue by joweber123** [Automattic/themes#1118] opened 2019-07-22 03:33 UTC
## Steps to replicate
1.) Create a *Heading block* and select the text alignment to centered.
![screenshot](https://cld.wthms.co/pdVhrK+)
[*Direct link to screenshot if the above does not load correctly*](https://cld.wthms.co/pdVhrK)
2.) Publish the post.

## Result
1.)view it while logged in as a superadmin.  The added class has a corresponding class in the stylesheets and aligns centered. 
![screenshot](https://cld.wthms.co/DCFVT9+)
[*Direct link to screenshot if the above does not load correctly*](https://cld.wthms.co/DCFVT9)

2.) View the same page in an incognito window.  The added class does not have a corresponding class in the stylsheets and aligns left as is the default. 
![screenshot](https://cld.wthms.co/JevDLb+)
[*Direct link to screenshot if the above does not load correctly*](https://cld.wthms.co/JevDLb)

## Expected

I expected that the style applied to the block would reflect on the site even when viewed in an incognito window.  

* User report: #10710827-hc
* Follow-up ticket: #2196780-zd

**Comment by davidakennedy** [comment] 2019-07-22 18:08
Hi @joweber123! Thanks for the report. Was this occurring in a specific theme or multiple themes?

**Comment by joweber123** [comment] 2019-07-22 23:49
@davidakennedy I'm sorry, this is my first time adding a theme bug via Github and didn't realize I wasn't in the specific theme repository.  This was noticed and tested on the Radcliffe 2 theme.

**Comment by katiebethbrown** [comment] 2019-07-24 00:46
I was working on opening a theme specific report for Shoreditch and noticed this one already open. I'm seeing the `has-text-align-center` class missing in that theme on the published site as well. It displays correctly when logged in. 

User report: #14026704-hc

Replicated on my Test site here: https://katiesstoreadminpractice.wordpress.com/

@davidakennedy  If you'd like I can open a new issue specific to Shoreditch, but wanted to mention it here since it sounds like it may be a larger issue.

**Comment by ersatzpenguin** [comment] 2019-07-25 21:14
I have another instance of this happening, this time on Sophisticated Business.

User report: 2207070-zen

I had one other instance of this a ~week ago on another "Business" theme (Calm Business, I believe). So, unless I'm mistaken, this seems to be an issue that spans multiple themes.

**Comment by iamtakashi** [comment] 2019-07-29 10:20
This doesn't seem a theme level issue. Gutenberg block library CSS is somehow missing from logged out websites. It's been reported here: https://github.com/Automattic/wp-calypso/issues/34932

**Comment by katiebethbrown** [comment] 2019-08-08 01:10
A note that this seems to be a duplicate of this issue:

https://github.com/Automattic/wp-calypso/issues/34932

**Comment by iamtakashi** [comment] 2019-08-08 14:02
I'm closing this as not a theme specific issue. Please follow this issue on Automattic/wp-calypso#34932

**Closed by iamtakashi** 2019-08-08 14:02 UTC
