### ISSUE TITLE
Snaps: Hamburger menu icon not functioning on mobile devices

### ISSUE THREAD

**Issue by kgeorgee** [Automattic/themes#5750] opened 2022-03-24 22:37 UTC
## Steps to replicate

1. Open site on either desktop or mobile browser. Used Chrome and Safari to troubleshoot the issue.
2. When opened on a desktop browser, resize the browser to the size of a mobile device.
3. Tap or click the hamburger menu icon.
https://snipboard.io/TNdBLz.jpg]

## Result
The hamburger is unresponsive. Nothing happens when it is clicked.

## Expected
The hamburger icon is supposed to expand and display all the menu items.

* User report: [80195331-hc]
* Follow-up ticket: [4890527-zen]
* User’s site: [https://cheryldphoto.com/]

![Screenshot 2022-03-24 at 10 14 36 PM](https://user-images.githubusercontent.com/9421242/160021390-4451583d-1a80-4cd0-a743-6187e81e87d5.png)

**Comment by poeticabdul** [comment] 2022-05-29 14:53
Had a similar report here 5240082-zd-woothemes for the site `thewhimsicalpaintbrushstudio.wordpress.com`.

On testing further, I was able to get the menu showing on mobile for my issue and the main issue. Pics attached. It seems, the site needs to load fully for the menu to work.

Main issue:

![Screenshot_20220529-144705_Samsung Internet](https://user-images.githubusercontent.com/4719037/170875785-f43e3a81-b764-4c5d-860d-ec0ae4ad87e8.jpg)

My issue: 

![Screenshot_20220529-144743_Samsung Internet](https://user-images.githubusercontent.com/4719037/170875790-2a57c7ad-3576-4790-9dc1-b73f3d4f31ef.jpg)

**Comment by Thelmachido** [comment] 2022-06-15 03:31
Hi, @kgeorgee and @poeticabdul closing this issue since it turned out to be something being caused by AMP plugin. There is an ongoing thread about that [here](https://github.com/Automattic/wp-calypso/issues/57369) 

Feel free to add your interaction on that thread.

**Closed as not planned by Thelmachido** 2022-06-15 03:31 UTC
Labels: [Status] wontfix, Themes
