### ISSUE TITLE
Dara: Featured Image srcset issue

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/themes#3] opened 2018-02-24 01:30 UTC
Originally reported by @senff in 4348-wpcom-themes:

The Featured Image on the home page is being cropped inconsistently. On page load it is cropped, but when switching to iPad view, and then back to normal view, it is not cropped anymore. Even after a refresh, it stays uncropped. 

## Steps to replicate

1. Go here: ​https://jswbaileylaw.com/

2. The Featured Image is a bit cropped (you can not see the boats at the bottom of the image, first screenshot). Refreshing the page will not change this.

![](https://cldup.com/3xcLR_jR-8-3000x3000.png)

3. Open the inspector into iPad view. The boats are now visible at the bottom (second screenshot)

![](https://cldup.com/crNJqoRbwy-3000x3000.png)

4. Close inspector panel. The window is back to the original size, but now the boats are visible. Refreshing the page will "reset" that (third screenshot)

![](https://cldup.com/MZz6y8udQv-3000x3000.png)

5. Open the site again in a new tab. Now the boats are gone again even though the window is the exact same size as the other tab. 

## Testing

I tried to replicate this on a test site, but I can not seem to reproduce it. So I'm not sure if it's a bug or just a quirky edge case. Also, it only appears on Chrome/Windows, no issues on Mac. 

* User report: 3037275-t
* User's site: https://jswbaileylaw.com/

**Comment by alaczek** [comment] 2018-03-05 03:03
I'm for wontfixing this one as well.

**Comment by sixhours** [comment] 2018-03-05 15:17
I can't reproduce this any more, either. Wontfixing.

**Closed by sixhours** 2018-03-05 15:17 UTC
Labels: bug, needs patch, support
