### ISSUE TITLE
Baskerville 2: Social media block not displayed correctly when aligncenter is chosen

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/themes#3859] opened 2021-05-16 19:37 UTC
## Steps to replicate

- Add social media block to page (on site using Baskerville theme)
- Set block to center alignment

## Result
Buttons are shown in a full width list instead

![Screen Shot 2021-05-16 at 9 35 58 AM](https://user-images.githubusercontent.com/1967448/118410236-258fe100-b62a-11eb-97f9-4d0dd19d5298.png)

It appears the theme is missing the correct CSS, but adding the following seems to correct the issue (if CSS is an option for your user)

.wp-block-social-links.aligncenter{
    display: flex;
}

* User report: https://wordpress.com/forums/topic/social-links-block-doesnt-center

**Comment by kathrynwp** [comment] 2021-05-16 22:32
duplicate of #2336

**Closed as completed by kathrynwp** 2021-05-16 22:32 UTC
Labels: [Type] Bug
