### ISSUE TITLE
Pendant: Site title & categories font weight

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#5951] opened 2022-04-27 15:47 UTC
I'm still seeing the site title and the categories in a different font weight than the mockup. It might be just me but I wanted to check: can you replicate?

| Test site | Figma |
| ----- | ----- |
| <img width="536" alt="Captura de ecrã 2022-04-27, às 16 45 05" src="https://user-images.githubusercontent.com/65220155/165558674-1ecd31b2-0783-4c44-988a-2326d81adce7.png"> | <img width="614" alt="Captura de ecrã 2022-04-27, às 16 46 51" src="https://user-images.githubusercontent.com/65220155/165558795-21e32e0e-f877-4257-9153-0449db410514.png"> |

**Comment by madhusudhand** [comment] 2022-04-28 08:42
Created a PR for the site-title font style.

And for the categories, there seems to be an issue with Gutenberg (loading only first entry from defined fontfaces) and is fixed in **v13.1.0**

<img width="390" alt="image" src="https://user-images.githubusercontent.com/1935113/165713625-3b8427af-b103-4d59-a5b2-f86211f24518.png">

**Comment by pbking** [comment] 2022-04-28 12:53
> And for the categories, there seems to be an issue with Gutenberg (loading only first entry from defined fontfaces) and is fixed in v13.1.0

Indeed both fonts look correct with the fix in place.  As you rightly point out though @madhusudhand the original design uses Playfair in that space.  I have asked a question of the designer to see if it should be changed or if we can leave it as-is and just wait for the fix to land.

I think we have decided not to release Pendant to wporg until that version of Gutenberg has been released and wpcom until that version is on simple sites.

**Comment by beafialho** [comment] 2022-04-28 13:39
As commented in #5957 Playfair was there by mistake. If this happens again (sometimes I forget to change every bit of text for the final iteration) please double check the theme's [styles](https://www.figma.com/file/JdntsOfLqo8Vy0d5uTWHTI/Pendant?node-id=674%3A104) which should mention every font the theme uses. If that's still unclear in styles though, ask me 🙂

**Comment by pbking** [comment] 2022-04-28 16:17
This turns out to just be caused by the bug in Gutenberg.  All will be right when 13.1 lands.

Closing. :)

**Closed as completed by pbking** 2022-04-28 16:17 UTC
Labels: [Theme] Pendant, [Status] Needs Design Approval
