### ISSUE TITLE
Quadrat: The background shape at the bottom of the page doesn't quite reach the bottom

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#4593] opened 2021-09-14 18:45 UTC
Current:

<img width="1126" alt="Screen Shot 2021-09-14 at 2 42 48 PM" src="https://user-images.githubusercontent.com/1202812/133315580-639f23c5-7a24-4241-ae69-2e6ee144e59a.png">

Intended:

<img width="1126" alt="Screen Shot 2021-09-14 at 2 45 24 PM" src="https://user-images.githubusercontent.com/1202812/133315911-7c60b119-227f-435b-8351-333929855b27.png">

**Comment by pbking** [comment] 2021-09-20 19:13
This is not reproducing for me (either on wpcom or locally). 
I've seen this in the past; I think it was related to the `:-)` for tracking.  I see that in the screenshot above though there was a recent change to hide that by default (without theme-specific styling).  I suspect it's related.

**Comment by kjellr** [comment] 2021-09-21 11:31
> This is not reproducing for me (either on wpcom or locally).

I can see this on the theme demo: https://quadratdemo.wordpress.com

**Comment by pbking** [comment] 2021-09-23 14:26
Do you have the demo sandboxed and your sandbox fully up-to-date?
I'm fairly certain the `:-)` issue caused it and has been addressed in wordpress (not the theme).  I checked again and both not sandboxing and sandboxing fully up-to-date the issue isn't happening for me on the demo site:

![image](https://user-images.githubusercontent.com/146530/134525432-79fa0ff4-852a-4e9e-85bf-694d67dfb186.png)

**Comment by kjellr** [comment] 2021-09-23 16:58
I'm not sandboxed — I see it there on the currently live, non-sandboxed demo. I see it in Chrome, Firefox, and Safari.
![error](https://user-images.githubusercontent.com/1202812/134551177-ecd5dd9b-5785-4e35-9367-fd03c7b620ea.gif)

**Comment by scruffian** [comment] 2021-09-28 13:00
I can't replicate either :(

**Comment by scruffian** [comment] 2021-09-29 12:23
This is caused by the `:-)` on the page which is now hidden.

**Closed as completed by scruffian** 2021-09-29 12:23 UTC
Labels: [Type] Bug, [Theme] Quadrat
