### ISSUE TITLE
Blocks not going full width in page editor Creatio 2

### ISSUE THREAD

**Issue by rickmgithub** [Automattic/themes#7841] opened 2024-05-30 07:08 UTC
### Quick summary

Adding blocks in the page editor results in blocks not being full-width even with the full-width option selected. Go to the site editor and the block now displays correctly. 

### Steps to reproduce

1. Set up a simple site with Creatio 2
1. Create a page in the page editor (not site editor)
2. Add a group block and some content to it. 
4. Notice how the group block is not full width.
![Markup on 2024-05-30 at 17:03:16](https://github.com/Automattic/themes/assets/13706336/39facf55-67da-4fd1-963b-5e1e8b37b9cb)
5. Try to make it full width with any icon or the block settings and it stays narrow with gaps down the sides in the editor page
6. Go to the site editor and notice how when viewing the page the content within it is now full width. 

### What you expected to happen

The page editor to reflect the site editor

### What actually happened

There are gaps down each side of the content in the page editor but not in the site editor.

### Context

8252965-zd

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by liviopv** [comment] 2024-06-10 11:05
📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Replicated / Could Not Replicate / Uncertain
- Tested on P2 (optional) – Replicated / Could Not Replicate / Uncertain
- Replicable outside of Dotcom – Yes/No

📌 FINDINGS/SCREENSHOTS/VIDEO
Simple

https://github.com/Automattic/themes/assets/14153300/d6e69fe8-bb32-4f6f-ac5b-763f0934f8d7


📌 ACTIONS
- Closed as could not replicate (please reopen if the issue reoccurs)


📌 Message to Author
@rickmgithub based on what I saw on the user's site, I think it could be due to the how the settings on the Group/Columns Block have been selected, and the Content Block in the template might also be involved. Definitely not a theme-specific limitation

**Closed as completed** 2024-06-10 11:05 UTC
Labels: [Type] Bug, [Status] Cannot reproduce, [Pri] Normal, Needs triage, Customer Report, [Feature Group] Appearance & Themes
