### ISSUE TITLE
Business: Horizontal scroll at screens wider than 800px

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/themes#296] opened 2018-11-01 13:56 UTC
There is about 10-15px of horizontal scroll at every screen size over 800px wide.

## Steps to replicate

**Browsers tested:** Firefox 63.0 & Chrome 70.0.3538.77

1. Open https://businessthemedemo.wordpress.com/ in Firefox or Chrome
2. Make the browser wider than 800px

**OS** macOS 10.12.6 

## Result

You can scroll side-to-side by about 10-15px.

Screencast:

https://cloudup.com/cElE7u9nBGp

## Expected

You should not be able to scroll horizontally.

## Site

Tested on demo: https://businessthemedemo.wordpress.com/

No user issue, noticed on my own

**Comment by arunsathiya** [comment] 2018-11-02 03:48
Noting that I am not able to reproduce on MacBook Pro (15-inch, 2016) with the same demo site.

- [Video indicating this behaviour with Google Chrome Version 70.0.3538.77 (Official Build) (64-bit)](https://cloudup.com/c7jtFCGjiTA).
- [Video indicating this behaviour with Firefox Quantum 63.0.1 (64-bit)](https://cloudup.com/c8jdsO5Ef20).

In both the cases, the screen was wider than 800px. Both on macOS 10.14 - Mac OS Mojave.

**Comment by jessestu** [comment] 2018-11-13 23:16
I see these horizontal scroll bars.

On my Mac, in System Preferences → General → Show scroll bars, I have it set to _Always_ after seeing a tip to keep those on from another dev.

@arunsathiya and @kathrynwp, what settings do you have in these tests for your scrollbars?

When the scrollbars are always on, I see this:

![screen shot on 2018-11-13 at 17 09 32](https://user-images.githubusercontent.com/32908730/48449174-1aad1a80-e767-11e8-99ba-a616c99ee5cb.png)

When I turn off always showing the scrollbar, I see this (note the white pixel column to the left of the Gutenberg cover image block:

![screen shot on 2018-11-13 at 17 13 36](https://user-images.githubusercontent.com/32908730/48449319-a757d880-e767-11e8-95b7-3801029a2ae6.png)

**Comment by arunsathiya** [comment] 2018-11-14 13:17
@jessestu You are right. I should have checked with the scroll bars visible all the time. 👍🏽

**Comment by laurelfulford** [comment] 2018-12-28 17:45
Assigning to @mendezcode as I believe this will be fixed in other updates he's making in Business (Ernesto, just let me know if this is not the case!).

**Comment by mendezcode** [comment] 2019-01-11 18:53
This has been fixed as part of the [editor styles rewrite](https://github.com/Automattic/default-small-business-theme/commit/b39bb05a191fd2177c8e547089843dcf6cd40806).

**Closed by mendezcode** 2019-01-11 18:53 UTC
Labels: bug, needs patch, support
