### ISSUE TITLE
Twenty Seventeen: Images tremble/shake when scrolling in Safari 13

### ISSUE THREAD

**Issue by geekinthegirl** [Automattic/themes#2190] opened 2020-06-28 15:51 UTC
## Steps to replicate

- Example site: https://panoramicrv.com 
- Place images in the panels for the home page. 
- View the site using Safari (version Version 13.1.1).

## Result

Images in the backgrounds between panels tremble/shake in Safari while scrolling down the home page.

As a sidenote, this also happens with the theme demo: https://twentyseventeendemo.wordpress.com/

## Expected

I expected the site's images to remain steady and smooth while scrolling down the home page, as is the case with other browsers like Firefox and Chrome.

* User report: #22239886-hc

**Comment by naxoc** [comment] 2020-07-24 14:37
I've seen this issue too in #3170160-zen - it seems like it's the same issue Pique has.

**Comment by pauljacobson** [comment] 2020-07-29 09:28
We have another instance of this in 3170160-zen

Here's an example in Firefox Developer Edition v79.0b9:

![Screen Shot on 2020-07-29 at 12:24:54](https://user-images.githubusercontent.com/2912202/88782799-af071d00-d196-11ea-9f8a-104ae1e03f38.png)

And this is in Safari 13.1.2:

![Annotation on 2020-07-29 at 12-24-20](https://user-images.githubusercontent.com/2912202/88782964-e249ac00-d196-11ea-8494-8a25e57c1626.png)

**Comment by KristinaKay** [comment] 2020-07-29 16:55
The issue is actually on the Home page. 1. From what I can tell, the reason this happens on the home page and not on the other pages is because the home page is using fixed background images for the Parallax effect. 

Site: https://bethmoorephotography.net

2. Provided user with a temp fix:

```
/* remove parallax effect on home page #3170160-z | KD */
    .background-fixed .panel-image {
       background-attachment: scroll; 
    }
```

**Comment by kathrynwp** [comment] 2022-07-14 16:35
I'm no longer seeing this issue in Safari 15.3.

Over 2.5 years have gone by since the initial report, and there have been only a handful of reports. A CSS workaround is also available to remove the faux-parallax effect on the homepage panel background images.

For all these reasons, I'm going to go ahead close this issue as a wontfix.

Since this is a bundled/default theme, if anyone feels strongly that this issue should still be looked at by core developers, this issue can be reopened and a corresponding issue should be reported over in WP.org Trac: https://core.trac.wordpress.org/

**Closed by kathrynwp** 2022-07-14 16:35 UTC
Labels: [Type] Bug, [Pri] Normal, [Theme] Twenty Seventeen
