### ISSUE TITLE
Varia Themes: Mobile safari does not scale featured images on Simple Sites

### ISSUE THREAD

**Issue by khristiansnyder** [Automattic/themes#7095] opened 2023-05-22 21:12 UTC
### Quick summary

On Varia based themes and the homepage set to show latest posts, the featured images do not scale on Safari on mobile, resulting in massive featured imges.

### Steps to reproduce

1. Activate a Varia theme, such as Hever
2. Publish a post with a featured image
3. Set homepage to show latest posts
4. Check homepage on Safri on mobile

### What you expected to happen

I expect images to scale to the browser's width.

### What actually happened

The browser does not scale the featured images. I tested on Varia, Hever, and Exford via Browserstack. They show massively.

I can see this CSS applied: 

```
 header *, main *, footer * {
    max-width: unset;
}
```

<img width="1359" alt="Screenshot on 2023-05-22 at 14:07:56" src="https://github.com/Automattic/wp-calypso/assets/41035049/c14569dd-0a22-495b-9f9f-a602ddbd6272">

Toggling that CSS off allows it to show properly: 
![ezgif com-resize](https://github.com/Automattic/wp-calypso/assets/41035049/10204dec-3a71-486e-b0fb-7337b984a6ac)

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Logs or notes

Gutenberg: v15.8.0
Editing Toolkit: 3.66163
WP AMP: 2.0.5
CoBlocks: 2.18.1-simple-rev.4

**Comment by john-legg** [comment] 2023-05-22 22:51
📌 REPRODUCTION RESULTS

Tested on Simple – Replicated 
Tested on Atomic – Could Not Replicate
Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO

I tested this on a few Varia themes like Hever and Maywood and I was able to replicate it as described. I also tested on different browsers and was able to confirm that it's mobile Safari only. I'm not able to reproduce it on Atomic (WPCOM and self-hosted), so it seems to be Simple only.


https://github.com/Automattic/wp-calypso/assets/96805492/29c17db3-9f1f-49a8-aa56-b429db0436ec



📌 ACTIONS

Transferred to themes (@Automattic/theam)

**Comment by tvolpert** [comment] 2023-05-25 16:42
Had another report of this here:

- [ ] 6328959-zen

For this user at least, I was able to provide a workaround with the following code:

```
footer *, header *, main * {
    max-width:100%;
}
```

Also, for anyone doing testing: you can replicate this bug in an Incognito Window in Chrome at mobile sizes; for whatever reason it seems to only affect logged-out users on desktop.

**Comment by tvolpert** [comment] 2023-05-25 20:30
another one here:

- [ ] 6328919-zen

**Comment by kelasante** [comment] 2023-05-25 21:07
Another one here:

6330822-zen

**Comment by cuemarie** [comment] 2023-05-25 23:20
This is one of several recent issues pointing to a very similar CSS problem, so I've escalated here: p1685056613665109-slack-C029FM1EH

**Comment by tvolpert** [comment] 2023-05-26 19:54
another report here: 

- [ ] 6334336-zen

**Comment by jromales** [comment] 2023-05-30 01:10
3 sites affected in 6343469-zd-woothemes

I used the CSS workaround: 

```
footer *, header *, main * {
	max-width: 100%;
}
```

**Comment by sudeepbaral** [comment] 2023-05-30 04:00
- [ ] 6321897-zen

Theme: Rockfield

User would like to be notified after the issue is resolved

**Comment by retnonindya** [comment] 2023-05-30 04:31
6343854-zd-woothemes

Theme: Hever

**Comment by cuemarie** [comment] 2023-05-30 18:01
Reported what seems to be the underlying issue here: 

- https://github.com/Automattic/wp-calypso/issues/77561

Please collect all future interactions on that report

**Comment by pbking** [comment] 2023-05-31 14:58
So far I have discerned that the cause is that (at least when viewing the site in an incognito browser) the CSS targeting the `img` element is loading in a different order compared to when viewing the site logged in.

(incognito, not expected)
<img width="341" alt="image" src="https://github.com/Automattic/themes/assets/146530/5a770071-ce65-48cc-95a4-13f34054d997">

vs

(logged in, expected)
<img width="315" alt="image" src="https://github.com/Automattic/themes/assets/146530/eb117b66-7d0c-40a5-9aa9-7e173e05092e">

I didn't find any differences between desktop and mobile browsers (safari or otherwise).  The only difference I found was logged-in vs not-logged-in.

I'm not sure WHY the difference exists yet but I continue to look.

I suspect that the change was relatively recently and unrelated to the specific themes in question but those are the ones that are affected.

**Comment by pbking** [comment] 2023-05-31 15:37
Ok, I continue to be VERY confused as to why two very different CSS files are loaded for the same site when logged in vs not-logged in.

One example of not-logged-in points to the theme CSS file here: 
https://s0.wp.com/wp-content/themes/pub/morden/style.css?m=1684754137h&cssminify=yes
and the logged in version (of the same site) here:
https://s0.wp.com/_static/??/wp-content/themes/pub/morden/style.css,/wp-content/mu-plugins/admin-bar/masterbar-overrides/masterbar.css?m=1684754137j&cssminify=yes

The CSS in question is being derived from this source: 
https://github.com/Automattic/themes/blob/trunk/varia/style.css

Note that in the original source the `img {` [block](https://github.com/Automattic/themes/blob/trunk/varia/style.css#L1690) is AFTER the `header *, main *, footer* {` [block](https://github.com/Automattic/themes/blob/trunk/varia/style.css#L737).  

This causes the `max-width` attribute in the `img` block to "win".

Note that in the 'logged in css' that is the same.  It is the CSS that is expected and the site works as expected.

Note that in the 'not logged in css' that is NOT the same, the `header *, main *, footer* {` block is AFTER the `img {` block which causes the `max-width` attribute defined THERE to win.

There are a few paths forward here.

Option 1: Change the Varia CSS 
This would fix Varia and the Varia children themes.  A quick change points to just removing the `max-width: unset;` attribute.  This would fix the problem at hand, but I'm not entirely sure why that code exists in the first place.  It might also cause breakage in other places.
Additionally there are OTHER (non-varia children) themes that are also affected by this.  Those would also need to be changed.

Option 2: Figure out why the two CSS files are so different and address THAT issue.  This would fix ALL of the themes in question without the potential for breakage.

Considering that this has been confirmed to be a WordPress.com Simple Site exclusive issue then fixing WordPress.com seems to be a better fix than fixing each theme affected.

**Comment by mreishus** [comment] 2023-05-31 17:29
@pbking ~~Do you know of a simple html document I can try with various CSSes to see if the bug is happening? Is this sufficient? (Or is it simpler to make a real site?)~~
```
<!DOCTYPE html>
<html>
    <head>
        <title>Test Page</title>
        <link rel="stylesheet" type="text/css" href="./style.css">
    </head>
<body>
    <div>
        <img src="https://picsum.photos/200/300" alt="Randomly generated placeholder image">
    </div>
</body>
</html>
```

EDIT: Nevermind - this was not sufficient. I ended up making a simple site, copying its html, and swapping out the link to the css.

**Comment by cuemarie** [comment] 2023-05-31 20:40
A [fix has been deployed](https://github.com/Automattic/wp-calypso/issues/77561#issuecomment-1570917159)

**Closed as completed by cuemarie** 2023-05-31 20:40 UTC
Labels: [Type] Bug, [Pri] Low, [Theme] Varia, Triaged, [Status] Duplicate, [Platform] Simple, Images

**Comment by cuemarie** [comment] 2023-05-31 22:29
A batch user reply will be sent out to all interactions noted above this comment. Please refer to main issue https://github.com/Automattic/wp-calypso/issues/77561 for updates on that process.
