### ISSUE TITLE
Some Blockbase child themes: Links missing the underlining in live view

### ISSUE THREAD

**Issue by mxhassani** [Automattic/themes#6541] opened 2022-09-13 10:16 UTC
### Quick summary

The underlining of links is showing in front end, but not in editor.
Theme: Zoologist and Geologist

This may be related to a previous fix (the opposite was happening, underlines appearing in backend but not front end):
Report: 6085-gh-Automattic/themes
Fix: 6382-gh-Automattic/themes

### Steps to reproduce

1.  Set theme to Zoologist
2.  To a page add text in a paragraph block.
3.  And add a link to it.
4.  In Editor, links show **without** underlining
5.  In Live view, links **do** show underlining

### What you expected to happen

To see the underline under the text in both the front end and the editor. 

### What actually happened

What I see in the editor:

![image](https://user-images.githubusercontent.com/81776920/189874025-47b06523-0b5e-449c-a3c4-5f9d3555eeb7.png)

What I see in the front end:

![image](https://user-images.githubusercontent.com/81776920/189874091-dcc61aee-d1e9-43a4-ae6f-c6de38394ffa.png)

### Context

5544157-zd-woothemes

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Theme-specific issue?

Yes, tested with Zoologist and Geologist

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

No but the platform is still usable

**Comment by Robertght** [comment] 2022-09-13 13:01
📌 HOUSEKEEPING
- Labels ✅ 
- Priority ✅ 
- Replicable on Core - Yes

📌 SCRUBBING
- Tested on P2 - no 
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 

📌 FINDINGS/SCREENSHOTS/VIDEO
- The issue is present only in Geologist, Zoologist, Quadrat
- The underline is ok in Skatepark, Russell, Blockbase
- The behavior is present on self-hosted sites

📌 ACTIONS
- Marked as Themes
- Transferred to XYZ external repo: https://github.com/Automattic/themes/i

**Comment by bangank36** [comment] 2023-01-03 11:21
Closing as the issue can not be reproduced. Check the following screenshot:
|           | Simple Sites | Atomic |
|-----------|--------------|--------|
| Zoologist |       ![image](https://user-images.githubusercontent.com/10071857/210342393-36f384ff-1f4b-4010-b97c-ad06a2d43733.png) ![image](https://user-images.githubusercontent.com/10071857/210342628-6c81e1e9-123a-47bb-b846-48444bb76d23.png)       |  ![image](https://user-images.githubusercontent.com/10071857/210340337-69540676-30ed-4ccc-bbe3-fa2875dc90ad.png) ![image](https://user-images.githubusercontent.com/10071857/210340599-13875628-55f9-4ff9-a7b8-519afe654bf4.png)|
| Geologist |       ![image](https://user-images.githubusercontent.com/10071857/210343536-be86f946-b863-4f6e-9722-e227d6dfa25f.png) ![image](https://user-images.githubusercontent.com/10071857/210345796-7dd5258f-87cf-41b8-a74b-a62a1a00013e.png)       | ![image](https://user-images.githubusercontent.com/10071857/210341088-8c0b9ed7-cc54-4727-bcd6-01373179352c.png) ![image](https://user-images.githubusercontent.com/10071857/210341292-822449a4-15e1-4981-8f8e-5793aea33217.png)  |
| Quadrat |      ![image](https://user-images.githubusercontent.com/10071857/210347554-e073f2e0-2694-41f6-ae65-74a60399cf91.png) ![image](https://user-images.githubusercontent.com/10071857/210347574-d3ac4d9c-1ae7-4492-b87a-2205dee63dcb.png)        | ![image](https://user-images.githubusercontent.com/10071857/210342188-473aa0d8-c93a-4b12-bf66-8d56e7ce15bf.png) ![image](https://user-images.githubusercontent.com/10071857/210342303-d351f035-8cef-43cb-9e51-f13004d51f3a.png)  |

**Closed as completed by bangank36** 2023-01-03 11:21 UTC
Labels: [Type] Bug, [Pri] High, Triaged, [Platform] Simple, [Platform] Atomic, Lego Maintenance
