### ISSUE TITLE
Varia: Button Text Colour in Blocks with Background Colour

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#1763] opened 2020-01-24 12:29 UTC
I've noticed this while I was testing Calendly block. If a button is in a block that has a background colour, the button text colour changes to `currentColor`, and it becomes unreadable if the background colour is a light colour.

<img width="867" alt="Screenshot 2020-01-24 at 12 27 43" src="https://user-images.githubusercontent.com/908665/73069201-0903ee80-3ea5-11ea-9c18-84cae490742a.png">

**Comment by MaggieCabrera** [comment] 2021-01-28 13:35
Hi @iamtakashi I couldn't reproduce this. I'm testing on a cover block with white background and a button on it, setting the overlay to white:

<img width="1451" alt="Screenshot 2021-01-28 at 14 33 44" src="https://user-images.githubusercontent.com/3593343/106145547-f9814a80-6175-11eb-99bc-5791d760333c.png">

**Comment by scruffian** [comment] 2021-02-04 16:58
Should be fixed by #3181

**Comment by scruffian** [comment] 2021-02-05 10:51
Fixed by #3185

**Closed by scruffian** 2021-02-05 10:51 UTC
Labels: [Theme] Varia, [Type] Bug
