### ISSUE TITLE
Stratford: Blog post block last post height issue

### ISSUE THREAD

**Issue by Robertght** [Automattic/themes#1988] opened 2020-05-07 10:56 UTC
## Steps to replicate

1. Have a few posts with a featured image on for better clarity
2. Create a new page and add the latest blog posts block with the image on top.
3. The last article will be taller because of this rule:

```
@media only screen and (min-width: 782px){
 .wpnbha.is-grid article, .wpnbha.is-grid article:last-child {
    margin-bottom: 1em;
 }
}
```

## Result

![httpsalumniupf wordpress com 2020-05-07 13-53-02](https://user-images.githubusercontent.com/6737345/81286853-68f45e80-906a-11ea-96cc-3e473c16a60f.png)

## Expected

To have it the same height as the others.

Workaround:

```
@media only screen and (min-width: 782px){
 .wpnbha.is-grid article, .wpnbha.is-grid article:last-child {
    margin-bottom: 96px;
 }
}
```

* User report: #2953213-zen

**Comment by laurelfulford** [comment] 2020-06-04 16:27
Hey @robertbpugh! This sounds like a duplicate of https://github.com/Automattic/newspack-blocks/issues/482, so I'm going to close this theme issue and move the report over there. 

There's a fix, it's just waiting to be synced with WP.com

**Closed by laurelfulford** 2020-06-04 16:27 UTC
Labels: [Type] Bug, support
