### ISSUE TITLE
Hey: turn Site Logo into Site title block to reflect the changes

### ISSUE THREAD

**Issue by Robertght** [Automattic/themes#8412] opened 2024-11-12 16:50 UTC
### Quick summary

Coming from [here](https://github.com/Automattic/dotcom-feedback/issues/300):

> • The title on the front page of the Hey is super confusing. It doesn’t sync with the site title, and it’s not possible to edit during onboarding. Potential solution: turn it into a site title block.

### Steps to reproduce

1. Create a new site
2. Go through the "Let's get ready to launch" steps
3. Change the site title

### A clear and concise description of what you expected to happen.

I expected to see the site title get reflected on the homepage

### What actually happened

I could only see a site logo block.

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by andregardi** [comment] 2024-11-12 17:52
I am experiencing something different.
Digging into the slack thread, I see this is based on p5j4vm-4Fm-p2 P2 post from August.

Walking through it, it doesn't seem to be specifically related with Hey theme. It is more related with the fact that the Ella was presented to **Post writing** page before even setting up the blog title. Because it just state `Add a title` it feels like this is the blog title.

I agree that is bad experience, but outdated. I followed the steps from the P2 and faced different onboard.
We have a explicit page prompting for the blog name before presenting the user with any Post writing, which is work fine.
![Image](https://github.com/user-attachments/assets/a1c7d94f-d28f-4900-99b2-92da30fb71fd)


---

I tested different paths and there is still a way to access the checklist before setting the site title, by choosing `Promote myself or business` on the **What are your goals?** survey.
But even in that way there are options to `Give your site a name` and `Write your first post` which are explicitly distinct.

![Image](https://github.com/user-attachments/assets/545aa965-9252-4b3e-b6d4-d2e8dbed0235)

**Comment by andregardi** [comment] 2024-11-12 17:55
@Robertght and @inaikem 
Is that ok if I close it as not reproducible? Or did I get anything wrong?

**Comment by Robertght** [comment] 2024-11-19 13:07
My understanding of this is that the Site logo block in the Editor should be changed to Site Title block or have both so that this change can reflect:


![9y20TTUeuCDfOhpxCA1LMO9bMjapRQhG7PDPBmZD.jpg](https://github.com/user-attachments/assets/aa2792b0-a2d8-4a64-a9e8-0841a59b2980)

**Comment by dsas** [comment] 2024-12-02 17:34
Duplicate of https://github.com/Automattic/themes/issues/8024

**Closed as not planned by dsas** 2024-12-02 17:34 UTC
Labels: [Type] Bug, [Pri] Normal, Triaged, [Status] Priority Review Triggered, [Theme] Hey, [Feature Group] Appearance & Themes
