### ISSUE TITLE
All Themes: Make sure input and button in Subscription block are the same height

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#2488] opened 2020-09-21 14:04 UTC
It was raised by Pablo here: https://github.com/Automattic/blockpatterns/issues/99#issuecomment-693610951

The input field and the button are not the same height in many themes and that doesn't look good. When they are placed inline which is the default, they should be the same height.

Seedlet:
![Screenshot 2020-09-21 at 14 59 42](https://user-images.githubusercontent.com/908665/93776109-1ed7d800-fc1b-11ea-8855-ad057a6b35fd.jpg)

Varia and its child themes (the difference may vary in each child theme)
![Screenshot 2020-09-21 at 15 01 31](https://user-images.githubusercontent.com/908665/93776317-5b0b3880-fc1b-11ea-9109-7190a4938b35.jpg)

**Comment by alaczek** [comment] 2020-09-29 00:21
Hmm... I actually thought this is a block issue and reported here https://github.com/Automattic/jetpack/issues/17196 but now that I tested it in TwentyTwenty and Seedlet, it looks like the only themes affected are Varia child themes, so I'm going to close that one.

**Comment by MaggieCabrera** [comment] 2020-10-23 09:57
I'm looking into this and all the styles for this block are inline, which forces the theme to override using !important which is kind of terrible. I think we might need to fix that on the block before we handle how the theme renders it

**Comment by scruffian** [comment] 2020-10-23 10:01
To me it feels like the fixes should live in the block anyway - if the theme is breaking the block it's probably because the block's styles aren't strong enough...

**Comment by iamtakashi** [comment] 2020-10-23 11:06
> [...] which forces the theme to override using !important which is kind of terrible.

Isn't that exactly what Seedlet and Varia are already doing?

**Seedlet**  https://github.com/Automattic/themes/blob/3992b5c9988d17ec64a3849ca225bbc315a505e4/seedlet/assets/sass/blocks/subscription/style.scss#L3

**Varia**
https://github.com/Automattic/themes/blob/3992b5c9988d17ec64a3849ca225bbc315a505e4/varia/sass/blocks/subscription/style.scss#L3

Removing the !important` makes the issue better, but the input and the button won't still be the same height like on Twenty Twenty. What is causing the height discrepancy in those themes?

**Comment by MaggieCabrera** [comment] 2020-10-23 12:45
> Isn't that exactly what Seedlet and Varia are already doing?
Yeah, and it's good and bad at the same time.

We have two problems here:

- The block has inline styles, that forces the theme to use `!important` to override them. It is legitimate that the theme would want to do that because for example, the block is forcing no border radius and a specfic font size and that causes the form to diverge from what the rest of the forms on the theme would look like (in this example I'm comparing to the Gutenberg search block):

<img width="548" alt="Screenshot 2020-10-23 at 14 23 42" src="https://user-images.githubusercontent.com/3593343/97003470-c195b600-153b-11eb-8a73-08109b031676.png">

- The theme is trying to force some of its form styles to the block and it's only half succeding. The cause of the missalignment is the base button styles adding a negative margin to the ::before and ::after pseudo-elements of the button. Besides that, even with the same padding, any difference in line height, weight, font size... between the button and the input will cause a difference in height too.

I propose:

- To move the block css to a stylesheet instead of inline so themes can customize them if they need to without forcing !important.
- To fix the height issue on the block with display flex. This will fix the block natively and if themes want to have different font size/weight on the button and the input they will be able to without breaking the form.

**Comment by scruffian** [comment] 2020-10-23 13:48
@Automattic/explorers is this something you would be able to handle?

**Comment by iamtakashi** [comment] 2020-10-23 15:00
cc @apeatling for thoughts on this.

**Comment by creativecoder** [comment] 2020-10-23 15:41
> @Automattic/explorers is this something you would be able to handle?

@scruffian If you can create an issue in Jetpack with the specifics, we'll try to get it into an upcoming cycle.

**Comment by scruffian** [comment] 2020-10-23 16:03
I created an issue here: https://github.com/Automattic/jetpack/issues/17590

**Comment by retrofox** [comment] 2020-10-23 16:09
> I created an issue here: [Automattic/jetpack#17590](https://github.com/Automattic/jetpack/issues/17590)

sorry, maybe it's duplicated with https://github.com/Automattic/jetpack/issues/17196, already it's already closed, though.

**Comment by scruffian** [comment] 2020-10-23 17:24
Yeah looks like the same thing. I don't agree that it's a theme issue though.

**Comment by retrofox** [comment] 2020-10-23 17:46
> Yeah looks like the same thing. I don't agree that it's a theme issue though.

Agree. At least there are some tweaks to do in the block itself imo.

**Comment by apeatling** [comment] 2020-10-23 21:21
I believe the reason for this is that there is no set height for either the button or the input field for the block. This is because the height is defined by the padding set by the control in the block. This is also why styles are inline, it's all controlled by the user. If a strong height or padding value is set by the theme, it's going to cause this sort of problem.

**Comment by jeffikus** [comment] 2022-01-14 12:31
Closing this as the PR's are merged.

**Closed by jeffikus** 2022-01-14 12:31 UTC
Labels: [Pri] High, [Theme] Varia, jetpack
