### ISSUE TITLE
Cols: Dropdown menus sporadically don't appear

### ISSUE THREAD

**Issue by samjhamdy** [Automattic/themes#194] opened 2018-07-10 19:38 UTC
## Steps to replicate

1. Open a site using the Cols theme or the Cols theme demo: https://colsdemo.wordpress.com/
2. Slowly move mouse from top level menu item to dropdown item

Screencast from user's site: https://cloudup.com/c9UojDoo0bS

## Result

Dropdown menu sometimes stays visible and sometimes disappears.

## Expected

Dropdown menu should always appear and be clickable.

* User report: Business 1:1 session
* Follow-up ticket: #1266536-zd
* User's site: https://avgblkgirl.com/

**Comment by laurelfulford** [comment] 2018-07-10 19:41
I looked at this with @samjhamdy and it looks like the issue is the top positioning of the dropdown menus -- it's a little further down than the hover area of the top level.

Switching it from `25px` to `100%` should fix this, like:

```.main-navigation ul ul {
    top: 100%;
}```

**Comment by laurelfulford** [comment] 2018-07-23 20:55
This has been fixed in r49069-wpcom-themes. I'll follow up again when it's been synced up with our Business Sites, when the update will be available on the user's site.

**Closed by laurelfulford** 2018-07-23 20:55 UTC
Labels: bug, needs patch, support

**Comment by laurelfulford** [comment] 2018-07-31 23:50
This fix is now available on Business sites!

@samjhamdy it looks like the ZD ticket is closed, so I can't add a note there -- can you please follow up with the user on this? Thanks!
