### ISSUE TITLE
Rebalance: Ads covering main page content

### ISSUE THREAD

**Issue by kamikazeballoon** [Automattic/themes#36] opened 2018-03-09 07:56 UTC
## Steps to replicate
I can't actually replicate this, but:

1. Create a free site.
2. Activate Rebalance.
3. Set up featured posts.

## Result

For the user, this: https://www.flickr.com/photos/127668302@N04/40695242261/in/dateposted-public/

Verified by myself and another HE, before we turned ads off. Reenabling ads makes the issue come right back. Sorry if this isn't actually a theme issue - I can't think what else it could be!

## Expected

Ads showing up without blocking content.

* User report: #1004811-zd
* User's site: https://3rdworldarchitecture.wordpress.com/ (I've disabled ads for now!)

**Comment by sixhours** [comment] 2018-03-09 19:51
What steps did you take to try to reproduce this on a test site? Were there any errors in the console on the user's site?

I'm not able to reproduce this on the ads test site with similar content. This points to something in the customer's site, specifically that could be affecting ads placement; maybe an unclosed tag.

Without more info, the only way to troubleshoot this further is to re-enable ads on the user's site and look at the source.

**Comment by kamikazeballoon** [comment] 2018-03-09 22:34
> What steps did you take to try to reproduce this on a test site? 

The steps I posted in 'steps to replicate'; my best guess was that it didn't work because my site wasn't showing ads anyway being as new as it was. I considered exporting the user's site and uploading it to mine for testing, but that seemed like a bad call that wouldn't necessarily fix the inability to replicate.

> Were there any errors in the console on the user's site?

Just this one: 
`ima3.js:formatted:15439 Unrecognized feature: 'autoplay'.
(anonymous) @ ima3.js:formatted:15439`

>This points to something in the customer's site, specifically that could be affecting ads placement; maybe an unclosed tag.

Both the specific About page and the featured tag display ads correctly; I'd also checked the html in the former and removed a couple of `class="js-about-module-title module__title__link"` parameters in `a` tags to no avail. 

In resizing my browser window just now, I noticed that ads display under the content in the featured image section as I would expect them to at 880px wide and lower.

![screen shot 2018-03-10 at 11 01 24 am](https://user-images.githubusercontent.com/1575367/37232132-836a1542-2452-11e8-9381-042894ff6aa2.png)
![screen shot 2018-03-10 at 11 01 53 am](https://user-images.githubusercontent.com/1575367/37232133-83a70b5a-2452-11e8-972a-cd29811f5bd8.png)

>Without more info, the only way to troubleshoot this further is to re-enable ads on the user's site and look at the source.

I'm happy to reenable and let the user know we need to do that in order to troubleshoot; let me know!

Thank you :) I'm well aware this was a subpar late-night report on my end and would love any feedback on what I could have done better next time.

**Comment by sixhours** [comment] 2018-03-12 12:56
Thanks for the detailed follow up! I turned on ads super-quick to copy the source code then turned them off.

Not sure why it's not happening on the ads test site; it looks like that area isn't designed to show ads at all. Will dig deeper.

**Comment by sixhours** [comment] 2018-03-12 13:08
Reported this behavior on the Ads P2 to get their take. Will follow up here when I know more!

**Comment by sixhours** [comment] 2018-03-13 17:34
They noted that the site is not a WordAds client, so it's OK if the ads remain turned off for their site permanently. They'll investigate why the ads are appearing in that space on this particular customer's site.

I don't think further action is required, since this appears to be an issue specific to this customer's site and not the theme. Marking as worksforme.

**Closed by sixhours** 2018-03-13 17:34 UTC
Labels: bug, support

**Comment by torres126** [comment] 2018-12-05 14:00
This seems to be happening with another user's site, but I'm not too sure if it's worth creating a new issue over. 

## Result

Adverts cover the Featured Content. I'm unable to recreate it on sites with the Rebalance theme without this, and I can't recreate on my test site because I can't currently make adverts appear on it. I can, however, see it on the user's site and so can they. 

![screenshot_20181205-134304](https://user-images.githubusercontent.com/43215253/49518046-921d2800-f895-11e8-85ce-0c7bc39d1f2b.jpg)

* User report: https://en.forums.wordpress.com/topic/adverts-22/
* User's site: dubaodubao.wordpress.com

**Comment by litwlamp** [comment] 2018-12-07 14:45
@sixhours 

I am having the same issue - my blog is the one posted above by @torres126.

I can see that you closed the thread - was your issue eventually resolved? If so, what needs to be done in order to remove the ads?

I'd appreciate your help on this - thank you!
