### ISSUE TITLE
Skatepark: Duotone doesn't update on live page

### ISSUE THREAD

**Issue by rosepajaroja** [Automattic/themes#6093] opened 2022-06-16 13:53 UTC
Color change on Duotone works while working on the editor, but the changes don't show on preview. 

## Steps to replicate

1 - Activate "Skatepark" theme. 
2 - Add/Edit a page/post. 
3 - Add image block. 
4 - Apply Duotone filter. 
5 - Change the colors. 
6 - Preview. 

## Result

The color remains green. 

## Expected

The new color will display on the preview. 

*Sample on my test site - https://happinessbarbloggingdemo.wordpress.com/538-2/

* User report: zd-5301354
* Follow-up ticket: zd-5301354

**Comment by KokkieH** [comment] 2022-06-22 09:05
Closing as a duplicate of #5602

@rosepajaroja if your user is on the Pro or legacy Premium/Business Plan, there's a CSS workaround on that issue you can share with them. But this is a bug that needs to be fixed in Core.

**Closed as completed** 2022-06-22 09:08 UTC
Labels: [Theme] Skatepark, [Status] Duplicate
