### ISSUE TITLE
Calm Business: Missing .is-style-wide CSS for separator block

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#762] opened 2019-04-30 22:53 UTC
Currently, wide style variation for the block display the same separator as short style.

<img width="1051" alt="Screen Shot 2019-04-30 at 23 49 09" src="https://user-images.githubusercontent.com/908665/56998339-dc83a600-6ba2-11e9-8991-7e3a741e5956.png">

Need a wider style :)

**Comment by torres126** [comment] 2019-05-01 16:40
Duplicate of #751

**Closed** 2019-05-02 19:18 UTC
Labels: [Pri] Normal, bug, needs patch
