### ISSUE TITLE
Sela: Double tap required on menu items on mobile

### ISSUE THREAD

**Issue by davipontesblog** [Automattic/themes#214] opened 2018-07-27 15:15 UTC
## Steps to replicate

1. Open https://locaellaobjetos.com/ on mobile. I tested it using my Google Pixel 2 Android device, using Google Chrome version 67.0.3396.87.
2. Tap on Menu
3. Tap on "Rupert" (as an example. any item behaves the same way)
4. Tap on "Rupert" again. Menu item loads.

## Result

Tapping the menu item on mobile doesn't work, it only places highlights the item it seems. A second tap is required to have the item be opened.

## Expected

We expect to be able to open the menu items on mobile with a single tap.

* User report: #5300831-hc
* Follow-up ticket: #1308107-zd
* User's site: https://locaellaobjetos.com/

**Comment by ehti** [comment] 2018-07-29 15:40
@davipontesblog actually, it looks like the behavior is a bit different here. Not all items require a double tap.

Some menu items work just fine with a single tap for me. Like Rupert's WIP, Erenest's WIP, Needle Felting, Silicone, Online, Shop, About Me, Contact.

It appears, if a menu item has this structure:

* **Parent -> Child -> Sub-child**. Then, you can single-tap sub-child, but not the other two.
* **Parent -> Child**: Can single-tap the child.
* **Parent only**: Can single-tap the parent.

Also tested on Sela demo and above theory seems to work there too for me.

Checked using Chrome, Android. However, it doesn't work for @ajaykj on Chrome, only on default browser it works like above.

I checked your Slack convo with @davidakennedy, but don't think it was discussed. So, I'm wondering if this is how Sela is supposed to work, OR is it really a bug?


They reached out again wanting a timeline for a 'fix'.

**Comment by ehti** [comment] 2018-07-29 17:03
User also confirmed my theory.

E.g. for **Parent -> Child** structure, they can single tap the children. While parent requires double tap.

**Comment by davidakennedy** [comment] 2019-07-16 18:41
Doubling back to this. It works as expected because of the JavaScript loaded it the theme. The double tapping allows users to expect a menu on a touch device where the menu is not fully collapsed under a toggle, like it is on mobile.

Closing this.

**Closed by davidakennedy** 2019-07-16 18:41 UTC
Labels: [Pri] Low, bug, needs patch, support

**Comment by csabarakasz** [comment] 2022-09-14 08:52
Another report of this here: #6710396-hc

The menu is collapsed as default, so the double tap makes no sense. Although it is a retired theme so I am suggesting switching themes.
