### ISSUE TITLE
Radcliffe 2 theme - Customizer error 500

### ISSUE THREAD

**Issue by maciejpilarski** [Automattic/themes#7947] opened 2024-07-09 18:45 UTC
### Quick summary

On a Starter plan/simple site, when trying to access Customizer from the Appearance section, the link points to the free WordPress.com domain instead of the primary domain authorspiritwalker.com, and the URL displays an error 500. URL of the error page:
https://freelancermerlyn.wordpress.com/wp-admin/customize.php?return=https%3A%2F%2Fwordpress.com%2Fdomains%2Fmanage%2Fauthorspiritwalker.com

I was not able to reproduce the issue on my test site. The error seems to be strictly related to the authorspiritwalker.com site.

### Steps to reproduce

1. In the site dashboard, navigate to the Appearance section
2. Click on the Customize option
3. The page reloads and points to an error page.

### What you expected to happen

The Customizer should open.

### What actually happened

Error 500 under the following link https://freelancermerlyn.wordpress.com/wp-admin/customize.php?return=https%3A%2F%2Fwordpress.com%2Fdomains%2Fmanage%2Fauthorspiritwalker.com

### Impact

One

### Available workarounds?

No and the platform is unusable

**Comment by jartes** [comment] 2024-07-10 12:58
Thanks for reporting this one, Maciej! 

📌 REPRODUCTION RESULTS
- Tested on Simple – Could Not Replicate
- Tested on Atomic – Could Not Replicate

📌 FINDINGS/SCREENSHOTS/VIDEO
While I could not reproduce it, I saw some internal errors on IRC (p1720616392371009/1720614979.439469-slack-C01UW7SB411) for other sites. The error is this one:

```
Fatal error for http://freelancermerlyn.wordpress.com/wp-admin/customize.php?return=https%3A%2F%2Fwordpress.com%2Fdomains%2Fmanage%2Ffreelancermerlyn.wordpress.com on in /home/wpcom/public_html/wp-content/themes/pub/radcliffe-2/inc/customizer.php:16 - Uncaught Error: Attempt to assign property "transport" on null in /home/wpcom/public_html/wp-content/themes/pub/radcliffe-2/inc/customizer.php:16
```

📌 ACTIONS
- Triaged
- Transferred to the themes repo.

**Comment by donnapep** [comment] 2024-10-10 20:22
Closing as this is no longer reproducible on the user's site.

**Closed as completed by donnapep** 2024-10-10 20:22 UTC
Labels: [Type] Bug, [Pri] Normal, [Theme ]Radcliffe 2, Triaged, Customizer, [Status] Priority Review Triggered, Customer Report, [Feature Group] Appearance & Themes
