### ISSUE TITLE
Blockbase: allow child theme headers to override parent headers

### ISSUE THREAD

**Issue by colinduwe** [Automattic/themes#5956] opened 2022-04-27 23:08 UTC
## Steps to replicate

Copy header-default.html from Blockbase to a child theme and edit copied header file.

## Result

The theme continued to display the version of header-default.html from Blockbase

## Expected

The child theme version of the file should be displayed.

Here's a fix: https://github.com/Automattic/themes/pull/5955

**Comment by Thelmachido** [comment] 2022-06-15 02:53
Closing this issue in favor of [#5955](https://github.com/Automattic/themes/pull/5955) since the issue is being discussed there at the moment.

**Closed as completed by Thelmachido** 2022-06-15 02:53 UTC
Labels: [Theme] Blockbase, [Status] Duplicate
