### ISSUE TITLE
Twenty Sixteen: Sub-menus won't open (mobile)

### ISSUE THREAD

**Issue by ezebecke** [Automattic/themes#7092] opened 2023-05-21 13:45 UTC
### Quick summary

When using theme Twenty Sixteen and on mobile, trying to tap the arrow on the parent menu to display sub-menu items throws an error and won't open. 

### Steps to reproduce

1- Activate "Twenty Sixteen".
2- Create a menu with at least one menu-item containing sub-menus. 
3- Try to access the sub-menu on a mobile device.

### What you expected to happen

To have the sub-menu opened and be able to select a sub-menu item.

### What actually happened

The menu won't open, and browser console throws error:

`Uncaught TypeError: el.matches is not a function`

Video example: 
https://github.com/Automattic/wp-calypso/assets/24919469/b1aab3f8-e7c8-4ba9-8e17-208141ebb10d

the 

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Simple, Atomic

### Logs or notes

`Uncaught TypeError: el.matches is not a function`

**Comment by masperber** [comment] 2023-05-22 16:32
Also reported here: 6316413-zen

I could reproduce on my test sites.

**Comment by john-legg** [comment] 2023-05-22 16:34
📌 REPRODUCTION RESULTS

Tested on Simple – Replicated 
Tested on Atomic – Replicated 
Replicable outside of Dotcom – No

📌 FINDINGS/SCREENSHOTS/VIDEO

I was able to reproduce the issue on Simple and Atomic sites using Chrome, Firefox, and Safari. However, the menu on mobile appears to work on self-hosted sites (all browsers).

**Simple and Atomic (all browsers)**

https://github.com/Automattic/wp-calypso/assets/96805492/134e367f-5920-44c9-a670-627f1303d975

**Self-Hosted (all browsers)**

https://github.com/Automattic/wp-calypso/assets/96805492/29d7abb1-e1b0-4ee1-a993-0abe8b43dc6a



📌 ACTIONS

Transferred to themes (@Automattic/theam)
Found a duplicate issue opened after this one (https://github.com/Automattic/themes/issues/7091). I'll make a note to reference this issue instead.

**Comment by masperber** [comment] 2023-05-22 16:58
Customer requested followup when this is resolved: 6316576-zen

**Comment by kylemcph** [comment] 2023-05-23 05:56
Customer requested followup when this is resolved: 6315153-zen

**Comment by pauljacobson** [comment] 2023-05-23 14:20
Also reported here: 6318910-zen

Please also include this customer in follow-up when the issue is resolved.

**Comment by zdenys** [comment] 2023-05-24 15:26
6324490-zd-woothemes

**Comment by kelasante** [comment] 2023-05-24 16:41
Another report in 6325200-zd

**Comment by retnonindya** [comment] 2023-05-25 04:39
6326163-zd-woothemes

**Comment by christianguerrag** [comment] 2023-05-29 15:41
Another report here 6339297-zen

**Comment by cecilearkay** [comment] 2023-05-30 08:04
Another report it 6340010-zen

**Comment by ezebecke** [comment] 2023-05-31 12:56
Another report 6343873-zd-woothemes

**Comment by lizkarkoski** [comment] 2023-05-31 14:42
We have another report coming in the WordPress.com forums. 

https://wordpress.com/forums/topic/menu-drop-down-to-sub-item-not-working-on-iphone-or-ipade/?view=all#post-3960901

I have replicated the behavior for the user site and the theme demo too.

**Comment by desnum** [comment] 2023-05-31 15:50
Another report: 6351099-zdm

**Comment by masperber** [comment] 2023-05-31 21:26
Another report: 6352814-zen

**Comment by janmckell** [comment] 2023-06-02 20:19
I think that this may be occurring for other themes as well. I was testing this, to see if it is the issue for this [ticket](6318910-zd-woothemes).

I tried these themes, and for all of them, the dropdown on mobile did not work:
Penscratch 2
Libre 2
Independent Publisher 2
Nucleare

**Comment by jerrysarcastic** [comment] 2023-06-04 17:43
Also reported in https://wordpress.com/forums/topic/custom-links-in-menu-not-working-on-mobile/

**Comment by ezebecke** [comment] 2023-06-05 17:48
Reported on 6370721-zd-woothemes

**Comment by goblinartificer** [comment] 2023-06-13 07:16
reported on 6380908-zd-woothemes

**Comment by filipanoscampos** [comment] 2023-06-13 08:08
Reported here: 6402179-zd-woothemes

**Comment by maciejpilarski** [comment] 2023-06-13 11:17
Another one: 6402667-zd

**Comment by scruffian** [comment] 2023-06-13 12:17
I spent a bit of time looking into this. It seems like the JS on dotcom is not in sync with the js on the default theme, so we should probably just update the dotcom version.

**Comment by retnonindya** [comment] 2023-06-15 00:26
This issue is now fixed 🎉 
p1686746300497929/1686656399.278849-slack-C029FM1EH

A customer reached out on ticket and confirmed that they no longer see the issue on their end.

**Closed as completed by retnonindya** 2023-06-15 00:26 UTC
Labels: [Type] Bug, [Pri] Normal, [Theme] Twenty Sixteen, [Platform] Simple, [Platform] Atomic, [Interaction #] > 10
