### ISSUE TITLE
Exford: Columns Break on Frontend when using Donation & Subscription Blocks

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/themes#5026] opened 2021-11-12 17:00 UTC
## Steps to replicate

1. Create a Columns block.
2. Insert Donations block into the first column
3. Insert Subscription block into the second column
4. Preview page

## Result

Columns do not display properly on frontend of the site:

<img width="1777" alt="Screenshot on 2021-11-12 at 11-54-48" src="https://user-images.githubusercontent.com/45246438/141504777-5c415b25-6c68-4855-9034-e3ebaa58dbbb.png">

Columns are displaying properly in editor:

<img width="1355" alt="Screenshot on 2021-11-12 at 11-55-57" src="https://user-images.githubusercontent.com/45246438/141504939-ddbddcb6-e57e-4a17-972f-94570acc90d3.png">

## Expected

The layout on the frontend of the site should match the editor.

* User report: 32703247-hc
* Follow-up ticket: 4450639-zen

**Comment by jordesign** [comment] 2021-11-19 04:41
This look slike it isn't theme specific - but is instead being caused by a known error with the Donations Block. Closing this in favour of https://github.com/Automattic/jetpack/issues/20309

**Closed as completed by jordesign** 2021-11-19 04:41 UTC
Labels: [Type] Bug, [Theme] Exford, Triaged
