### ISSUE TITLE
Fontaine: Default Header template plate is applying reversed colors

### ISSUE THREAD

**Issue by tanjoymor** [Automattic/themes#8404] opened 2024-11-09 21:36 UTC
### Quick summary

When you edit the default header template part, the text color is different than it displays in the template. And if you change the text and background colors they display as reversed in the template and are opposite when directly editing the Template Part.

### Steps to reproduce

1. Activate Fontaine on a Dotcom Simple site with any paid plan
2. Edit the Front Page template
3. Note the color of the text in the default header
4. Select the Header Template Part and click edit
5. Note that the color of the text is different
6. Change the color of the text and the background on the Group block
7. Go back to the template
8. Note that the colors are reversed

### A clear and concise description of what you expected to happen.

I expected the colors in the template and the template part to match the colors assigned to the pieces.

### What actually happened

The colors match the settings in the template part editor, but are reversed and/or different in the template.

https://github.com/user-attachments/assets/4aea1161-28ef-43a8-a9e3-f4b2f58385e6

### Impact

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### If the above answer is "Yes...", outline the workaround.

If you set up the colors to be the opposite of what you want, it can work. This is not easy to explain in a way users will understand and not many users are going to figure this out on their own.

### Platform (Simple and/or Atomic)

Simple

### Logs or notes

I have only tested this on Dotcom Simple sites.

**Comment by sudeepbaral** [comment] 2024-11-10 02:38
This issue was discovered here: 

- [ ] 9016335-zen

**Comment by Robertght** [comment] 2024-11-12 06:18
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated 
- Tested on Atomic – Replicated 
- Replicable outside of Dotcom – Yes

📌 FINDINGS/SCREENSHOTS/VIDEO
- I managed to replicate this on self-hosted sites too.

📌 ACTIONS
- Triaged
- Updated the title
- Leaving priority to Normal

**Comment by alaczek** [comment] 2024-11-13 01:20
This has to do with the [special treatment of the header elements](https://developer.mozilla.org/en-US/docs/Web/CSS/mix-blend-mode) (they change color when they overlap other elements). There's a special class add to achieve this effect - https://github.com/Automattic/themes/blob/trunk/fontaine/style.css#L75

The problem is this class is added to the parent group block that wraps the header in the homepage template. I think the issue could be solved by moving the class to the parent group block in the header template part.

> I expected the colors in the template and the template part to match the colors assigned to the pieces.

This won't be possible because of the special effect added via CSS class. While unintuitive, this is expected:

![Image](https://github.com/user-attachments/assets/003f1c9f-dcf5-433e-b2da-94b06b790d0b)

If having this effect isn't important to the customer we could advise them to remove the CSS class from the header and that should fix it.

**Comment by iamtakashi** [comment] 2024-11-20 23:10
Sorry for causing confusion with this feature.

> I think the issue could be solved by moving the class to the parent group block in the header template part.

@alaczek I'm unsure if I correctly understand your suggestion, but I'm interested. Could you make a PR so that we can test it? Thanks in advance!

> If having this effect isn't important to the customer we could advise them to remove the CSS class from the header and that should fix it.

Yes, for those customers, removing the CSS class `blending-mode` should do. ![Image](https://github.com/user-attachments/assets/94b79cd7-da07-4888-8f3a-61a454874c0e)

**Comment by iamtakashi** [comment] 2024-12-03 16:12
> I think the issue could be solved by moving the class to the parent group block in the header template part.

@alaczek I tried what I think you suggested, but it wouldn't work, would it? Or am I misunderstanding your suggestion?

![Image](https://github.com/user-attachments/assets/c007f5ec-f682-46d4-9972-36573ef77917)

**Comment by alaczek** [comment] 2024-12-05 00:54
> The problem is this class is added to the parent group block that wraps the header in the homepage template. I think the issue could be solved by moving the class to the parent group block in the header template part.

I think I was too optimistic there - moving the class, moves the problem, doesn't solve it really :(

**Comment by iamtakashi** [comment] 2024-12-05 11:12
I'm closing this as "won't fix".

I'm sorry that using the CSS blending mode has confused some users. For those, and if the effect isn't important, I'd advise removing the custom CSS class highlighted in the screenshot above.

**Closed as completed by iamtakashi** 2024-12-05 11:12 UTC
Labels: [Type] Bug, [Pri] Normal, Triaged, [Platform] Simple, Customer Report, [Feature Group] Appearance & Themes
