### ISSUE TITLE
The Shore: Header missing site title

### ISSUE THREAD

**Issue by alaczek** [Automattic/themes#8168] opened 2024-09-17 00:38 UTC
The Shore does not include the site title in the header, only Logo and navigation. This causes confusion for the customers, and we should avoid this design pattern.

Could we please add site title to the header? It's ok if the demo site displays the logo only.

cc @iamtakashi @MaggieCabrera

**Comment by beafialho** [comment] 2024-09-17 11:48
I don’t think the site title _and_ site logo look good in this particular theme. We ship so many themes with site title and not site logo, I thought this one could offer a different alternative.

**Comment by alaczek** [comment] 2024-09-18 01:03
We had the same issue with Hey, and ultimately decided to delist the theme because of it, so I want to avoid this in the future: https://github.com/Automattic/themes/issues/8024

> We ship so many themes with site title and not site logo, I thought this one could offer a different alternative.

Adding the site title doesn't take away customers' choice to remove it or leave empty. On the other hand, not adding it is confusing because:
* one of the steps we recommend customers complete in launchpad is adding a site title. It's confusing when it doesn't show up anywhere on the site. 
* we know from all the customer interviews we did that people find navigating the Editor hard and struggle with seemingly simple tasks like adding a block. Adding a site title requires knowing that there is such a thing as site title block and being able to navigate the document, both of which are quite advanced skills.

I understand this will affect the aesthetics, and I think we can keep it to logo only on the demo site if it helps.

**Comment by beafialho** [comment] 2024-09-18 09:16
Thank you for the extra context @alaczek!

> we know from all the customer interviews we did that people find navigating the Editor hard and struggle with seemingly simple tasks like adding a block. Adding a site title requires knowing that there is such a thing as site title block and being able to navigate the document, both of which are quite advanced skills.

This is intriguing. Adding a site title should not be a difficult or "advanced" skill, in my opinion 😞 This customer feedback is worth sharing in the appropriate product channels.

Let's keep the demo site without the site title, but add it to the theme to improve the experience overall.

**Comment by iamtakashi** [comment] 2024-09-18 11:45
I have a mixed feeling about this. 

Should the experience in the Launchpad dictate theme design?—I don't believe so—Themes shouldn't have to have a site title block because of that, and the Launchpad could change anytime. Such tools, including Gutenberg, must consider the design variety in themes, which should be one of the main drivers for the tools to be robust and flexible.

I've seen feedback and discussions about themes using terms such as UX and A11y, and those tend to judge themes either "good" or "bad". I don’t think the dichotomy of UX and a11y is healthy—It can make theme design stifle and monotonous. Those feedback should be shared and addressed in the tools, not reducing the theme variety. I don't have a problem with WP.com delisting or not launching some themes that don't fit in WP.com, but there should be spaces for themes without a site title block outside of WP.com. Maybe WP.com can skip this theme?

**Comment by beafialho** [comment] 2024-09-18 15:25
> I don't have a problem with WP.com delisting or not launching some themes that don't fit in WP.com, but there should be spaces for themes without a site title block outside of WP.com. Maybe WP.com can skip this theme?

Just noting that when I created this theme, I built it with the intent to fill a gap in the WP.com showcase. It would be a shame if it's not launched there.

> Should the experience in the Launchpad dictate theme design?—I don't believe so—Themes shouldn't have to have a site title block because of that, and the Launchpad could change anytime. Such tools, including Gutenberg, must consider the design variety in themes, which should be one of the main drivers for the tools to be robust and flexible.

However, I agree with this. Using and customising a theme should be easy and intuitive enough to make a simple change of replacing a site logo with a site title. If these difficulties caused by the platform, condition theme design, is not a good premise in my opinion, given that we also want to "push the boundaries" of what's possible with blocks.

**Comment by iamtakashi** [comment] 2024-09-18 16:11
> Just noting that when I created this theme, I built it with the intent to fill a gap in the WP.com showcase. It would be a shame if it's not launched there.

Ah, yes, I remember that now. I'll stand by my opinion that themes should not have to have a site title, but I don't mind adding it in this case because you seem ok with it. Which size would you like?

**Comment by beafialho** [comment] 2024-09-18 17:58
Thank you @iamtakashi. The default size of that block would work. If we add the site title, it won't be visible in the theme preview, right? The theme preview shows the demo site?

**Comment by iamtakashi** [comment] 2024-09-18 18:41
> the theme preview

Do you mean this in dotcom? If so, yes, this shows the demo site.

![CleanShot 2024-09-18 at 19 38 10@2x](https://github.com/user-attachments/assets/29b8874d-cb30-46a3-ae4f-cbf07369ee19)

**Comment by alaczek** [comment] 2024-09-18 23:24
Thanks for adding the site title! To answer some of your concerns:

> Should the experience in the Launchpad dictate theme design?

Launchpad experience is not the main point (although I don't think it should be entirely discarded either - most our themes have the largest customer base on WordPress.com). 

We're not talking here about some obscure, proprietary WordPress.com feature - without the site title block this theme is also ignoring core WordPress settings (Settings > General > Site title).

It's also worth bearing in mind that a huge portion of customers (both .com and .org) will not have a logo at all, and would be forced to figure out how to insert site title, which requires knowing how to navigate the document structure to insert it in just the right spot, to preserve the layout on both desktop on mobile. It is no small feat.

> and those tend to judge themes either "good" or "bad"

For the record, I'm not judging this theme as "bad". I think it will be popular with our customers. This discussion is about making it better, by making it easier to use. 

> Those feedback should be shared and addressed in the tools, not reducing the theme variety.

I agree. In this particular theme's case though, the header design isn't really pushing the boundaries in any special way - it's pretty standard as far as headers go. It won't loose it's character by the inclusion of site title imho.

As for encouraging theme variety, I think there should be a space for experimentation and pushing the design boundaries, and we can discuss this on a case by case basis.

>  I don't have a problem with WP.com delisting or not launching some themes that don't fit in WP.com

Yep, I personally wouldn't mind either if some themes launched on .org only.

> If we add the site title, it won't be visible in the theme preview, right? The theme preview shows the demo site?

I'm ok with removing the site title on the demo site, and presenting it as originally designed.
The preview on the right is from the actual demo site.

**Comment by beafialho** [comment] 2024-09-19 08:26
> Do you mean this in dotcom? If so, yes, this shows the demo site.
> The preview on the right is from the actual demo site.

Sounds good, as long as the demo site looks as intended I'm ok with it.

**Comment by iamtakashi** [comment] 2024-09-19 12:17
> For the record, I'm not judging this theme as "bad". 

I know, I didn't say that you did that. I meant there have been such feedback and discussions too quickly concluding that themes must change their design in the name of "UX" and "A11y". It's just something bothering me lately—not every theme needs to be like a default theme.

> Launchpad experience is not the main point (although I don't think it should be entirely discarded either)

>Yep, I personally wouldn't mind either if some themes launched on .org only.

Ok, I'm glad we agree that some themes could only launch WP.org if they don't fit in with a WP.com-specific feature rather than tailoring themes to WP.com. The majority of themes will fit, though.

Anyway, I'll add a site title block to this theme.

**Closed as completed** 2024-09-24 02:40 UTC
