### ISSUE TITLE
Mayland: background colour affecting social links colour

### ISSUE THREAD

**Issue by ianstewart** [Automattic/themes#2895] opened 2020-12-07 21:23 UTC
What happened:

Using a background colour with Mayland changes the colour of the Social Links block.

![image](https://user-images.githubusercontent.com/545779/101407032-e5b91680-389f-11eb-8f71-8db069cbf3bc.png)

What I expected: 

The social links block to be unaffected by the background colour change.

**Comment by alaczek** [comment] 2021-02-03 04:56
Sounds like I duplicated this issue in #3156, but I also noticed weird square background on hover in the editor.

**Comment by pbking** [comment] 2021-02-04 18:51
I tried hard but I've been unable to reproduce this (or #3156) using any of the steps provided.  Colors for social icons appear as expected in every scenario I could think to test Mayland in: Customiser, Post Editor, View... all appears as expected with backgrounds (and every other color adjusted) both with pre-defined palettes and custom colors.

![image](https://user-images.githubusercontent.com/146530/106940871-14ad0680-66f0-11eb-9214-68a345c1b466.png)

**Comment by alaczek** [comment] 2021-02-05 00:16
@pbking you can see this issue live on https://balanstarter.wordpress.com/ and https://knappstarter.wordpress.com/

**Comment by jffng** [comment] 2021-02-05 16:19
Closed by #3189, but will ship with a bundle of updates next week.

**Closed as completed by jffng** 2021-02-05 16:19 UTC
Labels: [Type] Bug, [Theme] Varia
