### ISSUE TITLE
[Bug]: Dropdown icon appears out of the field for Assembler Theme

### ISSUE THREAD

**Issue by krutidugade** [Automattic/themes#7973] opened 2024-07-28 12:48 UTC
### Quick summary

The dropdown icon appears outside of the "select" field for Assembler theme. The CSS for this is same as other WP.com themes. I verified with Cultivate theme. It is unclear why the CSS doesn't work as expected but works for other themes. 

### Steps to reproduce

1. Activate Assembler theme
2. Create/Edit a page and add Form block
3. Add dropdown field and few options
4. Publish or update the page

### What you expected to happen

The dropdown field should appear on contact page with downward arrow inside the field/

### What actually happened

The downward arrow (dropdown icon) appears below the field.
<img width="1483" alt="Screenshot 2024-07-28 at 1 13 00 PM" src="https://github.com/user-attachments/assets/4e01d747-470c-4a11-8479-f7a8c5b3a4e0">

### Browser

Google Chrome/Chromium

### Context

8541929

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

None

**Comment by retnonindya** [comment] 2024-08-16 06:57
📌 REPRODUCTION RESULTS
Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO

The dropdown arrow looks good on the editor:
<img width="1039" alt="Screenshot 2024-08-16 at 2 51 28 PM" src="https://github.com/user-attachments/assets/086ef19f-0522-471a-9cdd-8458077156f1">

But not so on the live site:
<img width="739" alt="Screenshot 2024-08-16 at 2 51 48 PM" src="https://github.com/user-attachments/assets/a8ae0881-87bc-416c-9201-2ea2475c1f3b">

📌 ACTIONS
Triaged

... And escalated to the team: pekYwv-4wd-p2#comment-4055. The team is currently reviewing how Assembler flow works, and since theme Assembler closely related with the flow, I raised it with the team.

**Comment by richtabor** [comment] 2024-11-11 17:22
Marking this as a duplicate of https://github.com/Automattic/themes/issues/8035

**Closed as completed by richtabor** 2024-11-11 17:22 UTC
Labels: [Type] Bug, [Pri] Normal, Customer Report, [Theme] Assembler
