### ISSUE TITLE
Varia: CoBlocks Social block disappears with a wide alignment

### ISSUE THREAD

**Issue by eduardozulian** [Automattic/themes#1515] opened 2019-10-14 14:42 UTC
## Steps to replicate

1. Activate on Varia-based theme (tested with Rivington and Alves) on an AT site with Gutenberg active 
2. Create a post/page
3. Add CoBlocks Social Profiles block
4. Choose the `wide` alignment
5. Visit your site

## Result

Different button styles produce different results:

Style: Default (just the background)

<img width="789" alt="Captura de Tela 2019-10-14 às 11 33 27" src="https://user-images.githubusercontent.com/1136160/66759374-87003480-ee76-11e9-9032-973628eb159a.png">

Style: Mask (nothing visible)

<img width="853" alt="Captura de Tela 2019-10-14 às 11 34 18" src="https://user-images.githubusercontent.com/1136160/66759411-97181400-ee76-11e9-8f41-8f13f4414343.png">

Style: Icon & Text (odd alignment)

## Expected

To see them properly.

There is something conflicting with this code (in this case `.entry-content > .alignwide` and `max-width: calc(100% - 32px)`):

```
@media only screen and (min-width: 1280px)
.entry-content > .alignwide, .entry-content > .alignwide.wp-block-jetpack-gif, .entry-content > .alignwide.wp-block-jetpack-tiled-gallery {
    width: calc(calc( 782px - 32px) + 256px);
    max-width: calc(100% - 32px);
}
```

The workaround, for now, is to use some CSS to fix it:

```
/* CoBlocks (Social): add a max width -- XXXX-hc (EZ) */
.wp-block-coblocks-social.alignwide {
    max-width: 100%;
}
```

* User report: #15948727-hc (cc @gugaalves)

**Comment by iamtakashi** [comment] 2019-10-24 16:46
This seems to be caused by the inherited max-width.

```
header *,
main *,
footer * {
	max-width: inherit;
}
```
The value should be `unset` and it's already been fixed for Varia in https://github.com/Automattic/themes/commit/7c0a36aa61ab9721441222301d1f3fdba330d02a , but each child theme sets this in `_config-child-theme-deep.scss` so we'll need to modify it manually in child theme.

**Comment by allancole** [comment] 2019-11-04 18:33
Closing this as the fix has been added to Varia and all it’s child-themes.

**Closed by allancole** 2019-11-04 18:33 UTC
Labels: bug, varia

**Comment by eduardozulian** [comment] 2019-11-06 18:00
Thanks, Allan!
