### ISSUE TITLE
Baskerville 2: Theme applies overlapping bullet points to Navigation Block

### ISSUE THREAD

**Issue by xpurichan** [Automattic/themes#1719] opened 2019-12-20 14:41 UTC
**Theme:** Baskerville 2

**Issue:** When using Gutenberg and creating a Navigation block the theme automatically applies bullet points to each menu item within the block. The bullet points overlap the menu items so this doesn't look nice.

This is what it looks like on this theme:
![Screenshot: https://cldup.com/7P_TRv2KHS.jpg](https://cldup.com/7P_TRv2KHS.jpg)

I tested multiple other new and old themes (Barnsbury, Stow, Dara, and Intergalactic 2) and this behavior doesn't occur on them. For the other themes I tested we just see the menu items listed, without bullet points:

![Screenshot: https://cldup.com/33CP0P31WC.jpg](https://cldup.com/33CP0P31WC.jpg)

Until this bug is fixed you can use the following CSS to resolve the problem:

```
/* remove disc from navigation block #-hc | KD */
.wp-block-navigation>ul li {
list-style: none;
}
```

**Comment by Gustavo-Hilario** [comment] 2022-10-14 17:25
I couldn't reproduce this issue on local sites and WordPress.com. I tested it with Baskerville 2 and Dara. I'm closing this issue for now.

**Closed by Gustavo-Hilario** 2022-10-14 17:25 UTC
Labels: [Type] Bug, Support, [Theme] Dara
