### ISSUE TITLE
Atomic sites with classic themes: Widget button custom styles not applied to live site

### ISSUE THREAD

**Issue by filipanoscampos** [Automattic/themes#7318] opened 2023-08-16 10:44 UTC
### Quick summary

On an Atomic website, activate a Classic theme with a Footer widget area, such as Stow.
Add a few button blocks to the Footer and set custom styles.
The changes are visible on the editor and the Customizer, but not on the live site.

### Steps to reproduce

1. On am Atomic site, activate Stow
2. Add a few buttons to the Footer widget area
3. Add custom colors
4. Notice that the changes are visible on the editor and the Customizer, but not on the live site.

### What you expected to happen

The custom styles to apply to the live site.
![Screenshot 2023-08-16 at 11 42 35](https://github.com/Automattic/themes/assets/2540430/149f51e9-710b-4041-8bb6-1e739543d221)

### What actually happened

They are overridden:
![Screenshot 2023-08-16 at 11 43 04](https://github.com/Automattic/themes/assets/2540430/299de035-5943-44ee-9c36-31b1f4716159)

### Context

zen-6644059

### Platform (Simple, Atomic, or both?)

Atomic

### Other notes

Tested on Stow and Morden.

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

None

**Comment by cuemarie** [comment] 2023-08-17 00:09
Duplicate of https://github.com/Automattic/themes/issues/7309

📌 ACTIONS
- Closed as duplicate

📌 Message to Author
- @filipanoscampos the issue is actually due to the way Varia child themes are impacted by the Page Optimize plugin. See linked issue for workarounds the user can try.

**Closed as not planned by cuemarie** 2023-08-17 00:09 UTC
Labels: [Type] Bug, [Status] Duplicate, [Pri] TBD
