### ISSUE TITLE
Shoreditch: [presentation] shortcode error on Panel Page Template when shortcode used on child page

### ISSUE THREAD

**Issue by laurelfulford** [Automattic/themes#9] opened 2018-02-24 04:19 UTC
Originally reported by @juliasydnor in 4844-wpcom-themes.

## Steps to replicate

1. Publish a page using the Panel Page Template.

![](https://cldup.com/dGfS9BPupk.png)

2. Publish a child page of that page with the [presentation] shortcode.

![](https://cldup.com/FWK0UM_AbQ-3000x3000.png)

## Result

The slideshow generated by the [presentation] shortcode is correctly displayed on the child page.

![](https://cldup.com/EDRD80mc7p-3000x3000.png)

The slideshow is not displayed correctly in the panel on the parent page using the Panel Page Template. An "This slideshow could not be started. Try refreshing the page or viewing it in another browser." error is shown instead.

![](https://cldup.com/RA1_mainBZ-3000x3000.png)

## Expected

The slideshow generated by the [presentation] shortcode to appear in the panel on the parent page using the Panel Page Template. 

This was reproduced on a test site.

* User report: 716679-zd
* User's site: https://villagrecamore.wordpress.com/test-top-page/

**Comment by sixhours** [comment] 2018-03-06 17:46
The presentation plugin is looking at the parent page to see if there's a `[presentation]` shortcode present. When it doesn't find one, it doesn't load the corresponding scripts and styles. It doesn't check the child pages for the shortcode because it's only looking at the original page query.

I confirmed this by adding a presentation shortcode to the parent page; when I do this, both presentations show up.

This is not specific to Shoreditch; it happens in any theme where a presentation shortcode is used in the content that is not part of the main query. Affinity and Pique have similar setups, where you can select specific pages to be displayed on the front page; the presentation shortcode does not work in these cases, either.

I believe this is something that would need to be fixed in the plugin, not the theme, so going to open a ticket for it in Jetpack.

**Comment by sixhours** [comment] 2018-03-06 17:55
Reported in the Jetpack repo above, closing this ticket as a duplicate.

**Closed by sixhours** 2018-03-06 17:55 UTC
Labels: bug, duplicate, support
