### ISSUE TITLE
Quadrat: Option to reduce space under header

### ISSUE THREAD

**Issue by mikeicode** [Automattic/themes#4828] opened 2021-10-08 11:56 UTC
### What

Quadrat uses inline CSS to add space under the header, resulting in a large gap on desktop and mobile. Ideally this would be adjustable.

### Why

I assume this was a design decision but not having this setting as adjustable results in the need for custom CSS for users who would like to reduce the space.

Desktop:

![Screen Shot on 2021-10-08 at 07:43:12](https://user-images.githubusercontent.com/10353785/136551712-045529a5-9dba-485e-a3d7-669b80887a31.png)

Mobile:

![Screen Shot on 2021-10-08 at 07:48:24](https://user-images.githubusercontent.com/10353785/136551725-af01fb6c-2953-4be4-a2d9-10e28c815cd1.png)

One request:

31480501-hc

### How

Perhaps a Customizer setting.

For now we can use CSS:

```
/* Space under header */
 
.site-header {
    padding-bottom: 0px !important;
}
```

**Comment by pbking** [comment] 2021-10-13 17:34
That's correct @jordesign the FSE is the only (non CSS) way to adjust that gap and is the intended mechanism.  There are no plans to make that adjustable outside of that.

Closing this as expected behavior.

**Closed as completed by pbking** 2021-10-13 17:34 UTC
Labels: [Theme] Quadrat

**Comment by mikeicode** [comment] 2021-10-23 16:46
Requested: 4399026-zd-woothemes

**Comment by mikeicode** [comment] 2021-10-29 19:57
Another 31818301-hc
