### ISSUE TITLE
Blank Canvas Theme Does Not Display Footer Credit

### ISSUE THREAD

**Issue by mgozdis** [Automattic/themes#6804] opened 2022-12-21 23:03 UTC
### Quick summary

EDIT on 9 Feb 2023 by @autumnfjeld : the actual issue is that the customizer should not show for an FSE theme.  p1675930513873919/1675930224.873229-slack-CRWCHQGUB

On Free, Personal, and Premium plans, the footer credit does not display when using the Blank Canvas theme even when explicitly trying to change the footer credit to different values under the Customizer. No footer credit displays at all despite notices and upsells stating a plan upgrade is required to hide the footer credit. 

### Steps to reproduce

1. Add a new site on Free plan
2. Change theme to Blank Canvas

Behavior is the same whether preserving or replacing content.

### What you expected to happen

I expected the footer credit to display either the default value or any of the selected values under the Customizer. 

### What actually happened

Nothing. No footer credit is displayed.

### Context

Internal testing on simple platform only. Reproducible on every test site I created.

### Platform (Simple, Atomic, or both?)

Simple

### Theme-specific issue?

Blank Canvas

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

There is no user impact

**Comment by zachspears** [comment] 2022-12-29 01:00
Can confirm that the footer credit is not displayed. Leaving normal priority as it provides a workaround to a benefit for upgrading WordPress.com plans.

**Comment by autumnfjeld** [comment] 2023-02-09 08:11
This was a deliberate decision:
https://github.com/Automattic/wp-calypso/issues/67856#issuecomment-1254350572
p1663805097212879/1663295644.661609-slack-CRNF6A9DX

So it appears that the issue is that the customizer isn't in sync with this decision.

Also though I'd say, we don't really expect users to use the customizer for an FSE theme.  I have a memory of a discussion that it shouldn't be available for an FSE theme.  I've asked here for more info on this:  p1675930224873229-slack-CRWCHQGUB

**Comment by autumnfjeld** [comment] 2023-02-09 08:30
Actually the info I provided above might be out of date.
Currently the only way a user can get a BC theme is by going through the Assembler step in onboarding.
[Heads-up: Pattern Assembler Flow MVP is Launching!] p7DVsv-fWw-p2

I see that all but two footer patterns include the footer credit
<img width="352" alt="image" src="https://user-images.githubusercontent.com/5665959/217757691-87e97089-4366-4f34-8aed-f811411e7eb6.png">



![image](https://user-images.githubusercontent.com/5665959/217757957-54a64470-c32d-4a44-bc94-0bcb6116a101.png)


These are the same footer patters in https://dotcompatterns.wordpress.com/category/footer/


@miksansegundo or @alaczek  Should all these footer patterns have a footer credit?

**Comment by autumnfjeld** [comment] 2023-02-09 08:37
p1675930513873919/1675930224.873229-slack-CRWCHQGUB

> I don't think we should be allowing access to customizer in this theme

**Comment by alaczek** [comment] 2023-02-09 23:10
> Should all these footer patterns have a footer credit?

I'd say yes. I'll go ahead and update them today.

**Comment by alaczek** [comment] 2023-02-13 23:40
I found three footer patterns without the credit, and fixed them:
* https://dotcompatterns.wordpress.com/2020/07/06/contact-11/
* https://dotcompatterns.wordpress.com/2022/04/28/footer-with-social-icons-address-e-mail-and-telephone-number/
* https://dotcompatterns.wordpress.com/2022/04/08/footer/

**Comment by autumnfjeld** [comment] 2023-07-28 16:27
Closing this issue.  Blank Canvas has been delisted. https://fieldguide.automattic.com/delisted-themes/

**Closed as completed** 2023-07-28 16:27 UTC
Labels: [Type] Bug, [Pri] Normal, Triaged, [Platform] Simple, Lego Maintenance
