### ISSUE TITLE
Sigler: Vimeo video size / centering mobile issue

### ISSUE THREAD

**Issue by mikeicode** [Automattic/themes#4829] opened 2021-10-08 13:41 UTC
### Quick summary

Sigler uses a Vimeo video on the homepage. On smaller mobile screens the video appears off centered.

### Steps to reproduce

View the [Sigler homepage demo](PdnlTu-2-p2) on a small mobile screen.

### What you expected to happen

Video should be sized correctly and centered.

### What actually happened

It's too large or not centered.

![Screen Shot on 2021-10-08 at 09:29:01](https://user-images.githubusercontent.com/10353785/136565824-27c70235-2421-441c-a646-fb673dca66c9.png)

### Context

The issue has been reported twice today:

32097895-hc

31032144-hc

We used this on one site to resolve:

```
/* Cover block - mobile */

@media only screen and (max-width: 767px) {
  .home .wp-block-cover .wp-block-cover__inner-container {
    width: unset;
  }
}
```

![Screen Shot on 2021-10-08 at 09:29:16](https://user-images.githubusercontent.com/10353785/136565856-b117528b-b0c3-4c1a-a305-67742b50cf48.png)

### Operating System

macOS, iOS

### Browser

Google Chrome/Chromium, Mozilla Firefox, Apple Safari

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

This may not be specific to this theme (I see the same issue when activating other themes), but since this theme uses this layout as the default homepage perhaps it can be resolved for the one theme at least. 

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

If the site can use CSS the solution posted above appears to work.

**Comment by Greatdane** [comment] 2021-10-13 00:46
This is one of many new themes released recently; p7DVsv-cHN-p2
Not sure if affects all seedlet/Blank Canvas related themes.

**Comment by jordesign** [comment] 2021-12-03 03:17
Confirmed this looks ok until 420px wide - at which point the vimeo embed stops resizing.

Being caused by this CSS - which is appearing in addition to padding on the content.

```
.wp-block-cover .wp-block-embed {
    min-height: 240px;
    min-width: 320px;
}
```

**Comment by jordesign** [comment] 2021-12-03 03:30
On further research - this CSS seems to be coming from Gutenberg core - and the issue is related to the Embed being nested inside the Cover block. The issue does not occur when the Embed is *not* inside a Cover block.

As Sigler may be getting phased out soon - I'm closing this issue. We can re-open it if we need.

**Closed as completed by jordesign** 2021-12-03 03:30 UTC
Labels: [Type] Bug, [Theme] Sigler, Triaged
