### ISSUE TITLE
Button 2: Mobile menu stopped working when a page is set as static homepage

### ISSUE THREAD

**Issue by arcangelini** [Automattic/themes#3201] opened 2021-02-06 13:55 UTC
## Summary
It looks like the latest update to 5.6 has broken the jQuery on the site. This is causing an error with the navigation js.

## Steps to replicate

1. Activate Button 2 theme
2. Setup primary menu
3. View site from a mobile device (dev console viewer does not replicate this, you need to use BrowserStack or actual mobile phone)
4. Try to open mobile menu.
5. View console

## Result

Nothing opens. Error in console for no jQuery defined.
[Screenshot](https://d.pr/i/MrCuup)

## Expected

Menu should open : )
[Screenshot](https://d.pr/i/Djicbk)

* User report: #27552996-hc
* Follow-up ticket: #3717531-zd

**Comment by retnonindya** [comment] 2021-02-08 05:47
The ticket reopened, and I'm curious because I can't replicate the issue on the theme demo site. 

I noticed two things:

- For some reason, the menu "Primary" is not assigned on "Header" area on Menu Locations. Not exactly "not assigned," it's assigned, but the checkbox under Menu Location is not clicked. It seems like a stuck (?) condition? 🤔 
![image](https://cldup.com/FKWMCWrQVV.png)
*Direct link: https://cldup.com/FKWMCWrQVV.png*

- I also asked the user to publish the changes on Customizer. I'm not sure when they set it as Draft, but if this happened when they reached out on chat, most likely we are not looking at the final version.
![image](https://cldup.com/QHwIviVn7W.png)
*Direct link: https://cldup.com/QHwIviVn7W.png*

Once the user responded with their findings, we can proceed from there.

**Comment by ctdealba** [comment] 2021-02-08 17:04
User has followed the steps given and the button is still not working. 

User is now claiming that the top banner is now lost.

**Comment by retnonindya** [comment] 2021-02-09 00:48
Thank you for the updates, @ctdealba!

Missing top banner is due to "Display Site Title and Tagline" option is inactive. I have activated it from Customize and things should reappear now.

Now, about the mobile menu. After confirmed the issue persists even with everything assigned and saved properly, I cross-checked with my test site and I can replicate it when **static page is set as homepage.** This issue not happened when latest blog posts is set as the homepage.

**Comment by davoraltman** [comment] 2021-02-13 11:01
I had a similar case in 27645172-hc for the AT site https://eleonmonastery.com/. After disabling the Page Optimize plugin, the menu worked when checking on a mobile device.

I then tested this on my test AT site and I couldn't replicate (with and without a static homepage) with the Page Optimize plugin active.

**Comment by mikeicode** [comment] 2021-02-18 16:26
Another on a Simple site: 26941292-hc

One possible temporary solution is to hide the mobile toggle with CSS:

```
/* Hide mobile menu toggle */

.menu-toggle {
  display: none;
}
```

Then you can add a menu widget to the footer widget area. Not ideal, but worth suggesting.

Also there is another issue for this here:

https://github.com/Automattic/themes/issues/2831

**Comment by zdenys** [comment] 2021-04-27 16:06
29262053-hc: simple site with a static homepage.

**Comment by donalirl** [comment] 2021-05-19 07:30
Another report in #3993647-zen. Switching from static homepage to latest posts, then back to static homepage again seemed to solve it.

**Comment by metabreakr** [comment] 2021-06-11 19:23
4061073-zen

**Comment by kaitohm** [comment] 2021-06-14 05:00
I'm adding details I found testing 4061073-zd-woothemes

When switching the homepage from a static page to showing latest posts, and then back again, the menu started to work if I had loaded the page once while showing the static posts. The browser seems to have cached something, so the mobile menu would work when switching back to showing a static front page.

However, if I were to open the site in a fresh browser after the switch, the menu would still not load. So, we're still stuck.

**Comment by galakhyati** [comment] 2021-06-29 05:59
Another simple (Personal plan site): 4099521-zd-woothemes

Setting the static page to the latest posts and then back to the static page fixed the issue, though there are still some errors appearing in the site's console.

When checking from another browser, the menu is still stuck.

**Comment by vajrasar** [comment] 2021-06-29 18:15
Another simple (Personal plan) site: 4100719-zd-woothemes

In this case, setting the static page to the latest posts and then back also did not solve the issue.

**Comment by liviopv** [comment] 2021-06-30 10:13
Another in #30401625-zen

Changing Homepage Settings back and forth fixed the issue. I also got it working when I created a second menu and assigned it to the Primary menu area.

**Comment by kcswong** [comment] 2021-07-02 18:23
Report in 26748133-hc, Atomic site

Changed homepage to latest posts, and sent steps for making sticky posts so they could have some static content at the top of the feed as an alternative to static homepage

**Comment by formosattic** [comment] 2021-11-23 05:16
+1 4537979-zd-woothemes

Things I tried that didn't work:
* Create a new menu
* Switch back between Latest Posts and Static Homepage

**Comment by sharonlaker19** [comment] 2021-11-23 17:48
+1 31233839-hc
They're hesitant to switch to latest posts on the homepage.
Would like an update on the bug when it's available. Thanks!

**Comment by radtechgh** [comment] 2021-11-23 19:38
Reported here: 4539263-zen

Site will work with Latest posts as homepage.
Tried switch to Latest posts, then back to static, did not work.

**Comment by jordesign** [comment] 2021-11-24 09:26
Button2 is in use on ~300k sites -  we're still getting very regular reports of this issue.

I've been unable to recreate this in my testing (on iOS with Mobile Safari and Chrome) on my own sites - and had mixed results checking user reports from above.

**Comment by jordesign** [comment] 2021-11-24 09:59
Additional interactions:

* #20940197-hc
* #3710131-zen
* #3709265-zen
* #3664428-zen
* #3664428-zen
* #3500752-zen

Total of 20 reports so far

**Comment by seanbelly** [comment] 2021-11-24 19:20
Another one here: #625646-hc
I couldn't replicate on test site but saw the problem on iphone 12.

**Comment by rinazrina** [comment] 2021-11-25 13:47
Another one: #4544354-zen

**Comment by ChrissiePollock** [comment] 2021-11-27 13:55
Another on #4548816-zen. Site has Premium plan.

**Comment by ClassicRKR27** [comment] 2021-11-29 20:43
Another report here: [26965677-hc](https://hud.happychat.io/chat/26965677)

**Comment by ktyfuller604** [comment] 2021-11-29 21:33
Another report: #10375964-hc

Issue also occurred on Android until AMP was turned off. 

Ultimately switched to Shawburn.

**Comment by arcangelini** [comment] 2021-12-01 09:48
I am looking into this today and am struggling to find any sites that are experiencing the issue still. I have been testing in BrowserStack with my own sites as well as the user-reported sites, but every user site has either changed themes or is no longer experiencing it. Is there anyone who has a site or a configuration that I can use to troubleshoot this?

**Comment by pauloeaquino** [comment] 2021-12-02 00:54
Encountered in #7478991-hc

**Comment by jordesign** [comment] 2021-12-02 01:48
@arcangelini looks like you can try out http://thelittlepilgrim.com on a mobile device

**Comment by radtechgh** [comment] 2021-12-02 20:45
4562338-zen is for the site http://thelittlepilgrim.com/

**Comment by rinazrina** [comment] 2021-12-03 05:23
Run into another report here: #4556644-zen

I can reproduce the issue when accessing [the site](http://thelittleglutenfreebakingblog.com/) by typing the address from Google app. However, when I type the site address directly on mobile browser bar, the menu button is working fine. I'm on Android 11. 

As a workaround, I suggested the user enable the mobile theme mode via /wp-admin/themes.php?page=mobile-options

**Comment by msilbers** [comment] 2021-12-07 15:28
reported in 4574078-zen

Switching the front page to the posts page and back did not resolve it

**Comment by arcangelini** [comment] 2021-12-07 18:12
Thanks @jordesign and @rinazrina I was able to replicate it using http://thelittleglutenfreebakingblog.com/ but not http://thelittlepilgrim.com/ here is an updated screenshot.

<img width="1198" alt="Markup 2021-12-07 at 10 56 23" src="https://user-images.githubusercontent.com/33258733/145072605-4b79598a-486e-4d55-b798-8cd33a3d1a4d.png">

It have made a PR to address this and it just needs to be reviewed and merged. I will keep y'all posted.

**Comment by jordesign** [comment] 2021-12-07 20:40
That's so awesome- thanks Tony!

**Comment by poeticabdul** [comment] 2021-12-09 10:19
User came back in chat 32879604-hc to check on status of this bug

**Comment by cuemarie** [comment] 2021-12-09 18:21
33115256-hc

Switching the homepage to latest posts then back to static had no effect on the issue

**Closed as completed** 2021-12-10 15:13 UTC
Labels: [Type] Bug, Support, [Pri] Normal, [Pod] Design Selection, Triaged

**Comment by jordesign** [comment] 2021-12-12 22:42
@arcangelini !!!! Thank You!

**Comment by jordesign** [comment] 2021-12-13 02:38
Hi everyone 👋 Just a quick note to let you all know @Automattic/bug-herders have finished following up with affected users reported in this thread (all those who reported in June or more recently). We've deliberately not contacted users from older reports than that.

Thanks for the reports, please let us know here if you see any future recurrence of the issue.
