### ISSUE TITLE
Maywood: Gallery Block set with 2 columns shows stacked in single vertical line when viewing page

### ISSUE THREAD

**Issue by gwensmithx** [Automattic/themes#2455] opened 2020-09-12 22:51 UTC
On a simple site using Maywood theme, add a gallery block and set it with 2 images, cropped and set to 2 columns so they are side-by-side.

In the editor this looks correct but on the page the images are stacked in a single line.

Example when viewing page: 
![Screen Shot 2020-09-12 at 4 34 50 PM](https://user-images.githubusercontent.com/5779512/93006309-cd8f6080-f517-11ea-985b-8009927a21d3.png)

If you switch the theme it will appear correctly like this (using Twenty Twenty in this example):
![Screen Shot 2020-09-12 at 4 36 46 PM](https://user-images.githubusercontent.com/5779512/93006321-eac42f00-f517-11ea-9457-afd7f6e2dec6.png)

## Result

Using Maywood theme shows 2 column gallery images stacked in single line when viewing the page (looks correct in Editor). If you switch the theme it will show up correctly.

## Expected

Expected the 2 columns to show side-by-side as seen and set in the editor

First reported here: #3305826-zd

**Comment by nielslange** [comment] 2020-09-13 02:10
The problem seems to be caused by the following CSS code

```
.blocks-gallery-grid .blocks-gallery-image, .blocks-gallery-grid .blocks-gallery-item, .wp-block-gallery .blocks-gallery-image, .wp-block-gallery .blocks-gallery-item {
    margin: 0 1em 1em 0;
    display: flex;
    flex-grow: 1;
    flex-direction: column;
    justify-content: center;
    position: relative;
}
```

which should be 

```
.blocks-gallery-grid .blocks-gallery-image, .blocks-gallery-grid .blocks-gallery-item, .wp-block-gallery .blocks-gallery-image, .wp-block-gallery .blocks-gallery-item {
    margin: 0 16px 16px 0;
    display: flex;
    flex-grow: 1;
    flex-direction: column;
    justify-content: center;
    position: relative;
}
```

This code comes from https://github.com/WordPress/gutenberg/blob/bc77362f7dd7007af0390ca5aeea1466a0be890b/packages/block-library/src/gallery/style.scss#L10-L18. Strange enough, I'm not able to reproduce this problem on a WordPress.org testing site.

**Comment by nielslange** [comment] 2020-09-15 11:00
Duplicate of #2437

**Closed by nielslange** 2020-09-15 11:00 UTC
Labels: [Pri] Normal, [Theme] Varia, [Type] Bug
