### ISSUE TITLE
Baskerville 2: Post order leaving white space with Infinite Scroll Active.

### ISSUE THREAD

**Issue by rezzap** [Automattic/themes#210] opened 2018-07-23 15:11 UTC
## Steps to replicate

1. Navigate to the Post Page a site using the Baskerville 2 Theme with the Infinite Scroll Option enabled in Chrome or Firefox.
2. Scroll to the bottom of the page and hit Refresh.

## Result

An extra amount of white space loads above the posts. Sometimes this happens on first load as reported to the user, but only with Infinite Scroll enabled. 

The user was not able to get the posts to display correctly at all using Chrome 67 of Windows 7. 

You can see a quick screen recording of this happening on my site here: 
https://cl.ly/0M362600350w 

## Expected

You would expect the posts to load correctly no matter where you are in the page when it refreshes. 

* User report: #4920299-hc
* Follow-up ticket: #1298320-zd
* User's site: https://cilantroroots.com Issue is on the homepage.

**Comment by laurelfulford** [comment] 2018-07-23 21:56
Thanks @rezzap ! After reviewing the two tickets, this looks like a duplicate of #208; I've moved this report over there and updated the description.

**Closed by laurelfulford** 2018-07-23 21:56 UTC
Labels: bug, support
