### ISSUE TITLE
Check spacing and alignment in the Course theme

### ISSUE THREAD

**Issue by merkushin** [Automattic/themes#7121] opened 2023-05-30 08:01 UTC
Check if we broke alignment and spacing in the Course theme.
First thing to check if the problems were introduced in the Learning Mode Improvements project.
Depending of the scope, create new issues or fix here.

- Buttons in one of our course theme got miss aligned. They should be aligned to the left with the content.
- Some of the previous for the Lesson Wizard blocks have some issues. (Screenshots attached.)
- Title is also miss-aligned. It should be aligned to the left with the rest of the content.
- Spacing between header and content is too big as well.

![Image](https://github.com/Automattic/sensei/assets/329356/1fe6f3a6-ad08-40de-a8e4-1cb31df244bf)
![Image](https://github.com/Automattic/sensei/assets/329356/0902a05d-1b82-427a-b6ee-044087fd9d35)
![Image](https://github.com/Automattic/sensei/assets/329356/6127355a-ec46-4bd9-af5a-0309d3260445)
![Image](https://github.com/Automattic/sensei/assets/329356/cfc50f6a-b625-4686-a4b4-2bb06c3b5239)
![Image](https://github.com/Automattic/sensei/assets/329356/88b03475-d98c-4b72-9a52-9e8773df33dd)
![Image](https://github.com/Automattic/sensei/assets/329356/69b389d2-b485-4bde-8959-d72b75451565)
![Image](https://github.com/Automattic/sensei/assets/329356/86ed3fe2-82aa-4585-8e6b-7660fe400686)

Origin: p1685368834127169-slack-C02P7FHLVR9

**Comment by gabrielcaires** [comment] 2023-05-31 18:04
I used the following branches
* sensei#feature/learning-mode-improvements
* course#feature/learning-mode
* sensei-pro#feature/learning-mode
* Sensei

I could fix the following issues:

- [x] Buttons in one of our course theme got miss-aligned. They should be aligned to the left with the content. [Fixed on the PR  ](https://github.com/Automattic/themes/pull/7119)
- [x] Spacing between header and content is too big as well. [Fixed on the PR  ](https://github.com/Automattic/themes/pull/7119)
- [x] Title is also miss-aligned. It should be aligned to the left with the rest of the content. [PR](https://github.com/Automattic/sensei/pull/6938) 


I couldn't reproduce any issue related to wrong colors.

**Comment by gabrielcaires** [comment] 2023-05-31 18:05
PR 1 -  https://github.com/Automattic/sensei/pull/6938
PR 2 - https://github.com/Automattic/themes/pull/7119

**Closed as completed** 2023-06-01 16:15 UTC
Labels: [Type] Bug
