### ISSUE TITLE
Blank Canvas: template parts, blocks set in FSE disappear when WooCommerce is activated

### ISSUE THREAD

**Issue by formosattic** [Automattic/themes#5663] opened 2022-03-13 00:53 UTC
### Quick summary

With Blank Canvas, when WooCommerce is activated, the templates will be lost.
This bug likely needs to be moved to the Themes repo.

Slack convo (cc @jamiepalatnik ): p1647106924327449-slack-C01UW7SB411

### Steps to reproduce

1. Setup a front page (set in Customize) with some demo content (can use Patterns)
2. Take a look at the front page
3. Activate WooCommerce, and check the front page, it looks the same
4. Change the theme to Blank Canvas, then recheck the front page

### What you expected to happen

Blocks, templates parts should remain.

![image1](https://user-images.githubusercontent.com/15944096/158349891-32d758b9-5209-4d87-a754-2cdde6d842b2.png)

### What actually happened

The blocks, templates parts disappeared, aren't loading.

![image2](https://user-images.githubusercontent.com/15944096/158350050-09c1095d-7a17-4482-930a-1a613799e14d.png)

### Context

Ticket: 4852841-zd-woothemes

Related, from .org forum with other themes:

* https://wordpress.org/support/topic/template-part-has-been-deleted-or-is-unavailable-2/
* https://wordpress.org/support/topic/template-part-has-been-deleted-or-is-unavailable-error/
* https://wordpress.org/support/topic/woocommerce-missing-header-title-after-wp-update/

### Simple, Atomic or both?

Atomic

### Theme-specific issue?

Blank Canvas, maybe other themes.

### Available workarounds?

Yes, easy to implement

### Workaround details

Switch to another theme.

**Comment by formosattic** [comment] 2022-03-15 10:01
Issue also happening on self-hosted, but behavior is slightly different, instead of nothing showing, the front page loads the page content only.

| Expected (Quadrat) - FSE template is applied  | What happened (Blank Canvas) - Only page content is showing |
| ------------- | ------------- |
| ![image1](https://user-images.githubusercontent.com/15944096/158353466-875bbe2d-2d44-42ff-87a0-00b35c13e381.png)  | ![image2](https://user-images.githubusercontent.com/15944096/158353451-b82f3056-a794-41d1-b0b8-1cc3828a49a9.png) |

**Comment by Robertght** [comment] 2022-03-15 11:43
Currently asking [here](p1647344541881399/1647106924.327449-slack-C01UW7SB411) as I'm a bit confused of the issue and how to replicate it properly.

**Comment by Robertght** [comment] 2022-03-21 10:26
I'm not successful in replicating this behavior and based on this(p1647545710834279-slack-C01DF571R5Y) the templates and template-parts should be theme specific:

>They are theme specific, yes. If you change themes you will have different templates/parts to work with. They aren't entirely 'lost' as reactivating a previous theme where you had made customizations will still have those customizations in place.

I'm going to close this for now, but if there are any further cases, please re-open.

**Closed as completed by Robertght** 2022-03-21 10:26 UTC
Labels: [Type] Bug, [Pri] Normal, [Theme] Blank Canvas

**Comment by thesacredpath** [comment] 2022-04-24 20:21
Another report of this here, but WooCommerce was not installed. Theme switch was prior to them going AT.

 What triggered the issue according to the user, was going from Simple Pro to AT Pro. Currently only one non-WP.com plugin installed, for custom facebook feed.

5162993-zen

**Comment by filipanoscampos** [comment] 2023-03-28 11:51
Although I was not able to reproduce it on my test site, we ran into a similar case here: 6074641-zd-woothemes

The site is using the Thriving Artist theme.
