### ISSUE TITLE
Sequential:  Byline is not shown in entry meta.

### ISSUE THREAD

**Issue by jerrysarcastic** [Automattic/themes#5256] opened 2021-12-27 01:51 UTC
## Steps to replicate
No need to replicate this can be observed by visiting the [theme demo site](P5ePuv-1H-p2) and loading any blog post.  If you examine the source code the byline info is shown, but it not visible on the site:

<img width="990" alt="Markup 2021-12-26 at 17 46 04" src="https://user-images.githubusercontent.com/1967448/147426268-2ad92a2e-358e-4dba-af4a-50005b8db093.png">

Does not seem to be affected by the author setting in the customizer (Content Options) from what I can tell the byline is hidden regardless of the setting.

* User report: https://wordpress.com/forums/topic/sequential-theme-full-width-page/#post-3771456

**Comment by supernovia** [comment] 2021-12-27 22:24
Jennifer pointed out this may be one of those themes that hides the author if there's only one on the site. I think she's right, as I can see the author name in my testing.

**Comment by kathrynwp** [comment] 2022-07-07 21:13
I believe @supernovia is correct. This theme hides the author name on single-author blogs, by design, as you can see in this portion of the theme's CSS:

```
.byline,
.updated:not(.published) {
	display: none;
}
.group-blog .byline {
	display: inline;
}
```

Closing as wontfix.

**Closed as completed** 2022-07-07 21:13 UTC
Labels: [Status] wontfix
