### ISSUE TITLE
[Bug]: Radcliffe 2 theme | Logo size does not change

### ISSUE THREAD

**Issue by carolframen** [Automattic/themes#7496] opened 2023-11-16 16:28 UTC
### Quick summary

The Radcliffe 2 theme has the option of changing the logo size on the Customizer, but when you try to change it, it changes on the customizer, but not on the live site. And the default logo size is very small.

https://github.com/Automattic/themes/assets/119800062/ff66646b-706d-49ce-a939-ad2124f237e1

### Steps to reproduce

1. Activate the Radcliffe 2 theme
2. Add a logo to the site
3. Try to adjust the size of the logo
4. Save the changes
5. Check the site

### What you expected to happen

The logo should be bigger or smaller, depending on the size settings you chose

### What actually happened

The logo remains the same size, doesn't matter what you do.

### Browser

Google Chrome/Chromium, Mozilla Firefox

### Context

Customer report #7321578-zen

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

None

**Comment by carolframen** [comment] 2023-11-16 16:37
Another case 7322215-zen

This user is on the Premium plan and tried adjusting it with CSS, but it did not work

**Comment by ricklabsdotn8** [comment] 2023-11-18 14:44
7328035-zen

CSS override with !important works:
`.custom-logo {
	height: 100px !important;
	width: 100px !important;
}`

**Comment by ClassicRKR27** [comment] 2023-11-18 16:02
Another instance here: 7329360-zd-a8c

Using the CSS workaround from @ricklabsdotn8 works here as well

**Comment by carolframen** [comment] 2023-11-18 17:26
7330407-zen
Personal plan, so no CSS workaround possible

**Comment by carolframen** [comment] 2023-11-18 17:28
7330429-zen, another one on the Personal plan

**Comment by Aurorum** [comment] 2023-11-18 17:54
7330444-zen

**Comment by OgeAmadi** [comment] 2023-11-18 19:37
7330617-zen, another case (_The user is on a Premium plan so I suggested the CSS fix_ @ricklabsdotn8 )

**Comment by robinkel** [comment] 2023-11-19 21:17
> 7322215-zen

Using the CSS workaround from @ricklabsdotn8 works here as well

**Comment by upwardmomentum84** [comment] 2023-11-21 16:24
7341672-zd-a8c

Provided CSS to set width with !important and set height to auto also with !important.

**Comment by OmarFPG** [comment] 2023-11-21 17:46
Another one on a Personal plan, can't provide CSS. 7335970-zen, the user is very upset about this.

I thought of providing a workaround for the user of placing the logo as part of the navigation bar (I've used images in nav menus for quite a few customers, so I thought of this alternative), but for some reason, it isn't working (I'm not sure if this is a restriction on .com sites or personal sites? HTML is enabled for personal sites; the IMG tag is available to use https://wordpress.com/support/code/#html, but the image is not showing up).

**Comment by OmarFPG** [comment] 2023-11-22 15:50
One more: 7330005-zen.

**Comment by Aurorum** [comment] 2023-11-22 18:14
7338872-zen

**Comment by Gustavo-Hilario** [comment] 2023-11-23 14:58
- [ ] Another report: 7333948-zen

**Comment by Gustavo-Hilario** [comment] 2023-11-23 15:00
- [ ] Another one: 7322156-zen

**Comment by pauljacobson** [comment] 2023-11-26 13:12
We have a report here too: 7330454-zen

The site is on a WordPress.com Business plan so I'll share a Custom CSS workaround.

**Comment by pauljacobson** [comment] 2023-11-28 14:56
Another report here: 7373978-zen

**Comment by cat-og** [comment] 2023-12-02 04:08
Another report here: 7393738-zd-a8c

**Comment by Aurorum** [comment] 2023-12-02 09:49
7388860-zen

**Comment by OgeAmadi** [comment] 2023-12-02 12:22
7394878-zen - _The user is on a Personal plan so I couldn't provide the CSS workaround_

**Comment by Aurorum** [comment] 2023-12-02 16:04
I can't reproduce this on an Atomic site, and there have been no recent changes to Radcliffe 2 that could affect this. This is a hunch, but I suspect that recent jQuery deprecations are responsible for this issue. Without being able to recreate it on an Atomic environment though, I can't say for certain.

**Comment by Aurorum** [comment] 2023-12-02 16:29
The problem seems to be that the SVN for WP.com has not been aligned with this repo. Instead, for `logo_awesomeness_min_max`, this has been registered.

```
/* Helper function to determine the max size of the logo */
function logo_awesomeness_min_max( $short, $long, $short_max, $long_max, $percent, $min ){
	$max = [];
	$size = [];

	$ratio = 0;
	$max['long'] = 0;
	$max['short'] = 0;
	$size['short'] = 0;
	$size['long'] = 0;
	if (
		is_int( $long )
		&& is_int( $short )
	) {
		$ratio = ( $long / $short );
		$max['long'] = ( $long_max >= $long ) ? $long : $long_max;
		$max['short'] = ( $short_max >= ( $max['long'] / $ratio ) ) ? floor( $max['long'] / $ratio ) : $short_max;

		$size['short'] = round( $min + ( $percent * $ppp ) );
		$size['long'] = round( $size['short'] / ( $short / $long ) );
	}

	$ppp = ( $max['short'] - $min ) / 100;

	return $size;
}
```

I have no clue how or why that's happened, and it doesn't seem to have been made in this repo first. It should be this function here: https://github.com/Automattic/themes/blob/012258cc65cfdfc99bc32117ef951f2c9dbb7189/radcliffe-2/inc/logo-resizer.php#L96-L110

**Comment by TPilgs** [comment] 2023-12-04 17:32
7403245-zen Provided the user the CSS workaround for now, on the Business plan.

**Comment by ricklabsdotn8** [comment] 2023-12-05 14:34
7407757-zen

**Comment by OmarFPG** [comment] 2023-12-05 16:25
Another one 7408319-zen. Premium user so the CSS workaround was provided.

**Comment by jerren1327** [comment] 2023-12-06 09:17
7377334-zen

Personal plan, so no CSS workaround possible

**Comment by marutim** [comment] 2023-12-08 02:59
Another report here: 7422528-zen

Personal plan

**Comment by OgeAmadi** [comment] 2023-12-08 11:38
Another case here: 7423499-zen

_The user is on the Premium plan, so I sent the CSS workaround_

**Comment by Oriz-p** [comment] 2023-12-10 22:52
This another one - #7430407, the user is on Personal plan so no CSS custom code could be provided

**Comment by mreishus** [comment] 2023-12-13 18:04
This should be solved now.

> The problem seems to be that the SVN for WP.com has not been aligned with this repo. Instead, for `logo_awesomeness_min_max`, this has been registered.
> 
> 
> I have no clue how or why that's happened, and it doesn't seem to have been made in this repo first. It should be this function here:

Hey, thanks for tracking it down. This was related to some changes we made to solve division by 0 fatals, but there was bug in the change. I've moved the `$ppp` calculation to the correct location, which should fix this issue. ( D131923-code ). I'll update the copy in this repo to match, too.

**Comment by Aurorum** [comment] 2023-12-13 18:12
Thanks so much @mreishus! I'll update the users who didn't have access to the CSS workaround now.

Hey, while you're at it, would you mind syncing #7518 with SVN if you have a spare moment? It's already been approved and merged, but we've had a few users following up about when it'll be deployed.

**Comment by mreishus** [comment] 2023-12-14 16:20
There's also a duplicate of this issue here with its own interaction list: #7508.  @Aurorum , do you want any help following up with the non-workaround users?
I'll close this ticket since the issue is solved (if that's not right, let me know).

**Closed as completed by mreishus** 2023-12-14 16:20 UTC
Labels: [Type] Bug, Needs triage, [Interaction #] > 20, [Pri] TBD, Customer Report
