### ISSUE TITLE
Hever: Hyperlink hover color not using the color set on the block editor

### ISSUE THREAD

**Issue by ezebecke** [Automattic/themes#7797] opened 2024-05-13 16:41 UTC
### Quick summary

Changed hyperlink hover color on a text block doesn't show the color on the live site.

### Steps to reproduce

1- Activate Hever theme
2- Go to a page editor, add a paragraph with a hyperlink, and set a color for the hover.
3- Hover links shows fine on editor but not on published page. 

### What you expected to happen

Respect the hover color added on the editor.

### What actually happened

I believe the color for the hover is coming from the "Colors & Backgrounds" from the Customizer

### Browser

Google Chrome/Chromium

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

One

### Available workarounds?

Yes, easy to implement

### Workaround details

User CSS code to adjust the hyperlink color on a tags.

**Comment by CodeAllNightNDay** [comment] 2024-05-14 14:48
8189146-zd-a8c I have a user with a similar case, but it's happening on the Shawburn theme.

**Comment by CodeAllNightNDay** [comment] 2024-05-15 18:59
Same issue here: 8193815-zen

**Comment by rickmgithub** [comment] 2024-05-23 05:56
## 📌 REPRODUCTION RESULTS ##
- Tested on Atomic – Could Not Replicate

## 📌 ACTIONS ##
- Author feedback

## MESSAGE TO AUTHOR ##
Thanks so much for the report. I couldn't replicate the issue looking at the user's site but as there are other reports it feels like I'm missing something in the steps? Can you share some more details on how to replicate this, where they've set the colors etc? It looks like the colors on the public site match the global styles currently?

**Comment by liviopv** [comment] 2024-05-23 10:02
Similar report in https://github.com/Automattic/wp-calypso/issues/90725 I couldn't replicate as well.

@ezebecke @CodeAllNightNDay have you been able to reproduce this on a test site? If so, can you share the link here, please?

**Comment by ezebecke** [comment] 2024-05-25 18:01
@liviopv Not sure what has changed since the report, but I can not replicate it anymore.

**Comment by liviopv** [comment] 2024-05-28 11:22
@ezebecke I'm going to close this, then, but please reopen if needed.

**Closed as completed by liviopv** 2024-05-28 11:22 UTC
Labels: [Type] Bug, [Pri] Normal, Triaged, Customer Report, [Feature Group] Appearance & Themes
