### ISSUE TITLE
Twenty Twenty-Two (Mint) theme shows all images in black and white

### ISSUE THREAD

**Issue by tvolpert** [Automattic/themes#5602] opened 2022-02-10 20:24 UTC
### Quick summary

Any image added to a site using the Twenty Twenty-Two (Mint) theme has a black and white duotone filter applied. None of the other flavors of Twenty Twenty-Two seem to be affected.

IMPORTANT NOTE: This is NOT a bug of the theme, but rather an issue with Gutenberg.  See [this comment](https://github.com/Automattic/themes/issues/5602#issuecomment-1076072599) below.  

This issue will remain open for visibility until the Gutenberg issue has been addressed.

### Steps to reproduce

Activate the Twenty Twenty-Two (Mint) theme on a test site, and add an image or gallery block to any page or post. 

### What you expected to happen

The pictures should be shown in full color. 

### What actually happened

All images display with a Black and White duotone filter. Hitting "clear" from the Duotone button on the block toolbar does nothing.

### Context

User report: 34045134-hc

### Simple, Atomic or both?

Simple, Atomic

### Theme-specific issue?

Twenty Twenty Two (Mint)

### Browser, operating system and other notes

Chrome and Safari on MacOS.

Checking in dev tools, I can see the following from the theme's CSS:

```
.wp-block-image img {
    filter: var(--wp--preset--duotone--default-filter);
}
```

So the default duotone filter is being applied to all `img` elements whose parent belongs to the `wp-block-image` class –  which, as far as I know, is pretty much ALL images on a WP site. 

You can add a _different_ Duotone filter, and it will display properly, but if cleared, it will return to the black and white default

Adding a custom Duotone filter results in the following:

```
.wp-duotone-6202f37045d67 img {
    filter: url('#wp-duotone-6202f37045d67') !important;
}
```

So I think the first rule just needs to be deleted entirely? Or at least made overridable by the user, somehow. 

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

You can override the behavior with the following CSS snippet:
```
.wp-block-image img {
    filter: none!important;
}
```

Any custom duotone filters added by the user will have their own classes generated, so this doesn't affect that functionality.

**Comment by vipulpradhan** [comment] 2022-02-15 23:31
User report: 4782455-zen

Was able to reproduce this issue on 'Pink' version as well. Tested and confirmed that the main 'Twenty Twenty-Two' theme does not have the grayscale duotone effect as default.

Because the user is on Personal plan, I advised switching to the main 'Twenty Twenty-Two' theme while preserving their homepage content.

**Comment by formosattic** [comment] 2022-02-16 05:56
+1 4780109-zd-woothemes
Sent CSS workaround.

**Comment by jordesign** [comment] 2022-02-20 19:43
This probably needs to be transferred to the Themes GH repo - but I'm just pinging for a gut check.
p1645386161641019-slack-C029FM1EH

**Comment by danielk-am** [comment] 2022-02-23 05:39
Also encountered on 4786473-zen (Personal).

Suggested to the user to activate the main Twenty Twenty-Two theme, as the "Pink" version defaults to duotone on all images.

**Comment by carinapilar** [comment] 2022-02-25 12:40
I don't see any updates on the Slack thread mentioned above, so I'll share another report on 20512734-hc - user activated _Twenty Twenty-Two (Pink)_ and all images on the site turned into black and white. I recommended activating _Twenty Twenty-Two_ instead.

**Comment by KirkwallDay** [comment] 2022-03-06 20:15
Another report here: 4836332-zen this one is the (Mint) varient.

**Comment by metabreakr** [comment] 2022-03-11 17:32
This also affects Skatepark, reported here: https://wordpress.com/forums/topic/image-green-filter/?view=all

**Comment by supernovia** [comment] 2022-03-12 20:14
Noting re: Skatepark that even changing the site's default colors to something else keeps the duotone going in bright green.

**Comment by supernovia** [comment] 2022-03-12 23:07
We have another case in Twenty Twenty Two Mint: https://wordpress.com/forums/topic/customisation-16/

**Comment by mxhassani** [comment] 2022-03-15 20:31
Similar case here: 4863474-zen

Workaround provided:

```
body {
  --wp--preset--duotone--default-filter : none;
}
```

**Comment by jp-imagines** [comment] 2022-03-21 15:20
Another case in 4876729-zd-woothemes (using Twenty Twenty-Two (Pink)). Only seems to have affected the logo, so I provided this:

```
.wp-block-site-logo img {
    filter: unset;
}
```

**Comment by wiesenhauss** [comment] 2022-03-21 18:17
4880218-zen

Same issue on Twenty Twenty-Two (Swiss). The workaround provided by _tvolpert_ works there as well.

**Comment by xue28** [comment] 2022-03-22 06:02
4881833-zen

Another ticket here: Twenty Twenty-Two (Pink)

**Comment by khristiansnyder** [comment] 2022-03-23 06:59
Any updates? Have another user with the same issue on Twenty Twenty-Two (swiss). #34637558-hc
User would like an update if that does get resolved.

**Comment by madhusudhand** [comment] 2022-03-23 07:54
@kjellr Following themes has duotone filter applied to all images. figma designs also has duotone images for these. 
Can you suggest on this design change.

* twentytwentytwo-swiss
* twentytwentytwo-mint
* twentytwentytwo-pink

**Comment by MaggieCabrera** [comment] 2022-03-23 08:22
This is not a bug on the theme, this filter is intended for those variations. The existing bugs are on Gutenberg so that users will be able to disable the filter if they want to:

- https://github.com/WordPress/gutenberg/issues/38504
- https://github.com/WordPress/gutenberg/issues/34122

We can leave this issue open if it's helpful for HEs, but the themes are working as intended, if users don't want these filters, that option will come from GB when those issues are fixed.

**Comment by kjellr** [comment] 2022-03-23 13:38
That's correct, this is intended, and is shown on the theme demos and in the preview. For example: 

https://twentytwentytwomintdemo.wordpress.com
https://twentytwentytwoswissdemo.wordpress.com

As Maggie noted we're waiting for Gutenberg functionality that will allow folks to turn that off globally. And also there's a very confusing bug (https://github.com/WordPress/gutenberg/issues/35331) that doesn't apply duotone in the Site Editor, or in pattern previews.

**Comment by KokkieH** [comment] 2022-03-24 09:22
Noting https://wordpress.org/support/topic/disable-duotone-on-images/ (Skatepark) for follow-up once the issues in GB are fixed.

**Comment by supernovia** [comment] 2022-03-27 18:28
Noting this one for follow-up as well:
https://wordpress.com/forums/topic/twenty-twenty-two-theme/

**Comment by xue28** [comment] 2022-03-31 02:42
4908220-zen

Another ticket here: Twenty Twenty-Two (Pink)

**Comment by xue28** [comment] 2022-03-31 06:07
4908224-zen

Another ticket here: Skatepark

**Comment by jamiepalatnik** [comment] 2022-04-05 02:16
Another report: 4920631-zd-woothemes
Theme: Twenty Twenty-Two (Pink)

**Comment by yashitamittal11** [comment] 2022-04-08 05:27
Another report- #4931315-zen
Theme: Skatepark

**Comment by nerdysandy** [comment] 2022-04-08 18:16
Reported on 35093764-hc

Theme: Twenty Twenty-Two (Swiss)

**Comment by danielk-am** [comment] 2022-04-12 06:36
Another one 35043875-hc
Theme: Skatepark

Provided the "filter: none" CSS workaround to remove the tint.

**Comment by jromales** [comment] 2022-04-16 03:26
Another one here: 4951832-zd-woothemes 

Theme: Twenty Twenty-Two (Pink)

I shared CSS snippet as workaround fix

**Comment by supernovia** [comment] 2022-04-16 21:24
Since we aren't supposed to glomb onto Gutenberg github issues, we have another case here:
https://wordpress.com/forums/topic/duotone-remove-from-my-blog/

The CSS snippet won't work on free sites. Noting this case for followup.

**Comment by KokkieH** [comment] 2022-04-19 10:25
Another in https://wordpress.com/forums/topic/images-are-greyscale/ using Twenty Twenty-Two(Swiss)

Recommended they use Twenty Twenty-Two for now.

**Comment by KokkieH** [comment] 2022-04-21 10:11
https://wordpress.com/forums/topic/my-pictures-turn-black-and-white/ using Skatepark

**Comment by darnelldibbles** [comment] 2022-04-22 22:30
Another user from the thread above using Skatepark as well: https://wordpress.com/forums/topic/my-pictures-turn-black-and-white/?view=all#post-3816111

**Comment by xue28** [comment] 2022-04-25 02:14
Another ticket using Twenty Twenty-Two (Pink): 5164444-zen

I provided the CSS workaround

**Comment by hacchism** [comment] 2022-04-25 22:55
Another report using Twenty Twenty-Two (Swiss) - 35165819-hc

I provided the CSS workaround.

**Comment by KokkieH** [comment] 2022-04-26 06:48
https://wordpress.com/forums/topic/disabling-colours-on-images/?view=all - Skatepark

**Comment by KokkieH** [comment] 2022-04-27 05:53
https://wordpress.com/forums/topic/black-and-white/ - Twenty Twenty-Two (Pink)

**Comment by xue28** [comment] 2022-04-29 03:16
Another ticket using Skatepark: 4963423-zen

**Comment by KirkwallDay** [comment] 2022-05-01 14:16
Another instance here with Skatepark: 5182227-zen

**Comment by eduardozulian** [comment] 2022-05-01 14:50
Another in #5182227-zen. Filters are also affecting images under other blocks, like carousel, so I focused on the `img` tag instead:

```
img {
    filter: none !important;
}
```

But heads-up that this will affect all img tags on their site.

**Comment by ghost** [comment] 2022-05-03 06:09
Using Twenty Twenty-Two (Mint) theme user in hc-33386606 had the same issue.

Sent CSS workaround.

**Comment by danielk-am** [comment] 2022-05-04 01:10
One here 35360092-hc (Skatepark). Provided the CSS workaround. The user said that it was complicated. Suggested switching to another theme that does not have the duotone applied to images by default. The user decided to cancel the subscription and refund.

**Comment by donalirl** [comment] 2022-05-05 01:43
In #5191080-zen using Skatepark theme, the Duotone filter cannot be removed as the Customizer setting is missing.

**Comment by essleeung** [comment] 2022-05-13 07:50
5211150-zd-woothemes 
Another one here using Skatepark theme, can't remove Duotone filter and also can't give user CSS workaround as they are on a Personal plan.

**Comment by a4jp-com** [comment] 2022-05-13 08:59
I had the same problem. Is this a theme bug or WordPress bug? I also have the same problem with lots of other themes as well.

**Comment by a4jp-com** [comment] 2022-05-13 09:01
In the Skatepark theme you can clear the color but it doesn't save or change the CSS properly.

**Comment by ai2n** [comment] 2022-05-13 18:51
25243874-hc (Skatepark), used a CSS workaround

**Comment by ai2n** [comment] 2022-05-13 18:51
@a4jp-com see this comment, it's a Gutenberg bug: https://github.com/Automattic/themes/issues/5602#issuecomment-1076072599

**Comment by formosattic** [comment] 2022-05-14 00:37
+1 35486212-hc, CSS workaround worked.

**Comment by xue28** [comment] 2022-05-29 15:38
Another ticket using Skatepark: 5253740-zen. Free plan.

**Comment by KokkieH** [comment] 2022-05-30 10:20
https://wordpress.com/forums/topic/twenty-twenty-two-image-colours/?view=all

**Comment by syds87** [comment] 2022-05-31 17:22
Reported here as well: https://wordpress.com/it/forums/topic/immagini-12/?view=all

TwentyTwentytwo Pink - Free plan.

**Comment by ccwalburn** [comment] 2022-06-02 12:55
35690837-hc (Skatepark), used a CSS workaround

**Comment by xue28** [comment] 2022-06-10 01:46
Another ticket using Skatepark: 5285243-zen. Starter plan.

**Comment by xue28** [comment] 2022-06-14 03:36
Another ticket using Skatepark: 5294772-zen. Personal plan.

**Comment by tvolpert** [comment] 2022-06-14 15:43
Another case from 2022 Mint: 35726031-hc (and 35800836-hc, they got disconnected in between). In this case, we had already given them a CSS fix, and it stopped working (presumably after a theme update). The filter was now being applied to the `figure` and other parent elements of images, rather than the `img` itself. I initially provided the Snippet suggested by @mxhassani above, but apparently the Customizer will strip out variable declarations after saving? Or it did on this user's site, at least. I gave them this, instead:

```
/* Remove default gray duotone filter from entire site | 35800836-hc tcrv */
body .wp-block-site-logo ,
body .wp-block-post-featured-image , body .wp-block-image {
filter: none;
}
/* End | 35800836-hc tcrv */
```

**Comment by edwinho89** [comment] 2022-06-15 09:51
5295918-zd-woothemes applied this workaround provided in the earlier comments.

```
body {
  --wp--preset--duotone--default-filter : none;
}
```

**Comment by khristiansnyder** [comment] 2022-06-15 18:22
Came up again in Skatepark. User couldn't set their own duotone filters despite the preview looking okay.
35812565-hc

Gave CSS to fix: 

```
body {
  --wp--preset--duotone--default-filter : none;
}
```

**Comment by jerrysarcastic** [comment] 2022-06-15 21:57
Also reported in https://wordpress.com/forums/topic/color-16

Theme: Skatepark

Also gave CSS to fix

**Comment by Jaykame** [comment] 2022-06-16 01:35
Reported in 35539001-hc

Theme: Skatepark

Applied a CSS for workaround.

**Comment by rw-ye** [comment] 2022-06-20 00:35
User report: 5307216-zd-woothemes

Theme: Skatepark

Personal plan.

**Comment by KokkieH** [comment] 2022-06-22 09:03
https://wordpress.com/forums/topic/image-duatone-filter-not-working/

Skatepark

Free plan

**Comment by ClassicRKR27** [comment] 2022-06-23 14:56
- [ ] Another report here: [35883779-hc](https://hud.happychat.io/chat/35883779)

Applied CSS fix to resolve the issue

Skatepark

Pro Plan

**Comment by happychait** [comment] 2022-06-24 02:16
Another report in 5308136-zen

**Comment by devNigel** [comment] 2022-06-29 00:43
Another report: 35931018-hc

Skatepark 
Pro plan

Shared CSS fix.

**Comment by KokkieH** [comment] 2022-06-30 05:45
https://wordpress.com/forums/topic/black-and-white-images/?view=all

TT2 Mint

Free plan

**Comment by poeticabdul** [comment] 2022-07-05 11:39
>User from 35726031-hc and 35800836-hc came back. CSS shared with them didn't work. 

In this chat 35986447-hc, I shared this CSS code with them.

```/* Remove default gray duotone filter from entire site | 35986447-hc tcrv */

img {
    filter: none !important;
}
```

**Comment by Babylon1999** [comment] 2022-07-29 18:24
Another case here: 5433083-zd


I provided the CSS workaround.


Note:

I noticed that force switching to the black and white Dune tone in Gutenberg and removing it seems to fix this, I don't know what's triggering the problem thou so I'm not sure it will switch back in the future. Might be useful for non-CSS enabled sites.

**Comment by syds87** [comment] 2022-08-01 12:00
Another case reported here: 36256873-hc using Twenty Twenty-Two Mint. Solved with CSS workaround

**Comment by jamiepalatnik** [comment] 2022-08-09 15:06
Another report: 3547318-hc

Shared CSS workaround.

**Comment by ClassicRKR27** [comment] 2022-08-25 17:57
Another report for Skatepark: 36629405-hc

CSS workaround did the trick, user was happy with the result

**Comment by csonnek** [comment] 2022-10-03 15:48
Another report for Twenty Twenty-Two (Pink): https://wordpress.com/forums/topic/no-colour-on-images/?view=all

**Comment by kspilarski** [comment] 2022-10-17 08:01
Same case in 14062091-hc , Twenty Twenty Two Mint, free plan.

**Comment by cat-og** [comment] 2023-02-17 08:15
Same case with 5961209-zd , Twenty Twenty-Two (Pink), on the Personal Plan.

**Comment by MaggieCabrera** [comment] 2023-02-22 16:45
This will be solved once https://github.com/WordPress/gutenberg/pull/48255 merges; the users will be able to unset duotone from the affected blocks globally instead of one by one.

**Comment by MaggieCabrera** [comment] 2023-02-24 11:09
that PR got merged today and if everything goes according to plan it will make it to 15.3, feel free to close when that makes it to dotcom!

**Comment by jamiepalatnik** [comment] 2023-05-31 14:37
Tested this today related to a user report and it seems to be fixed now. It is probably OK to close and follow up with the affected users, but I'll leave this open for someone else to review to confirm.

**Comment by ianstewart** [comment] 2024-01-07 18:30
With no new reports I'm marking this as closed.

**Closed as completed by ianstewart** 2024-01-07 18:30 UTC
Labels: [Type] Bug, [Pri] High, [Theme] Skatepark, Triaged, [Theme] Twenty Twenty-Two, Editor issue, [Interaction #] > 20, Customer Report
