### ISSUE TITLE
Zaino: "Select Options" appears twice on this theme when WooCommerce is active.

### ISSUE THREAD

**Issue by arinoch** [Automattic/themes#7539] opened 2023-12-11 00:17 UTC
### Quick summary

On the shop page, the link to "select options" appears twice when using this theme and variants.

### Steps to reproduce

1. Create, or use existing, a site running WooComerce with products loaded.
2. Switch to Zaino or an equivalent theme.
3. Set your shop page to display products, no categories.

### What you expected to happen

The "select options" link should only appear once.

### What actually happened

It appears twice instead.

### Context

Reported in 7398919-ZEN, confirmed by me. It looks like potentially an ARIA issue.

### Platform (Simple, Atomic, or both?)

Atomic

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Possibly can hide one of the occurrences with CSS.

**Comment by TeniCola** [comment] 2023-12-13 20:05
Just an update that this user has returned to live chat to request an update. I've set expectations for them regarding the estimated time frame in 74479570-zen, if we would like to correspond with them there. Pinging @arinoch for awareness

**Comment by TeniCola** [comment] 2023-12-14 19:39
We've confirmed with Themes that this original issue was likely caused by a change in the user's template settings, rather than a theme bug. More details and threads can be found in the notes of 74479570-zen, and we can close this without changes.

**Closed as not planned by TeniCola** 2023-12-14 19:39 UTC
Labels: [Type] Bug, Needs triage, [Pri] TBD, Customer Report, [Feature Group] Appearance & Themes
