### ISSUE TITLE
Spearhead: Color issues with the WP.com homepage template

### ISSUE THREAD

**Issue by beafialho** [Automattic/themes#2655] opened 2020-10-21 14:59 UTC
As I began testing Spearhead on WordPress.com on Chrome, using the default WordPress.com homepage template, I noticed that there were some color issues:

— On the top of the page the background is dark grey, as below.

<img width="1788" alt="Captura de ecrã 2020-10-21, às 15 52 19" src="https://user-images.githubusercontent.com/65220155/96737409-8cf7f200-13b5-11eb-854f-bf55f90b6916.png">

— As I scroll, the background turns white and the text is also white.

<img width="1784" alt="Captura de ecrã 2020-10-21, às 15 47 56" src="https://user-images.githubusercontent.com/65220155/96737495-a4cf7600-13b5-11eb-9bec-3dee021cc27b.png">

— As I kept scrolling I noticed the "E-mail address" is very hard to read.

<img width="1788" alt="Captura de ecrã 2020-10-21, às 15 52 30" src="https://user-images.githubusercontent.com/65220155/96737804-f972f100-13b5-11eb-8897-dbd265cf9b50.png">

**Comment by jffng** [comment] 2020-10-27 15:53
@beafialho can you confirm that this bug was found in dark mode? 

I'm pretty sure this is same problem as #2644 — we can't update the editor palette based on dark/light mode preferences, and these layouts pull from the editor palette colors. 

Moving this to blocked until we can agree on a path forward there.

**Comment by pbking** [comment] 2021-01-25 17:08
I wasn't able to completely reproduce as seen.  The hard to read text is likely addressed by https://github.com/WordPress/gutenberg/pull/28233 though.  Unfortunately I wasn't able to verify that it will since I couldn't reproduce the colors seen.

**Comment by scruffian** [comment] 2021-01-26 12:58
This seems to be fixed. Closing. Feel free to reopen if there are still issues.

**Closed by scruffian** 2021-01-26 12:58 UTC
Labels: [Theme] Spearhead, [Type] Bug
