### ISSUE TITLE
Classic P2: Issues with posting comments and using the front-end editor

### ISSUE THREAD

**Issue by rantoncuadrado** [Automattic/themes#597] opened 2019-02-14 11:19 UTC
[Edited by @laurelfulford : note that this issue happens on other sites running p2 Classic; the number of comments does not affect it - more info in the comments]

## Steps to replicate

Comments are not nested in a post. Instead, each new comment is a 1st level one even if clicked to answer a previous comment. The comment field is shown to the end of the page.
I tried to create a second post, but the problem is still taking place. I left the post with 4 comments as a draft (It is called "nuevo post")
post: https://independeciacatalunya.com/2016/01/01/independencia-catalunya/comment-page-41
User said they changed nothing when this started to occur. There are lots of nested comments, but it started malfunctioning 2 days ago (12 Feb 2019)

Context.
https://independeciacatalunya.com/2016/01/01/independencia-catalunya/ in the ONLY post in this site. There are more than 5740 comments so far. 
DIscussion settings seem to be ok (Nested comments up to 10 levels, Break comments into pages...)
(See attached picture)

Actions carried out
I tested with other values in nested comments levels and in the comments pagination sizes with no luck.
I tested creating a new post with no comments, but the problem persisted.

I tested several other themes and the nested comments issue disappears. Heads up! The theme needs to allow to break comments in several pages (P2, the new, doesn't allow this and the page loading time is huge so it will not work). I tested Libre 2 Penscratch 2 and Twenty Nineteen

Next Steps
I told the user to 1) Consider creating several posts where to generate discussions from now on  2) Change the Theme they are using

## Expected

Comments should be nested even it a so big list of comments

* User report: #1800660-zen

**Comment by laurelfulford** [comment] 2019-02-15 18:02
This looks like this isn't specific to this site, as it's cropped up in another report here: p1550238085151500-slack-themes.

Both sites are currently throwing a JavaScript error for comment-reply.min.js, which was recently updated: r187351-wpcom.

**Comment by laurelfulford** [comment] 2019-02-15 20:10
Reverting the above change on my test site did stop the issue from happening. 

The error seems to be coming from this line:

`var supportsDataset = !! document.body.dataset;`

... because `document.body` from that script, when in P2, returns `null`.

 P2 Classic has the `comment-reply.js` enqueued in the `head`, before [the `body` is defined](https://stackoverflow.com/questions/9916747/why-is-document-body-null-in-my-javascript). This is different to where it's normally enqueued in other themes, further down the page.

This seems to be caused by `comment-reply.js` being listed as a dependency in p2/inc/js.php for another script loaded on `init`. Removing it there seems to fix it, but could cause other problems, since there's prooooobably a reason it needs to be available sooner for the theme's scripts 😕 I'll try to spin up a patch for this to see if we can change in the theme, but am not 100% sure, since P2 has a lot of other funky stuff going on.

**Comment by laurelfulford** [comment] 2019-02-15 21:33
This is going to take more work than I'd hoped 😕 the priority has been bumped, since it affects the theme's functionality pretty badly.

**Comment by KokkieH** [comment] 2019-02-17 17:40
Another report in https://en.forums.wordpress.com/topic/cannot-reply-on-a-submitted-comment/

Site: https://writingpractitioners.wordpress.com/

**Comment by laurelfulford** [comment] 2019-02-20 17:46
This should be fixed with r53399-wpcom-themes. 

I've added a comment to the original ZD ticket.

I will follow up in the forum thread!

**Closed by laurelfulford** 2019-02-20 17:46 UTC
Labels: [Pri] High, bug, needs patch, support

**Comment by KokkieH** [comment] 2019-02-21 06:41
Thank you for the forums follow-up, @laurelfulford!
