### ISSUE TITLE
Cubic: Centered Image Blocks are not centered. 

### ISSUE THREAD

**Issue by scosgro** [Automattic/themes#2223] opened 2020-07-03 23:23 UTC
## Steps to replicate

1. Activate Cubic
2. Create a Post. 
3. Add some text, then add an Image Block, center the image block, add some text underneath it. 
4. Publish the post. 

## Result

The centered image block appears left aligned, even further left than the paragraphs around it. 
![image](https://user-images.githubusercontent.com/30731356/86500857-fee5f600-bd48-11ea-9039-064b06a685b0.png)

## Expected

A centered image block to appear in the center. 

* User report: #17280877-hc

**Comment by nielslange** [comment] 2020-07-15 06:53
**Please leave this issue for training purposes.**

**Comment by Robertght** [comment] 2020-07-31 06:07
#3185879-zen

**Comment by davipontesblog** [comment] 2020-09-19 13:57
Closing this as a duplicate of https://github.com/Automattic/themes/issues/1504. Merged the comments there.

**Closed by davipontesblog** 2020-09-19 13:57 UTC
Labels: [Type] Bug, support
