### ISSUE TITLE
Apostrophe 2: Social Icons block in Footer Widget area is picking up list CSS, adding extra content

### ISSUE THREAD

**Issue by synora** [Automattic/themes#7062] opened 2023-05-08 10:01 UTC
### Quick summary

An extra character appears below certain icons in the Social Icons Block. This extra character isn't seen until the block is published.

This seems to be only affecting the Apostrophe 2 theme. The Social Icons block renders to the screen as expected on FSE themes like Adventurer.

### Steps to reproduce

1. Apply the Apostrophe 2 theme to a simple site. 
2. Navigate to Appearance > Widgets > Footer Sidebar and add the Social Icons Block
3. Insert the Mail, Instagram, Twitter, and Facebook icons and give their icons a name and link.
4. Notice how the icons appear as expected in the Widget editor and publish the changes. 
5. Visit the homepage and notice how an extra "|" character appears on a new line under the icon's name. 

### What you expected to happen

It was expected that the icon just have the name and link as it appears in the Widget editor: 

<img width="687" alt="Screen Shot on 2023-05-08 at 05-48-13" src="https://user-images.githubusercontent.com/10015451/236795555-705f448f-245c-488d-b71a-e2973dba1c77.png">

### What actually happened

An extra character appears under the Mail, Instagram, and Twitter icon names once published. Notice that the Facebook icon renders as expected:

<img width="652" alt="Screen Shot on 2023-05-08 at 05-49-25" src="https://user-images.githubusercontent.com/10015451/236795662-8bfdd470-7379-4112-b9ce-86f4348d0826.png">

We can discovered more helpful info within the browser inspector: 
<img width="1359" alt="Screen Shot on 2023-05-08 at 06-05-06" src="https://user-images.githubusercontent.com/10015451/236796929-91b8dbdc-5c69-4a4c-a8b1-587359d34105.png">

### Browser

Google Chrome/Chromium

### Context

Customer report and I replicated in testing.

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

Although not ideal, we can suggest users switch to a different theme.

**Comment by synora** [comment] 2023-05-08 10:21
User report: 6270553-zen

**Comment by karenroldan** [comment] 2023-05-08 12:26
📌 REPRODUCTION RESULTS

- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO

- Replicated exactly as described. The last item from the social icons doesn't have the extra character. 

![Screenshot 2023-05-08 at 14 12 51](https://user-images.githubusercontent.com/67279475/236823223-8de09f4f-23e5-40b5-86e9-b5415f64c1a8.png)

![Screenshot 2023-05-08 at 14 10 23](https://user-images.githubusercontent.com/67279475/236823238-2bd746f9-21b9-4ab8-af4f-9f8d2ce74a89.png)

📌 ACTIONS

- Assigned to Themes

**Comment by synora** [comment] 2023-06-02 10:22
Hi @karenroldan and @cuemarie can we get an update on when this will be looked into? The issue is still ongoing.

**Comment by cuemarie** [comment] 2023-06-06 17:00
Hey @synora ! This is on the Themes team's triage board for further review, but given the low impact here, I don't expect it to be prioritized over other issues in their inbox. I took another look, and here's some additional details that might be of use for the themes team or users still impacted by this:

The issue stems from this CSS:

```
.site-footer .widget-area li::after {
  content: "|";
  display: inline;
  padding-left: 10px;
}
``` 

Which means the issue is specific to widgets added to the site's footer only.  It's possible that problem is related to this larger issue in core: 

- https://github.com/WordPress/gutenberg/issues/50486

### Workarounds

- Placing the social icons somewhere else, such as the Primary sidebar

![Markup on 2023-06-06 at 09:58:04](https://github.com/Automattic/themes/assets/27249804/7934a795-eaf4-48e9-ac1b-a2f71409a2a6)

- Using CSS to remove the added content:

```
.site-footer .widget-area li:after {
    display: none;
}
```

- Using the theme's built-in social menu instead

![Markup on 2023-06-06 at 09:49:08](https://github.com/Automattic/themes/assets/27249804/568131b8-f01d-42e3-a97f-68e7a8d22bbf)

Hope this helps in the meantime!

**Comment by synora** [comment] 2023-06-07 17:01
Hi @cuemarie!

Thank you! These workarounds are helpful. The first and third ones should work out as they're on the free plan.

**Closed as completed** 2023-12-04 19:49 UTC
Labels: [Type] Bug, [Pri] Low, Triaged, [Theme] Apostrophe 2, Themes
