### ISSUE TITLE
Assembler Theme is Stretching Radio Buttons At Run-Time

### ISSUE THREAD

**Issue by MikeoMattic** [Automattic/themes#8407] opened 2024-11-11 16:54 UTC
### Quick summary

I encountered a user who was having an issue with the radio buttons they had added to their site.  While editing the page the radio buttons appear normally. During run-time the buttons stretch out vertically. I spun up a business plan test site with no plugins, created a page, and added buttons and experienced the same thing.

Link to theme:  https://wordpress.com/theme/assembler

Link to test form created to show stretched buttons:  https://breakfixtestsitemikem.wordpress.com/centered-heading-with-contact-form/

### Steps to reproduce

1. Create business plan test site
2. Install and activate Assembler Theme
3. Create simple page with radio buttons
4. Publish page and visit

Image of radio buttons in editor:
![Image](https://github.com/user-attachments/assets/9671472c-c824-4efe-8c32-0e64b04f4d97)

Image of radio buttons at run-time:
![Image](https://github.com/user-attachments/assets/f1a28eb9-4c06-43cf-bacd-a7becb6065be)

### A clear and concise description of what you expected to happen.

Expected the radio buttons to resemble their appearance in the editor.

### What actually happened

The radio buttons are stretched vertically.

### Impact

One

### Available workarounds?

Yes, difficult to implement

### If the above answer is "Yes...", outline the workaround.

Changing the theme fixes the issue but the user is nearly done with the site and does not want to start over.

**Comment by richtabor** [comment] 2024-11-11 17:19
Duplicate of https://github.com/Automattic/themes/issues/7959

**Closed as completed by richtabor** 2024-11-11 17:19 UTC
Labels: [Type] Bug, [Pri] Normal, Needs triage, [Feature Group] Appearance & Themes, [Theme] Assembler
