### ISSUE TITLE
Varia themes: Default text Color inside the Cover Block is not the same in the editor and the front-end

### ISSUE THREAD

**Issue by AtrumGeost** [Automattic/themes#4993] opened 2021-11-04 16:30 UTC
## Steps to replicate

1. Activate the Hever theme and select the option to replace the Home page
2. Open the new Home page in the editor
3. Notice the color of the text inside the Cover block (white)
4. Notice the color on the actual site (black)

## Result

![Screen Shot on 2021-11-04 at 11-29-21](https://user-images.githubusercontent.com/3696121/140379726-8d0e405b-aed4-4bf5-b336-623847b2608b.png)

## Expected

To have the same color as in the editor:

![Screen Shot on 2021-11-04 at 11:30:11](https://user-images.githubusercontent.com/3696121/140379844-be99a981-da16-42d4-bbe8-2dd2a700dd18.png)

* User report: 4429491-zd-woothemes

**Comment by dcoleonline** [comment] 2021-11-04 18:15
Also in 4424948-zen

We should update them once this is resolved. For now, I've manually set the color option in the editor to override this issue.

**Comment by AtrumGeost** [comment] 2021-11-13 14:45
Another report here:

4452487-zd-woothemes

**Comment by jordesign** [comment] 2021-11-16 20:06
With some testing I've been able to narrow down this issue a little more. It appears to happen in the Varia parent theme and all child themes. (all I tested anyway).

The issue is that the default text color for content within Cover blocks (and others as well like Form blocks) isn't matching between editor and front-end preview.

Case (you can check Pdw1nU-d-p2 for testing):

Editor (default text appears white):

<img width="1368" alt="Screen Shot 2021-11-17 at 6 57 48 am" src="https://user-images.githubusercontent.com/1842363/142056730-8ff10058-1854-44ed-9359-2886d046692b.png">

Front End (default text appears dark):
<img width="1186" alt="Screen Shot 2021-11-17 at 6 58 49 am" src="https://user-images.githubusercontent.com/1842363/142056833-a90413bc-78dc-4cc5-be03-d9f77674fd46.png">

----

For bonus weirdness I made some changes to the colors in the customizer - and they had unexpected effects on the color pallet in the editor and the front end.

Customizer change (changing default text color to light green):
This changed text colors even when other colors had already been specifically applied (using color presets in the editor)

<img width="1474" alt="Screen Shot 2021-11-17 at 7 00 08 am" src="https://user-images.githubusercontent.com/1842363/142057219-f4e2a8ef-3111-4f6b-8a18-3592f9fe16d4.png">

In the Editor:

<img width="1735" alt="Screen Shot 2021-11-17 at 7 00 55 am" src="https://user-images.githubusercontent.com/1842363/142057485-9061105d-d4ba-4721-9c98-cac5f63a39e4.png">

----

Noting that the match of color labels between Customizer and Editor (and the fact they are in different positions) are:

Background > Background
Text Color > Foreground
Link Color > Primary
Secondary > Secondary

**Comment by jordesign** [comment] 2021-11-16 20:07
As this appears to be affecting all Varia themes - I'm raising it as high priority.

**Comment by jordesign** [comment] 2021-11-16 20:17
Could this be related to the introduction of Opacity for background colors in Gutenberg 11.8?
https://github.com/WordPress/gutenberg/pull/35065

**Comment by mrsjaved** [comment] 2021-11-17 12:05
Another report here 18999453-hc
Follow-up ticket: 4462522-zd-woothemes user wants to receive an update when the issue is resolved.

**Comment by AtrumGeost** [comment] 2021-11-17 20:21
Another report here: 4463353-zd-woothemes

**Comment by mrsjaved** [comment] 2021-11-18 11:45
Another report here: 4063903-hc

**Comment by jartes** [comment] 2021-11-19 11:22
Another one on 30758439-hc

Did some CSS for them to fix colors manually.

**Comment by ccwalburn** [comment] 2021-11-19 15:33
Another report here: 32814121-hc
Had them manually set the color in the editor

**Comment by vinnykaur** [comment] 2021-11-20 05:12
One more - 4531506-zd
Had to set the color manually from the block settings.

**Comment by vinnykaur** [comment] 2021-11-20 05:32
4462244-zd 
Had them set the color manually from the block settings.

**Comment by csonnek** [comment] 2021-11-22 18:24
Also in https://wordpress.com/forums/topic/letters-turned-from-white-to-black-on-my-theme/

**Comment by AtrumGeost** [comment] 2021-11-23 16:16
Another report here 4534534-zd-woothemes

**Comment by kriskorn** [comment] 2021-11-29 07:54
Another report here: 28882174-hc
Had them manually set the color in the editor.

**Comment by ghost** [comment] 2021-12-07 18:40
Another report here: 4575897-zd-woothemes 
Asked them to manually set the color in the editor
Stow theme

**Comment by jackiejade** [comment] 2021-12-07 20:51
Another report: 30891016-hc

Manually switching the color in the editor fixed the issue.

**Comment by jartes** [comment] 2021-12-13 12:00
Another one on: 33146819-hc

Indicated to set the color manually.

**Comment by ai2n** [comment] 2021-12-15 02:14
I think another related one in: 4613234-zen

It seems they somehow were able to solve it in between the time I pushed to ticket and followed up with them, but I suggested a manual workaround just in case.

**Comment by scruffian** [comment] 2021-12-20 09:32
This should have been fixed by #5212

**Closed as completed** 2021-12-20 10:00 UTC
Labels: [Type] Bug, [Pri] High, [Theme] Varia, [Theme] Hever, Triaged
