### ISSUE TITLE
Rockfield: setting border color to the pre-defined color doesn't reflect on the frontend

### ISSUE THREAD

**Issue by liviopv** [Automattic/themes#6899] opened 2023-03-12 18:16 UTC
### Quick summary

![CleanShot 2023-03-12 at 18 15 53@2x](https://user-images.githubusercontent.com/14153300/224564209-b754a153-a01a-4e22-bb95-8dfaddad414f.png)

### Steps to reproduce

1. Add a block to a page with a Border option, like the Columns Block
2. Set the border color to a color predefined on My Sites > Appearance > Customize > Colors
3. The color will be applied in the editor, but not on the frontend

### What you expected to happen

The colors in the front end should be the same as the ones in the editor.

### What actually happened

On the front end, the border displays with the base text color.

### Browser

Google Chrome/Chromium

### Context

Customer report

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

**Comment by kavyagokul** [comment] 2023-03-16 10:02
📌 SCRUBBING : RESULT
- Tested on Simple - Replicated
- Tested on AT - Replicated 
- Tested on Self-hosted - Replicated 
- Replicable on Core - Yes

📌 ACTIONS
- Closed as duplicate of https://github.com/Automattic/wp-calypso/issues/69025

**Closed as completed by kavyagokul** 2023-03-16 10:02 UTC
Labels: [Type] Bug, Triaged, [Status] Duplicate
