### ISSUE TITLE
Lodestar: Blog Page's featured image is ignored in favour of site header image

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/themes#226] opened 2018-08-13 13:34 UTC
## Steps to replicate

The user has configured their site with a static homepage. There is a header image in place, too.

![](http://cld.wthms.co/sPkzrl+)

Their latest posts page is titled "Blog". The user has set a different image as Blog's featured image to the header image.

![](http://cld.wthms.co/DzLBci+)

They noticed that the site doesn't display Blog's featured image when viewing the Blog page. Instead, the site displays the header image.

Other pages are displayed with their respective featured images. This issue only affects the latest posts page, namely the Blog page.

Is this related to how a page acting as the latest posts page is handled by WordPress, compared to "normal" pages?

## Result

I suggested that the user remove the header image, but when they did this, the Blog page didn't display a featured image at all.

![](http://cld.wthms.co/3Y5bPz+)

## Expected

I expected the site to display the Blog page's featured image when one is set in the editor. At the very least, if the header image is overriding the Blog page's featured image, removing the header image should re-enable the Blog page's featured image.

* User report: 3271141-hc
* Follow-up ticket: 1344066-zen
* User's site: https://wildanimalwelfare.com/blog/

**Comment by kristenzuck** [comment] 2018-08-22 16:31
Reported by another user here as well 1364256-zen

**Comment by laurelfulford** [comment] 2018-08-22 19:14
This is working as designed: like a lot of themes, Lodestar treats the blog index like it does any other archive page. You can't customize the title, and content you add to the page itself won't show up. It also won't use the featured image that's assigned to the blog posts page. 

That being said, I don't think adding this functionality will break anything -- the one issue I can think of would be if someone using the theme unknowingly has a featured image assigned to their blog post page, and it suddenly starts being used. In that vein, I'm going to switch this to an 'enhancement' -- I'd really appreciate a second opinion on the add, too!

**Comment by alaczek** [comment] 2018-09-06 04:55
Looks like it's the same issue as in #251 

I agree with Laurel here - the page assigned to serve as blog index is a placeholder page, and not displaying it's content, author, comments, featured image etc. is expected. I'm not against making it work that way though.

**Comment by nielslange** [comment] 2020-02-11 10:28
Closed due to inactivity as discussed in https://github.com/Automattic/themes/issues/927#issuecomment-584184883

**Closed by nielslange** 2020-02-11 10:28 UTC
Labels: [Pri] Low, [Status] Needs Patch, [Type] Enhancement, support
