### ISSUE TITLE
Twenty Twenty-one free banner hides mobile menu

### ISSUE THREAD

**Issue by fstath** [Automattic/themes#3593] opened 2021-03-31 11:55 UTC
## Steps to replicate

Load on a mobile device a free WordPress.com site with the Twenty Twenty-one theme that has a menu.

## Result

The mobile menu button is not shown because of the top banner that's displayed on free WordPress.com sites.

## Expected

For the mobile menu to be displayed.

* User report: https://wordpress.com/forums/topic/mobile-view-23/

**Comment by fstath** [comment] 2021-04-05 08:35
Another report here: https://wordpress.com/forums/topic/wordpress-advertisement-is-blocking-my-menu-2/

**Comment by darcie** [comment] 2021-04-09 04:00
This is also reported here: https://github.com/Automattic/wp-calypso/issues/51060

**Comment by fresatomica** [comment] 2021-04-28 12:02
Another report here: https://wordpress.com/forums/topic/i-cannot-see-the-primary-navigation-menu-on-mobile-view-on-my-phone/.

The issue seems to be isolated to browsers based on Chromium. 
I can't reproduce this on Firefox.

**Comment by KokkieH** [comment] 2021-05-10 04:40
Another report in https://wordpress.com/forums/topic/marketing-bar-prevents-use-of-hamburger-menu-on-mobiles/

**Comment by KokkieH** [comment] 2021-05-11 05:41
Another in https://wordpress.com/forums/topic/wordpress-twenty-twenty-one-theme-cover-block-mobile-issue/

**Comment by fstath** [comment] 2021-05-19 11:56
Another report in #4001599-zen

**Comment by DanielSmithMichigan** [comment] 2021-06-01 17:03
The banner at the top is called the "marketing bar."

It looks like when the marketing bar is loaded, some CSS files are loaded with it. Those CSS files [give the root 'HTML' element a margin](https://user-images.githubusercontent.com/10274366/120362267-e2479a80-c2d8-11eb-91f1-4c50b5a2e079.png). This margin isn't respected by the menu, because it is positioned absolutely:

```
position: absolute;
top: var(--global--admin-bar--height);
right: 0;
```

The issue might be either:

- Just that we need to add a margin for the navbar to the CSS file mentioned above
- The `--global--admin-bar--height` variable above, which is evaluating to 0px, maybe it should evaluate to 46px in this situation

**Comment by DanielSmithMichigan** [comment] 2021-06-02 22:38
I found a better place for the code change, which is in the core-themes-compat code in wpcom.

I created differential D62228-code to show the change that I'm thinking about. Some details may change, such as the selector or the styling, but I will probably put the change into this file.

**Comment by kwight** [comment] 2021-06-09 21:32
Fixed by @DanielSmithMichigan in D62228-code.

**Closed as completed by kwight** 2021-06-09 21:32 UTC
Labels: [Type] Bug, [Pri] Normal, [Theme] Twenty Twenty-One, [Pod] Design Selection

**Comment by KokkieH** [comment] 2021-06-10 04:03
Thank you! I've followed up with the users who reported the issue to let them know.
