### ISSUE TITLE
Twenty Sixteen: Add Styling for Blog Subscription Widget Title

### ISSUE THREAD

**Issue by juliasydnor** [Automattic/themes#436] opened 2018-12-18 11:28 UTC
## Description

The Blog Subscription widget title appears as a `<label>` without the `widget-title` class, which means all the normal widget title styling doesn't get applied to it. We have to send custom CSS to users to fix this, but that can't be done on the Free or Personal plans.

## Steps to replicate

1. Go to My Site > Customize > Widgets.
2. Add a Blog Subscription widget to any widget area.
3. Click Publish. 

## Result

The widget title (label) does not look like other widget titles on the site.

<img width="332" alt="screenshot at dec 18 11-24-23" src="https://user-images.githubusercontent.com/29981758/50150991-90049180-02b7-11e9-8ce9-1892e3222e95.png">

I sent the user this custom CSS to resolve it (fonts will vary per site, depending on what's being used in the Customizer):

```
/*--- style subscription widget title to match other widget titles / 1649273-zen JS ---*/
.widget_blog_subscription label {
	font-family: "calluna-1","calluna-2",serif;
    font-style: normal;
    font-weight: 400;
	font-size: 1.4em;
	line-height: .046875em;
	text-transform: uppercase;
}
#subscribe-blog {
	margin-top: 1.3125em;
}
```

## Expected

I expected the widget title (label) to look like other widget titles on the site.

* User report: #1649273-zen
* User's site: https://againorway.com/ (first widget in sidebar)

**Comment by laurelfulford** [comment] 2018-12-18 22:21
Thanks for the report, @juliasydnor! It looks like this was caused by a change to the widget itself that removed the title tags. 

I've reported this here: 8124-wpcom. 

I'm going to close this ticket, since it's not theme-specific.

**Closed by laurelfulford** 2018-12-18 22:21 UTC
Labels: bug, support

**Comment by laurelfulford** [comment] 2018-12-18 22:23
Added a comment to the ZD ticket pointing to the new report.

**Comment by laurelfulford** [comment] 2018-12-18 22:50
And it turns out this was already fixed :) Will follow up again in the ZD ticket, and remove the Custom CSS fix!
