### ISSUE TITLE
Theme: Twenty Twenty-Two, Archeo, Pendant - Simple sites missing Featured Image function

### ISSUE THREAD

**Issue by sophiegyo** [Automattic/themes#6194] opened 2022-07-12 15:01 UTC
### Quick summary

Featured Image function is missing in the block editor, for pages, posts and custom post types like Jetpack portfolio. 

**NOTE:** I also reliably replicated this with Archeo theme and Pendant theme on a Simple site.
*I don't know if there are other FSE themes which don't include it.*

Affects:

**SIMPLE sites only, with theme Twenty Twenty-Two active.**
*Could not replicate on self-hosted, or Atomic, with or without the Gutenberg plugin active, while still using Twenty Twenty-Two.*

I'm pretty sure this is a bug, not a feature. The theme showcase page for Twenty Twenty-Two mentions featured images:
https://wordpress.com/theme/twentytwentytwo

### Steps to reproduce

1. Start at any Simple wpcom site URL
2. Activate theme Twenty Twenty-Two
3. Try to add a new page, post, portfolio project, testimonial
4. Try to add a featured image to your post

### What you expected to happen

The post/page/portfolio project/testimonial should have an option to add a featured image.

### What actually happened

No option appears:
<img width="1301" alt="image" src="https://user-images.githubusercontent.com/36608681/178518220-ccae3a12-1f3d-451b-a5bd-9060145b6e07.png">

Also missing 'Featured Image' panel from editor preferences:
<img width="953" alt="image" src="https://user-images.githubusercontent.com/36608681/178518540-91f7a6fa-da5a-4b48-919c-2faba12af812.png">

The option to add a Featured Image is just flat out not there.
No errors in the browser console. It's just not added in.

### Context

Customer report - 36047244-hc and follow-up 5367728-zen

### Simple, Atomic or both?

Simple

### Theme-specific issue?

Twenty Twenty-Two
Archeo
Pendant

I haven't found any others so far.

### Browser, operating system and other notes

Firefox v 102 on Mac OS 11.6 
Chrome 103.0 on Mac OS X 10.15.7 

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

No but the platform is still usable

### Workaround details

The only workaround I can find is to change theme.

**Comment by Joshgrygiel** [comment] 2022-07-12 16:33
📌 SCRUBBING
- Tested on P2 - N/A
- Tested on Simple ✅ 
- Tested on AT ✅ 
- Tested on Self-hosted ✅ 
- Replicable on Core - No

📌 FINDINGS/SCREENSHOTS/VIDEO
- I can confirm while having Twenty Twenty-Two, Archeo, or Pendant active on a simple site, there is no option to set a featured image for any taxonomy type:

![tttsimplenofeaturedimage](https://user-images.githubusercontent.com/88345647/178544676-bc975f34-ee65-481d-9d2b-fd920893dd44.png)

- I further tested on Self Hosted/AT and the option to add a featured image is displayed as normal:
![atfeaturedimage](https://user-images.githubusercontent.com/88345647/178544912-7b397d4f-906c-487a-ad0f-3979d9b8e6bd.png)

- Definitely appears to be a bug as I'd expect the Featured Image option to be apparent regardless of whether the site is AT/Simple/SH.  


📌 ACTIONS
- Marked as Triaged for Quality Squad review
- Transferred to Themes

**Comment by Robertght** [comment] 2022-07-13 05:28
I believe this might be a combo between Jetpack's Portfolio post type and the themes, but I cannot pinpoint if that's changed in a recent Jetpack update or not.

cc @jeherve or @karenalma

**Comment by sophiegyo** [comment] 2022-07-13 06:46
I was wondering if that was the case too, but it doesn't make sense to me that *some* FSE themes don't show the Featured Image function, but others do - I didn't look at all of them but to compare, Meraki, Antonia, and Heiwa are all FSE themes and work just fine.

Could it be that the other two I saw are based off of Twenty Twenty-Two framework (I know they're not child themes, but I assume there has to be a link between them), while the ones which do work are based off of, say, Blockbase or Blank Canvas (which also have the Featured Image function working correctly on Simple)?

**Comment by jeherve** [comment] 2022-07-13 13:39
Interestingly, I cannot seem to reproduce on a simple site with Twenty Twenty Two right now. I do however use the wp-admin editor. I wonder if the problem may be limited to the iFramed editor in Calypso? Do you still miss the Featured Image panel when trying to create a new post in `wp-admin/post-new.php`?

**Comment by sophiegyo** [comment] 2022-07-14 09:16
> Interestingly, I cannot seem to reproduce on a simple site with Twenty Twenty Two right now. I do however use the wp-admin editor. I wonder if the problem may be limited to the iFramed editor in Calypso? Do you still miss the Featured Image panel when trying to create a new post in `wp-admin/post-new.php`?

Decidedly yes for me with pages:

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/36608681/178948066-ac275320-6fe4-4bea-9c95-830237605844.png">

With posts it's fine:

<img width="1293" alt="image" src="https://user-images.githubusercontent.com/36608681/178948260-fbc6ff6c-6dbd-4ad9-a360-17be279a8630.png">

Edit:

Portfolios also have the same issue for me:

<img width="1313" alt="image" src="https://user-images.githubusercontent.com/36608681/178948590-14391ad1-0c5c-4966-bcc3-8dd5cbf002ad.png">

**Comment by jeherve** [comment] 2022-07-14 15:33
Ah, thank you. I can reproduce on the page editor as well. For some reason, on WordPress.com something seems to change the response from the `themes` endpoint to indicate that Twenty Twenty Two only supports `post-thumbnails` for posts:

<img width="922" alt="image" src="https://user-images.githubusercontent.com/426388/178987631-158a2d82-4a87-456e-96c9-6cf2f51b8e40.png">

On self-hosted sites, it just returns `true`, and thus post thumbnails are available for all post types:

<img width="1243" alt="image" src="https://user-images.githubusercontent.com/426388/178987804-b3c37348-639c-4cc8-9b9d-b2f330c66a5b.png">

I'm not quite sure how block themes declare support for featured images, so I don't know where WordPress.com would overwrite that response. This may be a good question for someone working on Gutenberg, or on Gutenberg's integration on WordPress.com? @ebinnion Would you know who to ping about this?

**Comment by sophiegyo** [comment] 2022-07-18 08:01
- [ ] Just noting another case from 5349934-zen

This user uses Twenty Twenty Two for almost all of their sites. Please can we update them when this issue is resolved (added by @pauljacobson )

**Comment by happychait** [comment] 2022-08-19 01:55
Pendant theme doesn't have the option to set featured images for pages, but allows featured images for posts.

- [ ] 36530753-zen

**Comment by noahtallen** [comment] 2022-08-25 01:14
The root cause is that the way theme support for this feature is added by core WordPress is incompatible with the way our public-api setup works. (Hence the problem only happens on simple sites, where the public-api exists.) For some context, `post-thumbnails` support is automatically added by core WordPress for any block-based theme as part of the `setup-theme` action.

More info here as we explore possible workarounds: https://github.com/Automattic/wp-calypso/issues/65895#issuecomment-1226610626

**Comment by noahtallen** [comment] 2022-08-26 22:10
This issue should be resolved in production 👍 (Fix: D86721-code)

**Closed as completed by noahtallen** 2022-08-26 22:10 UTC
Labels: [Type] Bug, [Pri] High, Triaged, Themes
