### ISSUE TITLE
All Themes: Color customization changes didn’t reflect on live site until Palette is chosen

### ISSUE THREAD

**Issue by retnonindya** [Automattic/themes#2360] opened 2020-08-15 12:31 UTC
I unable to replicate this on my test site, but I received a user report -- and I able to replicate it on the user's site. On this case, Barnsbury theme.

## How to replicate

1. Activate Barnsbury theme with static homepage (presumed using default page Home that created as the theme is activated.)
2. Go to Customize > Colors & Backgrounds. Change the colors on the color options/circles accordingly.
3. Click 'Save Changes'.

## What I expect
The color changes saved and reflected properly on the live site

## What happened instead
The colors are still using Barnsbury's default color scheme (green and cream)

## Workaround (sort of...?)
I found that the expected change happened if we are using this flow:

1. Noticed the colors didn't change
2. Go to Customize > Colors & Backgrounds
3. Click the available palette on the 'Choose a palette' option.
4. Click 'Save changes'

_Then_, the colors are saved.

I'm not sure what happened and why we need to 'kickstart' it from palette -- and I unable to replicate it on my test site. 

I hope this is the correct GH repo. Feel free to transfer this issue to its appropriate repo if this is not the correct place. Thank you.

Reference: Since this is user report, I can't provide the direct link. Feel free to ping me if you need more details. Thanks!

**Update:** other [workaround suggested](https://github.com/Automattic/themes/issues/2360#issuecomment-677795001), to reset the colors cache, add `?clear-colors-cache=1` to the end of their wordpress site URL, ie `https://USERSITENAME.wordpress.com/?clear-colors-cache=1`

**Comment by ktyfuller604** [comment] 2020-08-17 19:37
Another report using the Barnsbury theme.

I also noticed if you edit text on a page, and change the color of the text to one of the new "default" colors, the color used is one of the theme colors. But, if you use a custom color, it works fine. 

To reproduce - 
Follow the same steps to set custom colors in the original report. 

1. Edit any page or post, and select a header block. 
2. Edit the color of the text to one of the custom colors that appear. 
3. Preview page - note that the theme's default color gets applied. 

Applying the workaround worked for fixing that example as well. 

I was also able to reproduce the issue using the Exford theme.

**Comment by JoshuaGoode** [comment] 2020-08-18 15:35
Encountered this with the Balasana theme on 22818168-hc

The custom colors were working in the customizer preview and the block editor -- but not the front end.

We discussed a bit in slack on p1597762340405000-slack-C03TY6J1A

@davipontesblog set the colors to default and then changed them back to resolve initially.

User returned later saying they were back to the default on the front end.

I did the following to help get it to stick.

1. Asked the user to leave the customizer
2. Selected a featured palette and saved instead of setting it back to default
3. Set the colors back to their custom colors and saved 

This appears to have made it stick.  The user could have had an older instance of the Customizer open or it could have been due to the default palette.

**Comment by brookewp** [comment] 2020-08-19 21:22
Ran into another instance with Barnsbury: zd-3228309

**Comment by brookewp** [comment] 2020-08-19 21:49
And another for Balsana: zd-3225366

**Comment by brookewp** [comment] 2020-08-19 22:25
Another for Balsana: zd-3191855

**Comment by allancole** [comment] 2020-08-20 17:21
Hi all, yes this is a known issue. 
We haven’t found an all-encompassing fix yet, but the short cut to fixing this for users who report it is to reset the colors cache. 

You can do so by adding `?clear-colors-cache=1` to the end of their wordpress site URL, ie: 

`https://USERSITENAME.wordpress.com/?clear-colors-cache=1`

**Comment by joweber123** [comment] 2020-08-26 03:27
Another report here for Balasana: 8299656-hc

**Comment by devNigel** [comment] 2020-09-03 04:11
Ran into this issue on Barnsbury theme: zd-3282285

Followed the workaround mentioned to fix it.

**Comment by poojashetty18** [comment] 2020-09-09 08:16
Another report here for Balasana: zd-3299762

**Comment by TeniCola** [comment] 2020-09-10 21:40
Another report for the Brompton theme: zd-3305400

I was able to follow the workaround to help assist the user.

**Comment by retnonindya** [comment] 2020-09-14 06:28
Two more reports: 
zd-3313145
zd-3313616

**Comment by ahmadbaig1** [comment] 2020-09-16 19:03
Something like this happened here as well-
zd-3291895

I re-applied the link colors from Customizer and it fixed it for me.

**Comment by carinapilar** [comment] 2020-09-17 19:19
I had a user with the same issue on hc-24211215. They use the Exford theme, on top of not seeing the chosen colors from the Customizer on the site, the Button block also wasn't showing the selected background colors set in the editor.

The user complained that 2 of their buttons on the front page were in a different color, which was correct when editing the page, but not on the site. Even after changing the button's background color multiple times, it seems it wasn't being applied to the page's code. I manually added the style to the page's code, then it saved, although we had to use `?clear-colors-cache` to be able to see it on the site.

I also wasn't able to replicate on a test site - I'm afraid it might be somehow related to this cache thing.

**Comment by formosattic** [comment] 2020-09-18 03:12
Another report in 23694557-hc

**Comment by sanjeev00733** [comment] 2020-09-18 04:04
Another report in #8869730-hc

**Comment by mikeicode** [comment] 2020-09-19 16:31
Another 3329520-zen

**Comment by Nic-Sevic** [comment] 2020-09-20 06:06
Another with the Redhill theme #3318365-zen

**Comment by lakellie** [comment] 2020-09-20 15:54
Similar report in #3329520-zen
In this case, the colors were actually showing on the live site, but the editor was still showing the default colors. Choosing a palette and then re-selecting the custom colors fixed the editor.

**Comment by chrisfromthelc** [comment] 2020-09-20 23:03
Another report in #23304656-hc

**Comment by serabi** [comment] 2020-09-22 12:26
Another report in 24017955-zen. In this case, the colors were showing in the editor, but not on the live site.

**Comment by serabi** [comment] 2020-09-22 21:39
Reported in 3324926-zen. I flushed the color cache and that worked.

**Comment by carinapilar** [comment] 2020-09-23 12:32
I'm not sure if it's related to this issue, but I got another user complaining that the colors on buttons weren't working on the live site, with what they selected in the editor, and it was working a while ago, so I wonder if this issue is somehow related to the recent color changes. It was on the Obsidian theme though. I reported on its Trac, link is on the chat's note: 24328471-hc

**Comment by benchilcote** [comment] 2020-10-05 16:50
Another case 3376768-zen.  Flushing color cache worked

**Comment by ianstewart** [comment] 2020-10-08 21:01
I was able to replicate this with Seedlet today. I expect it's happening on all themes. Not just Varia-based ones.

cc @jeffikus @kathrynwp

**Comment by kristarella** [comment] 2020-10-13 23:37
> We haven’t found an all-encompassing fix yet, but the short cut to fixing this for users who report it is to reset the colors cache.
> 
> You can do so by adding `?clear-colors-cache=1` to the end of their wordpress site URL, ie:
> 
> `https://USERSITENAME.wordpress.com/?clear-colors-cache=1`

This didn't work for me using Barnsbury on site beyourownsenseicom.wordpress.com

**Comment by RafaelFunchal** [comment] 2020-10-15 13:18
Another report for Barnsbury here: 3363804-zen

**Comment by mikeicode** [comment] 2020-10-15 17:20
Another on Exford  23201526-hc

**Comment by mikeicode** [comment] 2020-10-16 15:59
Another Balasana 24810681-hc

**Comment by ccwalburn** [comment] 2020-10-20 20:53
I had a report for Redhill here: 3423640-zen

I could replicate on my test site with Redhill and found that if I selected a palette and reset the custom color in the Customizer, it would fix the color in the editor, but the front end would go back to the default. If I cleared the color cache, it would fix the front end, but the editor would go back to the default. So, I was unable to find a workaround for Redhill.

**Comment by KristinaKay** [comment] 2020-10-22 19:27
Another issue for Maywood here: 25082939-hc

/?clear-colors-cache=1 fixed it.

**Comment by samiff** [comment] 2020-11-06 20:17
Another report for Barnsbury in 25381420-hc

**Comment by retnonindya** [comment] 2020-11-10 01:11
Report for Exford in 22299341-hc. The previous HE changed one of the colors and changed it back again then saved the changes.

**Comment by mikeicode** [comment] 2020-11-13 13:10
Used `?clear-colors-cache=1` to resolve the lower semicircle on the Brompton theme being the incorrect color:

https://github.com/Automattic/themes/issues/2800#issuecomment-726697155

**Comment by ktyfuller604** [comment] 2020-11-13 21:09
Report for Mayland in #9590470-hc

Used `?clear-colors-cache=1` to resolve the issue

**Comment by iamgabrielma** [comment] 2020-11-14 18:16
Another one on 3487742-zen (Theme: Exford)

`?clear-colors-cache=1` fixed the problem

**Comment by nagpai** [comment] 2020-11-16 06:05
Another report #25389206-hc (Barnsbury)

?clear-colors-cache=1 fixed the problem

**Comment by carinapilar** [comment] 2020-11-16 18:27
Another report on #25294999-hc (Brompton)

`?clear-colors-cache` fixed the problem

**Comment by separatelyunited** [comment] 2020-11-19 19:17
Received a report of this from a user with Coutoire. I could not replicate on my own site and changing the colors and saving again did not work but using `?clear-colors-cache=1` did the trick.

#3500939-zen

**Comment by kristarella** [comment] 2020-11-19 22:34
Everyone is saying `?clear-colors-cache=1` worked for them, but it won't for me. Am I doing it wrong?
I've tried on both beyourownsenseicom.wordpress.com/?clear-colors-cache=1 and beyourownsensei.com/?clear-colors-cache=1

**Comment by ktyfuller604** [comment] 2020-11-23 13:55
Theme: Balasana
Report: #3497042-zen
`?clear-colors-cache=1` resolved the issue.

**Comment by rinazrina** [comment] 2020-11-28 14:16
Theme: Mayland
Report: #3523893-zen
`?clear-colors-cache=1` resolved the issue.

**Comment by aamills** [comment] 2020-11-30 19:01
Theme: Coutoire
Report: 22017747-hc
Set a palette then custom colors again and it worked as expected.

**Comment by jamiepalatnik** [comment] 2020-12-03 23:46
I noticed that this is affecting the Cover block too—if you try to choose a solid color and choose one of the theme color options, the color will display correctly in the editor but show the default colors on the live site.

`?clear-colors-cache=1` resolves the issue on my simple site, but not on my AT site.

As a workaround for the Cover block issue, if you click the custom color link and choose a custom color for the Cover block background color instead of one of the colors from the theme palette, it will display as expected.

**Comment by KristinaKay** [comment] 2020-12-06 18:22
Another report here: #3548573-zen

I was able to fix by choosing a palette first then changing to the user's custom colors.

**Comment by kspilarski** [comment] 2020-12-08 20:54
- Theme: Maywood
- ?clear-colors-cache=1 did not work
- 3556582-zd

**Comment by TeniCola** [comment] 2020-12-10 22:41
Another report in #3564333-zen, Exford theme

We originally tried to fix it with CSS. When the user returned, I adjust the pallete first and then changed it back to the user's preferred colors, and that did the trick.

**Comment by ccwalburn** [comment] 2020-12-15 15:14
Another report here: 26357727-hc
Theme: Brompton

`?clear-colors-cache=1` fixes it on the front end, but not in the editor.

**Comment by jerrysarcastic** [comment] 2020-12-16 23:36
I've been seeing this in the forums as well.  Here are a few recent ones:

- https://wordpress.com/forums/topic/changing-colors-in-maywood-theme-2/
- https://wordpress.com/forums/topic/colors-keep-going-back-to-default/
- https://wordpress.com/forums/topic/theme-background-color-isnt-changing/
- https://wordpress.com/forums/topic/background-colora

For the first 3, I did not know about the `?clear-colors-cache=1` trick, so i entered the customizer, tweaked some small setting (to force the customizer to show the save button) and that fixed it

For the last post, `?clear-colors-cache=1` worked to show the custom colors

**Comment by philnick206** [comment] 2020-12-28 13:44
Another report here: #3601486-zen
Theme: Coutoire

**Comment by shohanhossainnab** [comment] 2020-12-30 14:42
The workarounds suggested here didn't work for this user #3601486-zen

**Comment by dolgelukkig** [comment] 2020-12-31 08:27
Another report: [#3595881-zen](https://woothemes.zendesk.com/agent/tickets/3595881)
Theme Redhill

**Comment by rinazrina** [comment] 2021-01-04 04:06
Another report: #24554670-hc
Clearing color cache helped. 
Theme: Alves

**Comment by selectedselections** [comment] 2021-01-06 19:35
I came across this today for Balsana 

#26826377-hc
Clearing color cache resolved.

**Comment by retnonindya** [comment] 2021-01-11 05:46
Barnsbury

#26917646-hc

Clearing color cache resolved the issue.

**Comment by alevarsir** [comment] 2021-01-14 14:18
Barnsbury

#27002900-hc

?clear-colors-cache=1 solved the issue.

**Comment by ivan-ottinger** [comment] 2021-01-14 14:50
Just noting here that in the 27002900-hc case (mentioned in the previous comment), the `?clear-colors-cache=1` initially solved the issue, but then the site title was still showing up in the original green color. → CSS workaround helped.

**Comment by scruffian** [comment] 2021-01-15 15:25
This issue is very hard to replicate. We've deployed some code that we hope will fix it in D55359. If you still notice issues please reopen this issue. Thank you for all the reports.

**Comment by nerdysandy** [comment] 2021-01-18 18:04
Ran into this on Exford theme. #27074082-hc

Cleared cache with `?clear-colors-cache=1` to fix the issue.

**Comment by melek** [comment] 2021-01-19 00:25
Ran into this again, also on the Exford theme: #27100398-hc, a followup from @nerdysandy's report above.

Clearing the color cache with `?clear-colors-cache=1` did not work for me. In Slack it was reported to have worked earlier in the day, but the the user got back in touch and the problem was still there (or had returned).

I directed the user to change their Color palette, correct the colors, and save changes. That worked for them across the site.

**Comment by annbingle** [comment] 2021-01-20 21:04
Another report from the user here 27148213-hc but the workaround works for now.

**Comment by nicelyj2** [comment] 2021-01-22 21:55
Another report from the user in HC 27199789, using Redhill theme. `clear-colors-cache=1` workaround was successful.

**Comment by kathrynwp** [comment] 2021-01-24 16:10
Another issue with Balasana. Fixed with color-cache query string.

25891447-hc

**Comment by inaikem** [comment] 2021-01-25 03:47
Another issue, this time with Redhill. Clearing cache in BRC and using the colour-cache query string did not help. Added a space to the site title fixed the issue.

H/T @katiebethbrown

**Comment by lakellie** [comment] 2021-01-25 16:57
Another report: 26409169-hc

**Comment by katiebethbrown** [comment] 2021-01-26 21:04
Report in 10959553-hc

Color cache clear with `?clear-colors-cache=1` seemed to have no impact. Made a change in the customizer, saved, then removed the change and saved again and the site shows the correct colors now.

**Comment by joweber123** [comment] 2021-01-28 23:09
Another report here 27345551-hc

**Comment by joweber123** [comment] 2021-01-29 03:07
Another report 26151308-hc

**Comment by jamiepalatnik** [comment] 2021-01-29 20:57
Another report in 4431940-hc
?clear-colors-cache=1 workaround resolved the issue.

**Comment by happychait** [comment] 2021-01-29 21:05
Another report in 27155088-hc

Worked around with the /?clear-colors-cache=1 URL.

**Comment by tanjoymor** [comment] 2021-01-29 22:16
Another report here: 27369245-hc

**Comment by felipevelzani** [comment] 2021-01-30 20:08
Another report: 21675342-hc (follow-up 3689794-zen)

**Comment by xpurichan** [comment] 2021-01-31 21:04
Another report in 27407533-hc.

**Comment by pauloeaquino** [comment] 2021-02-01 06:32
Another report in 27218065-hc (Exford theme)

**Comment by erricgunawan** [comment] 2021-02-02 08:19
Another report: 27439501-hc (Leven theme). Using `?clear-colors-cache=1` workaround worked.

**Comment by zdenys** [comment] 2021-02-02 14:44
Another case in 3703638-zen. I suggested the workaround to see if it helps.

**Comment by khristiansnyder** [comment] 2021-02-02 19:20
Another case in 27384640-hc

**Comment by mikeicode** [comment] 2021-02-03 12:28
Another Exford: 25405114-hc

`?clear-colors-cache=1` didn't work, adding an extra space character in the Site Title and saving did.

**Comment by thehenrybyrd** [comment] 2021-02-03 13:58
Again in 27479552-hc

**Comment by scruffian** [comment] 2021-02-03 16:03
Ok, I've had another go at fixing this in D566401-code. I'll close this again, but if you see more issues please reopen.

**Comment by donalirl** [comment] 2021-02-04 01:41
This came up just now on the Bromptom theme in #27494766-hc. Using ?clear-colors-cache made the correct colors appear on the site.

**Comment by rinazrina** [comment] 2021-02-05 13:47
Another one #3713890-zen
`?clear-colors-cache=1` worked

Theme: Mayland

**Comment by scruffian** [comment] 2021-02-05 16:38
Ok, I really think this time it is solved (in D56574-code). Of course reopen if its still broken :)

**Closed by scruffian** 2021-02-05 16:38 UTC
Labels: Involves Happiness, [Pri] Normal, [Theme] Varia, [Type] Bug
