### ISSUE TITLE
Button 2: Infinite Scroll button style not displaying correctly

### ISSUE THREAD

**Issue by kathrynwp** [Automattic/themes#518] opened 2019-01-27 20:11 UTC
## Steps to replicate

- Activate Button 2 on an Atomic site
- In Jetpack > Settings > Writing, in the Infinite Scroll section, select "Load more posts in page with a button" and save changes.
- Publish more than 10 posts

## Result

- Visit blog page and scroll to end of the posts
- Look at the Infinite Scroll button:

![can be bribed with food page 2 a blog about a passion for food and a passion for sharing that passion-1](https://user-images.githubusercontent.com/7662449/51806137-2081aa80-2244-11e9-99ae-95606e0eb712.jpg)

- Visible on https://canbebribedwithfood.blog – but note that I gave the user custom CSS to work around the issue for now.

## Expected

Infinite Scroll button should match the Button 2 button style, as seen on a WordPress.com Simple site:

![test test](https://user-images.githubusercontent.com/7662449/51806147-3d1de280-2244-11e9-81aa-a1f33ff40a7f.jpg)

## Other Themes

I tested half a dozen themes, and was able to replicate in the [Natural](https://wordpress.com/theme/natural) premium theme from WP.com:

![blog - trfit supplmenentos](https://user-images.githubusercontent.com/7662449/51806155-5b83de00-2244-11e9-824a-c4017845c7e5.jpg)

I was **not** able to replicate in:
- Storefront
- Aquene
- Twenty Seventeen
- Twenty Sixteen
- Penscratch 2

##Jetpack

I noticed this CSS coming from version 6.9 of Jetpack, at `css/jetpack.css`:

```
#infinite-handle span {
    background: #333;
    border-radius: 1px;
    color: #eee;
    cursor: pointer;
    font-size: 13px;
    padding: 6px 16px;
}
```

I wonder if a recent change in Jetpack is causing this issue in certain themes. That said, I was **not** able to reproduce this site on a localhost install with Button 2 and Jetpack 6.9.

* Follow-up ticket: 1752694-zd

**Comment by laurelfulford** [comment] 2019-02-05 16:06
Doubling back to this, I'm unable to reproduce this in Button 2 or Natural -- I wonder if it got changed back in Jetpack 7.0?

@kathrynwp can you please double-check, and see if you're still seeing this?

**Comment by laurelfulford** [comment] 2019-02-08 18:26
I've double-checked again, the button is now displaying as expected on both WordPress.com and self-hosted sites. I've also verified this on the user's site.

I'm going to close this one as it seems to have been resolved in Jetpack, but we can always reopen if the issue reoccurs.

**Comment by laurelfulford** [comment] 2019-02-08 18:28
Nope, wait, I am seeing this on AT sites, just not on WP.com sites.

**Comment by laurelfulford** [comment] 2019-02-08 18:40
I think the issue may be how the styles are loaded on AT sites.

All of the Jetpack CSS is being concatenated into one file, which is enqueued after the theme's styles:

![image](https://user-images.githubusercontent.com/177561/52498457-b47d3b80-2b8d-11e9-8f08-8ac4201847d9.png)

Whereas on WordPress.com, the CSS is separate, and the infinity.css is enqueued before the theme's CSS:

![image](https://user-images.githubusercontent.com/177561/52498530-ec847e80-2b8d-11e9-96a4-e25cb41829aa.png)

**Comment by laurelfulford** [comment] 2019-02-08 18:52
The former seems to be the norm for self-hosted sites -- I think having `JETPACK_DEV_DEBUG` set to true on my localhost may be overriding it.

**Closed** 2019-02-08 19:35 UTC
Labels: [Pri] Normal, bug, needs author reply, needs patch, support

**Comment by laurelfulford** [comment] 2019-02-08 19:37
I confirmed that this is not new behaviour (p1549653466261100-slack-jetpack)so likely something that snuck under the radar for a while, since it doesn't affect WP.com simple sites.

I've committed a fix in r53322-wpcom-themes; that should be synced to this site next week.
