### ISSUE TITLE
Twenty Twenty One: Block Pattern "Alternating images with titles" doesn't apply custom link colors from the editor

### ISSUE THREAD

**Issue by dcoleonline** [Automattic/themes#4622] opened 2021-09-15 23:51 UTC
## Steps to replicate

1. Apply the Twenty Twenty One theme to a simple site on WordPress.com 
2. Create a blank page
3. Add the `Alternating images with titles` block pattern to the page
4. In one of the Header blocks that comes with the pattern, add a link to some text.
5. In that Header block's settings, set a custom link color
6. In the editor, you'll see the link color applied
7. Publish the page and the link color will not be applied

## Result

The link color was not applied to the published page.

## Expected

The link color should have been applied to the published page.

## Screenshots

Editor:

![image](https://user-images.githubusercontent.com/3505172/133527288-9455e164-fe84-41fa-b0b3-5733ef7590ad.png)

Published view with code inspector: 
![image](https://user-images.githubusercontent.com/3505172/133527233-dfef6386-ce7b-453d-b484-95bee3cbcfd8.png)

## Additional notes:

I tested this same content on multiple themes on WordPress.com and the red text showed on those themes. Twenty Twenty One is the only theme that I could not get to work. 

In the user report below, I supplied a temporary workaround using CSS, but not everyone will have access to this option.

* User report: [31672237-hc]
* Follow-up ticket: [4298720-zen]

We should notify the customer once this is resolved.

**Comment by jordesign** [comment] 2021-12-21 20:28
Interestingly - for me the same issue occured in the editor as well - regardless of the color selected as the 'Link color' of the heading block - it showed as black

<img width="1236" alt="Screen Shot 2021-12-22 at 7 27 12 am" src="https://user-images.githubusercontent.com/1842363/146993380-b9160817-c61a-4b5e-b4fc-363cb1a480b2.png">

**Comment by scruffian** [comment] 2021-12-22 15:49
The problem is that the link color is also being set on the group at a higher level. I think it would be good to improve the pattern so that the text color is set on the group rather than on the heading block. The specific issue mentioned here is a Gutenberg issue - I created an issue for it in the Gutenberg repo: https://github.com/WordPress/gutenberg/issues/37582.

I have also updated the pattern itself so that the colors are set on the group block, which should avoid this problem in the future. I think we can close this one.

**Closed as completed by scruffian** 2021-12-22 15:49 UTC
Labels: [Type] Bug, [Pri] Normal, [Theme] Twenty Twenty-One, Triaged
