### ISSUE TITLE
Geologist: Headings and titles barely visible in the editor, wrong font color being applied

### ISSUE THREAD

**Issue by jp-imagines** [Automattic/themes#7636] opened 2024-02-05 15:22 UTC
### Quick summary

On at least a couple of the Geologist theme's default styles, headings appear as dark gray on a dark gray background in the editor, making them nearly invisible and difficult to edit. On the live site, headings use a different font color and are clearly legible.

### Steps to reproduce

1. Activate the Geologist theme. (In screenshots below, I'm using the second style preset, "Charcoal." A similar issue occurs with the "Default" preset as well.)
2. Open the editor for a post or page – both the post/page editor or the Site Editor should be affected.
3. View the post/page's title. Note its color.
4. Add a Heading block. Note its color as well.
5. Preview the post/page. Note the title and heading colors.

### What you expected to happen

Title & heading color in the editor should match what is seen on the live site. Titles and headings should be legible in the editor.

### What actually happened

In the editor, titles and headings use a different font color, and can be very difficult (or nearly impossible) to read.

![Al9EVT.png](https://github.com/Automattic/themes/assets/5630717/1536bc1e-820f-480e-9b78-fe1021f406e3)

Page preview:
![xLjypk.png](https://github.com/Automattic/themes/assets/5630717/d8bc0860-b250-427b-abb6-f8874a856f75)

### Context

7693894-zd-a8c

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

Only tested on Simple so far. Unsure if other themes are affected as well. 

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

Disable "use theme styles" setting in the editor preferences (kebab menu > Preferences > Appearance).

**Comment by Aurorum** [comment] 2024-02-10 19:58
7696950-zen

**Comment by marutim** [comment] 2024-02-15 06:45
Another report here: 7742672-zen

**Comment by alaczek** [comment] 2024-08-27 04:10
I can't reproduce this anymore, might have been due to an editor issue that got fixed in the meantime. I will be closing this one, but feel free to reopen if I missed something, or it pops up again.

Editor:

![Image](https://github.com/user-attachments/assets/3f4057a8-0c57-4f30-92ee-844e796e3a3a)



Preview:


![Image](https://github.com/user-attachments/assets/39c13126-851f-4f6b-9183-248780776f5e)

**Closed as completed by alaczek** 2024-08-27 04:10 UTC
Labels: [Type] Bug, [Pri] Normal, Triaged, Customer Report, [Feature Group] Appearance & Themes
