### ISSUE TITLE
Dara: Full Width, No Sidebar template not applyting correctly in pages other than the homepage

### ISSUE THREAD

**Issue by mxhassani** [Automattic/themes#7828] opened 2024-05-24 13:25 UTC
### Quick summary

The template effectively removes the sidebar in all pages, but it applies the full-width style on the homepage only, not other pages.

Homepage with the template "Full Width, No Sidebar":

![image](https://github.com/Automattic/themes/assets/81776920/094af038-a47b-4788-9bce-dc187775e8fb)

Another page with the same template:
![image](https://github.com/Automattic/themes/assets/81776920/46cc0143-6cac-4fdb-bf6f-24a63401731c)

### Steps to reproduce

1. Activate Dara theme
2. Create a new page
3. Add random text to a paragraph block 
4. Give the block a background color
5. Save
6. Check the width of the paragraph block on the published page.
7. Now, to set the page as the homepage, go to Customizer > Homepage Settings >  A static page > Select your page > Save
8. Visit the page again, the width of the block is bigger now. 

### What you expected to happen

To have the full width appearance visible on all pages with that template, instead of just the homepage.

### What actually happened

The full width applies only if the page has that template and is set as the homepage.

### Context

8229334-zen

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Other notes

There seem to be other related reports:
* https://github.com/Automattic/themes/issues/2268
* https://github.com/Automattic/themes/issues/6247

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

```
/* Force pages with full-width template to be in full-width */
.content-wrapper.full-width.with-featured-image, .content-wrapper.full-width.without-featured-image {
  margin: 0;
  padding: 1.6em 55px 3.2em;
}
```

**Comment by liviopv** [comment] 2024-05-28 11:00
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO
The "Full Width, No Sidebar" template is designed to take 73% of the max width (1180px) on Dara, while the front page template doesn't have any limitation.

It's by design as seen in the screenshot included for the template in the showcase: https://wordpress.com/theme/dara.

Note that the width in the "Full Width, No Sidebar" template actually increases by adding a Featured Image, so that might be a good alternative for your customer @mxhassani. Another alternative might be moving to Shawburn https://shawburndemo.wordpress.com/ for more control over template widths.

📌 ACTIONS
- Closed by design

**Closed as completed by liviopv** 2024-05-28 11:00 UTC
Labels: [Type] Bug, Triaged, [Pri] TBD, Customer Report, [Feature Group] Appearance & Themes
