### ISSUE TITLE
Radcliffe 2: contact information not displaying on mobile

### ISSUE THREAD

**Issue by ariel-maidana** [Automattic/themes#7755] opened 2024-04-20 14:30 UTC
### Quick summary

On sites with the Radcliffe 2 theme active, contact information does not appear on the header on mobile devices.

### Steps to reproduce

1. Activate Radcliffe 2.
2. Add contact information (Appearance ---> Customize ---> Contact info). Fill in address, phone, and email.
3. Choose to display in the header.
4. Save the settings.
5. Visit the site from a mobile device.

### What you expected to happen

Contact information should appear at the top of the site header, like it does on the desktop.

### What actually happened

Contact information is not showing.

### Context

Customer report: 8068856-zen

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

Might be related to this other issue: https://github.com/Automattic/themes/issues/7744
8068856-zen reported both issues together.

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

None

**Comment by vinnykaur** [comment] 2024-04-22 10:19
8061784-zd-a8c

**Comment by rickmgithub** [comment] 2024-04-24 11:48
## 📌 REPRODUCTION RESULTS ##
- Tested on Atomic – Replicated / Could Not Replicate / Uncertain 

## 📌 FINDINGS/SCREENSHOTS/VIDEO ##
Replicated. This is how to see how to test this and the effect it has.


https://github.com/Automattic/themes/assets/13706336/f0687b77-0cb5-4b1a-8a81-3f6692ea21ed


## 📌 ACTIONS ##
Triaged

**Comment by alaczek** [comment] 2024-07-16 05:06
This theme is quite old, but from what I remember the expected behaviour is to minimize the contact info to the icon only on mobile (tapping the icon performs associated action - open maps, open email app, or call). I tried it just now, and it is indeed how it worked for me (and this is how the [demo site](https://radcliffe2demo.wordpress.com/) behaves too)

These icons (without the associated text) is the expected bahavior on mobile:
![Image](https://github.com/user-attachments/assets/9fcb68c8-23c5-402e-8d82-c22502550646)

But the video from @rickmgithub doesn't have the icons - do you have a link to that site or can you still replicate so that I can investigate more?

**Comment by lsl** [comment] 2024-07-26 02:50
Duplicate of https://github.com/Automattic/themes/issues/7711 - svg icons being hidden, already fixed by @miksansegundo https://github.com/Automattic/themes/issues/7711#issuecomment-2079808269

**Closed as completed by lsl** 2024-07-26 02:50 UTC
Labels: [Type] Bug, [Pri] High, Triaged, [Status] Priority Review Triggered, Customer Report, [Feature Group] Appearance & Themes
