### ISSUE TITLE
AltoFocus: Blog Posts Block Headings don't respond to Type Scale Setting

### ISSUE THREAD

**Issue by ccwalburn** [Automattic/themes#2482] opened 2020-09-18 21:52 UTC
The Blog Posts block Type Scale setting changes the font size while in the editor, but when viewed on the front-end, it only changes the excerpt size. The heading size stays the same regardless of the Type Scale setting.

## Steps to replicate

1. Activate Alto Focus theme
2. Create new Post
3. Add Blog Posts block
4. Set to **Grid View**
5. Ensure **Show Featured Image** and **Show Excerpt** toggles are on
6. Change **Type Scale** setting to 1
7. Publish post and view it

## Result

The post looks like this:

![screenshot](https://d.pr/i/jO6bWq+)
Image URL: https://d.pr/i/jO6bWq

## Expected

I expected it to look like it does in the editor:

![screenshot](https://d.pr/i/yJuh03+)
Image URL: https://d.pr/i/yJuh03

* User report: #3313351-zd

**Comment by MaggieCabrera** [comment] 2020-11-05 10:18
I could not reproduce this as the screenshots. 

I did found however the way the block handles the font scaling to be problematic since it's using em units and the editor will look different if the body base font size is different to the frontend.

In any way this is not a matter related to the theme, but the block.

**Comment by MaggieCabrera** [comment] 2020-11-05 10:32
Reported this here: https://github.com/Automattic/newspack-blocks/issues/620

**Comment by scruffian** [comment] 2020-12-09 14:00
Since this is an issue in the Newspack block, I'm going to close this issue.

**Closed by scruffian** 2020-12-09 14:00 UTC
Labels: Newspack, [Block] Blog Posts, [Pri] Normal, [Type] Bug, support
