### ISSUE TITLE
Twenty Twenty: Font Annotation Bugged

### ISSUE THREAD

**Issue by sdixon194** [Automattic/themes#1712] opened 2019-12-17 19:28 UTC
On Twenty Twenty, when using a custom font in the header, the font type (bold, italic, etc) gets applied to all text on the site, not just heading.

## Steps to replicate

1. Open the customizer
2. Set a custom header font
3. Change font type (italicized, font weight, etc)

## Result

The font type (italicized, font weight, etc) changes for all the text on the site, instead of just the heading.

## Expected

Only the header font type to change. 

##Screenshare

![Screen Capture on 2019-12-17 at 14-07-05](https://user-images.githubusercontent.com/33553323/71027515-699b5100-20d9-11ea-9b76-0510236c03af.gif)

#2566091-zen

**Comment by nielslange** [comment] 2019-12-22 01:19
@sdixon194 Shouldn't this issue be reported on https://core.trac.wordpress.org/ instead of on https://github.com/Automattic/themes/issues/? After all, it's not a free WordPress.com theme but a bundled core theme.

**Comment by KokkieH** [comment] 2020-01-06 06:27
Adding here as it's likely related:

For the base font, "Normal" comes in at 21px font size. "Small" come in at 27.3px font size, which is in fact bigger than the normal setting.

Reproduced in FF and Chrome.

Reported in https://en.forums.wordpress.com/topic/2020-theme/

**Comment by KokkieH** [comment] 2020-01-06 06:30
And with headings, "Normal" is 64px, with "Large" being only 47px and "Huge" only 58px, both smaller than "Normal"

**Comment by matiasbenedetto** [comment] 2021-12-15 21:29
I'm not able to reproduce the original problem described by this issue:

https://user-images.githubusercontent.com/1310626/146267682-6f00c1a7-089d-41d3-b748-b8826172d9da.mp4

**Comment by MaggieCabrera** [comment] 2021-12-16 09:01
I think this one was fixed when https://github.com/Automattic/themes/issues/2814 was fixed. I'm closing this but please feel free to reopen if this issue persists

**Closed by MaggieCabrera** 2021-12-16 09:01 UTC
Labels: [Type] Bug
