### ISSUE TITLE
Twenty Ninteen: Misaligned text input in Comment reply box

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/themes#445] opened 2018-12-20 06:40 UTC
## Steps to replicate

According to the user who reported this:

>There is another Twenty Nineteen bug that I forgot to report with the comment form when replying to comments on a post / page where the Comment Here Text and your reply starts in the middle of the comment form and not the top, and this only happens in the comment form when replying to a comment but not in the comment form when commenting on the post / page itself

## Result

![twentynineteen_theme_issue_comment](https://user-images.githubusercontent.com/2912202/50268077-18a73d00-0432-11e9-9a9b-1b1c65e92af9.jpg)

## Expected

Replies should start at the top of the text input box.

* User report: 1653241-zen
* User's site: https://johnjronline.wordpress.com/2018/12/15/the-prophecy-ii-7-8-movie-clip-how-does-this-work-1998-hd/

**Comment by laurelfulford** [comment] 2018-12-29 00:53
Thanks for the report, @pauljacobson!

I'm not able to recreate this -- I tried in Safari, Chrome and Firefox. 

![image](https://user-images.githubusercontent.com/177561/50531574-0cba1b80-0ac1-11e9-9dda-f985a6262d2a.png)

I'm wondering if it was fixed since the original report -- can you still recreate this, and if so, is it in a specific browser?

**Comment by goodjohnjr** [comment] 2018-12-29 06:08
> Thanks for the report, @pauljacobson!
> 
> I'm not able to recreate this -- I tried in Safari, Chrome and Firefox.
> 
> ![image](https://user-images.githubusercontent.com/177561/50531574-0cba1b80-0ac1-11e9-9dda-f985a6262d2a.png)
> 
> I'm wondering if it was fixed since the original report -- can you still recreate this, and if so, is it in a specific browser?

Hello Laurelfulford,

You can reproduce this issue by trying to reply to a comment that was already made on a post / page; it does not happen when you are making a new comment, it happens when replying to an already made comment. ;)

Thank you,
-John Jr

**Comment by laurelfulford** [comment] 2018-12-29 19:47
D'oh! Thanks @goodjohnjr -- that was in the issue description, too, and I somehow completely missed it.

I can see the issue now - thank you for the reply!

**Comment by goodjohnjr** [comment] 2018-12-29 19:56
> D'oh! Thanks @goodjohnjr -- that was in the issue description, too, and I somehow completely missed it.
> 
> I can see the issue now - thank you for the reply!

Great, you are welcome, and thank you Laurelfulford. ;)

-John Jr

**Comment by laurelfulford** [comment] 2019-01-03 23:41
This should be fixed in r52758-wpcom-themes!

**Closed by laurelfulford** 2019-01-03 23:41 UTC
Labels: bug, needs patch, support
