### ISSUE TITLE
[Livro]: Page Break block does not work

### ISSUE THREAD

**Issue by AnjanaV93** [Automattic/themes#7441] opened 2023-10-23 06:44 UTC
### Quick summary

[Page Break Block](https://wordpress.com/support/wordpress-editor/blocks/page-break-block/#) does not split the post/page.

### Steps to reproduce

1. Activate Livro theme
2. Add page break between some content
3. See that the break does not work in the front-end

### What you expected to happen

Page break block to work as clarified in the docs [Page Break Block](https://wordpress.com/support/wordpress-editor/blocks/page-break-block/#)

### What actually happened

Page Break does not work.

### Browser

Google Chrome/Chromium

### Context

Customer report in 7171882-Zen

### Platform (Simple, Atomic, or both?)

Simple

### Reproducibility

Consistent

### Severity

All

### Available workarounds?

None

**Comment by john-legg** [comment] 2023-10-23 21:03
📌 FINDINGS/SCREENSHOTS/VIDEO

> See that the break does not work in the front-end

I'm not what I should be looking for exactly, but after doing a quick check with the Livro theme, it appears to be the same issue that was reported recently, which affects multiple themes:
https://github.com/Automattic/wp-calypso/issues/81898

📌 ACTIONS
Closed as duplicate of issue https://github.com/Automattic/wp-calypso/issues/81898
Added a comment on the other issue with the customer ticket as well

📌 Message to Author
@AnjanaV93 I'm going to close this as a duplicate. Please let me know if that shouldn't be the case 😄 Thank you!

**Comment by john-legg** [comment] 2023-10-23 21:05
📌 FINDINGS/SCREENSHOTS/VIDEO

See that the break does not work in the front-end

I'm not what I should be looking for exactly, but after doing a quick check with the Livro theme, it appears to be the same issue that was reported recently, which affects multiple themes:
https://github.com/Automattic/wp-calypso/issues/81898

📌 ACTIONS
Closed as duplicate of issue https://github.com/Automattic/wp-calypso/issues/81898
Added a comment on the other issue with the customer ticket as well

📌 Message to Author
@AnjanaV93 I'm going to close this as a duplicate. Please let me know if that shouldn't be the case 😄 Thank you!

**Closed as not planned** 2023-10-23 21:05 UTC
Labels: [Type] Bug, [Theme] Livro, Needs triage, [Status] Duplicate, [Pri] TBD, Customer Report, [Feature Group] Appearance & Themes
