### ISSUE TITLE
[Yuga] Theme does not render query loop in pages

### ISSUE THREAD

**Issue by metabreakr** [Automattic/themes#7411] opened 2023-10-04 14:36 UTC
### Quick summary

With the Yuga theme active, adding a query loop shows the content in the editor, however it does not render when viewing the site.

https://github.com/Automattic/themes/assets/39252765/65c63e8f-8c5d-40f1-8bce-fbd783b9c9f8

### Steps to reproduce

1. Create a new simple site
2. Activate the Yuga theme
3. Add a few blog posts, and publish them
4. Create a new page, adding a query loop block
5. Select an existing pattern
6. Observe that the pattern displays as expected in the editor
7. Publish the page, and observe that the query loop doesn't display content

### What you expected to happen

I expected the query loop to display my blog posts in the selected pattern.

### What actually happened

The query loop did not display my blog posts when viewing the published page.

### Platform (Simple, Atomic, or both?)

Simple

### Other notes

Not tested on Atomic.

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

Yes, easy to implement

### Workaround details

Use the blog posts block, which has fewer design options.

**Comment by metabreakr** [comment] 2023-10-04 15:31
Discussed here: p1696431286555269-slack-C0160HSMDQV

**Comment by iamtakashi** [comment] 2023-10-04 17:10
The video shows using a pattern from Core. Not the one shipped with Yuga. This has nothing to do with Yuga.

The one shipped with Yuga, `Grid of blog posts` has specified as `"inherit":false`. See [here](https://github.com/Automattic/theme-yuga/blob/trunk/patterns/grid-of-posts.php#L11).

**Comment by iamtakashi** [comment] 2023-10-04 17:15
Testing the same scenario in multiple themes is one way to see whether the phenomenon is a theme-specific issue.

**Comment by metabreakr** [comment] 2023-10-04 17:46
Thank you @iamtakashi , I appreciate your help!

**Comment by cuemarie** [comment] 2023-10-04 18:54
From my triage testing and reviewing the discussion thread linked above, it looks like we're in agreement that the issue here is the QL block's default "Inherit query from template" setting when added to a page.  That's in review here:

- https://github.com/WordPress/gutenberg/issues/50790

Recording - Simple Site, TT3 theme:

https://github.com/Automattic/themes/assets/27249804/b5376cf4-f465-48bb-8db8-ce884e36054a

📌 ACTIONS
- Closed as not reproducible (as Yuga is not the underlying issue).

**Closed as not planned by cuemarie** 2023-10-04 18:54 UTC
Labels: [Type] Bug, [Status] Cannot reproduce, [Pri] Normal, Triaged, [Feature Group] Appearance & Themes
