### ISSUE TITLE
Archeo: Jetpack Contact form has inconsistent field styles

### ISSUE THREAD

**Issue by kjellr** [Automattic/themes#5600] opened 2022-03-01 19:29 UTC
Not sure if this is something the theme needs to update or not, but if you use the Jetpack contact form, the form field styles are inconsistent: 

<img width="682" alt="Screen Shot 2022-03-01 at 2 05 25 PM" src="https://user-images.githubusercontent.com/1202812/156234178-78cebd11-22a9-4a0b-a5ff-428659823d26.png">

The style around the "Messages" textarea looks more correct than that text fields.

**Comment by madhusudhand** [comment] 2022-03-03 07:53
@kjellr I am not able to replicate the issue. Styles seems to be working good.
Do you have a link to replicate this?

<img width="722" alt="image" src="https://user-images.githubusercontent.com/1935113/156520523-ffb652a3-9ea1-4344-91f6-98b8d132e6ac.png">

**Comment by MaggieCabrera** [comment] 2022-03-04 10:02
I can reproduce, but only on Safari

**Comment by kjellr** [comment] 2022-03-04 21:07
Ah yes. I think it's a Safari-only bug. 🤔

**Comment by mikachan** [comment] 2022-03-10 17:57
It looks like this is because Safari only applies a border to textareas by default and not inputs. It can be fixed by applying `border-width: 1px; border-style: solid;` on all inputs with CSS. This sounds like it should live in Jetpack I think? I can go ahead and create an issue there.

**Comment by mikachan** [comment] 2022-03-15 10:45
I've opened an issue for this in Jetpack: https://github.com/Automattic/jetpack/issues/23440

After some more testing, I now believe these styles are the default for Safari, and other browsers use more consistent borders between input elements and textareas. I think if we want to fix this for Archeo, we would need to add some CSS.

I'll close this issue for now, but will reopen if we want to fix this in Archeo itself.

**Closed as completed by mikachan** 2022-03-15 10:45 UTC
Labels: [Type] Bug, [Theme] Archeo
