### ISSUE TITLE
Blockbase: Calendly block won't load on front end

### ISSUE THREAD

**Issue by radtechgh** [Automattic/themes#4833] opened 2021-10-13 15:34 UTC
### Quick summary

Calendly block does not load the calendar preview on the front end when they choose the inline style. The link version works though 
Example: https://share.getcloudapp.com/jkuE7reG
Seems to be an issue with Quadrat theme.

### Steps to reproduce

1. https://sheetaljairth.com/thank-you-for-your-purchase/
2. Works on test site: Pdrz4c-5-p2
3. Embedded okay on test site with 2021 theme. 
4. Disappeared when switched to Quadrat.

### What you expected to happen

Expected calendar preview

### What actually happened

could only use inline link

### Context

4370660-zen

### Theme-specific issue?

Quadrat

### Other notes

I did not perform these tests, the content was taken from an open ended ticket with "create bug report" in Next Steps.

### Reproducibility

Consistent

**Comment by annbingle** [comment] 2021-12-02 02:17
Another report from here 33007379-hc

**Comment by vinnykaur** [comment] 2022-01-12 11:20
Also reported with Zoologist on 4668180-zen and 4635990-zen

**Comment by tavilla61** [comment] 2022-01-19 22:20
Another instance with Radiant Theme on 4702600-zen

**Comment by kingsleyinfo** [comment] 2022-01-28 15:59
Another issue here 33909387-hc Byrne theme

**Comment by ccwalburn** [comment] 2022-02-15 20:27
Another report here 34211680-hc / 4782765-zen
Russell theme

**Comment by KirkwallDay** [comment] 2022-02-24 21:22
Another instance here: 33964196-hc
Russell theme.

**Comment by tellisbethel** [comment] 2022-03-01 11:25
Another report here: 4821628-zd-woothemes
Jackson theme.

**Comment by matiasbenedetto** [comment] 2022-03-02 17:10
An update after a little research about this issue I can confirm that this is not related to Blockbase theme.

**Currently we are able to embed the Calendly widget in these ways:**

- On **self-hosted WordPress instances (.org)** you can use the Custom HTML block and paste there the Calendly embed code:

https://user-images.githubusercontent.com/1310626/156411638-7c017132-7474-4cdd-8f92-b3aef83bb607.mp4




- On **WordPress.com** you need to use the Calendly block with your Calendly calendar link (this block is only available for premium users). The Custom HTML option doesn't work here for security reasons.

https://user-images.githubusercontent.com/1310626/156411763-ac827915-9d0c-43c0-868b-1dd8e6de290e.mp4

I'm closing this ticket.

**Comment by KirkwallDay** [comment] 2022-03-02 19:04
Hi @matiasbenedetto, thank you for looking into this! 

From your reply, it's not clear to me how this is not blockbase theme-related. Can clarify your thought process so I can determine the best place to direct this bug report?

**Comment by matiasbenedetto** [comment] 2022-03-02 19:35
> From your reply, it's not clear to me how this is not Blockbase theme-related. Can clarify your thought process so I can determine the best place to direct this bug report?

Hi, @KirkwallDay, this is not Blockbase related because it can be reproduced in other themes (I tested it with TT2  and Stewart, for example). But It is not a theme-related problem either. The problem is produced by how the Custom HTML block contents are saved in dotCom. It seems that for security reasons, the content of this block is escaped to remove all the potentially risky contents, so this HTML:

```
<!-- Calendly inline widget begin -->
<div class="calendly-inline-widget" data-url="https://calendly.com/matiasbenedetto/30min" style="min-width:320px;height:630px;"></div>
<script type="text/javascript" src="https://assets.calendly.com/assets/external/widget.js" async></script>
<!-- Calendly inline widget end -->
```

is saved as
```
<!-- Calendly inline widget begin -->
<div class="calendly-inline-widget" style="min-width:320px;height:630px;"></div>
<a href="https://assets.calendly.com/assets/external/widget.js">https://assets.calendly.com/assets/external/widget.js</a>
<!-- Calendly inline widget end -->
```

 The embed can't be loaded as expected because of the `script` tag transformation to an `a` tag.

**Comment by KirkwallDay** [comment] 2022-03-02 22:06
>Hi, @KirkwallDay, this is not Blockbase related because it can reproduced in other themes (I tested it with TT2 and Stewart, for example). But It is not a theme-related problem either. The problem is produced by how the Custom HTML block contents are saved in dotCom. It seems that for security reasons, the content of this block is escaped to remove all the potentially risky contents, so this HTML:

Thanks for the explanation Matias, I really appreciate it. I'm going to submit this to Calypso, I'm wondering if it's FSE related then as the block works fine on non-FSE sites. I'll reply back here with the Github issue. Closing this.

**Closed as completed by KirkwallDay** 2022-03-02 22:06 UTC

**Comment by KirkwallDay** [comment] 2022-03-02 22:21
Reported here as an FSE issue: Automattic/jetpack#23357

**Comment by dcoleonline** [comment] 2022-03-16 14:15
adding 4865992-zen just for tracking purposes

I've also sent the workaround as suggested in https://github.com/Automattic/jetpack/issues/23357
