### ISSUE TITLE
Exford: Pullquote no longer having top and bot padding

### ISSUE THREAD

**Issue by Robertght** [Automattic/themes#7805] opened 2024-05-15 08:28 UTC
### Quick summary

It appears that somewhere in the recent updates the top and bottom padding for the Pullquote block was removed from the theme styling and it needs to be manually set within the block settings.

### Steps to reproduce

1. Start on a simple site
2. Activate Exford.
3. Add a pullquote on a page and check the results.
4. The text should be closer to the top and bottom padding, yet the preview in the editor is correct.

### What you expected to happen

To see the quotes with a top and bottom padding as in the editor.

### What actually happened

The padding wasn't there but if we check the block settings, the padding are set to 0 until we start adjusting them.

### Browser

Google Chrome/Chromium

### Context

8185819-zd-a8c

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

### Workaround details

For existing sites with the Explorer plan, we can use CSS to adjust the padding for all blocks at once. Example:

```
.wp-block-pullquote {
   padding-top: 32px;
   padding-bottom: 32px;
```

**Comment by liviopv** [comment] 2024-05-28 10:23
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 FINDINGS/SCREENSHOTS/VIDEO

Simple
![CleanShot 2024-05-28 at 11 20 26@2x](https://github.com/Automattic/themes/assets/14153300/441c15bf-b9f0-40c2-ae25-694e11321b6f)

Atomic
![CleanShot 2024-05-28 at 11 22 20@2x](https://github.com/Automattic/themes/assets/14153300/13a54966-bffa-4d68-b46f-f39cf76eeebd)


📌 ACTIONS
- Triaged

**Comment by alaczek** [comment] 2024-08-28 01:33
I was unable to reproduce it - might have been a Gutenberg thing?

**Comment by Robertght** [comment] 2024-08-28 04:24
I cannot replicate this on my end anymore.

**Comment by alaczek** [comment] 2024-08-28 05:13
I'm going to close this issue at this time. Feel free to reopen if it pops up again or if I missed something.

**Closed as completed by alaczek** 2024-08-28 05:13 UTC
Labels: [Type] Bug, [Pri] Normal, [Theme] Exford, Triaged, Customer Report, [Feature Group] Appearance & Themes
