### ISSUE TITLE
Varia/Child Themes: Google Docs Embed Displayed Incorrectly

### ISSUE THREAD

**Issue by edequalsawesome** [Automattic/themes#1953] opened 2020-04-29 22:47 UTC
## Steps to replicate

1. Create a new post or page
2. Add a Google Docs embed

## Result

The embed is shown on the left side of the screen because no `display` is set for iframes -- that's not a problem for most embeds (since they're wrapped in a `wp-block-embed` div), but for Google Doc embeds, it's added to the post content without a wrapping `wp-block-embed` div.

[![Google Doc Embed without CSS Applied](https://d.pr/i/IF22cV+)](https://d.pr/i/IF22cV)

## Expected

The Google Doc embed would be shown with `margin-left: auto` and `margin-right: auto` applied to keep the embed in-line with the other standard-alignment content on the site.

[![Google Doc Embed with CSS Applied](https://d.pr/i/gTJXL1+)](https://d.pr/i/gTJXL1)

The following CSS will fix this for any iframe that's embedded from Google Docs:

```
/* fix iframe display bug for google doc embeds | #XXXXXX-hc/zen */
.entry-content iframe[src*="docs.google.com"] {
	display: block;
}
```

* User report: #19929254-hc
* Follow-up ticket: #2930103-zen

**Comment by tbradsha** [comment] 2020-05-09 14:40
Possible duplicate of #1732, which contains a non-CSS fix.

**Comment by edequalsawesome** [comment] 2020-05-22 21:57
Nope, this is a different issue -- #1732 is showing the iframe on the left side of the screen, but it _also_ doesn't display at the correct width because it has an inline style attribute. Here, the iframe is shown at the correct width (because there aren't any inline style attributes), but is put outside of the area you'd expect the iframe to be displayed based on how other content is displayed on the site :)

To test it, I added the `<span>` tag before the shortcode as mentioned in the other report, and it still had the same issue:

[![Span Added, Still Broken](https://d.pr/i/8dlfNZ+)](https://d.pr/i/8dlfNZ)

**Comment by scruffian** [comment] 2020-11-04 21:06
This seems to be fixed already. Closing.

**Closed by scruffian** 2020-11-04 21:06 UTC
Labels: [Type] Bug, support
