### ISSUE TITLE
Sela: Logo does not show in customizer or live site

### ISSUE THREAD

**Issue by jjchrisdiehl** [Automattic/themes#49] opened 2018-03-21 15:43 UTC
## Steps to replicate
This appears to be a one-off instance, a couple of us couldn't replicate.

Ideally,

- Add logo in Customizer

- Logo appears in Live Preview and live site

- Dance of joy begins.

## Result
Unfortunately, the logo is added to the customizer panel, but does not appear in preview or live.

## Expected
Expected the logo to be previewed in the theme and posted live.

* User report: #2123559-hc
* Follow-up ticket: #1032899-zen
* User's site: https://libbeyjean.com/
* Slack https://a8c.slack.com/archives/C029FM1EH/p1521576991000804

**Comment by alaczek** [comment] 2018-03-21 21:45
Similar issue reported in 5005-wpcom-themes

**Comment by crunnells** [comment] 2018-03-22 00:30
Turns out this is a conflict with WordAds. Confirmed on the user's site by disabling WordAds, which caused the logo to appear. Tracked it down to an issue where the function tied to the `jetpack_the_site_logo` filter was returning `false` instead of the logo content. Reported to ads team: p4x5kY-Fi-p2

**Comment by crunnells** [comment] 2018-03-28 20:16
Fixed by r172510-wpcom

**Closed by crunnells** 2018-03-28 20:16 UTC
Labels: bug, support
