### ISSUE TITLE
Twenty Fourteen: Gutenberg: Title always appears in uppercase

### ISSUE THREAD

**Issue by arunsathiya** [Automattic/themes#401] opened 2018-11-27 00:54 UTC
#### Steps to reproduce 

- Start with a WordPress.com site and install Twenty Fourteen theme from WordPress.com on it
- Click on `Add` next to `Blog posts`/`Site pages` and opt-in for the new WordPress Editor (Gutenberg) editor
- Enter a title for that post/page

#### What is expected 

The title appears as it is typed.

#### What happens instead 

The title appears in uppercase

<img width="964" alt="screenshot 2018-11-27 at 07 53 24" src="https://user-images.githubusercontent.com/18581859/49051241-943e1180-f219-11e8-9539-34268904cc58.png">
<img width="590" alt="screenshot 2018-11-27 at 07 53 34" src="https://user-images.githubusercontent.com/18581859/49051242-94d6a800-f219-11e8-95b1-e870948b60b8.png">

#### More notes:

This cannot be reproduced on Twenty Fourteen core theme (version 2.2) with Gutenberg from `master` [branch from repo](https://github.com/WordPress/gutenberg). 

Creating a post using the classic editor instead shows the title as typed.

<img width="961" alt="screenshot 2018-11-27 at 07 53 05" src="https://user-images.githubusercontent.com/18581859/49051247-9902c580-f219-11e8-8623-4d430323f105.png">

**Comment by laurelfulford** [comment] 2018-11-27 06:04
Hi @arunsathiya!

> The title appears in uppercase

That's actually working as intended: the styles for the new block-based editor mirror what's shown on the front-end. Since the title is displayed in uppercase, it's previewed in uppercase in the editor as well. These styles were recently added to Twenty Fourteen; there's some more information about that here: https://wp.me/p7DVsv-5If

I'm going to close this since it's working as expected, but if you do run into any issues with these styles for default themes that can be recreated on a non-WP.com site, please report them to the WordPress Core Trac. Just give me a ping if you're not sure :) Thanks!

**Closed by laurelfulford** 2018-11-27 06:04 UTC
Labels: bug

**Comment by soshaugh** [comment] 2020-08-26 21:55
Is there a way to override this? I don't mind that it displays in all caps on the site but I don't want it changing to all caps in the editor. I send my title to social media and it shouldn't be in all caps there so it is not possible to make sure that it is properly formatted.
