### ISSUE TITLE
Illustratr: left margin is erroneously added to the tiled gallery block

### ISSUE THREAD

**Issue by silvio-meter** [Automattic/themes#2945] opened 2020-12-28 14:08 UTC
## Steps to replicate

1. Activate the Illustratr theme
2. Create a new page and add the Tiled Gallery Block with few images

## Result

A left margin of 1.5em is added to the Block automatically.

Screenshot:

![Optional alternative text if image doesn't load](https://testsite257com.files.wordpress.com/2020/12/annotation-on-2020-12-28-at-15-00-46.png)

## Expected

The Title Gallery Block should appear without the left margin.

* User report: [ #13603434-zd]
* Follow-up ticket: [ #13603434-zd]

**Comment by ivan-ottinger** [comment] 2021-01-10 08:33
The user came back asking for an update.

→ Provided a workaround with the help of a _Layout Grid_ block with **one column** and **no gutter**. Basically we will drag the _Tiled Gallery_ block into that _Layout Grid_ block and the gallery will display correctly.

Hopefully this can help other user in case they encounter the same issue before it is fixed.

**Comment by deancroyal** [comment] 2022-09-20 23:10
Another report in #31057107-zd

Used CSS as temporary workaround.

**Comment by bobmatyas** [comment] 2022-09-26 18:07
@silvio-meter and @ivan-ottinger I looked into this one and I couldn't reproduce it.

When adding a Tiled Gallery in Illustratr I get the expected results without the margin:
<img width="912" alt="Screenshot on 2022-09-26 at 14-06-48" src="https://user-images.githubusercontent.com/45246438/192348929-0e44b8bf-cd6b-41c8-bba5-469bcd087087.png">

I'm wondering if this has been resolved since the issue was opened.

**Comment by ivan-ottinger** [comment] 2022-09-27 13:50
Thanks for the ping, Bob!

> When adding a Tiled Gallery in Illustratr I get the expected results without the margin:

That's right, I couldn't reproduce the issue anymore either. I think we can close this issue. 👍🏼

**Closed as completed by ivan-ottinger** 2022-09-27 13:50 UTC
Labels: [Type] Bug, Support
