### ISSUE TITLE
Canard: Button is invisible until hover

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#3306] opened 2021-02-18 12:54 UTC
## Steps to replicate

Buttons in Canard aren't visible until hover:

<img width="907" alt="Screenshot 2021-02-18 at 12 52 48" src="https://user-images.githubusercontent.com/275961/108359794-56f23f80-71e8-11eb-9b27-57596e547f76.png">

<img width="914" alt="Screenshot 2021-02-18 at 12 52 43" src="https://user-images.githubusercontent.com/275961/108359805-59ed3000-71e8-11eb-9397-b765fe33ab69.png">

**Comment by Gustavo-Hilario** [comment] 2022-10-14 17:15
I couldn't reproduce this issue on local sites and WordPress.com. I'm closing this report for now.

**Closed as completed by Gustavo-Hilario** 2022-10-14 17:15 UTC
Labels: [Status] Cannot reproduce, [Theme] Canard
