### ISSUE TITLE
Seedlet Blocks: Layout Grid Block: Ensure all the options work as expected

### ISSUE THREAD

**Issue by scruffian** [Automattic/themes#2881] opened 2020-12-02 15:46 UTC
Some of the options with the Layout Grid block don't work as expected. We should test them and ensure that they all work.

cc @ianstewart @iamtakashi

**Comment by MaggieCabrera** [comment] 2021-07-07 16:06
I think this one is a duplicate of https://github.com/Automattic/themes/issues/3364

**Closed as completed by MaggieCabrera** 2021-07-07 16:06 UTC
Labels: [Theme] Seedlet Blocks
