### ISSUE TITLE
Blockbase (and other FSE themes): New page / new article: Template 404

### ISSUE THREAD

**Issue by ghost** [Automattic/themes#6124] opened 2022-06-23 15:54 UTC
## Steps to replicate

choose "new article" or "new page" to open site editor and write new article or new page.
go to sidebar, Template area.

## Result

Sidebar says: "Template: 404".
Clicking on "Modify" sends to 404 template (instead of single or page).

<img width="960" alt="2022-06-23" src="https://user-images.githubusercontent.com/25288484/175341949-8f560afa-5891-4d21-99de-11ae89dbc9cb.png">

## Expected

Expected to see "Template: page" or "Template: article".
Modify should send to page or article template.

## Replication:
happens consistently, in different environments.
See also https://github.com/Automattic/themes/issues/5410 .

## Workaround:
After saving once, the correct template is shown.
Yet, it took me a long time to research the bug before I discovered the workaround, and it might confuse new users.

**Comment by Thelmachido** [comment] 2022-06-29 10:30
I wasn't able to reproduce this issue, steps taken:

1. Added Blockbase theme to my site 
2. Created a new post, the template didn't show 404 as shown below:

<img width="1710" alt="Screenshot 2022-06-29 at 12 17 57" src="https://user-images.githubusercontent.com/41231764/176415279-e3139132-4460-41dd-b083-51517526d097.png">

Since this was reported here #5410 closing this issue as a duplicate.

**Closed as not planned** 2022-06-29 10:31 UTC
Labels: [Status] Cannot reproduce, [Theme] Blockbase
