### ISSUE TITLE
Multiple Themes: Centre align block isn't centred

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#761] opened 2019-04-30 22:44 UTC
**Affected Themes: Professional, Sophisticated**

**Currently**
<img width="1323" alt="Screen Shot 2019-05-10 at 17 54 04" src="https://user-images.githubusercontent.com/908665/57543590-adacc300-734c-11e9-8b62-fe7475535ba0.png">

Horizontal margins are set to 0 for centred elements for some reason.

**Comment by torres126** [comment] 2019-05-10 18:11
Noting that this is a duplicate of #646 (alt PR #648) and Automattic/wp-calypso#28756 (alt PR #660)

**Closed** 2019-05-10 21:46 UTC
Labels: [Pri] Normal, bug, needs patch

**Comment by michaelswengel** [comment] 2019-10-04 20:46
Having the same issue here. It looks like this particular bug has been around for a while. Will it ever be fixed?

**Comment by iamtakashi** [comment] 2019-10-05 04:06
@michaelswengel Which theme are you having this issue? All the business themes have been retired and will no longer be updated.

**Comment by michaelswengel** [comment] 2019-10-05 14:41
Multiple themes. The issue is not isolated to one theme. I’m using Elementor (the page builder), however, and that appears to be overriding Gutenberg’s alignment. Odd. 

So I think I have an Elementor problem more than a Gutenberg problem.
