### ISSUE TITLE
Dara: closing quote for blockquote

### ISSUE THREAD

**Issue by kristarella** [Automattic/themes#627] opened 2019-02-18 22:27 UTC
## Steps to replicate

Blockquote style has an opening quote, but no closing quote
<img width="798" alt="screen shot 2019-02-19 at 9 23 39 am" src="https://user-images.githubusercontent.com/2031017/52979137-6b987300-3428-11e9-871c-53e9b56a1e89.png">

## Result

It's just a style thing, but a customer felt it was incorrect

## Expected

They expected a closing quote. I was able to add one in CSS like this:

```
blockquote p:last-child::after {
    color: #ccc;
    content: "\201C";
    font-family: "Yrsa",Georgia,serif;
    font-size: 140px;
    font-style: normal;
    line-height: 1;
    position: absolute;
    bottom: -10px;
    right: -10px;
    transform: rotate(0.5turn);
}
```

* User report: 10537733-hc

**Comment by laurelfulford** [comment] 2019-02-19 18:10
Thanks for this report, @kristarella!

As you noted, this is as designed. Unfortunately, it's not something we can change now without it affecting existing sites, possibly in unwanted ways. 😕 

I'm glad this could be fixed in this case using Custom CSS. I'm going to close this issue; not sure a follow up is needed since it is displaying as this user wants on their site.

**Closed by laurelfulford** 2019-02-19 18:10 UTC
Labels: enhancement, support
