### ISSUE TITLE
Textbook: Reblogged posts are unexpectedly placed in featured content area

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/themes#127] opened 2018-05-10 06:21 UTC
## Steps to replicate

The user reblogs posts from another site. The reblogged posts appear in both the featured content area as well as in the general blog post listing. Here is an example:

![](https://cldup.com/rV3FJLMlmn.png)

The user also schedules posts for publication and noticed that when a scheduled post is published, the reblogged post is removed from the featured content area and only appears in the general blog post listing below the featured content section.

The user also pointed out that they **don't** add the tag used for featured content to reblogged posts (they haven't seen this option available).

**Note: this seems to have started happening recently. Was the theme updated in the last week or two?**

>You know, this recently started happening in the last week or so. It never used to do this.

This may be a related commit:

https://github.com/Automattic/themes/commit/faa6e8a59c89b8acbd1f5aca967b3d66a5aa615e

## Result

Reblogged posts are shared both in the featured content section, and the general blog post listing below the featured content section.

## Expected

Unless they are tagged with the featured content tag, reblogged posts should only appear in the general blog post listing section as a normal (as opposed to featured) blog post.

* User report: 1146828-zen
* User's site: https://colleenchesebro.com/

**Comment by alaczek** [comment] 2018-05-15 03:28
Unfortunately the user switched themes :| I don't suppose you were able to replicate this?

**Comment by laurelfulford** [comment] 2018-07-04 19:05
I tried to recreate this; even with the same `featured` tag on the post being reblogged as was used on the site it was reblogged to, I couldn't get it to work.

@pauljacobson were you able to recreate this? If so, did it persist once the theme was switched to another theme that supports Featured Content?

**Comment by laurelfulford** [comment] 2018-12-27 17:35
I'm going to close this issue for now: we just have the one report, the customer who experienced the problem is still using a different theme, and we haven't been able to recreate it.

We can always reopen or create a new issue if this pops up again!

@pauljacobson I'm unable to comment on the ZD ticket, since it's closed. I'm not sure if a follow-up is needed at this point, but could you please follow up if it is? Thanks!

**Closed by laurelfulford** 2018-12-27 17:35 UTC
Labels: bug, support
