### ISSUE TITLE
Twenty Seventeen: Buttons block colors don't apply properly in front-end (seems to affect black and white only)

### ISSUE THREAD

**Issue by ivan-ottinger** [Automattic/themes#3291] opened 2021-02-17 14:42 UTC
## Steps to replicate

1. Make sure the _Twenty Seventeen_ theme is activated.
2. Add Buttons block to a page.
3. Set the text color to black and background color to white.
4. Review the page in the front-end.

![Markup on 2021-02-17 at 15:36:33](https://user-images.githubusercontent.com/25105483/108219721-471a2300-7136-11eb-8733-640957ad55bd.png)

## Result

The set colors are ignored in the front-end:

![Markup on 2021-02-17 at 15:38:32](https://user-images.githubusercontent.com/25105483/108219662-3c5f8e00-7136-11eb-8d13-d0eb7e4a40ce.png)

## Expected

Set colors are properly applied in both back-end and front-end.

## Workaround

As a workaround, we can set the colors to #fffffe and #000001 for example.

* User report: 27812807-hc

**Comment by kathrynwp** [comment] 2022-07-19 17:53
I was not able to replicate this one on a Simple WP.com site, nor on a local install running:

WP 6.0.1
Twenty Seventeen 3.0 
No active plugins

![Twenty_Seventeen_Test_Page_–_Self-hosted_Test](https://user-images.githubusercontent.com/7662449/179817135-5e1d0fec-7c89-4a99-bdaf-ac68d30e0ae4.jpg)

Because I can't reproduce, and also since the original user's site is no longer active, and because there was only one report of this issue, I'm going to go ahead and close this one without moving it over into Core Trac.

**Closed as not planned by kathrynwp** 2022-07-19 17:53 UTC
Labels: [Type] Bug, [Status] Cannot reproduce, [Theme] Twenty Seventeen
