### ISSUE TITLE
[Bug]: "Expand on Click" / Lightbox feature not working on Dyad 2 and Shawburn themes

### ISSUE THREAD

**Issue by caitlindawn** [Automattic/themes#7561] opened 2023-12-15 13:41 UTC
### Quick summary

When using the Dyad 2 or Shawburn themes, the "Expand on Click" / Lightbox feature doesn't work i.e. nothing happens when clicking on the image. This doesn't happen on other themes such as Spiel, Pomme, and Lettre.

### Steps to reproduce

1. Load up the Dyad 2 or Shawburn themes.
2. Add an image block to a Page or Post and enable the "Expand on click" feature.
3. Save changes and view the page/post.
4. Click on the image.

### What you expected to happen

Image should enlarge and be viewed in lightbox mode.

### What actually happened

Nothing happens when clicking.

### Browser

Google Chrome/Chromium, Mozilla Firefox, Apple Safari

### Context

Customer report on their Dyad 2-themed site, other HC also tested with Shawburn theme on their test site

### Reproducibility

Consistent

### Severity

None

### Available workarounds?

None

**Comment by caitlindawn** [comment] 2023-12-15 13:49
Encountered in 7451447-zen

**Comment by csonnek** [comment] 2023-12-18 15:09
Reported here: https://wordpress.com/forums/topic/expand-on-click/?view=all

**Comment by rw-ye** [comment] 2023-12-20 04:02
Another report: 7476424-zd-a8c
Theme: Cerauno

**Comment by tvolpert** [comment] 2023-12-22 19:01
This appears to be the same issue as reported here: https://github.com/Automattic/wp-calypso/issues/85638 I'm guessing this is the issue we want to go with since it notes that this seems to affect _all_ classic themes, not just the two named here?

**Comment by krutidugade** [comment] 2023-12-26 11:26
Another report: 7485749
Theme: Mayland

**Comment by liviopv** [comment] 2023-12-27 10:26
📌 REPRODUCTION RESULTS
- Tested on Simple – Replicated
- Tested on Atomic – Replicated

📌 ACTIONS

- Closed as duplicate of https://github.com/Automattic/wp-calypso/issues/85638

📌 Message to Author
@krutidugade @tvolpert @rw-ye @csonnek @caitlindawn please report new issues in the wp-calypso issue above, as this is not theme-specific.

**Closed as completed by liviopv** 2023-12-27 10:26 UTC
Labels: [Type] Bug, Triaged, [Status] Duplicate, [Pri] TBD, Customer Report
