### ISSUE TITLE
Intergalactic 2: Image Caption in Block Editor is Too Light to See

### ISSUE THREAD

**Issue by bobmatyas** [Automattic/themes#4040] opened 2021-06-10 16:03 UTC
https://wordpress.com/support/wordpress-editor/blocks/image-block/

- Cannot easily add caption on Intergalactic 2 theme
- CSS in block editor is making it too white and it doesn't show in editor

## Steps to replicate

* Add a new image block using Intergalactic 2 theme

## Result

* Once added the caption isn't visible in the editor

In this screenshot you can see that the caption text is displaying as a shade of white which is effectively hiding the caption and making it difficult to edit:

![Annotation on 2021-06-10 at 12-00-57](https://user-images.githubusercontent.com/45246438/121558592-cb452e80-c9e3-11eb-8f9d-2af2981d422b.png)

## Expected

When I add an image, I should be able to easily edit the caption.

* User report: 4047393-zen

**Comment by bobmatyas** [comment] 2021-06-10 16:17
The text rendered by a caption that is inputed via the Media Gallery also renders as white in the editor.

**Comment by kathrynwp** [comment] 2021-06-10 18:06
Dupe of https://github.com/Automattic/wp-calypso/issues/53422

**Closed as completed by kathrynwp** 2021-06-10 18:06 UTC
Labels: [Type] Bug, [Theme] Intergalactic 2
