### ISSUE TITLE
Dyad 2: Cannot use submenus in desktop menu on touchscreen

### ISSUE THREAD

**Issue by KokkieH** [Automattic/themes#1417] opened 2019-09-23 10:02 UTC
## Steps to replicate

1) Add a menu that contains some submenus and sub-submenus
2) On a tablet, in landscape mode (in portrait mode the theme will use the mobile menu hidden behind a menu button), tap on a parent menu-item to expand the submenu

## Result

The submenu expands, but the parent page immediately loads, causing a page refresh and the submenu collapsing again.

## Expected

For the first tap on the parent page to open the submenu, and for a second tap on the parent page to be required to actually load that page.

* User report: https://wordpress.org/support/topic/menu-on-ipad-problem/

Initially reported for the self-hosted version of Dyad 2. I was unable to replicate the issue using Browserstack or responsive mode in a desktop browser and so was another HE on an actual iPad.

The user has since reported it happening on a dotcom site using the original version of Dyad as well, and when checking again in responsive mode in my browser I can now replicate the issue on that site, the Dyad 2 demo site, and the self-hosted site from the original report. Don't have an actual tablet to check.

If using browser responsive mode to replicate, make sure to select an actual device preset - manually sizing the responsive browser window to tablet-size apparently doesn't activate touch simulation, which might, at least partially, explain why I wasn't able to replicate this initially.

**Comment by kathrynwp** [comment] 2021-07-11 20:27
Dupe of #810

**Comment by Robertght** [comment] 2021-12-09 09:41
I'm closing this in favor of https://github.com/Automattic/themes/issues/810 as they seem to share the same behavior.

**Closed by Robertght** 2021-12-09 09:41 UTC
Labels: [Type] Bug, support
