### ISSUE TITLE
Radcliffe 2: Logo Size Changes Not Respected

### ISSUE THREAD

**Issue by synora** [Automattic/themes#7508] opened 2023-11-21 19:31 UTC
### Quick summary

When adjusting the size of the logo using the blue "Logo Size" bar in Customize > Site Identity > Logo, the size change does not stay even when you save your changes. 

### Steps to reproduce

1. Activate the Radcliffe 2 theme
2. Navigate to Appearance > Customize > Site Identity > Logo
3. Upload a logo if one is not present
4. Use the blue bar "Logo Size" bar to adjust the size of the logo
5. Save your changes
6. Visit your homepage in a new tab

### What you expected to happen

For the updated logo size to be reflected on the site. 

### What actually happened

The logo size remained unchanged. 

### Browser

Google Chrome/Chromium

### Context

Customer report, HE replicated

### Platform (Simple, Atomic, or both?)

Simple, Atomic

### Other notes

Customer report at 7342428-zen

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, difficult to implement

### Workaround details

I've given the user the following CSS to enlarge the logo for now:

```
/*site icon resizing-7342181zen*/
img.custom-logo {
width: 400px;
}
```
The larger the width's pixel size, the more blurry the image becomes, however. Any other known workarounds can be reported back to the user.

**Comment by wiesenhauss** [comment] 2023-11-22 14:20
Another report here: 7346400-zen

**Comment by Aurorum** [comment] 2023-11-22 18:13
Duplicate of #7496

**Comment by Oriz-p** [comment] 2023-11-25 07:49
Another report here: #7359523-zen

**Comment by afzalpansuvi** [comment] 2023-11-26 12:41
Another ticket: 7346400 Zen
Personal Plan

**Comment by marutim** [comment] 2023-12-08 02:56
Another issue here: 7422528-ZD

Personal plan

**Comment by mreishus** [comment] 2023-12-14 16:21
The underlying bug is now fixed (but I don't believe all users have been followed up with - I can do it if needed).

**Closed as completed by mreishus** 2023-12-14 16:21 UTC
Labels: [Type] Bug, [Theme ]Radcliffe 2, Needs triage, [Pri] TBD, Customer Report, [Feature Group] Appearance & Themes
