### ISSUE TITLE
Dalston theme: Hover Reveal style not hiding the color background on WordPress 5.9

### ISSUE THREAD

**Issue by renatho** [Automattic/themes#8395] opened 2024-11-08 13:46 UTC
### Quick summary

The color/gradient background is not hidden when using the "Hover Reveal".

I noticed this issue as part of https://github.com/Automattic/themes/pull/8385, and I didn't fix to avoid creating issues with other versions since it's happening only with WP 5.9. Anyway, I'm creating this issue to document it in case we want to fix it in the future.

### Steps to reproduce

1. Create a site with WP 5.9
2. Add a cover block with an image or video
3. Add a color or gradient to the cover.
4. Select the "Hover Reveal" style.

### A clear and concise description of what you expected to happen.

The color/gradient should be hidden, and revealed with the content only on hover.

Video from WP 6.6:

https://github.com/user-attachments/assets/dd5dbfaa-7ccf-4da6-aeff-b50befd21026

### What actually happened

The color/gradient background is not hidden.

https://github.com/user-attachments/assets/273ba820-8c12-4348-bff4-8238a7bc9d23

### Impact

Some (< 50%)

### Available workarounds?

No but the platform is still usable

### Logs or notes

Theme Dalston
WordPress 5.9

**Comment by renatho** [comment] 2024-11-08 13:48
Adding a Low priority label since it's only on WP 5.9 and the impact is not very significant.

**Comment by alaczek** [comment] 2024-11-21 23:35
Can we close this as fixed?

**Comment by renatho** [comment] 2024-11-21 23:42
> Can we close this as fixed?

Hi, @alaczek! Do you mean because it's a low-priority issue?

**Comment by alaczek** [comment] 2024-11-22 00:44
Because I saw you merged a fix above? Or did this not fix the issue?

**Comment by renatho** [comment] 2024-11-22 23:40
> Because I saw you merged a fix above? Or did this not fix the issue?

Ah! I see. Maybe you are referring to [this PR](https://github.com/Automattic/themes/pull/8385), right? If yes, this wasn't fixed. I opened this issue to keep track because the issue still happens on WP 5.9. :)

**Comment by Robertght** [comment] 2024-12-14 07:08
I managed to replicate the behavior from the WP 6.6 video which appears to be correct, however, I don't know if we should fix the behavior for older versions of WP.

I wasn't able to replicate this on a self-hosted website with WP 6.7.1 either.

@Automattic/t-rex is this something we should fix?

**Comment by dsas** [comment] 2024-12-16 09:11
> @Automattic/t-rex is this something we should fix?

Ideally. Though if this is only reproducible on a three year old version of wp then there's roughly eleventy thousand more important uses of our time, and the longer we wait, the less important it will be.

**Closed as not planned** 2024-12-16 09:11 UTC
Labels: [Type] Bug, [Pri] Low, Triaged, [Status] Priority Review Triggered
