### ISSUE TITLE
WooCommerce Blocks: All Products Block renders product star ratings as "SSSSS" instead of five stars

### ISSUE THREAD

**Issue by pauljacobson** [Automattic/themes#7994] opened 2024-08-05 12:38 UTC
### Quick summary

A user reported that they see "SSSSS" under a product on their Store page where they'd expect to see stars as part of a product rating. On further investigation and with some testing, this seems to be an issue with the Pique theme that the site has active.

It looks like stars load briefly when the Store page loads, and are then replaced by "SSSSS" instead. See here:

https://github.com/user-attachments/assets/64801751-ac0d-4081-bdf9-474e44caa476

This affects the "Ash & Elm (American Pale Ale)" product that is currently the only product with a rating from a customer.

### Steps to reproduce

1. Start on the Shop page at https://staging-cb9f-bridscross.wpcomstaging.com/shop/ (this staging site has minimum plugins enabled for testing purposes) and observe the "Ash & Elm (American Pale Ale)" product;
2. Reload the page and briefly notice gold stars loading under the product before the stars are replaced by "SSSSS"
3. If I test with other themes such as Storefront or the Amulet theme, the stars load as stars instead.

### What you expected to happen

Instead of "SSSSS" under the product, I'd expect to see stars loading, like either of the following:

![CleanShot 2024-08-05 at 15 07 53@2x](https://github.com/user-attachments/assets/e7d5e1fb-d0e8-4ac8-8c97-68fa5a3e579b)
![CleanShot 2024-08-05 at 15 12 50@2x](https://github.com/user-attachments/assets/55370f04-e515-4a9e-b429-5e98602d9d82)

### What actually happened

Instead, we see "SSSSS" loading instead of stars, like this:

![CleanShot 2024-08-05 at 11 43 49@2x](https://github.com/user-attachments/assets/341af9b8-f0b1-49a3-847e-826e4649c8ac)

Interestingly, if I view the page in the editor, I see stars, like this:

![CleanShot 2024-08-05 at 11 48 00@2x](https://github.com/user-attachments/assets/18946239-35f0-47a2-a5f8-e2b2703e3643)

### Browser

Mozilla Firefox, Microsoft Edge

### Context

Customer report in 8558503-zen

### Platform (Simple, Atomic, or both?)

Atomic

### Other notes

These may be relevant: 3546c-pb/

### Reproducibility

Consistent

### Severity

Some (< 50%)

### Available workarounds?

Yes, easy to implement

### Workaround details

The workaround seems to be to change to a different, WooCommerce theme that supports displaying the product rating stars under the products.

**Comment by retnonindya** [comment] 2024-08-28 09:20
📌 REPRODUCTION RESULTS
- Tested on Atomic – Could Not Replicate. But... 

📌 FINDINGS/SCREENSHOTS/VIDEO
I can't replicate the issue when I'm using theme Pique. This is what it looks like on my site:

![Screenshot 2024-08-28 at 5 09 07 PM](https://github.com/user-attachments/assets/07021572-f813-4161-9003-7e1067229cb2)

_However_, I did found the culprit. I decided to check the user's website, and I found they use All Products Block on their page Shop instead of keeping it empty (because on classic themes, there is no need to add anything on the Shop page as it will be populated automatically.) When I added All Products Block, _that_ was when the rating changed to `SSSSS`.

This is the page editor on the page Shop, and you can see All Products Block:

![Screenshot 2024-08-28 at 5 19 14 PM](https://github.com/user-attachments/assets/708dd019-c70e-496e-9929-a1b9f8e2e4eb)

And this is how it looks like on the live site:

![Screenshot 2024-08-28 at 5 19 41 PM](https://github.com/user-attachments/assets/1fdee532-4788-4487-bbe5-3d8f991ec4c5)

**Update:**
I checked this issue with different themes, and I even noticed the `SSSSS` appears on the page Editor. On this test site, it's using theme Amulet -- which, the theme that _should_ work according to the original report:

![Screenshot 2024-08-28 at 5 27 54 PM](https://github.com/user-attachments/assets/e1663d39-9384-4c66-ad0c-07f13be5f073)

📌 ACTIONS
- Triaged

📌 Message to Author
@pauljacobson I understand the ticket has been marked as Solved/closed, but feel free to inform the user about this, and you can suggest they remove the All Products Block from the page Shop :D

**Closed as completed** 2024-08-30 01:02 UTC
Labels: [Type] Bug, [Plugin] WooCommerce, Customer Report, [Feature Group] Appearance & Themes
