### ISSUE TITLE
Cover Block: Opt in to the experimental Custom Spacing control.

### ISSUE THREAD

**Issue by iamtakashi** [Automattic/themes#2277] opened 2020-07-21 12:47 UTC
~Varia~ Most of the themes don't seem to have opted in the spacing option for the Cover block. It seems easy to implement, and the customer would be able to use it as soon as we add the support to the themes. 

Edit: This will require `theme.json` support, [see below](https://github.com/Automattic/themes/issues/2277#issuecomment-880210717). (@kwight)

Ref: https://github.com/WordPress/gutenberg/pull/21492

> This feature is opt-in via add_theme_support. In order to show the padding controls, the following needs to be added to a theme's function.php
`add_theme_support( 'experimental-custom-spacing' );`

cc @ianstewart @alaczek

**Comment by iamtakashi** [comment] 2020-09-18 20:46
Same as #2449, I'll change this to all themes (that specified in #2449) issue. cc @jeffikus

**Comment by jordesign** [comment] 2021-06-28 07:21
Happy to handle this - starting with Varia and Seedlet?

**Comment by jordesign** [comment] 2021-07-05 00:14
I've issued a PR - which _seems_ to add the control for Varia. Wanted to get it checked before I move on to Seedlet.
#4160

**Comment by jordesign** [comment] 2021-07-12 11:56
I'll confess I haven't been able to get this working. 

`add_theme_support( 'experimental-custom-spacing' );` seems to have no effect - and `add_theme_support( 'custom-spacing' );` still uses the original style.

@iamtakashi  does this padding option/property seem like something that is still possible?

**Comment by kwight** [comment] 2021-07-12 21:38
@jordesign It looks like it should be `add_theme_support('custom-spacing')`: https://github.com/WordPress/gutenberg/pull/27045

What do you mean by "still uses the original style"?

**Comment by jordesign** [comment] 2021-07-13 01:48
`add_theme_support('custom-spacing')` is already in place in Varia at the moment - and the result is this padding control:

<img width="1103" alt="Screen Shot 2021-07-13 at 11 47 24 am" src="https://user-images.githubusercontent.com/1842363/125377318-21850300-e3d0-11eb-8132-a1850ae3e43e.png">


But I haven't been able to enable the controls shown in https://github.com/WordPress/gutenberg/pull/21492

**Comment by kwight** [comment] 2021-07-14 21:07
@jordesign Hm, this may have been removed since it was merged; for example, `gutenberg_extend_settings_custom_spacing` is a function introduced in https://github.com/WordPress/gutenberg/pull/21492, which is no longer present in the `client-assets.php` [file](https://github.com/WordPress/gutenberg/blob/trunk/lib/client-assets.php). (I also confirmed it's not in the plugin version we have running on dotcom). If you like, you can try tracing back from the current version of the file to see when it was removed.

Maybe @jeffikus or @scruffian have more insight?

**Comment by jordesign** [comment] 2021-07-15 05:55
It looks like it may have been removed in https://github.com/WordPress/gutenberg/pull/25141 in order to have support added as part of theme.json.

**Comment by jordesign** [comment] 2021-07-15 07:22
Alrighty -  @MaggieCabrera was super helpful with some advice here:

> I think last time we tried to do this we found that we had to add a theme.json file to enable it. By doing that we are opting in to the new layout controls and that requires a whole other degree of refactoring as to not break the alignments of the theme. I’m not sure what we gain from adding the controls right now is worth the amount of work from refactoring the alignments we would have to do. 

I'd tend to agree with that - but happy for @ianstewart and @kwight to weigh in?

**Comment by kwight** [comment] 2021-07-15 15:10
> I'd tend to agree with that - but happy for @ianstewart and @kwight to weigh in?

Sure, it sounds like the Theme Team has been down this road before, and our pod is in no better position to start tackling broad `theme.json` support at this point (now that I think about it, this sounds vaguely familiar, Ben may have described that to me somewhere). We'll leave this open as it's still valid, but let's move on to other things @jordesign – thanks for digging in!

**Comment by jeffikus** [comment] 2022-01-28 13:12
@jordesign is this still an issue? If not let's close this out.

**Comment by jordesign** [comment] 2022-01-31 00:40
Thanks for checking @jeffikus  - confirming this is _no longer an issue_ - I'll close it out.

**Closed by jordesign** 2022-01-31 00:40 UTC
Labels: [Pri] High, [Theme] Varia, [Status] Needs Review
